"use client";

import { useState } from "react";
import InvestigationCard, { Investigation } from "@/components/cards/InvestigationCard";
import SearchFilter, { FilterState } from "@/components/ui/SearchFilter";
import { FileSearch, AlertTriangle } from "lucide-react";

// Comprehensive investigation database
const allInvestigations: Investigation[] = [
  {
    id: "trump-1",
    slug: "trump-criminal-compendium",
    title: "The Trump Criminal Compendium",
    summary: "A comprehensive juridical documentation of Donald Trump's crimes against humanity, universal law, and democratic institutions. Includes 40+ charges spanning election interference, human trafficking complicity, financial crimes, espionage, and incitement of insurrection.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "June 16, 2015",
    entityCount: 28,
    tags: ["Election Interference", "Human Trafficking", "Tax Evasion", "RICO", "January 6", "Epstein"],
  },
  {
    id: "epstein-1",
    slug: "epstein-network",
    title: "Epstein Network Investigation",
    summary: "Comprehensive investigation into Jeffrey Epstein's global trafficking operation, his connections to Trump, and the network of powerful individuals who enabled decades of abuse.",
    category: "Human Trafficking",
    severity: "critical",
    date: "March 5, 2016",
    entityCount: 15,
    tags: ["Epstein", "Maxwell", "Trump", "Trafficking", "Sexual Abuse"],
  },
  {
    id: "j6-1",
    slug: "january-6-insurrection",
    title: "January 6 Insurrection",
    summary: "The violent attack on American democracy: Trump incited a mob to storm the Capitol, resulting in deaths, injuries, and attempted overthrow of a lawful election. Includes criminal convictions and ongoing proceedings.",
    category: "Election Interference",
    severity: "critical",
    date: "January 6, 2021",
    entityCount: 12,
    tags: ["January 6", "Insurrection", "Seditious Conspiracy", "Proud Boys", "Oath Keepers"],
  },
  {
    id: "russia-1",
    slug: "russian-interference",
    title: "Russian Election Interference",
    summary: "Mueller investigation documented 'sweeping and systematic' Russian interference in 2016 to help Trump, 140+ Trump-Russia contacts, and 10+ instances of obstruction of justice.",
    category: "Election Interference",
    severity: "critical",
    date: "June 14, 2016",
    entityCount: 10,
    tags: ["Mueller", "Russia", "Obstruction", "Collusion", "Manafort"],
  },
  {
    id: "docs-1",
    slug: "mar-a-lago-documents",
    title: "Mar-a-Lago Classified Documents",
    summary: "Trump illegally retained 300+ classified documents including TOP SECRET/SCI material, hid them from FBI, and obstructed justice. 40 federal counts in indictment.",
    category: "National Security",
    severity: "critical",
    date: "August 8, 2022",
    entityCount: 5,
    tags: ["Classified Documents", "Espionage", "Obstruction", "National Security"],
  },
  {
    id: "ga-1",
    slug: "georgia-rico",
    title: "Georgia Election RICO",
    summary: "Trump and 18 co-conspirators indicted under RICO for criminal enterprise to overturn 2020 Georgia election. Includes 'find 11,780 votes' call, fake electors, Ruby Freeman harassment.",
    category: "Election Interference",
    severity: "critical",
    date: "January 2, 2021",
    entityCount: 19,
    tags: ["RICO", "Georgia", "Election Fraud", "Raffensperger", "Fake Electors"],
  },
  {
    id: "fraud-1",
    slug: "trump-org-fraud",
    title: "Trump Organization Fraud",
    summary: "Trump found liable for massive fraud inflating assets by billions. $454 million judgment. Criminal conviction of Trump Org on 17 felony counts. CFO Weisselberg pled guilty to perjury.",
    category: "Financial Crimes",
    severity: "critical",
    date: "July 1, 2021",
    entityCount: 6,
    tags: ["Fraud", "Tax Evasion", "NY AG", "Civil Judgment"],
  },
  {
    id: "hush-1",
    slug: "hush-money",
    title: "Hush Money Election Fraud",
    summary: "First former president convicted of felonies. 34 counts of falsifying business records to conceal payments to Stormy Daniels and influence 2016 election.",
    category: "Election Interference",
    severity: "critical",
    date: "October 27, 2016",
    entityCount: 7,
    tags: ["Stormy Daniels", "Michael Cohen", "Campaign Finance", "Felony Conviction"],
  },
  {
    id: "ukraine-1",
    slug: "ukraine-extortion",
    title: "Ukraine Extortion",
    summary: "First Trump impeachment: Withheld $391M in military aid to pressure Ukraine into announcing Biden investigations. 'I would like you to do us a favor though.'",
    category: "Abuse of Power",
    severity: "critical",
    date: "July 25, 2019",
    entityCount: 8,
    tags: ["Impeachment", "Ukraine", "Quid Pro Quo", "Giuliani"],
  },
  {
    id: "family-1",
    slug: "family-separation",
    title: "Family Separation Crisis",
    summary: "Zero tolerance policy deliberately separated 5,500+ children from parents at border. Children in cages, infants taken, 7 children died in custody, 1,000+ still not reunited.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "April 6, 2018",
    entityCount: 5,
    tags: ["Immigration", "Children", "Human Rights", "Stephen Miller"],
  },
  {
    id: "saudi-1",
    slug: "saudi-connections",
    title: "Saudi Arabia Connections",
    summary: "Khashoggi murder cover-up, MBS 'has Kushner in his pocket', $2B Saudi investment in Kushner's fund, emergency arms sales, Yemen war complicity.",
    category: "Foreign Corruption",
    severity: "critical",
    date: "October 2, 2018",
    entityCount: 5,
    tags: ["Saudi Arabia", "Khashoggi", "Kushner", "MBS", "Arms Deals"],
  },
  {
    id: "emol-1",
    slug: "emoluments",
    title: "Emoluments Violations",
    summary: "Trump profited from presidency through foreign government payments to his hotels. $72M+ from Trump DC Hotel, Saudi spending, T-Mobile executives during merger approval.",
    category: "Corruption",
    severity: "high",
    date: "January 20, 2017",
    entityCount: 4,
    tags: ["Emoluments", "Trump Hotel", "Foreign Payments", "Corruption"],
  },
  {
    id: "covid-1",
    slug: "covid-response",
    title: "COVID-19 Response Failure",
    summary: "Catastrophic pandemic mismanagement: 400,000+ preventable deaths, disbanded pandemic team, suppressed CDC guidance, promoted dangerous treatments, downplayed severity for months.",
    category: "Public Health",
    severity: "critical",
    date: "February 7, 2020",
    entityCount: 8,
    tags: ["COVID-19", "Pandemic", "Public Health", "CDC", "Death Toll"],
  },
  {
    id: "muslim-1",
    slug: "muslim-ban",
    title: "Muslim Travel Ban",
    summary: "Discriminatory ban on travel from Muslim-majority countries, implemented through chaos with no preparation, families separated, green card holders detained, courts intervened multiple times.",
    category: "Civil Rights",
    severity: "high",
    date: "January 27, 2017",
    entityCount: 5,
    tags: ["Muslim Ban", "Immigration", "Discrimination", "Executive Order"],
  },
  {
    id: "tax-1",
    slug: "tax-evasion",
    title: "Tax Evasion & Fraud",
    summary: "NY Times exposed decades of tax fraud: $100M+ evaded, fraudulent deductions, inheritance schemes, fake consulting payments to Ivanka. $454M civil judgment.",
    category: "Financial Crimes",
    severity: "critical",
    date: "October 2, 2018",
    entityCount: 6,
    tags: ["Tax Fraud", "NY Times", "Fred Trump", "Inheritance"],
  },
  {
    id: "obstruction-1",
    slug: "obstruction-of-justice",
    title: "Obstruction of Justice",
    summary: "Mueller documented 10+ instances of obstruction: Comey firing, witness tampering, dangling pardons, ordering Mueller fired, lying to investigators.",
    category: "Abuse of Power",
    severity: "critical",
    date: "May 9, 2017",
    entityCount: 7,
    tags: ["Mueller", "Obstruction", "Comey", "Pardons"],
  },
  {
    id: "climate-1",
    slug: "climate-sabotage",
    title: "Climate & Environmental Sabotage",
    summary: "Paris Agreement withdrawal, 100+ environmental rollbacks, EPA captured by industry, Scott Pruitt corruption scandals, accelerated climate destruction.",
    category: "Environment",
    severity: "critical",
    date: "June 1, 2017",
    entityCount: 5,
    tags: ["Climate", "EPA", "Paris Agreement", "Rollbacks"],
  },
  {
    id: "uni-1",
    slug: "trump-university",
    title: "Trump University Fraud",
    summary: "Fake university scammed 6,000+ students with worthless 'education' and high-pressure sales. $25 million settlement. Not accredited, not a university.",
    category: "Financial Crimes",
    severity: "high",
    date: "July 14, 2015",
    entityCount: 3,
    tags: ["Fraud", "Education", "Settlement", "Victims"],
  },
  {
    id: "foundation-1",
    slug: "trump-foundation",
    title: "Trump Foundation Self-Dealing",
    summary: "Charity fraud: Used foundation funds for campaign, portraits of himself, legal settlements. $2M penalty, forced dissolution, banned from running NY charities.",
    category: "Financial Crimes",
    severity: "high",
    date: "June 14, 2018",
    entityCount: 4,
    tags: ["Foundation", "Charity Fraud", "Self-Dealing", "NY AG"],
  },
  {
    id: "voter-1",
    slug: "voter-suppression",
    title: "Voter Suppression & USPS Sabotage",
    summary: "DeJoy dismantled mail sorting machines before 2020 election, Georgia 'find 11,780 votes' call, Big Lie campaign, fake electors scheme across 7 states.",
    category: "Election Interference",
    severity: "critical",
    date: "August 18, 2020",
    entityCount: 8,
    tags: ["Voter Suppression", "USPS", "DeJoy", "Big Lie"],
  },
  {
    id: "money-1",
    slug: "money-laundering",
    title: "Money Laundering Operations",
    summary: "Trump properties as laundromats for Russian/foreign cash: all-cash purchases, shell companies, Deutsche Bank relationship ($2B+ loans), suspicious property sales.",
    category: "Financial Crimes",
    severity: "critical",
    date: "March 6, 2013",
    entityCount: 6,
    tags: ["Money Laundering", "Russia", "Deutsche Bank", "Real Estate"],
  },
  {
    id: "assault-1",
    slug: "sexual-assault",
    title: "Sexual Assault Allegations",
    summary: "26+ women accusing Trump of sexual misconduct. E. Jean Carroll: Found liable for sexual abuse and defamation ($88.3M). Access Hollywood tape admission.",
    category: "Criminal Conduct",
    severity: "critical",
    date: "October 7, 2016",
    entityCount: 4,
    tags: ["Sexual Assault", "E. Jean Carroll", "Access Hollywood", "Defamation"],
  },
  {
    id: "pardons-1",
    slug: "pardons-corruption",
    title: "Corrupt Pardons",
    summary: "Pardoned Russia investigation witnesses (Manafort, Stone, Flynn), war criminals (Blackwater), cronies (Bannon), and family (Kushner's father). Obstruction via clemency.",
    category: "Abuse of Power",
    severity: "high",
    date: "December 23, 2020",
    entityCount: 10,
    tags: ["Pardons", "Obstruction", "Manafort", "Stone", "Flynn"],
  },
  {
    id: "cambridge-1",
    slug: "cambridge-analytica",
    title: "Cambridge Analytica",
    summary: "87 million Facebook users harvested without consent. Bannon-led firm used psychographic targeting for Trump campaign. $5 billion Facebook fine. Company dissolved.",
    category: "Election Interference",
    severity: "critical",
    date: "March 17, 2018",
    entityCount: 5,
    tags: ["Cambridge Analytica", "Facebook", "Bannon", "Data Harvesting"],
  },
  {
    id: "opioid-1",
    slug: "opioid-crisis",
    title: "Opioid Crisis Response",
    summary: "500,000+ Americans dead. Regulatory capture: Alex Azar (pharma exec) as HHS Secretary. Drug czar nominee withdrew after exposé on weakening DEA enforcement.",
    category: "Public Health",
    severity: "critical",
    date: "June 12, 2017",
    entityCount: 5,
    tags: ["Opioid", "Pharma", "Regulatory Capture", "Deaths"],
  },
  {
    id: "wall-1",
    slug: "build-the-wall-fraud",
    title: "Build the Wall Fraud",
    summary: "Steve Bannon and Brian Kolfage's 'We Build the Wall' scam: $25M raised, millions stolen for personal use. Bannon pardoned by Trump. Kolfage sentenced to 51 months.",
    category: "Financial Crimes",
    severity: "high",
    date: "December 17, 2018",
    entityCount: 5,
    tags: ["Bannon", "Fraud", "Wall", "Pardon", "Crowdfunding"],
  },

  {
    id: "proud-boys-1",
    slug: "proud-boys-sedition",
    title: "Proud Boys Seditious Conspiracy",
    summary: "Proud Boys leadership convicted of seditious conspiracy for plotting to violently stop the transfer of power on January 6. Enrique Tarrio: 22 years, longest January 6 sentence.",
    category: "Election Interference",
    severity: "critical",
    date: "January 6, 2021",
    entityCount: 7,
    tags: ["Proud Boys", "Seditious Conspiracy", "January 6", "Tarrio", "Domestic Terrorism"],
  },
  {
    id: "oath-keepers-1",
    slug: "oath-keepers-sedition",
    title: "Oath Keepers Seditious Conspiracy",
    summary: "Stewart Rhodes and Oath Keepers convicted of seditious conspiracy for January 6. Stored weapons at DC-area hotel for 'quick reaction force.' First sedition convictions since 1995.",
    category: "Election Interference",
    severity: "critical",
    date: "January 6, 2021",
    entityCount: 6,
    tags: ["Oath Keepers", "Seditious Conspiracy", "January 6", "Stewart Rhodes", "QRF"],
  },
  {
    id: "fake-electors-1",
    slug: "fake-electors",
    title: "Fake Electors Scheme",
    summary: "Coordinated scheme across 7 states to submit fraudulent electoral certificates to overturn 2020 election. Dozens charged in Georgia, Michigan, Arizona, Nevada, Wisconsin.",
    category: "Election Interference",
    severity: "critical",
    date: "December 14, 2020",
    entityCount: 12,
    tags: ["Fake Electors", "Election Fraud", "Georgia RICO", "Eastman", "Chesebro"],
  },
  {
    id: "dominion-1",
    slug: "dominion-defamation",
    title: "Dominion Defamation",
    summary: "Fox News settled for record $787.5 million after spreading lies about Dominion Voting Systems. Giuliani ordered to pay $148 million for defaming election workers Ruby Freeman and Shaye Moss.",
    category: "Election Interference",
    severity: "critical",
    date: "November 7, 2020",
    entityCount: 9,
    tags: ["Dominion", "Fox News", "Giuliani", "Defamation", "Big Lie"],
  },
  {
    id: "deutsche-bank-1",
    slug: "deutsche-bank",
    title: "Deutsche Bank Investigation",
    summary: "Two decades of suspicious loans totaling $2+ billion to Trump when no other bank would lend. Connections to Russian money laundering, internal red flags ignored, ongoing investigations.",
    category: "Financial Crimes",
    severity: "critical",
    date: "September 22, 2015",
    entityCount: 8,
    tags: ["Deutsche Bank", "Money Laundering", "Russia", "Loans", "Fraud"],
  },
  {
    id: "inaugural-1",
    slug: "inaugural-committee",
    title: "Inaugural Committee Investigation",
    summary: "Record $107 million raised for Trump's 2017 inauguration, double Obama's total, yet delivered fewer events. Trump Hotel overcharged, $26M to Melania's friend, foreign donors investigated.",
    category: "Corruption",
    severity: "high",
    date: "January 20, 2017",
    entityCount: 7,
    tags: ["Inaugural Committee", "Tom Barrack", "Foreign Donations", "Nonprofit Fraud"],
  },
  {
    id: "charlottesville-1",
    slug: "charlottesville",
    title: "Charlottesville Response",
    summary: "After neo-Nazis killed Heather Heyer at 'Unite the Right' rally, Trump declared 'very fine people on both sides.' Defining moral failure condemned by military and religious leaders.",
    category: "Civil Rights",
    severity: "critical",
    date: "August 12, 2017",
    entityCount: 6,
    tags: ["Charlottesville", "White Supremacy", "Heather Heyer", "Very Fine People"],
  },
  {
    id: "lafayette-1",
    slug: "lafayette-square",
    title: "Lafayette Square Incident",
    summary: "Peaceful protesters tear-gassed so Trump could pose with a Bible at St. John's Church. Gen. Milley apologized. Military leaders issued rare public rebuke of authoritarian tactics.",
    category: "Abuse of Power",
    severity: "critical",
    date: "June 1, 2020",
    entityCount: 7,
    tags: ["Lafayette Square", "Tear Gas", "Photo Op", "BLM", "Military"],
  },
  {
    id: "puerto-rico-1",
    slug: "puerto-rico",
    title: "Puerto Rico Hurricane Response",
    summary: "Nearly 3,000 Americans died after Hurricane Maria. Trump threw paper towels, denied death toll, blocked billions in aid, and called it an 'incredible unsung success.'",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "September 20, 2017",
    entityCount: 6,
    tags: ["Puerto Rico", "Hurricane Maria", "FEMA", "Deaths", "Aid Blocked"],
  },
  {
    id: "defamation-1",
    slug: "defamation",
    title: "Defamation & Reputational Destruction",
    summary: "$88.3 million in judgments against Trump for defaming E. Jean Carroll (sexual assault survivor) and the Georgia election workers Ruby Freeman and Shaye Moss who received death threats.",
    category: "Criminal Conduct",
    severity: "critical",
    date: "June 21, 2019",
    entityCount: 7,
    tags: ["Defamation", "E. Jean Carroll", "Ruby Freeman", "Sexual Assault", "Election Lies"],
  },
  {
    id: "saudi-arms-1",
    slug: "saudi-arms-deal",
    title: "Saudi Arms Deal & Yemen Genocide",
    summary: "$110 billion arms deal enabling mass civilian casualties in Yemen. Over 150,000 dead. Trump vetoed congressional override. Kushner received $2B from Saudis after leaving office.",
    category: "Foreign Corruption",
    severity: "critical",
    date: "May 20, 2017",
    entityCount: 7,
    tags: ["Saudi Arabia", "Yemen", "Arms Sales", "War Crimes", "Khashoggi", "Kushner"],
  },
  // Historical and Systemic Investigations
  {
    id: "mkultra-1",
    slug: "mkultra",
    title: "MKUltra: CIA Mind Control Program",
    summary: "CIA conducted illegal experiments on unwitting Americans, testing LSD, electroshock, and mind control techniques. Thousands of victims. Most records destroyed to prevent accountability.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "January 17, 2010",
    entityCount: 5,
    tags: ["CIA", "MKUltra", "Mind Control", "LSD", "Human Experimentation"],
  },
  {
    id: "tuskegee-1",
    slug: "tuskegee-experiment",
    title: "Tuskegee Syphilis Study",
    summary: "40 years of deliberate medical torture: U.S. government withheld treatment from 399 Black men with syphilis to study disease progression. At least 128 died, 40 wives infected.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "April 22, 2009",
    entityCount: 3,
    tags: ["Tuskegee", "Medical Experimentation", "Racism", "Syphilis"],
  },
  {
    id: "cointelpro-1",
    slug: "cointelpro",
    title: "COINTELPRO: FBI Domestic Terrorism",
    summary: "FBI's systematic destruction of civil rights movement. Targeted MLK, Fred Hampton (assassinated), Black Panthers. Used illegal wiretaps, planted evidence, spread disinformation.",
    category: "Government Abuse of Power",
    severity: "critical",
    date: "March 29, 2010",
    entityCount: 5,
    tags: ["FBI", "COINTELPRO", "MLK", "Fred Hampton", "Black Panthers"],
  },
  {
    id: "mockingbird-1",
    slug: "operation-mockingbird",
    title: "Operation Mockingbird: CIA Media Control",
    summary: "CIA infiltrated American journalism, influencing 400+ journalists and 25 major news organizations to plant stories and suppress unfavorable coverage.",
    category: "Government Abuse of Power",
    severity: "critical",
    date: "July 14, 2010",
    entityCount: 4,
    tags: ["CIA", "Mockingbird", "Propaganda", "Media Manipulation"],
  },
  {
    id: "war-on-drugs-1",
    slug: "war-on-drugs",
    title: "War on Drugs: Systemic Racial Targeting",
    summary: "Nixon aide confessed: designed to target 'Black people and antiwar left.' $1 trillion spent, millions incarcerated, no reduction in drug use. Black Americans 5x more likely imprisoned.",
    category: "Systemic Racism",
    severity: "critical",
    date: "October 5, 2010",
    entityCount: 5,
    tags: ["War on Drugs", "Mass Incarceration", "Nixon", "Racial Targeting"],
  },
  {
    id: "police-brutality-1",
    slug: "police-brutality",
    title: "Police Brutality & Qualified Immunity",
    summary: "American police kill ~1,100 people annually - 30-60x more than other wealthy nations. Black Americans killed at 2.5x rate. Qualified immunity shields officers from accountability.",
    category: "Civil Rights",
    severity: "critical",
    date: "June 30, 2014",
    entityCount: 4,
    tags: ["Police Brutality", "Qualified Immunity", "George Floyd", "BLM"],
  },
  {
    id: "flint-1",
    slug: "flint-water-crisis",
    title: "Flint Water Crisis",
    summary: "Deliberate poisoning of Black city: 100,000 residents exposed to lead, children suffered brain damage. Officials covered up for 18 months. Criminal charges dropped.",
    category: "Environmental Racism",
    severity: "critical",
    date: "April 25, 2014",
    entityCount: 4,
    tags: ["Flint", "Lead Poisoning", "Environmental Racism", "Michigan"],
  },
  {
    id: "native-genocide-1",
    slug: "native-american-genocide",
    title: "Native American Genocide",
    summary: "Indigenous population reduced from 60-100 million to 800,000 through deliberate extermination, forced relocation, biological warfare, and cultural genocide. The largest genocide in history.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "March 15, 2009",
    entityCount: 3,
    tags: ["Genocide", "Native Americans", "Trail of Tears", "Boarding Schools"],
  },
  {
    id: "japanese-internment-1",
    slug: "japanese-internment",
    title: "Japanese American Internment",
    summary: "120,000 Americans imprisoned without charge based on race. 62% were U.S. citizens. No Japanese American was ever charged with espionage. Driven by racism.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "June 8, 2009",
    entityCount: 3,
    tags: ["Japanese Internment", "WWII", "Executive Order 9066", "Civil Liberties"],
  },
  {
    id: "nsa-surveillance-1",
    slug: "nsa-mass-surveillance",
    title: "NSA Mass Surveillance",
    summary: "Snowden exposed NSA collecting metadata on every American phone call, reading emails, accessing cloud data. Programs violated Fourth Amendment. No official faced consequences.",
    category: "Constitutional Violations",
    severity: "critical",
    date: "May 17, 2016",
    entityCount: 5,
    tags: ["NSA", "Snowden", "Mass Surveillance", "PRISM", "Privacy"],
  },
  {
    id: "tonkin-1",
    slug: "gulf-of-tonkin",
    title: "Gulf of Tonkin Incident",
    summary: "The lie that started Vietnam War: August 4 'attack' never happened, Johnson and McNamara knew and lied anyway. 58,000 Americans and 2-3 million Vietnamese died.",
    category: "War Crimes",
    severity: "critical",
    date: "February 12, 2011",
    entityCount: 4,
    tags: ["Vietnam War", "Gulf of Tonkin", "LBJ", "McNamara"],
  },
  {
    id: "cia-coups-1",
    slug: "cia-coups",
    title: "CIA Regime Change Operations",
    summary: "CIA overthrew 50+ governments: Iran (1953), Guatemala (1954), Chile (1973) and more. Killed millions, installed dictatorships, created lasting instability.",
    category: "War Crimes",
    severity: "critical",
    date: "November 8, 2011",
    entityCount: 4,
    tags: ["CIA", "Coup", "Regime Change", "Iran", "Chile", "Guatemala"],
  },
  {
    id: "kissinger-1",
    slug: "kissinger-crimes",
    title: "Henry Kissinger War Crimes",
    summary: "Architect of American atrocities: Cambodia bombing (150,000 civilians), Chile coup (3,000+ killed), Bangladesh genocide complicity (300,000-3,000,000 dead). Never prosecuted.",
    category: "War Crimes",
    severity: "critical",
    date: "August 9, 2011",
    entityCount: 5,
    tags: ["Kissinger", "War Crimes", "Cambodia", "Chile", "Bangladesh"],
  },
  {
    id: "dark-money-1",
    slug: "dark-money-politics",
    title: "Dark Money in American Politics",
    summary: "Citizens United enabled $1 billion+ in anonymous spending. Koch network spends $400M/cycle. Leonard Leo's $1.6B captured the judiciary. Billionaires bought democracy.",
    category: "Corruption",
    severity: "critical",
    date: "January 21, 2010",
    entityCount: 4,
    tags: ["Dark Money", "Citizens United", "Koch", "Leonard Leo"],
  },
  {
    id: "scotus-ethics-1",
    slug: "supreme-court-ethics",
    title: "Supreme Court Ethics Crisis",
    summary: "Thomas accepted millions from Harlan Crow. Alito took billionaire's private jet. No binding ethics code, refused recusals. Public trust collapsed to historic lows.",
    category: "Corruption",
    severity: "critical",
    date: "April 6, 2023",
    entityCount: 5,
    tags: ["Supreme Court", "Clarence Thomas", "Alito", "Ethics", "Corruption"],
  },
  {
    id: "iraq-war-1",
    slug: "iraq-war-lies",
    title: "Iraq War Lies",
    summary: "Bush administration lied about WMD and al-Qaeda connections to justify invasion. Hundreds of thousands killed, $2+ trillion cost, ISIS created. No accountability.",
    category: "War Crimes",
    severity: "critical",
    date: "April 22, 2013",
    entityCount: 5,
    tags: ["Iraq War", "WMD Lies", "Bush", "Cheney", "War Crimes"],
  },
  {
    id: "cia-torture-1",
    slug: "cia-torture-program",
    title: "CIA Torture Program",
    summary: "Post-9/11 torture at black sites: waterboarding, rectal feeding, coffin confinement. Senate report found no useful intelligence. No prosecutions - only whistleblower jailed.",
    category: "War Crimes",
    severity: "critical",
    date: "June 19, 2013",
    entityCount: 5,
    tags: ["CIA", "Torture", "Black Sites", "Waterboarding", "War Crimes"],
  },
  {
    id: "drone-1",
    slug: "drone-assassination-program",
    title: "Drone Assassination Program",
    summary: "Extrajudicial killing without due process. Thousands killed in Pakistan, Yemen, Somalia. American citizens assassinated. Civilian casualties systematically undercounted.",
    category: "War Crimes",
    severity: "critical",
    date: "January 9, 2014",
    entityCount: 4,
    tags: ["Drones", "Assassination", "Yemen", "Pakistan", "War Crimes"],
  },
  {
    id: "condor-1",
    slug: "operation-condor",
    title: "Operation Condor",
    summary: "CIA-backed assassination network of South American dictatorships. Six nations coordinated to murder 60,000+ dissidents. Kissinger authorized support. Letelier assassinated in Washington D.C.",
    category: "War Crimes",
    severity: "critical",
    date: "January 26, 2012",
    entityCount: 8,
    tags: ["Operation Condor", "CIA", "Chile", "Argentina", "Kissinger", "Assassination"],
  },
  {
    id: "chile-1",
    slug: "chile-coup",
    title: "Chile Coup (1973)",
    summary: "CIA helped overthrow democratically elected Salvador Allende. Pinochet dictatorship killed 3,000+, tortured 40,000+. Kissinger: 'I don't see why we need to stand by and watch a country go communist.'",
    category: "War Crimes",
    severity: "critical",
    date: "April 7, 2012",
    entityCount: 6,
    tags: ["Chile", "Pinochet", "CIA", "Coup", "Kissinger", "Allende"],
  },
  {
    id: "iran-coup-1",
    slug: "iran-coup",
    title: "Iran Coup (1953)",
    summary: "CIA/MI6 overthrew democratically elected Mosaddegh over oil nationalization. Installed Shah dictatorship, created SAVAK torture regime. Blowback: 1979 revolution, hostage crisis.",
    category: "War Crimes",
    severity: "critical",
    date: "July 15, 2012",
    entityCount: 5,
    tags: ["Iran", "CIA", "Coup", "Shah", "Oil", "Mosaddegh"],
  },
  {
    id: "project-2025-1",
    slug: "project-2025",
    title: "Project 2025: Authoritarian Blueprint",
    summary: "Heritage Foundation's 900-page plan to dismantle federal government, purge civil servants, weaponize DOJ, eliminate agencies, and consolidate executive power into autocracy.",
    category: "Abuse of Power",
    severity: "critical",
    date: "January 1, 2023",
    entityCount: 12,
    tags: ["Project 2025", "Heritage Foundation", "Authoritarianism", "Schedule F"],
  },
  {
    id: "federalist-1",
    slug: "federalist-society",
    title: "Federalist Society Judicial Capture",
    summary: "Dark money network has captured the federal judiciary. Leonard Leo directed $1.6B+ to install 6 Supreme Court justices who overturned Roe, gutted voting rights, and granted presidential immunity.",
    category: "Corruption",
    severity: "critical",
    date: "December 3, 2014",
    entityCount: 8,
    tags: ["Federalist Society", "Leonard Leo", "Supreme Court", "Dark Money", "Judicial Capture"],
  },
  {
    id: "vietnam-1",
    slug: "vietnam-war-crimes",
    title: "Vietnam War Crimes",
    summary: "My Lai massacre (500+ civilians murdered), Agent Orange (400,000 killed, 500,000 birth defects), Phoenix Program (20,000+ extrajudicial killings). 2-3 million Vietnamese dead.",
    category: "War Crimes",
    severity: "critical",
    date: "May 20, 2011",
    entityCount: 6,
    tags: ["Vietnam", "My Lai", "Agent Orange", "War Crimes", "Phoenix Program"],
  },
  {
    id: "abu-ghraib-1",
    slug: "abu-ghraib",
    title: "Abu Ghraib Torture Scandal",
    summary: "U.S. soldiers tortured Iraqi prisoners: sexual humiliation, electric shocks, mock executions, dogs. Photos leaked. Only low-level soldiers punished, commanders escaped accountability.",
    category: "War Crimes",
    severity: "critical",
    date: "February 14, 2013",
    entityCount: 5,
    tags: ["Abu Ghraib", "Iraq", "Torture", "War Crimes", "Military"],
  },
  {
    id: "boarding-schools-1",
    slug: "indian-boarding-schools",
    title: "Indian Boarding Schools",
    summary: "'Kill the Indian, save the man.' Children forcibly removed, native languages/culture forbidden. Physical and sexual abuse rampant. Thousands died. Federal investigation found 500+ burial sites.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "October 30, 2012",
    entityCount: 4,
    tags: ["Boarding Schools", "Native Americans", "Genocide", "Cultural Destruction"],
  },
  {
    id: "iran-contra-1",
    slug: "iran-contra",
    title: "Iran-Contra Affair",
    summary: "Reagan secretly sold weapons to Iran, used profits to fund Nicaraguan death squads in violation of law. Oliver North shredded evidence. Key figures pardoned by Bush.",
    category: "Government Abuse of Power",
    severity: "critical",
    date: "November 18, 2011",
    entityCount: 7,
    tags: ["Iran-Contra", "Reagan", "Oliver North", "Nicaragua", "Arms Dealing"],
  },
  {
    id: "bush-v-gore-1",
    slug: "bush-v-gore",
    title: "Bush v. Gore: Stolen Election",
    summary: "Supreme Court stopped Florida recount, selected Bush as president by 5-4 vote. Scalia: counting votes would cause 'irreparable harm.' Recount showed Gore won Florida.",
    category: "Election Interference",
    severity: "critical",
    date: "March 18, 2014",
    entityCount: 6,
    tags: ["Bush v. Gore", "Supreme Court", "Florida", "Election", "Scalia"],
  },
  {
    id: "watergate-1",
    slug: "watergate",
    title: "Watergate Scandal",
    summary: "Nixon's men burglarized DNC, then covered it up. Saturday Night Massacre. 'I am not a crook.' Nixon resigned facing certain impeachment. Many conspirators imprisoned.",
    category: "Government Abuse of Power",
    severity: "critical",
    date: "September 3, 2009",
    entityCount: 8,
    tags: ["Watergate", "Nixon", "Cover-up", "Impeachment", "Saturday Night Massacre"],
  },
  {
    id: "2008-crisis-1",
    slug: "2008-financial-crisis",
    title: "2008 Financial Crisis",
    summary: "Wall Street fraud crashed global economy. 8 million jobs lost, millions lost homes. Taxpayers bailed out banks. No executives jailed. Bonuses paid with bailout money.",
    category: "Financial Crimes",
    severity: "critical",
    date: "May 28, 2015",
    entityCount: 7,
    tags: ["Financial Crisis", "Wall Street", "Bailout", "Fraud", "Recession"],
  },
  {
    id: "mass-incarceration-1",
    slug: "mass-incarceration",
    title: "Mass Incarceration System",
    summary: "U.S. has 4% of world population, 25% of prisoners. 2+ million incarcerated. Black Americans 5x more likely imprisoned. Private prisons profit from human caging.",
    category: "Systemic Racism",
    severity: "critical",
    date: "October 15, 2014",
    entityCount: 5,
    tags: ["Mass Incarceration", "Prison", "Racism", "War on Drugs", "Private Prisons"],
  },
  {
    id: "health-insurance-1",
    slug: "health-insurance-deaths",
    title: "Health Insurance Industry Deaths",
    summary: "68,000+ Americans die annually from lack of insurance. Insurers deny claims to maximize profit. Prior authorization delays kill patients. CEO Thompson assassinated 2024.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "April 20, 2015",
    entityCount: 5,
    tags: ["Healthcare", "Insurance", "Deaths", "Denial of Care", "UnitedHealth"],
  },
  {
    id: "corporate-homicide-1",
    slug: "corporate-homicide",
    title: "Corporate Homicide: Unpunished Deaths",
    summary: "Corporations kill workers and consumers with impunity. Boeing 737 MAX (346 dead), Purdue Pharma opioids (500,000+ dead), Ford Pinto (180 dead). Executives rarely prosecuted.",
    category: "Criminal Conduct",
    severity: "critical",
    date: "February 11, 2015",
    entityCount: 6,
    tags: ["Corporate Crime", "Homicide", "Boeing", "Opioids", "Negligence"],
  },
  {
    id: "patriot-act-1",
    slug: "patriot-act",
    title: "USA PATRIOT Act",
    summary: "Rushed through Congress after 9/11. Enabled mass surveillance, NSL abuse, indefinite detention. Most legislators admitted they didn't read it. Still in effect.",
    category: "Constitutional Violations",
    severity: "critical",
    date: "August 11, 2013",
    entityCount: 4,
    tags: ["PATRIOT Act", "Surveillance", "9/11", "Civil Liberties"],
  },
  {
    id: "guantanamo-1",
    slug: "guantanamo-bay",
    title: "Guantánamo Bay Detention",
    summary: "Indefinite detention without trial. Torture including waterboarding, force-feeding, sleep deprivation. 780 detained, most never charged. Still open despite promises to close.",
    category: "War Crimes",
    severity: "critical",
    date: "October 28, 2013",
    entityCount: 5,
    tags: ["Guantánamo", "Torture", "Detention", "War on Terror", "Human Rights"],
  },
  {
    id: "private-prisons-1",
    slug: "private-prison-industry",
    title: "Private Prison Industrial Complex",
    summary: "CoreCivic and GEO Group profit from incarceration. Lobby for harsh sentencing. Deaths, abuse, inadequate care. Immigration detention contracts worth billions.",
    category: "Corruption",
    severity: "critical",
    date: "August 6, 2014",
    entityCount: 5,
    tags: ["Private Prisons", "GEO Group", "CoreCivic", "Immigration", "Lobbying"],
  },
  {
    id: "jfk-1",
    slug: "jfk-assassination",
    title: "JFK Assassination & Cover-Up",
    summary: "The assassination of President John F. Kennedy on November 22, 1963 and the decades-long coverup. The Warren Commission's lone-gunman conclusion contradicted by the House Select Committee finding of 'probable conspiracy.' CIA files still withheld.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "November 14, 2009",
    entityCount: 8,
    tags: ["JFK", "CIA", "Warren Commission", "Oswald", "Conspiracy"],
  },
  {
    id: "mlk-1",
    slug: "mlk-assassination",
    title: "Martin Luther King Jr. Assassination",
    summary: "FBI's COINTELPRO targeted MLK for years before his April 4, 1968 assassination. FBI sent him anonymous letters urging suicide. A 1999 civil trial jury found government agencies liable for King's death.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "March 22, 2010",
    entityCount: 6,
    tags: ["MLK", "FBI", "COINTELPRO", "Civil Rights", "Assassination"],
  },
  {
    id: "rfk-1",
    slug: "rfk-assassination",
    title: "Robert F. Kennedy Assassination",
    summary: "RFK assassinated June 5, 1968 while campaigning for president. Sirhan Sirhan convicted but evidence of second gunman, LAPD evidence destruction, and CIA connections never fully investigated.",
    category: "Government Cover-Up",
    severity: "high",
    date: "April 8, 2010",
    entityCount: 4,
    tags: ["RFK", "Assassination", "LAPD", "CIA"],
  },
  {
    id: "malcolm-x-1",
    slug: "malcolm-x-assassination",
    title: "Malcolm X Assassination",
    summary: "Malcolm X assassinated February 21, 1965. Two men wrongly convicted, exonerated in 2021 after 55 years. FBI and NYPD had informants in his inner circle and failed to prevent the killing despite advance knowledge.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "May 17, 2010",
    entityCount: 5,
    tags: ["Malcolm X", "FBI", "NYPD", "Nation of Islam", "COINTELPRO"],
  },
  {
    id: "fred-hampton-1",
    slug: "fred-hampton-assassination",
    title: "Fred Hampton Assassination",
    summary: "FBI and Chicago police assassinated Black Panther leader Fred Hampton in a pre-dawn raid on December 4, 1969. FBI informant provided floor plans. Officers fired 99 shots; Panthers fired one. Hampton was drugged by the informant.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "June 3, 2010",
    entityCount: 5,
    tags: ["Fred Hampton", "Black Panthers", "FBI", "COINTELPRO", "Chicago Police"],
  },
  {
    id: "move-1",
    slug: "move-bombing",
    title: "MOVE Bombing - Philadelphia 1985",
    summary: "Philadelphia police dropped a bomb on the MOVE organization's row house, killing 11 people including 5 children. The fire destroyed 65 homes in a Black neighborhood. No officers were ever charged.",
    category: "Civil Rights",
    severity: "critical",
    date: "July 19, 2010",
    entityCount: 4,
    tags: ["MOVE", "Philadelphia", "Police Bombing", "Racism"],
  },
  {
    id: "waco-1",
    slug: "waco-siege",
    title: "Waco Siege",
    summary: "ATF and FBI siege of Branch Davidian compound in Waco, Texas. 51-day standoff ended with fire that killed 76 people including 25 children on April 19, 1993. CS gas deployment, military equipment use against civilians, and evidence destruction.",
    category: "Government Overreach",
    severity: "critical",
    date: "August 14, 2010",
    entityCount: 5,
    tags: ["Waco", "ATF", "FBI", "Branch Davidians", "Siege"],
  },
  {
    id: "ruby-ridge-1",
    slug: "ruby-ridge",
    title: "Ruby Ridge",
    summary: "FBI and US Marshals killed Randy Weaver's wife Vicki (holding a baby) and 14-year-old son Sammy at Ruby Ridge, Idaho in 1992. Sniper Lon Horiuchi was never convicted. $3.1M settlement paid to the Weaver family.",
    category: "Government Overreach",
    severity: "critical",
    date: "September 5, 2010",
    entityCount: 4,
    tags: ["Ruby Ridge", "FBI", "US Marshals", "Horiuchi"],
  },
  {
    id: "civil-forfeiture-1",
    slug: "civil-asset-forfeiture",
    title: "Civil Asset Forfeiture Abuse",
    summary: "Police seize billions in property from Americans never charged with crimes. $68.8 billion seized 2000-2019. Departments keep proceeds, creating perverse incentives. Disproportionately targets minorities and the poor.",
    category: "Civil Rights",
    severity: "critical",
    date: "February 27, 2014",
    entityCount: 4,
    tags: ["Civil Forfeiture", "Police", "Property Rights", "Due Process"],
  },
  {
    id: "enron-1",
    slug: "enron-scandal",
    title: "Enron Scandal",
    summary: "Enron executives committed massive securities fraud, hiding billions in debt while inflating revenues. $74 billion in shareholder value destroyed. 20,000 employees lost jobs and retirement savings. CEO Ken Lay and CFO Jeff Skilling convicted.",
    category: "Financial Crimes",
    severity: "critical",
    date: "October 18, 2009",
    entityCount: 6,
    tags: ["Enron", "Arthur Andersen", "Skilling", "Lay", "Securities Fraud"],
  },
  {
    id: "madoff-1",
    slug: "bernie-madoff-ponzi",
    title: "Bernie Madoff Ponzi Scheme",
    summary: "Largest financial fraud in history: $64.8 billion Ponzi scheme spanning decades. SEC ignored whistleblower Harry Markopolos for 10 years. Wiped out charities, pension funds, and thousands of individual investors.",
    category: "Financial Crimes",
    severity: "critical",
    date: "March 12, 2011",
    entityCount: 5,
    tags: ["Madoff", "Ponzi Scheme", "SEC", "Fraud"],
  },
  {
    id: "wells-fargo-1",
    slug: "wells-fargo-fraud",
    title: "Wells Fargo Fake Accounts Scandal",
    summary: "Wells Fargo employees created 3.5 million unauthorized accounts to meet sales quotas. $3 billion in fines. CEO John Stumpf resigned. Employees who complained were fired. Disproportionately harmed minorities.",
    category: "Financial Crimes",
    severity: "critical",
    date: "November 3, 2016",
    entityCount: 5,
    tags: ["Wells Fargo", "Fake Accounts", "Banking Fraud", "Consumer Fraud"],
  },
  {
    id: "bp-1",
    slug: "deepwater-horizon",
    title: "BP Deepwater Horizon Disaster",
    summary: "Worst oil spill in US history: 4.9 million barrels over 87 days. 11 workers killed. BP cut safety corners to save money. $65 billion in costs. Gulf ecosystem devastated. Ongoing health effects for cleanup workers.",
    category: "Corporate Crime",
    severity: "critical",
    date: "June 15, 2012",
    entityCount: 5,
    tags: ["BP", "Deepwater Horizon", "Oil Spill", "Gulf of Mexico", "Halliburton"],
  },
  {
    id: "exxon-1",
    slug: "exxon-climate-coverup",
    title: "Exxon Climate Change Cover-Up",
    summary: "ExxonMobil knew about climate change since 1977 but spent decades funding denial. Internal scientists accurately predicted warming. Company spent $30M+ on climate disinformation campaigns while publicly casting doubt.",
    category: "Corporate Crime",
    severity: "critical",
    date: "January 20, 2016",
    entityCount: 6,
    tags: ["Exxon", "Climate Denial", "Fossil Fuels", "Disinformation"],
  },
  {
    id: "tobacco-1",
    slug: "big-tobacco-coverup",
    title: "Big Tobacco Cover-Up",
    summary: "Tobacco industry knew cigarettes caused cancer since the 1950s but lied to Congress and the public for decades. 480,000 Americans die annually. $206 billion Master Settlement Agreement in 1998 barely scratched the surface.",
    category: "Corporate Crime",
    severity: "critical",
    date: "December 8, 2009",
    entityCount: 6,
    tags: ["Tobacco", "Philip Morris", "RJ Reynolds", "Cancer", "Perjury"],
  },
  {
    id: "pharma-1",
    slug: "purdue-pharma-oxycontin",
    title: "Purdue Pharma & the Sackler Family",
    summary: "The Sackler family's Purdue Pharma deliberately created the opioid epidemic. Knew OxyContin was addictive, marketed it as safe. 500,000+ dead. Family extracted $10.7 billion before bankruptcy. Criminal settlement but no prison time.",
    category: "Corporate Crime",
    severity: "critical",
    date: "April 14, 2015",
    entityCount: 7,
    tags: ["Sackler", "Purdue Pharma", "OxyContin", "Opioid", "FDA"],
  },
  {
    id: "dupont-1",
    slug: "dupont-pfas-poisoning",
    title: "DuPont PFAS Forever Chemicals",
    summary: "DuPont knowingly poisoned communities with PFAS 'forever chemicals' for decades. Contaminated drinking water for 100,000+ people. Internal documents showed they knew of health effects since 1961. $670M settlement.",
    category: "Corporate Crime",
    severity: "critical",
    date: "May 22, 2015",
    entityCount: 5,
    tags: ["DuPont", "PFAS", "C8", "Teflon", "Water Contamination"],
  },
  {
    id: "volkswagen-1",
    slug: "volkswagen-emissions",
    title: "Volkswagen Emissions Fraud",
    summary: "VW installed defeat devices in 11 million diesel vehicles worldwide to cheat emissions tests. Cars emitted up to 40x legal NOx limits. $34.69 billion in fines and settlements. CEO arrested.",
    category: "Corporate Crime",
    severity: "high",
    date: "October 19, 2015",
    entityCount: 4,
    tags: ["Volkswagen", "Dieselgate", "Emissions Fraud", "EPA"],
  },
  {
    id: "boeing-1",
    slug: "boeing-737-max",
    title: "Boeing 737 MAX Crashes",
    summary: "Boeing's 737 MAX killed 346 people in two crashes (Lion Air & Ethiopian Airlines). MCAS system flaw concealed from pilots and regulators. Internal emails showed employees knew of problems. Boeing charged with conspiracy to defraud.",
    category: "Corporate Crime",
    severity: "critical",
    date: "November 8, 2018",
    entityCount: 6,
    tags: ["Boeing", "737 MAX", "FAA", "MCAS", "Lion Air", "Ethiopian Airlines"],
  },
  {
    id: "ftx-1",
    slug: "ftx-crypto-fraud",
    title: "FTX Cryptocurrency Fraud",
    summary: "Sam Bankman-Fried stole $8 billion from FTX customers. Used customer funds for Alameda Research trading, political donations, and luxury spending. 25-year prison sentence. Second-largest financial fraud after Madoff.",
    category: "Financial Crimes",
    severity: "critical",
    date: "December 14, 2022",
    entityCount: 5,
    tags: ["FTX", "SBF", "Cryptocurrency", "Fraud", "Alameda Research"],
  },
  {
    id: "theranos-1",
    slug: "theranos-fraud",
    title: "Theranos Blood Testing Fraud",
    summary: "Elizabeth Holmes defrauded investors of $700M+ with fake blood-testing technology. Endangered patients with inaccurate results. Board included Henry Kissinger, James Mattis, George Shultz. Holmes sentenced to 11+ years.",
    category: "Financial Crimes",
    severity: "high",
    date: "October 30, 2018",
    entityCount: 5,
    tags: ["Theranos", "Elizabeth Holmes", "Silicon Valley", "Healthcare Fraud"],
  },
  {
    id: "slc-1",
    slug: "savings-and-loan-crisis",
    title: "Savings & Loan Crisis",
    summary: "1,043 savings institutions failed due to fraud and deregulation. $132 billion taxpayer bailout. Charles Keating's Lincoln Savings alone cost $3.4 billion. Keating Five senators investigated. Neil Bush's Silverado banking scandal.",
    category: "Financial Crimes",
    severity: "critical",
    date: "November 15, 2009",
    entityCount: 6,
    tags: ["S&L Crisis", "Keating Five", "Deregulation", "Banking Fraud"],
  },
  {
    id: "libor-1",
    slug: "libor-scandal",
    title: "LIBOR Rate-Rigging Scandal",
    summary: "Major banks rigged LIBOR interest rate that affects $350 trillion in financial contracts. Banks manipulated rates to profit from trades and appear healthier during the financial crisis. $9 billion in fines. Multiple bankers convicted.",
    category: "Financial Crimes",
    severity: "critical",
    date: "August 24, 2015",
    entityCount: 5,
    tags: ["LIBOR", "Barclays", "Deutsche Bank", "Rate Rigging", "Banking Fraud"],
  },
  {
    id: "panama-1",
    slug: "panama-papers",
    title: "Panama Papers",
    summary: "11.5 million leaked documents from Mossack Fonseca revealed hidden wealth of 140+ world leaders, celebrities, and criminals. Exposed $11.3 trillion in offshore holdings. Led to arrests, resignations, and tax recoveries worldwide.",
    category: "Financial Crimes",
    severity: "critical",
    date: "April 8, 2016",
    entityCount: 6,
    tags: ["Panama Papers", "Tax Evasion", "Offshore", "Mossack Fonseca"],
  },
  {
    id: "pentagon-papers-1",
    slug: "pentagon-papers",
    title: "Pentagon Papers",
    summary: "Daniel Ellsberg leaked 7,000 pages proving the US government systematically lied about Vietnam War for decades. Four presidents misled Congress and the public. Nixon's attempts to suppress led directly to Watergate.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "October 3, 2009",
    entityCount: 5,
    tags: ["Pentagon Papers", "Ellsberg", "Vietnam", "Nixon", "First Amendment"],
  },
  {
    id: "afghanistan-papers-1",
    slug: "afghanistan-papers",
    title: "Afghanistan Papers",
    summary: "Washington Post obtained documents proving US officials systematically lied about progress in Afghanistan for 20 years. $2.3 trillion spent. Officials admitted privately the war was unwinnable while publicly claiming success.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "January 6, 2020",
    entityCount: 5,
    tags: ["Afghanistan", "Pentagon", "War", "Lies", "Nation Building"],
  },
  {
    id: "whistleblowers-1",
    slug: "whistleblower-persecution",
    title: "Whistleblower Persecution",
    summary: "Systematic destruction of those who expose government crimes: Chelsea Manning (7 years solitary), Edward Snowden (exile), Reality Winner (5 years prison), Daniel Hale (45 months), John Kiriakou (30 months for exposing CIA torture).",
    category: "Civil Rights",
    severity: "critical",
    date: "September 18, 2013",
    entityCount: 8,
    tags: ["Whistleblowers", "Espionage Act", "Manning", "Snowden", "Winner"],
  },
  {
    id: "paperclip-1",
    slug: "operation-paperclip",
    title: "Operation Paperclip",
    summary: "US government secretly recruited 1,600+ Nazi scientists after WWII, including war criminals who experimented on concentration camp prisoners. Whitewashed their records and gave them security clearances, citizenship, and government jobs.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "February 8, 2010",
    entityCount: 5,
    tags: ["Operation Paperclip", "NASA", "Nazis", "Von Braun", "CIA"],
  },
  {
    id: "northwoods-1",
    slug: "operation-northwoods",
    title: "Operation Northwoods",
    summary: "1962 Joint Chiefs of Staff proposed false flag attacks against Americans — bombings, hijackings, sinking boats — to justify invading Cuba. Signed by Chairman Lyman Lemnitzer. Rejected by JFK. Declassified in 1997.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "March 27, 2010",
    entityCount: 4,
    tags: ["False Flag", "Joint Chiefs", "Cuba", "JFK", "Lemnitzer"],
  },
  {
    id: "phoenix-1",
    slug: "phoenix-program",
    title: "Phoenix Program",
    summary: "CIA assassination program in Vietnam that killed 20,000-40,000 suspected Viet Cong. Included torture, execution without trial, and civilian massacres. William Colby later admitted 'it was wrong, I think.'",
    category: "War Crimes",
    severity: "critical",
    date: "June 22, 2011",
    entityCount: 5,
    tags: ["Phoenix Program", "CIA", "Vietnam", "Assassination", "Torture"],
  },
  {
    id: "gladio-1",
    slug: "operation-gladio",
    title: "Operation Gladio",
    summary: "CIA/NATO secret armies across Europe conducted false flag terrorist attacks blamed on leftists to influence elections. Exposed in 1990. Linked to bombings in Italy (Piazza Fontana, Bologna station), Belgium, and Turkey.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "September 14, 2011",
    entityCount: 5,
    tags: ["Gladio", "NATO", "CIA", "False Flag", "Stay-Behind Armies"],
  },
  {
    id: "fast-furious-1",
    slug: "operation-fast-and-furious",
    title: "Operation Fast and Furious",
    summary: "ATF knowingly allowed 2,000+ firearms to be trafficked to Mexican drug cartels to 'track' them. Lost track of most guns. Weapons found at murder scenes including Border Patrol Agent Brian Terry. AG Holder held in contempt.",
    category: "Government Cover-Up",
    severity: "high",
    date: "July 18, 2013",
    entityCount: 5,
    tags: ["Fast and Furious", "ATF", "Holder", "Gun Walking", "Mexico"],
  },
  {
    id: "extraordinary-rendition-1",
    slug: "extraordinary-rendition",
    title: "Extraordinary Rendition Program",
    summary: "CIA kidnapped suspects from 136 countries, flew them to black sites and allied nations to be tortured. 119+ known victims. Airlines and 54 countries complicit. Innocent people tortured for months. European Court found multiple violations.",
    category: "War Crimes",
    severity: "critical",
    date: "April 5, 2013",
    entityCount: 5,
    tags: ["Rendition", "CIA", "Black Sites", "Torture", "Kidnapping"],
  },
  {
    id: "school-americas-1",
    slug: "school-of-the-americas",
    title: "School of the Americas",
    summary: "US military facility trained Latin American soldiers who committed massacres, assassinations, and coups. Graduates include dictators and death squad leaders across El Salvador, Guatemala, Chile, Argentina, and Honduras.",
    category: "War Crimes",
    severity: "critical",
    date: "December 11, 2011",
    entityCount: 5,
    tags: ["SOA", "WHINSEC", "Death Squads", "Latin America", "Military Training"],
  },
  {
    id: "nuclear-testing-1",
    slug: "nuclear-testing-victims",
    title: "Nuclear Testing on Americans",
    summary: "US government conducted 1,032 nuclear tests exposing soldiers, civilians, and Pacific Islanders to radiation. Downwinders in Nevada, Utah, and Arizona developed cancer at elevated rates. Marshall Islands still uninhabitable. Atomic veterans denied care.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "August 14, 2009",
    entityCount: 5,
    tags: ["Nuclear Testing", "Downwinders", "Marshall Islands", "Atomic Veterans", "Radiation"],
  },
  {
    id: "agent-orange-1",
    slug: "agent-orange",
    title: "Agent Orange",
    summary: "US sprayed 20 million gallons of Agent Orange over Vietnam, contaminating 4.8 million people. Birth defects continue generations later. Dow Chemical and Monsanto knew of dioxin dangers. US veterans denied benefits for decades.",
    category: "War Crimes",
    severity: "critical",
    date: "July 2, 2011",
    entityCount: 5,
    tags: ["Agent Orange", "Vietnam", "Dow Chemical", "Monsanto", "Dioxin"],
  },
  {
    id: "jackson-water-1",
    slug: "jackson-water-crisis",
    title: "Jackson Mississippi Water Crisis",
    summary: "150,000 residents of majority-Black Jackson, Mississippi left without safe drinking water due to decades of disinvestment. Lead contamination, boil-water advisories lasting months. State refused to fund repairs for the capital city.",
    category: "Environmental Racism",
    severity: "critical",
    date: "September 7, 2022",
    entityCount: 4,
    tags: ["Jackson", "Water Crisis", "Environmental Racism", "Infrastructure"],
  },
  {
    id: "lead-poisoning-1",
    slug: "lead-poisoning-coverup",
    title: "Lead Poisoning Cover-Up",
    summary: "Lead industry knew lead paint and leaded gasoline poisoned children since the 1920s but fought regulation for 50+ years. 500,000 children still have elevated blood lead levels. Disproportionately affects Black communities.",
    category: "Corporate Crime",
    severity: "critical",
    date: "November 30, 2012",
    entityCount: 5,
    tags: ["Lead Poisoning", "Lead Paint", "Leaded Gas", "Children", "Cover-Up"],
  },
  {
    id: "tulsa-1",
    slug: "tulsa-race-massacre",
    title: "Tulsa Race Massacre & Cover-Up",
    summary: "White mobs destroyed 'Black Wall Street' on May 31-June 1, 1921, killing up to 300 Black residents and displacing 10,000. Covered up for decades — removed from history books, mass graves concealed. No perpetrators ever prosecuted.",
    category: "Civil Rights",
    severity: "critical",
    date: "January 8, 2010",
    entityCount: 4,
    tags: ["Tulsa", "Black Wall Street", "Greenwood", "Race Massacre", "Cover-Up"],
  },
  {
    id: "emmett-till-1",
    slug: "emmett-till",
    title: "Emmett Till Murder & Acquittal",
    summary: "14-year-old Emmett Till brutally murdered in Mississippi in 1955. His killers Bryant and Milam acquitted by all-white jury in 67 minutes, then confessed in a paid magazine interview. Carolyn Bryant admitted she lied. Case reopened in 2018.",
    category: "Civil Rights",
    severity: "critical",
    date: "February 19, 2010",
    entityCount: 4,
    tags: ["Emmett Till", "Lynching", "Mississippi", "Civil Rights"],
  },
  {
    id: "redlining-1",
    slug: "redlining-housing-discrimination",
    title: "Redlining & Housing Discrimination",
    summary: "Federal government created maps denying mortgages to Black neighborhoods from 1934. Banks, realtors, and the FHA enforced racial segregation. Created the racial wealth gap: median white family wealth is 10x Black family wealth.",
    category: "Civil Rights",
    severity: "critical",
    date: "September 20, 2012",
    entityCount: 5,
    tags: ["Redlining", "Housing Discrimination", "FHA", "Racial Wealth Gap", "Segregation"],
  },
  {
    id: "sundown-1",
    slug: "sundown-towns",
    title: "Sundown Towns",
    summary: "Thousands of US towns banned Black residents after dark, enforced through violence, signs, and sirens. Over 10,000 documented sundown towns across all 50 states. Legacy of exclusion persists in housing patterns today.",
    category: "Civil Rights",
    severity: "critical",
    date: "October 14, 2012",
    entityCount: 3,
    tags: ["Sundown Towns", "Segregation", "Racism", "Housing"],
  },
  {
    id: "lynching-1",
    slug: "lynching-in-america",
    title: "Lynching in America",
    summary: "4,400+ documented racial terror lynchings between 1877 and 1950. Used to maintain white supremacy and suppress Black political participation. Congress failed to pass anti-lynching legislation for over 100 years until the Emmett Till Act of 2022.",
    category: "Civil Rights",
    severity: "critical",
    date: "April 22, 2012",
    entityCount: 4,
    tags: ["Lynching", "Racial Terror", "Jim Crow", "White Supremacy"],
  },
  {
    id: "forced-sterilization-1",
    slug: "forced-sterilization",
    title: "Forced Sterilization Programs",
    summary: "States forcibly sterilized 60,000+ Americans deemed 'unfit' under eugenics programs from 1907 to 1981. Targeted Black women, Indigenous women, disabled people, and immigrants. California sterilized the most. ICE facility sterilizations reported in 2020.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "March 6, 2012",
    entityCount: 5,
    tags: ["Eugenics", "Forced Sterilization", "Racism", "Buck v. Bell", "ICE"],
  },
  {
    id: "convict-leasing-1",
    slug: "convict-leasing",
    title: "Convict Leasing System",
    summary: "After the 13th Amendment abolished slavery 'except as punishment for crime,' Southern states criminalized Black life and leased prisoners to corporations. Thousands died in mines, factories, and farms. Slavery by another name until 1942.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "May 18, 2012",
    entityCount: 4,
    tags: ["Convict Leasing", "13th Amendment", "Slavery", "Prison Labor"],
  },
  {
    id: "laos-1",
    slug: "laos-secret-bombing",
    title: "Secret Bombing of Laos",
    summary: "US dropped 2.5 million tons of bombs on Laos from 1964-1973 — more than all bombs dropped in WWII combined. 200,000+ civilians killed. 80 million unexploded bombs remain. The most heavily bombed country per capita in history.",
    category: "War Crimes",
    severity: "critical",
    date: "March 15, 2011",
    entityCount: 4,
    tags: ["Laos", "Secret War", "Bombing", "UXO", "Vietnam War"],
  },
  {
    id: "cambodia-1",
    slug: "cambodia-bombing",
    title: "Cambodia Secret Bombing",
    summary: "Nixon and Kissinger secretly bombed Cambodia from 1969-1973, killing 50,000-150,000 civilians. Operation Menu was concealed from Congress. Destabilized Cambodia and contributed to the rise of the Khmer Rouge genocide.",
    category: "War Crimes",
    severity: "critical",
    date: "April 2, 2011",
    entityCount: 4,
    tags: ["Cambodia", "Nixon", "Kissinger", "Bombing", "Khmer Rouge"],
  },
  {
    id: "libya-1",
    slug: "libya-intervention",
    title: "Libya Intervention & State Collapse",
    summary: "2011 NATO intervention in Libya led to state collapse, open-air slave markets, and ongoing civil war. 'We came, we saw, he died' — Clinton on Gaddafi. No plan for post-intervention stability. Created refugee crisis and weapons proliferation.",
    category: "War Crimes",
    severity: "critical",
    date: "April 20, 2013",
    entityCount: 5,
    tags: ["Libya", "NATO", "Gaddafi", "State Failure", "Slave Markets"],
  },
  {
    id: "yemen-1",
    slug: "yemen-war",
    title: "Yemen War & Famine",
    summary: "US-backed Saudi coalition created the world's worst humanitarian crisis. 377,000+ dead. 85,000 children starved. US provided bombs, targeting intelligence, and mid-air refueling. Both Obama and Trump administrations complicit.",
    category: "War Crimes",
    severity: "critical",
    date: "July 5, 2017",
    entityCount: 5,
    tags: ["Yemen", "Saudi Arabia", "Famine", "War Crimes", "Arms Sales"],
  },
  {
    id: "somalia-1",
    slug: "somalia-intervention",
    title: "Somalia: Black Hawk Down to Drone Wars",
    summary: "From the 1993 Battle of Mogadishu to decades of drone strikes. US killed hundreds of civilians in airstrikes. No congressional authorization. Africa Command (AFRICOM) operates with minimal oversight across the continent.",
    category: "War Crimes",
    severity: "high",
    date: "November 12, 2013",
    entityCount: 4,
    tags: ["Somalia", "AFRICOM", "Drone Strikes", "Special Operations"],
  },
  {
    id: "panama-invasion-1",
    slug: "panama-invasion",
    title: "US Invasion of Panama",
    summary: "1989 invasion killed up to 3,000 Panamanian civilians to remove CIA asset Manuel Noriega. Largest US military operation since Vietnam. Destroyed El Chorrillo neighborhood. Noriega had been a CIA informant for decades while trafficking drugs.",
    category: "War Crimes",
    severity: "critical",
    date: "November 22, 2011",
    entityCount: 4,
    tags: ["Panama", "Noriega", "CIA", "Invasion"],
  },
  {
    id: "grenada-1",
    slug: "grenada-invasion",
    title: "Invasion of Grenada",
    summary: "1983 US invasion of Grenada on false pretenses of 'rescuing' medical students. Violated international law. UN General Assembly condemned it 108-9. Served as template for future unilateral military interventions.",
    category: "War Crimes",
    severity: "high",
    date: "December 5, 2011",
    entityCount: 3,
    tags: ["Grenada", "Reagan", "Invasion", "International Law"],
  },
  {
    id: "stingray-1",
    slug: "stingray-surveillance",
    title: "Stingray Cell Phone Surveillance",
    summary: "Police secretly use cell-site simulators (Stingrays) to track phone locations without warrants. FBI requires police to drop cases rather than reveal the technology. Used at Black Lives Matter protests. No democratic oversight.",
    category: "Civil Rights",
    severity: "high",
    date: "March 14, 2016",
    entityCount: 4,
    tags: ["Stingray", "Surveillance", "Cell Phone Tracking", "Fourth Amendment"],
  },
  {
    id: "facial-recognition-1",
    slug: "facial-recognition-surveillance",
    title: "Facial Recognition & AI Surveillance",
    summary: "Police use facial recognition that misidentifies Black people at 10-100x the rate of white people. Multiple wrongful arrests. Clearview AI scraped billions of photos. China-style mass surveillance infrastructure being built domestically.",
    category: "Civil Rights",
    severity: "critical",
    date: "August 12, 2019",
    entityCount: 5,
    tags: ["Facial Recognition", "AI", "Clearview AI", "Bias", "Surveillance"],
  },
  {
    id: "predictive-policing-1",
    slug: "predictive-policing",
    title: "Predictive Policing & Algorithmic Bias",
    summary: "Police use algorithms trained on biased data to predict crime, creating feedback loops that over-police Black and brown communities. PredPol, Palantir, and other systems encode and amplify racial bias into law enforcement.",
    category: "Civil Rights",
    severity: "high",
    date: "October 5, 2019",
    entityCount: 4,
    tags: ["Predictive Policing", "Algorithm", "Bias", "Palantir", "PredPol"],
  },
  {
    id: "fox-news-1",
    slug: "fox-news-propaganda",
    title: "Fox News Propaganda Machine",
    summary: "Fox News operated as state-aligned propaganda: promoted election lies ($787.5M Dominion settlement proved they knew), amplified white supremacist narratives, and coordinated messaging with Trump administration. Sean Hannity texted Trump daily.",
    category: "Disinformation",
    severity: "critical",
    date: "June 20, 2019",
    entityCount: 7,
    tags: ["Fox News", "Murdoch", "Propaganda", "Dominion", "Disinformation"],
  },
  {
    id: "sinclair-1",
    slug: "sinclair-broadcasting",
    title: "Sinclair Broadcasting & Local News Capture",
    summary: "Sinclair Broadcast Group controls 294 TV stations reaching 40% of US households. Forces local anchors to read identical conservative scripts. 'This is extremely dangerous to our democracy' viral video exposed coordinated propaganda.",
    category: "Disinformation",
    severity: "high",
    date: "April 3, 2018",
    entityCount: 4,
    tags: ["Sinclair", "Local News", "Propaganda", "Media Consolidation"],
  },
  {
    id: "qanon-1",
    slug: "qanon-radicalization",
    title: "QAnon Radicalization",
    summary: "QAnon conspiracy movement radicalized millions: led to violence, kidnapping attempts, and the January 6 insurrection. Multiple adherents elected to Congress. Social media platforms amplified content for engagement. Linked to domestic terrorism incidents.",
    category: "Domestic Terrorism",
    severity: "critical",
    date: "November 2, 2020",
    entityCount: 5,
    tags: ["QAnon", "Radicalization", "Domestic Terrorism", "Social Media", "Conspiracy"],
  },
  {
    id: "citizens-united-1",
    slug: "citizens-united",
    title: "Citizens United & Dark Money",
    summary: "Supreme Court's 2010 Citizens United ruling unleashed unlimited corporate spending in elections. $14.4 billion in outside spending since. Koch network alone spent $1.5 billion. Campaigns now drowned in untraceable dark money.",
    category: "Corruption",
    severity: "critical",
    date: "March 1, 2012",
    entityCount: 6,
    tags: ["Citizens United", "Dark Money", "Koch", "Campaign Finance", "Supreme Court"],
  },
  {
    id: "koch-1",
    slug: "koch-network",
    title: "Koch Network & Political Influence",
    summary: "Koch brothers spent billions reshaping American politics: funded climate denial, attacked unions, pushed voter suppression, captured state legislatures, and built a political machine rivaling the Republican Party itself.",
    category: "Corruption",
    severity: "critical",
    date: "June 14, 2014",
    entityCount: 6,
    tags: ["Koch Brothers", "Dark Money", "ALEC", "Americans for Prosperity"],
  },
  {
    id: "alec-1",
    slug: "alec-model-legislation",
    title: "ALEC: Corporate-Written Laws",
    summary: "American Legislative Exchange Council lets corporations write model bills that state legislators introduce as their own. Produced Stand Your Ground, voter ID, anti-union, and private prison legislation. 1,000+ bills introduced annually.",
    category: "Corruption",
    severity: "critical",
    date: "August 28, 2014",
    entityCount: 5,
    tags: ["ALEC", "Model Legislation", "Corporate Influence", "Koch", "Stand Your Ground"],
  },
  {
    id: "leonard-leo-1",
    slug: "leonard-leo-network",
    title: "Leonard Leo's Judicial Capture",
    summary: "Leonard Leo's dark money network spent $580M+ to reshape the federal judiciary. Handpicked 6 Supreme Court justices. Network of anonymous donors funneled through Donors Trust. Received $1.6 billion from single donor Barre Seid.",
    category: "Corruption",
    severity: "critical",
    date: "September 15, 2020",
    entityCount: 6,
    tags: ["Leonard Leo", "Federalist Society", "Dark Money", "Judicial Capture", "Donors Trust"],
  },
  {
    id: "gerrymandering-1",
    slug: "gerrymandering",
    title: "Extreme Gerrymandering",
    summary: "Both parties use gerrymandering, but REDMAP (2010) was most systematic: Republicans spent $30M redistricting to lock in majorities. Won 33 more House seats than vote share warranted. Supreme Court ruled it non-justiciable in Rucho v. Common Cause.",
    category: "Election Interference",
    severity: "critical",
    date: "January 18, 2014",
    entityCount: 5,
    tags: ["Gerrymandering", "REDMAP", "Redistricting", "Supreme Court", "Democracy"],
  },
  {
    id: "ice-abuses-1",
    slug: "ice-detention-abuses",
    title: "ICE Detention Abuses",
    summary: "ICE detention facilities documented widespread abuse: forced hysterectomies at Irwin County (Dr. Mahendra Amin), sexual assault, deaths in custody, medical neglect, and deplorable conditions. 200+ deaths in ICE custody since 2003.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "October 22, 2019",
    entityCount: 5,
    tags: ["ICE", "Detention", "Hysterectomies", "Deaths in Custody", "Immigration"],
  },
  {
    id: "mmiw-1",
    slug: "missing-murdered-indigenous-women",
    title: "Missing & Murdered Indigenous Women",
    summary: "Indigenous women face murder rates 10x the national average. 5,712 reported missing in 2016 alone — only 116 logged by DOJ. Jurisdictional gaps between tribal, state, and federal law create accountability vacuums. Cases systematically ignored.",
    category: "Civil Rights",
    severity: "critical",
    date: "May 5, 2015",
    entityCount: 4,
    tags: ["MMIW", "MMIWG", "Indigenous Women", "Jurisdictional Gaps"],
  },
  {
    id: "dobbs-1",
    slug: "roe-v-wade-overturn",
    title: "Roe v. Wade Overturn & Consequences",
    summary: "Dobbs v. Jackson overturned 50 years of reproductive rights. 14 states immediately banned abortion. Women denied care during miscarriages. Maternal mortality rising. Dark money network spent decades orchestrating the overturn through judicial appointments.",
    category: "Civil Rights",
    severity: "critical",
    date: "July 1, 2022",
    entityCount: 6,
    tags: ["Dobbs", "Roe v. Wade", "Abortion", "Reproductive Rights", "Supreme Court"],
  },
  {
    id: "rwanda-1",
    slug: "rwanda-genocide-inaction",
    title: "Rwanda Genocide - US Inaction",
    summary: "800,000 Tutsis massacred in 100 days while the US refused to call it genocide so it wouldn't have to act. Clinton administration blocked UN reinforcements. Samantha Power: 'Bystanders to Genocide.' US chose inaction despite full knowledge.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "December 4, 2011",
    entityCount: 4,
    tags: ["Rwanda", "Genocide", "UN", "Clinton", "Inaction"],
  },
  {
    id: "indonesia-1",
    slug: "indonesia-mass-killings",
    title: "Indonesian Mass Killings (1965-66)",
    summary: "CIA provided kill lists to Indonesian military which massacred 500,000-1,000,000 suspected communists. US embassy tracked killings, called it 'an excellent development.' Documents declassified in 2017 confirmed US complicity.",
    category: "War Crimes",
    severity: "critical",
    date: "October 7, 2012",
    entityCount: 4,
    tags: ["Indonesia", "CIA", "Mass Killings", "Suharto", "Anti-Communism"],
  },
  {
    id: "east-timor-1",
    slug: "east-timor-genocide",
    title: "East Timor Genocide",
    summary: "Indonesia invaded East Timor in 1975 with US blessing. Gerald Ford and Kissinger gave green light hours before the invasion. 100,000-180,000 killed — up to a third of the population. US supplied 90% of Indonesia's weapons.",
    category: "War Crimes",
    severity: "critical",
    date: "November 10, 2012",
    entityCount: 4,
    tags: ["East Timor", "Indonesia", "Kissinger", "Ford", "Genocide"],
  },
  {
    id: "guatemala-1",
    slug: "guatemala-genocide",
    title: "Guatemala Genocide & CIA Coup",
    summary: "CIA overthrew democratically elected Arbenz in 1954 for United Fruit Company. Subsequent US-backed military governments committed genocide against Maya people: 200,000 killed, 45,000 disappeared. Reagan called dictator Ríos Montt 'a man of great integrity.'",
    category: "War Crimes",
    severity: "critical",
    date: "June 8, 2012",
    entityCount: 5,
    tags: ["Guatemala", "CIA", "United Fruit", "Genocide", "Maya"],
  },
  {
    id: "el-salvador-1",
    slug: "el-salvador-death-squads",
    title: "El Salvador: US-Backed Death Squads",
    summary: "US funded and trained Salvadoran military responsible for 75,000 deaths during civil war. El Mozote massacre killed 800+ civilians. Archbishop Romero assassinated. School of the Americas graduates led death squads.",
    category: "War Crimes",
    severity: "critical",
    date: "July 24, 2012",
    entityCount: 5,
    tags: ["El Salvador", "Death Squads", "El Mozote", "Romero", "SOA"],
  },
  {
    id: "haiti-1",
    slug: "haiti-exploitation",
    title: "US Exploitation of Haiti",
    summary: "200 years of US exploitation: military occupation (1915-34), support for Duvalier dictatorships, coups against Aristide, Clintons' post-earthquake profiteering. $13.3 billion in earthquake aid — Haitians received just 1%. Cholera introduced by UN peacekeepers.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "August 20, 2012",
    entityCount: 5,
    tags: ["Haiti", "Clinton", "Occupation", "Earthquake", "Exploitation"],
  },
  {
    id: "apartheid-1",
    slug: "us-support-for-apartheid",
    title: "US Support for Apartheid South Africa",
    summary: "US supported apartheid South Africa for decades. Reagan vetoed sanctions, called Nelson Mandela's ANC 'terrorists.' CIA provided intelligence that led to Mandela's arrest. US companies profited from apartheid labor practices.",
    category: "Civil Rights",
    severity: "critical",
    date: "September 8, 2012",
    entityCount: 5,
    tags: ["Apartheid", "South Africa", "Mandela", "Reagan", "CIA"],
  },
  {
    id: "union-busting-1",
    slug: "union-busting",
    title: "Systematic Union Busting",
    summary: "Corporations spend $340 million/year on anti-union consultants. Amazon, Starbucks, Walmart, and Tesla use surveillance, firings, and mandatory anti-union meetings. Union membership dropped from 35% (1954) to 10% (2023). NLRB gutted under Trump.",
    category: "Labor Rights",
    severity: "critical",
    date: "March 19, 2018",
    entityCount: 6,
    tags: ["Union Busting", "Amazon", "Starbucks", "NLRB", "Labor Rights"],
  },
  {
    id: "amazon-labor-1",
    slug: "amazon-labor-abuses",
    title: "Amazon Labor Exploitation",
    summary: "Amazon warehouse workers: forced to urinate in bottles, 6 killed at Bessemer tornado, union-busting, algorithmic firings, Prime Day injuries spike 45%. Drivers have 14-hour shifts with no bathroom breaks. Bezos wealth: $200 billion.",
    category: "Labor Rights",
    severity: "critical",
    date: "May 14, 2021",
    entityCount: 5,
    tags: ["Amazon", "Bezos", "Warehouse", "Union Busting", "Labor"],
  },
  {
    id: "school-shootings-1",
    slug: "gun-violence-inaction",
    title: "Gun Violence: Congressional Inaction",
    summary: "45,000 Americans die from gun violence annually. 400+ mass shootings per year. After Sandy Hook (20 first-graders killed), Congress did nothing. After Uvalde (19 children killed), minimal action. NRA spent $50M blocking legislation.",
    category: "Public Health",
    severity: "critical",
    date: "December 18, 2012",
    entityCount: 6,
    tags: ["Gun Violence", "NRA", "Sandy Hook", "Uvalde", "Mass Shootings"],
  },
  {
    id: "student-debt-1",
    slug: "student-debt-crisis",
    title: "Student Debt Crisis",
    summary: "Student debt reached $1.77 trillion. For-profit colleges like ITT Tech, University of Phoenix, and Corinthian defrauded millions. DeVos blocked relief as Education Secretary while owning shares in student loan servicers.",
    category: "Financial Crimes",
    severity: "high",
    date: "September 20, 2018",
    entityCount: 5,
    tags: ["Student Debt", "For-Profit Colleges", "DeVos", "Predatory Lending"],
  },
  {
    id: "standing-rock-1",
    slug: "standing-rock",
    title: "Standing Rock & Pipeline Repression",
    summary: "Water protectors opposing Dakota Access Pipeline met with militarized police response: rubber bullets, water cannons in freezing weather, attack dogs. Pipeline built through unceded Sioux territory. Corporate surveillance and infiltration of protesters.",
    category: "Civil Rights",
    severity: "critical",
    date: "September 10, 2016",
    entityCount: 5,
    tags: ["Standing Rock", "DAPL", "Indigenous Rights", "Police Militarization"],
  },
  {
    id: "pharmaceutical-pricing-1",
    slug: "pharmaceutical-price-gouging",
    title: "Pharmaceutical Price Gouging",
    summary: "US pays 2-3x what other nations pay for drugs. Insulin costs $300+ vs $30 in Canada. Martin Shkreli raised Daraprim 5,500%. Medicare was banned from negotiating prices until 2022. Pharma spends $300M/year lobbying — more than any industry.",
    category: "Corporate Crime",
    severity: "critical",
    date: "November 5, 2015",
    entityCount: 5,
    tags: ["Drug Prices", "Insulin", "Pharma Lobbying", "Medicare", "Shkreli"],
  },
  {
    id: "medical-bankruptcy-1",
    slug: "medical-bankruptcy",
    title: "Medical Debt & Healthcare Bankruptcy",
    summary: "100 million Americans carry medical debt. Medical bills are #1 cause of bankruptcy. 66.5% of all bankruptcies linked to medical issues. US spends $4.3 trillion on healthcare with worse outcomes than countries spending half as much.",
    category: "Public Health",
    severity: "critical",
    date: "February 15, 2015",
    entityCount: 4,
    tags: ["Medical Debt", "Bankruptcy", "Healthcare", "Insurance Industry"],
  },
  {
    id: "mccarthy-1",
    slug: "mccarthyism-red-scare",
    title: "McCarthyism & the Red Scare",
    summary: "Senator Joe McCarthy's crusade destroyed thousands of lives through baseless accusations of communism. HUAC, loyalty oaths, blacklists. Hollywood Ten imprisoned. Thousands fired from government. FBI's role in feeding McCarthy information.",
    category: "Civil Rights",
    severity: "critical",
    date: "December 20, 2009",
    entityCount: 5,
    tags: ["McCarthy", "Red Scare", "HUAC", "Blacklist", "FBI"],
  },
  {
    id: "october-surprise-1",
    slug: "october-surprise-1980",
    title: "1980 October Surprise",
    summary: "Evidence suggests Reagan campaign negotiated with Iran to delay hostage release until after the 1980 election, undermining Carter. Hostages released minutes after Reagan's inauguration. Iran-Contra arms deals followed.",
    category: "Election Interference",
    severity: "critical",
    date: "July 22, 2011",
    entityCount: 5,
    tags: ["October Surprise", "Reagan", "Iran Hostages", "Carter", "Election"],
  },
  {
    id: "cia-drugs-1",
    slug: "cia-drug-trafficking",
    title: "CIA Drug Trafficking",
    summary: "CIA facilitated drug trafficking to fund covert operations: Contra cocaine flooded Black communities (Gary Webb's 'Dark Alliance'), Air America heroin in Vietnam/Laos, Afghan opium trafficking. Webb found dead from 'two gunshots to the head' ruled suicide.",
    category: "Government Cover-Up",
    severity: "critical",
    date: "January 14, 2011",
    entityCount: 6,
    tags: ["CIA", "Cocaine", "Contras", "Gary Webb", "Dark Alliance", "Crack"],
  },
  {
    id: "iran-1953-detail-1",
    slug: "guatemala-coup-1954",
    title: "CIA Guatemala Coup (1954)",
    summary: "CIA's Operation PBSUCCESS overthrew democratically elected President Jacobo Árbenz to protect United Fruit Company profits. Replaced with military junta that began decades of genocide, death squads, and repression.",
    category: "War Crimes",
    severity: "critical",
    date: "May 14, 2012",
    entityCount: 5,
    tags: ["Guatemala", "CIA", "United Fruit", "Árbenz", "Coup"],
  },
  {
    id: "cointelpro-blk-1",
    slug: "war-on-black-america",
    title: "FBI's War on Black America",
    summary: "FBI systematically targeted Black leaders and movements: MLK surveillance and harassment, Black Panther infiltration and assassinations, Fred Hampton murder, MOVE bombing, BLM surveillance. From 1950s COINTELPRO to 2017 'Black Identity Extremist' label.",
    category: "Civil Rights",
    severity: "critical",
    date: "August 27, 2010",
    entityCount: 7,
    tags: ["FBI", "COINTELPRO", "Black Panthers", "MLK", "BLM", "Racism"],
  },
  {
    id: "syphilis-1",
    slug: "guatemala-syphilis-experiments",
    title: "Guatemala Syphilis Experiments",
    summary: "From 1946-1948, US researchers deliberately infected 1,300+ Guatemalans — including prisoners, sex workers, soldiers, and mental patients — with syphilis and gonorrhea without consent. Discovered in 2010. Obama apologized. No one was ever held accountable.",
    category: "Crimes Against Humanity",
    severity: "critical",
    date: "October 18, 2010",
    entityCount: 4,
    tags: ["Guatemala", "Syphilis", "Human Experimentation", "NIH"],
  },
  {
    id: "flint-water-expanded-1",
    slug: "water-contamination-nationwide",
    title: "Water Contamination Across America",
    summary: "Beyond Flint: 2,000+ water systems across all 50 states have dangerous lead levels. Newark, Jackson MS, and hundreds of communities affected. Military bases contaminated with PFAS. EPA consistently underfunded. Environmental racism drives exposure.",
    category: "Environmental Racism",
    severity: "critical",
    date: "April 8, 2017",
    entityCount: 5,
    tags: ["Water Contamination", "Lead", "PFAS", "EPA", "Environmental Racism"],
  },
  {
    id: "death-penalty-1",
    slug: "death-penalty-injustice",
    title: "Death Penalty Injustice",
    summary: "190+ death row exonerations — for every 8 executions, 1 person exonerated. Racial bias: Black people 4x more likely to receive death sentences. Innocent people executed. Botched executions. Cost: $1.26M more per case than life imprisonment.",
    category: "Civil Rights",
    severity: "critical",
    date: "February 2, 2013",
    entityCount: 5,
    tags: ["Death Penalty", "Innocence", "Exonerations", "Racial Bias", "Execution"],
  },
  {
    id: "solitary-1",
    slug: "solitary-confinement",
    title: "Solitary Confinement as Torture",
    summary: "80,000+ Americans in solitary confinement on any given day, some for decades. UN considers it torture after 15 days. Causes psychosis, hallucinations, self-harm. Kalief Browder spent 2 years in solitary at Rikers as a teenager for a crime he didn't commit, then died by suicide.",
    category: "Civil Rights",
    severity: "critical",
    date: "June 15, 2014",
    entityCount: 4,
    tags: ["Solitary Confinement", "Torture", "Kalief Browder", "Rikers", "Mental Health"],
  },
  {
    id: "police-militarization-1",
    slug: "police-militarization",
    title: "Police Militarization (1033 Program)",
    summary: "Pentagon's 1033 program transferred $7.4 billion in military equipment to police: tanks, grenade launchers, helicopters, bayonets. 8,000 agencies received equipment. Ferguson 2014 showed military-grade response to protesters. Obama limited it; Trump reversed.",
    category: "Civil Rights",
    severity: "critical",
    date: "September 25, 2014",
    entityCount: 5,
    tags: ["1033 Program", "Militarization", "Ferguson", "Pentagon", "Police"],
  },
  {
    id: "no-knock-1",
    slug: "no-knock-raids",
    title: "No-Knock Raids & Breonna Taylor",
    summary: "Police conduct 20,000+ no-knock raids annually. Breonna Taylor killed in her bed by Louisville police in a botched no-knock raid on March 13, 2020. Wrong address raids kill dozens. Disproportionately used against Black households.",
    category: "Civil Rights",
    severity: "critical",
    date: "April 3, 2020",
    entityCount: 5,
    tags: ["No-Knock Raids", "Breonna Taylor", "Police Violence", "Fourth Amendment"],
  },
];

const categories = [
  "Crimes Against Humanity",
  "Human Trafficking",
  "Election Interference",
  "National Security",
  "Financial Crimes",
  "Abuse of Power",
  "Foreign Corruption",
  "Corruption",
  "Public Health",
  "Environment",
  "Civil Rights",
  "Criminal Conduct",
  "Platform",
  "Government Abuse of Power",
  "Government Cover-Up",
  "Government Overreach",
  "Systemic Racism",
  "Environmental Racism",
  "Constitutional Violations",
  "War Crimes",
  "Corporate Crime",
  "Domestic Terrorism",
  "Disinformation",
  "Labor Rights",
];

const severityLevels = ["Critical", "High", "Medium", "Low"];

export default function InvestigationsPage() {
  const [filteredInvestigations, setFilteredInvestigations] = useState(allInvestigations);
  const [searchQuery, setSearchQuery] = useState("");

  const handleSearch = (query: string) => {
    setSearchQuery(query);
    filterInvestigations(query, null);
  };

  const handleFilterChange = (filters: FilterState) => {
    filterInvestigations(searchQuery, filters);
  };

  const filterInvestigations = (query: string, filters: FilterState | null) => {
    let results = allInvestigations;

    if (query) {
      const lowerQuery = query.toLowerCase();
      results = results.filter(
        (inv) =>
          inv.title.toLowerCase().includes(lowerQuery) ||
          inv.summary.toLowerCase().includes(lowerQuery) ||
          inv.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
      );
    }

    if (filters) {
      if (filters.category) {
        results = results.filter((inv) => inv.category === filters.category);
      }
      if (filters.severity) {
        results = results.filter(
          (inv) => inv.severity.toLowerCase() === filters.severity.toLowerCase()
        );
      }
    }

    setFilteredInvestigations(results);
  };

  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header - Crystal Clear */}
        <div className="py-8 lg:py-12">
          <div className="border-2 border-blood-800/60 bg-black/60 p-6 lg:p-8 mb-8">
            {/* Top decorative line */}
            <div className="flex items-center gap-4 mb-6">
              <span className="h-[2px] flex-1 bg-gradient-to-r from-blood-700 to-transparent" />
              <span className="text-xs text-zinc-600 uppercase tracking-[0.3em]">Declassified Files</span>
              <span className="h-[2px] flex-1 bg-gradient-to-l from-blood-700 to-transparent" />
            </div>

            {/* Main Title */}
            <div className="text-center mb-6">
              <h1 className="text-4xl lg:text-5xl font-black text-white uppercase tracking-wider mb-2">
                INVESTIGATIONS
              </h1>
              <p className="text-lg text-blood-600 font-bold uppercase tracking-[0.2em]">
                The Evidence They Don&apos;t Want You To See
              </p>
            </div>

            {/* Description */}
            <div className="max-w-3xl mx-auto text-center">
              <p className="text-zinc-400 leading-relaxed mb-4">
                Every document here represents a crime. Every file exposes a lie. Every investigation 
                traces the web of corruption from the shadows into the light.
              </p>
              <div className="flex flex-wrap justify-center gap-4 text-xs">
                <span className="flex items-center gap-2 text-zinc-500">
                  <span className="w-2 h-2 bg-blood-700" />
                  Government Operations
                </span>
                <span className="flex items-center gap-2 text-zinc-500">
                  <span className="w-2 h-2 bg-blood-700" />
                  Corporate Collusion
                </span>
                <span className="flex items-center gap-2 text-zinc-500">
                  <span className="w-2 h-2 bg-blood-700" />
                  Medical Experiments
                </span>
                <span className="flex items-center gap-2 text-zinc-500">
                  <span className="w-2 h-2 bg-blood-700" />
                  Cover-Ups & Lies
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Search & Filters */}
        <div className="mb-8">
          <SearchFilter
            onSearch={handleSearch}
            onFilterChange={handleFilterChange}
            categories={categories}
            severityLevels={severityLevels}
          />
        </div>

        {/* Results Count */}
        <div className="flex items-center justify-between mb-6">
          <p className="text-dark-400">
            Showing <span className="text-white font-semibold">{filteredInvestigations.length}</span> investigation{filteredInvestigations.length !== 1 ? "s" : ""}
          </p>
        </div>

        {/* Investigations Grid */}
        {filteredInvestigations.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredInvestigations.map((investigation, index) => (
              <InvestigationCard
                key={investigation.id}
                investigation={investigation}
                featured={index === 0 && filteredInvestigations.length > 2}
              />
            ))}
          </div>
        ) : (
          <div className="border border-zinc-800 bg-black/60 p-12 text-center">
            <div className="w-16 h-16 border-2 border-zinc-700 flex items-center justify-center mx-auto mb-4">
              <AlertTriangle className="w-8 h-8 text-zinc-600" />
            </div>
            <h3 className="text-xl font-bold text-white mb-2 uppercase tracking-wider">No Files Found</h3>
            <p className="text-zinc-500 max-w-md mx-auto">
              No investigations match your search criteria. Adjust your filters or check back 
              as new evidence is declassified.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
