"use client";

import { useState } from "react";
import Link from "next/link";
import { Building2, ChevronRight, Search, Skull } from "lucide-react";
import EntityCard, { Entity } from "@/components/cards/EntityCard";

// Placeholder data
const corporations: Entity[] = [
  {
    id: "trump-org",
    slug: "trump-organization",
    name: "The Trump Organization",
    type: "corporation",
    description: "Convicted of 17 felonies. $454M fraud judgment. CFO imprisoned. Money laundering, tax fraud, hush money payments. Deutsche Bank received $2B+ despite red flags.",
    role: "Criminal Enterprise",
    investigationCount: 5,
    riskLevel: "extreme",
  },
  {
    id: "trump-media",
    slug: "trump-media",
    name: "Trump Media & Technology Group",
    type: "corporation",
    description: "DJT stock meme company operating Truth Social. Lost $58M on $4M revenue. SEC SPAC merger investigation. Trump owns 60% - valuation driven by cult following, not fundamentals.",
    role: "Social Media / SPAC Shell",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "fox-news",
    slug: "fox-news",
    name: "Fox News Media",
    type: "corporation",
    description: "Paid $787.5 million settlement to Dominion after internal documents proved hosts knew election lies were false. Tucker Carlson fired. Roger Ailes resigned over harassment.",
    role: "Disinformation Network",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "cambridge-analytica",
    slug: "cambridge-analytica",
    name: "Cambridge Analytica",
    type: "corporation",
    description: "Harvested 87 million Facebook users' data without consent. Funded by Mercer family, led by Steve Bannon. Dissolved 2018 amid scandal. Facebook fined $5 billion.",
    role: "Data Harvesting Operation (Dissolved)",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "deutsche-bank",
    slug: "deutsche-bank",
    name: "Deutsche Bank AG",
    type: "corporation",
    description: "Loaned Trump $2+ billion when no other bank would. $630M fine for Russian money laundering. Internal red flags on Trump ignored. Whistleblower found dead.",
    role: "Trump's Bank, Russian Money Laundering",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "ami",
    slug: "american-media-inc",
    name: "American Media Inc.",
    type: "corporation",
    description: "National Enquirer owner ran catch-and-kill operation for Trump. Paid Karen McDougal $150K. CEO David Pecker testified as first witness in criminal trial.",
    role: "Catch-and-Kill Operation",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "blackrock",
    slug: "blackrock",
    name: "BlackRock, Inc.",
    type: "corporation",
    description: "World's largest asset manager ($10T+ AUM). Aladdin system controls $21.6 trillion. Housing market investments driving rent increases. Government advisory conflicts.",
    role: "Asset Management Giant",
    investigationCount: 0,
    riskLevel: "high",
  },
  {
    id: "kushner-companies",
    slug: "kushner-companies",
    name: "Kushner Companies",
    type: "corporation",
    description: "Kushner family real estate empire. 666 Fifth Avenue $1.8B bailout from Qatar-linked investors while Jared was in White House. Founder Charles Kushner pardoned for witness tampering.",
    role: "Real Estate / Political Access",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "affinity-partners",
    slug: "affinity-partners",
    name: "Affinity Partners",
    type: "corporation",
    description: "Jared Kushner's PE firm received $2 billion from Saudi PIF despite advisors recommending against. Payment for services rendered while in White House. Congressional investigation ongoing.",
    role: "Saudi-Funded Private Equity",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "fraud-guarantee",
    slug: "fraud-guarantee",
    name: "Fraud Guarantee LLC",
    type: "corporation",
    description: "Lev Parnas shell company that paid Rudy Giuliani $1M for Ukraine dirt-digging. Funded by Ukrainian oligarch. Both founders convicted of campaign finance fraud.",
    role: "Shell Company / Foreign Money Conduit",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "global-energy-producers",
    slug: "global-energy-producers",
    name: "Global Energy Producers LLC",
    type: "corporation",
    description: "Shell company formed same day as $325K donation to America First PAC. No real business. Used to funnel foreign money into US elections. Part of Parnas/Fruman scheme.",
    role: "Shell Company / Straw Donor",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "lincoln-project",
    slug: "the-lincoln-project",
    name: "The Lincoln Project",
    type: "corporation",
    description: "Anti-Trump Republican PAC. John Weaver sexual harassment scandal. Questions about founder payments and spending transparency despite raising $90M+.",
    role: "Political Action Committee",
    investigationCount: 0,
    riskLevel: "moderate",
  },
  {
    id: "lockheed-martin",
    slug: "lockheed-martin",
    name: "Lockheed Martin Corporation",
    type: "corporation",
    description: "World's largest defense contractor. $40B+ in government contracts. Supplied precision-guided bombs used in Yemen school bus bombing killing 40 children. Major Saudi arms deal beneficiary.",
    role: "Defense Contractor",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "geo-group",
    slug: "geo-group",
    name: "The GEO Group, Inc.",
    type: "corporation",
    description: "Second-largest private prison company. Profits from mass incarceration. Deaths in custody, sexual abuse, forced labor. Donated $500K to Trump inauguration.",
    role: "Private Prisons / Immigration Detention",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "corecivic",
    slug: "corecivic",
    name: "CoreCivic, Inc.",
    type: "corporation",
    description: "Largest private prison operator. Changed name from CCA after scandals. Documented abuse, inadequate medical care, deaths. Profits from immigrant detention.",
    role: "Private Prisons",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "koch-industries",
    slug: "koch-industries",
    name: "Koch Industries, Inc.",
    type: "corporation",
    description: "America's 2nd largest private company. Koch family spent $1B+ funding climate denial and dark money politics. $600M+ in environmental fines. Father built refineries for Nazis.",
    role: "Oil / Chemical / Dark Money",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "palantir",
    slug: "palantir",
    name: "Palantir Technologies",
    type: "corporation",
    description: "Peter Thiel's CIA-funded surveillance company. Contracts with ICE enabling deportations, NSA, military. Predictive policing software criticized as discriminatory.",
    role: "Surveillance Technology",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "clearview-ai",
    slug: "clearview-ai",
    name: "Clearview AI",
    type: "corporation",
    description: "Scraped 30+ billion photos from internet without consent for facial recognition. Sold to law enforcement. Banned in multiple countries, fined €50M+ for privacy violations.",
    role: "Facial Recognition / Surveillance",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "halliburton",
    slug: "halliburton",
    name: "Halliburton Company",
    type: "corporation",
    description: "Dick Cheney's company received $39.5B in Iraq War no-bid contracts. KBR subsidiary electrocuted soldiers with faulty work. War profiteering exemplified.",
    role: "Defense Contractor / Oil Services",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "facebook",
    slug: "meta",
    name: "Meta Platforms (Facebook)",
    type: "corporation",
    description: "Cambridge Analytica scandal, Instagram teen mental health crisis, Myanmar genocide facilitation, election interference platform. $5B FTC fine was a slap on wrist.",
    role: "Social Media / Data Harvesting",
    investigationCount: 4,
    riskLevel: "extreme",
  },
  {
    id: "google",
    slug: "google",
    name: "Google (Alphabet Inc.)",
    type: "corporation",
    description: "World's dominant search engine. NSA PRISM collaboration, antitrust monopoly violations, mass surveillance of users. Federal court ruled it an illegal monopoly in 2024.",
    role: "Technology / Advertising Monopoly",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "amazon",
    slug: "amazon",
    name: "Amazon.com, Inc.",
    type: "corporation",
    description: "Bezos bought Washington Post while Amazon landed $600M CIA contract. Union-busting, warehouse worker deaths, Alexa surveillance. Ring police partnerships.",
    role: "E-Commerce / Cloud / Media",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "att",
    slug: "att",
    name: "AT&T Inc.",
    type: "corporation",
    description: "Key NSA surveillance partner since 2001. Room 641A provided warrantless access to communications. Granted retroactive immunity for illegal wiretapping.",
    role: "Telecommunications / Surveillance",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "tiktok",
    slug: "tiktok",
    name: "TikTok (ByteDance)",
    type: "corporation",
    description: "Chinese-owned social media facing national security concerns. Potential CCP data access, algorithmic manipulation, censorship of content critical of China.",
    role: "Social Media",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "purdue-pharma",
    slug: "purdue-pharma",
    name: "Purdue Pharma",
    type: "corporation",
    description: "Sackler family company that sparked the opioid epidemic killing 500,000+ Americans. Knew OxyContin was addictive, marketed it aggressively anyway. Bankruptcy to escape accountability.",
    role: "Pharmaceutical (Dissolved)",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "exxonmobil",
    slug: "exxonmobil",
    name: "ExxonMobil Corporation",
    type: "corporation",
    description: "Knew about climate change since 1970s, funded denial campaigns for 40 years. Rex Tillerson became Secretary of State. Valdez spill devastated Alaska.",
    role: "Oil & Gas",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "raytheon",
    slug: "rtx",
    name: "Raytheon Technologies",
    type: "corporation",
    description: "Major defense contractor. Tomahawk missiles, Patriot systems, Javelin anti-tank weapons. Supplied bombs used in Yemen civilian massacres including school bus attack.",
    role: "Defense Contractor",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "boeing",
    slug: "boeing",
    name: "The Boeing Company",
    type: "corporation",
    description: "737 MAX crashes killed 346 people. Covered up design flaws. Weaponry supplied for Yemen war. DOJ deferred prosecution deal. CEO departed with $62M.",
    role: "Aerospace / Defense",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "equifax",
    slug: "equifax",
    name: "Equifax Inc.",
    type: "corporation",
    description: "2017 breach exposed data of 147 million Americans. Executives sold stock before disclosure. Controls credit scores affecting billions. $700M settlement.",
    role: "Credit Reporting / Data Broker",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "wells-fargo",
    slug: "wells-fargo",
    name: "Wells Fargo & Company",
    type: "corporation",
    description: "Employees created 3.5 million fake accounts to meet sales quotas. Foreclosed on homes using fraudulent documents. $3B+ in fines. Preyed on minority communities.",
    role: "Banking / Financial Services",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "jp-morgan",
    slug: "jpmorgan-chase",
    name: "JPMorgan Chase & Co.",
    type: "corporation",
    description: "Largest U.S. bank. Epstein accounts maintained despite red flags. Robo-signing mortgage fraud. Billions in fines. 'Fortress balance sheet' built on predatory practices.",
    role: "Banking / Financial Services",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "goldman-sachs",
    slug: "goldman-sachs",
    name: "Goldman Sachs Group, Inc.",
    type: "corporation",
    description: "2008 crisis profiteers - bet against securities they sold clients. 1MDB Malaysian scandal. SEC fraud settlement. 'Vampire squid' of Wall Street.",
    role: "Investment Banking",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "ira",
    slug: "internet-research-agency",
    name: "Internet Research Agency",
    type: "corporation",
    description: "Russian troll farm that ran 2016 election interference operation. Created fake American personas, organized real protests. Prigozhin funded before Wagner Group.",
    role: "Disinformation / Election Interference",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "twitter",
    slug: "twitter",
    name: "Twitter / X Corp",
    type: "corporation",
    description: "Elon Musk destroyed content moderation, reinstated banned accounts including Trump. Platform for election disinformation. 80% staff cut.",
    role: "Social Media",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "juul",
    slug: "juul-labs",
    name: "Juul Labs",
    type: "corporation",
    description: "Created teen nicotine epidemic with flavored pods and youth-targeted marketing. FDA finally banned. Altria paid $13B for stake, wrote it down to zero.",
    role: "E-Cigarettes / Tobacco",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "monsanto",
    slug: "monsanto",
    name: "Monsanto (Bayer)",
    type: "corporation",
    description: "Produced Agent Orange (Vietnam), Roundup (cancer-causing), PCBs, DDT. $10B+ Roundup settlements. Sued farmers for patent infringement on seeds that blew onto their land.",
    role: "Agriculture / Chemical (Acquired)",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "johnson-johnson",
    slug: "johnson-and-johnson",
    name: "Johnson & Johnson",
    type: "corporation",
    description: "Knew baby powder contained asbestos, sold it anyway. Opioid settlement. Talc bankruptcy scheme to avoid liability. 'Family company' poisoned families.",
    role: "Pharmaceutical / Consumer Products",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "pg",
    slug: "procter-gamble",
    name: "Procter & Gamble",
    type: "corporation",
    description: "Consumer products giant with history of environmental violations, animal testing controversies, and labor issues in supply chain.",
    role: "Consumer Products",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "walmart",
    slug: "walmart",
    name: "Walmart Inc.",
    type: "corporation",
    description: "World's largest retailer. Opioid dispensing scandal. Union-busting. Poverty wages subsidized by taxpayers ($6B/year in public assistance for employees).",
    role: "Retail",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "mckesson",
    slug: "mckesson",
    name: "McKesson Corporation",
    type: "corporation",
    description: "Drug distributor that shipped 14.1M opioid pills to single West Virginia town. $8B+ opioid settlement. DEA flagged suspicious orders ignored.",
    role: "Pharmaceutical Distribution",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "cardinal-health",
    slug: "cardinal-health",
    name: "Cardinal Health, Inc.",
    type: "corporation",
    description: "Opioid distributor that flooded communities with pills. Part of Big Three that distributed 76B pills over 6 years. Multi-billion settlement.",
    role: "Pharmaceutical Distribution",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "amerisource",
    slug: "amerisourcebergen",
    name: "AmerisourceBergen (Cencora)",
    type: "corporation",
    description: "Opioid distributor that ignored red flags to maximize profits. Part of $21B opioid settlement with states. Changed name to Cencora to escape reputation.",
    role: "Pharmaceutical Distribution",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "united-health",
    slug: "unitedhealth-group",
    name: "UnitedHealth Group",
    type: "corporation",
    description: "Largest health insurer. Navistar algorithm denied claims automatically. CEO Brian Thompson assassinated 2024. Record profits while denying coverage.",
    role: "Health Insurance",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "pfizer",
    slug: "pfizer",
    name: "Pfizer Inc.",
    type: "corporation",
    description: "Record $2.3B fraud settlement. Illegal drug marketing. Nigerian meningitis trials killed children. COVID vaccine profits while blocking global access.",
    role: "Pharmaceutical",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "hsbc",
    slug: "hsbc",
    name: "HSBC Holdings plc",
    type: "corporation",
    description: "Laundered $881M for Mexican drug cartels. Deferred prosecution deal - no executives jailed. 'Too big to jail' precedent. Sanctions violations.",
    role: "Banking",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "saudi-aramco",
    slug: "saudi-aramco",
    name: "Saudi Aramco",
    type: "corporation",
    description: "World's most profitable company. State-owned oil giant. Climate change driver. Funds regime that murdered Khashoggi. $2T+ valuation.",
    role: "Oil & Gas (State-Owned)",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "nestle",
    slug: "nestle",
    name: "Nestlé S.A.",
    type: "corporation",
    description: "Baby formula marketing killed millions in developing countries. Child labor in cocoa supply chain. Water privatization. 'Water is not a human right' - former CEO.",
    role: "Food & Beverage",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "general-dynamics",
    slug: "general-dynamics",
    name: "General Dynamics Corporation",
    type: "corporation",
    description: "Defense contractor building tanks, submarines, weapons systems. Supplied munitions used in Yemen war. Pentagon revolving door beneficiary.",
    role: "Defense Contractor",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "northrop",
    slug: "northrop-grumman",
    name: "Northrop Grumman",
    type: "corporation",
    description: "Defense contractor building B-21 bomber, drones, cyber weapons. Part of military-industrial complex Eisenhower warned about.",
    role: "Defense Contractor",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "alden-global-capital",
    slug: "alden-global-capital",
    name: "Alden Global Capital",
    type: "corporation",
    description: "Hedge fund notorious for acquiring and gutting local newspapers, slashing newsrooms to extract profits. Largest newspaper chain in America by number of publications.",
    role: "Hedge Fund / Media Vulture",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "alfa-bank",
    slug: "alfa-bank",
    name: "Alfa Bank",
    type: "corporation",
    description: "Russia's largest private bank flagged for suspicious DNS server communications with Trump Organization servers during the 2016 campaign. FBI investigated the covert digital link.",
    role: "Russian Banking",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "allied-security-operations-group",
    slug: "allied-security-operations-group",
    name: "Allied Security Operations Group",
    type: "corporation",
    description: "Hired to conduct the discredited Antrim County, Michigan election audit that fueled conspiracy theories about voting machines flipping votes in 2020.",
    role: "Security Consulting / Election Audit",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "american-water",
    slug: "american-water",
    name: "American Water Works",
    type: "corporation",
    description: "Largest publicly traded U.S. water and wastewater utility. Scrutinized over infrastructure failures, rate hikes, and the commodification of essential water resources.",
    role: "Water Utility",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "americas-project",
    slug: "americas-project",
    name: "America's Project",
    type: "corporation",
    description: "Conservative political organization involved in election-related advocacy and dark money networks supporting far-right candidates and policy initiatives.",
    role: "Political Organization",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "bayrock-group",
    slug: "bayrock-group",
    name: "Bayrock Group",
    type: "corporation",
    description: "Trump Tower development partner led by Felix Sater, a convicted felon with ties to Russian organized crime. Funneled money from former Soviet states into Trump-branded projects.",
    role: "Real Estate Development",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "blackwater",
    slug: "blackwater",
    name: "Blackwater (Academi)",
    type: "corporation",
    description: "Erik Prince's notorious private military company. Contractors massacred 17 Iraqi civilians at Nisour Square. Rebranded multiple times to escape its reputation.",
    role: "Private Military Contractor",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "breitbart-news",
    slug: "breitbart-news",
    name: "Breitbart News",
    type: "corporation",
    description: "Far-right media platform formerly chaired by Steve Bannon. Self-described 'platform for the alt-right.' Amplified white nationalist narratives into mainstream politics.",
    role: "Far-Right Media",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "cascade-investment",
    slug: "cascade-investment",
    name: "Cascade Investment",
    type: "corporation",
    description: "Bill Gates' private investment vehicle managing his $100B+ fortune. Largest private farmland owner in America. Holdings span energy, hospitality, and media.",
    role: "Private Investment",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "citadel",
    slug: "citadel",
    name: "Citadel LLC",
    type: "corporation",
    description: "Ken Griffin's hedge fund and market maker at the center of the GameStop trading controversy. Profited from payment for order flow while retail investors faced trading halts.",
    role: "Hedge Fund / Market Maker",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "citizens-united",
    slug: "citizens-united",
    name: "Citizens United",
    type: "corporation",
    description: "Conservative dark money group whose Supreme Court case unleashed unlimited corporate spending in elections. Fundamentally corrupted American democracy since 2010.",
    role: "Dark Money / Political Advocacy",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "coca-cola",
    slug: "coca-cola",
    name: "The Coca-Cola Company",
    type: "corporation",
    description: "Beverage giant facing scrutiny over environmental pollution, water resource depletion in developing nations, and alleged complicity in human rights abuses in its supply chain.",
    role: "Beverage / Consumer Products",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "colony-capital",
    slug: "colony-capital",
    name: "Colony Capital (DigitalBridge)",
    type: "corporation",
    description: "Tom Barrack's investment firm. Barrack chaired Trump's inaugural committee and was indicted for acting as an unregistered foreign agent for the UAE.",
    role: "Private Equity / Foreign Influence",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "conservative-partnership-institute",
    slug: "conservative-partnership-institute",
    name: "Conservative Partnership Institute",
    type: "corporation",
    description: "Mark Meadows-linked organization that served as an institutional hub for Trump allies and election denial efforts. Incubated groups involved in January 6th planning.",
    role: "Political Organization",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "crocus-group",
    slug: "crocus-group",
    name: "Crocus Group",
    type: "corporation",
    description: "Aras Agalarov's Russian real estate conglomerate that hosted the 2013 Miss Universe pageant in Moscow and facilitated the Trump Tower Moscow project discussions.",
    role: "Russian Real Estate / Trump Connection",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "dominion",
    slug: "dominion",
    name: "Dominion",
    type: "corporation",
    description: "Voting technology company that became the target of baseless conspiracy theories alleging its machines were rigged in the 2020 election. Won landmark defamation cases.",
    role: "Voting Technology",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "dominion-voting-systems",
    slug: "dominion-voting-systems",
    name: "Dominion Voting Systems",
    type: "corporation",
    description: "Election technology provider subjected to a coordinated disinformation campaign claiming vote manipulation. Secured a $787.5M settlement from Fox News for defamation.",
    role: "Election Technology",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "dow-chemical",
    slug: "dow-chemical",
    name: "Dow Chemical Company",
    type: "corporation",
    description: "Chemical manufacturer responsible for the Bhopal disaster aftermath and widespread environmental contamination. History of producing Agent Orange and toxic pesticides.",
    role: "Chemical Manufacturing",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "duke-energy",
    slug: "duke-energy",
    name: "Duke Energy",
    type: "corporation",
    description: "Utility giant responsible for the massive Dan River coal ash spill that contaminated 70 miles of waterway. Decades of environmental violations and regulatory capture.",
    role: "Energy Utility",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "dupont",
    slug: "dupont",
    name: "DuPont de Nemours",
    type: "corporation",
    description: "Knowingly poisoned communities with C8/PFAS 'forever chemicals' for decades. Internal documents revealed awareness of toxicity while concealing risks from regulators and the public.",
    role: "Chemical Manufacturing",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "dwac",
    slug: "dwac",
    name: "Digital World Acquisition Corp",
    type: "corporation",
    description: "SPAC that merged with Trump Media & Technology Group. SEC investigated for premature merger negotiations. Executives faced fraud charges over deal structure.",
    role: "SPAC / Financial Vehicle",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "elliott-management",
    slug: "elliott-management",
    name: "Elliott Management",
    type: "corporation",
    description: "Paul Singer's aggressive activist hedge fund known for suing sovereign nations to collect on distressed debt. Major Republican donor who initially funded Trump opposition research.",
    role: "Activist Hedge Fund",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "energy-transfer",
    slug: "energy-transfer",
    name: "Energy Transfer",
    type: "corporation",
    description: "Operator of the Dakota Access Pipeline built through Standing Rock Sioux sacred land despite massive protests. CEO Kelcy Warren donated $10M to Trump's campaign.",
    role: "Oil & Gas Pipeline",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "enron",
    slug: "enron",
    name: "Enron Corporation",
    type: "corporation",
    description: "Perpetrated one of the largest accounting frauds in history, destroying $74 billion in shareholder value. Executives enriched themselves while employees lost retirement savings.",
    role: "Energy Trading (Dissolved)",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "facebook-platform",
    slug: "facebook",
    name: "Facebook",
    type: "corporation",
    description: "Platform that enabled Cambridge Analytica's data harvesting, facilitated election interference, and amplified misinformation. Internal research showed Instagram harmed teen mental health.",
    role: "Social Media Platform",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "federalist-society",
    slug: "federalist-society",
    name: "The Federalist Society",
    type: "corporation",
    description: "Conservative legal organization that has effectively captured the federal judiciary. Vetted all Trump Supreme Court nominees and shaped the overturning of Roe v. Wade.",
    role: "Legal Advocacy / Judicial Selection",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "founders-fund",
    slug: "founders-fund",
    name: "Founders Fund",
    type: "corporation",
    description: "Peter Thiel's venture capital firm investing in surveillance tech and defense startups. Thiel funded Hulk Hogan's lawsuit that destroyed Gawker Media.",
    role: "Venture Capital",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "fox-corporation",
    slug: "fox-corporation",
    name: "Fox Corporation",
    type: "corporation",
    description: "Parent company of Fox News. Settled Dominion defamation suit for $787.5M. Internal communications revealed executives knowingly broadcast election lies to retain viewers.",
    role: "Media Conglomerate",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "free-speech-systems",
    slug: "free-speech-systems",
    name: "Free Speech Systems LLC",
    type: "corporation",
    description: "Alex Jones' holding company for Infowars. Filed for bankruptcy after $1.5 billion Sandy Hook defamation judgments. Funneled conspiracy media profits to Jones personally.",
    role: "Media Holding Company",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "freedom-caucus",
    slug: "freedom-caucus",
    name: "House Freedom Caucus",
    type: "corporation",
    description: "Far-right Congressional caucus that has repeatedly held government hostage over debt ceilings and spending. Members played key roles in election denial and January 6th.",
    role: "Political Caucus",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "ftx",
    slug: "ftx",
    name: "FTX Trading Ltd.",
    type: "corporation",
    description: "Sam Bankman-Fried's cryptocurrency exchange that collapsed in a massive fraud, losing $8 billion in customer funds. SBF convicted on seven counts of fraud and conspiracy.",
    role: "Cryptocurrency Exchange (Dissolved)",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "gettr",
    slug: "gettr",
    name: "GETTR",
    type: "corporation",
    description: "Social media platform launched by former Trump spokesman Jason Miller. Became a haven for extremist content and far-right figures banned from mainstream platforms.",
    role: "Social Media Platform",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "great-america-pac",
    slug: "great-america-pac",
    name: "Great America PAC",
    type: "corporation",
    description: "Pro-Trump Super PAC investigated for potential coordination with the campaign. Raised tens of millions while questions swirled about how funds were actually spent.",
    role: "Super PAC",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "heritage-foundation",
    slug: "heritage-foundation",
    name: "The Heritage Foundation",
    type: "corporation",
    description: "Conservative think tank behind Project 2025, a detailed blueprint for authoritarian consolidation of executive power. Architect of the radical right's policy agenda.",
    role: "Think Tank / Policy",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "infowars",
    slug: "infowars",
    name: "Infowars",
    type: "corporation",
    description: "Alex Jones' conspiracy media empire that spread Sandy Hook massacre denialism, resulting in $1.5 billion in defamation judgments. Radicalized millions through disinformation.",
    role: "Conspiracy Media",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "jeppesen-dataplan",
    slug: "jeppesen-dataplan",
    name: "Jeppesen Dataplan",
    type: "corporation",
    description: "Boeing subsidiary that provided logistical support for CIA extraordinary rendition flights, helping transport detainees to black sites for torture.",
    role: "Aviation Services / CIA Contractor",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "l-brands",
    slug: "l-brands",
    name: "L Brands (Bath & Body Works)",
    type: "corporation",
    description: "Les Wexner's retail empire linked to Jeffrey Epstein, who managed Wexner's finances and was gifted a $77 million Manhattan mansion. Victoria's Secret used as recruiting tool.",
    role: "Retail / Epstein Connection",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "las-vegas-sands",
    slug: "las-vegas-sands",
    name: "Las Vegas Sands Corp.",
    type: "corporation",
    description: "Sheldon Adelson's casino empire. Adelson was the largest individual Republican donor in history, spending $500M+ on political campaigns to shape U.S. and Israeli policy.",
    role: "Casino / Political Donor",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "liberty-strategic-capital",
    slug: "liberty-strategic-capital",
    name: "Liberty Strategic Capital",
    type: "corporation",
    description: "Steven Mnuchin's investment fund that received $1 billion from Saudi Arabia's sovereign wealth fund shortly after leaving his post as Trump's Treasury Secretary.",
    role: "Private Equity / Gulf Investment",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "lindell-management",
    slug: "lindell-management",
    name: "Lindell Management LLC",
    type: "corporation",
    description: "Mike Lindell's holding company that funneled MyPillow profits into election denial campaigns, symposiums, and legal challenges promoting debunked voting fraud claims.",
    role: "Holding Company / Election Denial",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "mc2-model-management",
    slug: "mc2-model-management",
    name: "MC2 Model Management",
    type: "corporation",
    description: "Modeling agency run by Jean-Luc Brunel, a key associate of Jeffrey Epstein. Used as a pipeline for trafficking young women under the guise of modeling careers.",
    role: "Modeling Agency / Trafficking Front",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "microsoft",
    slug: "microsoft",
    name: "Microsoft Corporation",
    type: "corporation",
    description: "Technology giant with antitrust history and massive government contracts. Major investor in OpenAI. Dominant position in enterprise software raises competition and surveillance concerns.",
    role: "Technology",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "murray-energy",
    slug: "murray-energy",
    name: "Murray Energy",
    type: "corporation",
    description: "Bob Murray's coal company that lobbied Trump to gut environmental regulations. Crandall Canyon mine collapse killed six workers. Filed for bankruptcy amid coal decline.",
    role: "Coal Mining (Dissolved)",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "mypillow",
    slug: "mypillow",
    name: "MyPillow, Inc.",
    type: "corporation",
    description: "Mike Lindell's pillow company that became a vehicle for election denial funding. Lindell spent tens of millions promoting debunked conspiracy theories about voting machines.",
    role: "Consumer Products / Election Denial",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "news-corp",
    slug: "news-corp",
    name: "News Corp",
    type: "corporation",
    description: "Rupert Murdoch's media empire spanning newspapers, publishing, and digital media. UK phone-hacking scandal. Decades of using media power to influence elections worldwide.",
    role: "Media Conglomerate",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "newsmax",
    slug: "newsmax",
    name: "Newsmax",
    type: "corporation",
    description: "Right-wing news network that amplified 2020 election fraud claims to poach Fox News viewers. Faces defamation lawsuits from Smartmatic over voting conspiracy coverage.",
    role: "Conservative Media",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "nexus-holdings",
    slug: "nexus-holdings",
    name: "Nexus Holdings",
    type: "corporation",
    description: "Opaque shell company appearing in multiple financial investigations. Linked to complex money flows and corporate structures designed to obscure beneficial ownership.",
    role: "Shell Company",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "nra",
    slug: "nra",
    name: "National Rifle Association",
    type: "corporation",
    description: "Gun lobby infiltrated by Russian agent Maria Butina. Funneled foreign money into elections. Wayne LaPierre convicted of fraud. blocked gun reform after every mass shooting.",
    role: "Lobbying / Foreign Influence",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "oath-keepers",
    slug: "oath-keepers",
    name: "Oath Keepers",
    type: "corporation",
    description: "Far-right anti-government militia whose leader Stewart Rhodes was convicted of seditious conspiracy for orchestrating the armed assault on the U.S. Capitol on January 6th.",
    role: "Extremist Militia",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "one-america-news",
    slug: "one-america-news",
    name: "One America News Network",
    type: "corporation",
    description: "Far-right news network that promoted election fraud conspiracies and was dropped by major carriers. Funded by AT&T. Faces multiple defamation lawsuits.",
    role: "Far-Right Media",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "openai",
    slug: "openai",
    name: "OpenAI",
    type: "corporation",
    description: "AI company that transitioned from nonprofit to capped-profit structure. Creator of ChatGPT. Faces scrutiny over safety practices, copyright issues, and concentration of AI power.",
    role: "Artificial Intelligence",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "parler",
    slug: "parler",
    name: "Parler",
    type: "corporation",
    description: "Far-right social media platform used to coordinate January 6th Capitol assault. Deplatformed by Apple, Google, and AWS. Briefly acquired by Kanye West.",
    role: "Social Media Platform",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "pepsico",
    slug: "pepsico",
    name: "PepsiCo, Inc.",
    type: "corporation",
    description: "Global beverage and snack conglomerate scrutinized for environmental impact, plastic pollution, and marketing unhealthy products in developing nations.",
    role: "Beverage / Consumer Products",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "philip-morris",
    slug: "philip-morris",
    name: "Philip Morris International",
    type: "corporation",
    description: "Tobacco giant that spent decades covering up the link between smoking and cancer. Internal documents revealed systematic deception of the public while millions died.",
    role: "Tobacco",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "proud-boys",
    slug: "proud-boys",
    name: "Proud Boys",
    type: "corporation",
    description: "Far-right extremist group whose leaders were convicted of seditious conspiracy for spearheading the January 6th Capitol breach. Trump told them to 'stand back and stand by.'",
    role: "Extremist Organization",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "renaissance-technologies",
    slug: "renaissance-technologies",
    name: "Renaissance Technologies",
    type: "corporation",
    description: "Mercer family hedge fund that bankrolled Breitbart, Cambridge Analytica, and Trump's 2016 campaign. Medallion Fund's $100B+ returns raise questions about market fairness.",
    role: "Hedge Fund / Political Funding",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "rj-reynolds",
    slug: "rj-reynolds",
    name: "R.J. Reynolds Tobacco",
    type: "corporation",
    description: "Tobacco company that targeted youth with Joe Camel marketing while suppressing cancer research. Decades of litigation over deliberate public health deception.",
    role: "Tobacco",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "scl-group",
    slug: "scl-group",
    name: "SCL Group",
    type: "corporation",
    description: "Parent company of Cambridge Analytica specializing in military-grade psychological operations. Applied PsyOps techniques to civilian elections worldwide before dissolving.",
    role: "Psychological Operations (Dissolved)",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "sinclair",
    slug: "sinclair",
    name: "Sinclair",
    type: "corporation",
    description: "Conservative media company operating local TV stations across America. Mandated 'must-run' right-wing commentary segments disguised as local news on all affiliates.",
    role: "Local Television Media",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "sinclair-broadcast-group",
    slug: "sinclair-broadcast-group",
    name: "Sinclair Broadcast Group",
    type: "corporation",
    description: "Largest local TV station owner in the U.S. Forced anchors to read identical pro-Trump scripts on air. Used local news trust to inject partisan messaging nationwide.",
    role: "Broadcasting / Conservative Media",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "smartmatic",
    slug: "smartmatic",
    name: "Smartmatic",
    type: "corporation",
    description: "Voting technology company that filed a $2.7 billion defamation lawsuit against Fox News over false election fraud claims. Provided systems to only one U.S. county in 2020.",
    role: "Voting Technology",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "spirit-aerosystems",
    slug: "spirit-aerosystems",
    name: "Spirit AeroSystems",
    type: "corporation",
    description: "Boeing 737 MAX fuselage supplier whose quality control failures led to a door plug blowing out mid-flight on Alaska Airlines. Whistleblowers reported systemic safety issues.",
    role: "Aerospace Manufacturing",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "stop-the-steal",
    slug: "stop-the-steal",
    name: "Stop the Steal",
    type: "corporation",
    description: "Election denial movement that organized the rally preceding the January 6th Capitol assault. Network of dark money, extremist groups, and Trump allies coordinating the big lie.",
    role: "Political Movement / Election Denial",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "sullivan-strickler",
    slug: "sullivan-strickler",
    name: "Sullivan Strickler LLC",
    type: "corporation",
    description: "Data forensics firm hired by Sidney Powell to access election systems in Coffee County, Georgia. Involved in unauthorized breach of voting equipment after 2020 election.",
    role: "Data Forensics",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "tc-energy",
    slug: "tc-energy",
    name: "TC Energy",
    type: "corporation",
    description: "Canadian energy company behind the controversial Keystone XL Pipeline that would have carried tar sands oil across indigenous lands and the Ogallala Aquifer.",
    role: "Energy / Pipeline",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "the-bulwark",
    slug: "the-bulwark",
    name: "The Bulwark",
    type: "corporation",
    description: "Anti-Trump conservative media outlet founded by former Weekly Standard writers. Provides center-right criticism of MAGA movement and Republican Party radicalization.",
    role: "Conservative Media",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "theranos",
    slug: "theranos",
    name: "Theranos",
    type: "corporation",
    description: "Elizabeth Holmes' blood-testing fraud that deceived investors, patients, and the military. Claimed revolutionary technology that never worked. Holmes sentenced to 11 years.",
    role: "Health Technology (Dissolved)",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "tigerswan",
    slug: "tigerswan",
    name: "TigerSwan",
    type: "corporation",
    description: "Private military contractor hired by Energy Transfer to conduct counterintelligence operations against Standing Rock water protectors, treating peaceful protesters as insurgents.",
    role: "Private Security / Military",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "trump-university",
    slug: "trump-university",
    name: "Trump University",
    type: "corporation",
    description: "Fraudulent for-profit education venture that scammed students with worthless courses. Not an accredited university. Trump paid $25 million to settle fraud lawsuits.",
    role: "Fraudulent Education (Dissolved)",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "truth-social",
    slug: "truth-social",
    name: "Truth Social",
    type: "corporation",
    description: "Trump's social media platform launched after his bans from mainstream sites. Operated by Trump Media & Technology Group. Minimal revenue against massive valuation.",
    role: "Social Media Platform",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "united-fruit-company",
    slug: "united-fruit-company",
    name: "United Fruit Company",
    type: "corporation",
    description: "Orchestrated CIA-backed coups in Guatemala and Honduras to protect banana profits. Coined the term 'banana republic.' Decades of exploitation across Latin America.",
    role: "Agriculture / Historical CIA Operations",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "volkswagen",
    slug: "volkswagen",
    name: "Volkswagen AG",
    type: "corporation",
    description: "Engineered sophisticated software to cheat emissions tests on 11 million diesel vehicles worldwide. Dieselgate scandal resulted in $30B+ in fines and settlements.",
    role: "Automotive",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "wagner-group",
    slug: "wagner-group",
    name: "Wagner Group",
    type: "corporation",
    description: "Russian paramilitary organization that committed war crimes in Ukraine, Syria, and Africa. Founded by Yevgeny Prigozhin, who died in a suspicious plane crash after a mutiny.",
    role: "Russian Paramilitary",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "washington-free-beacon",
    slug: "washington-free-beacon",
    name: "Washington Free Beacon",
    type: "corporation",
    description: "Conservative news outlet that initially funded Fusion GPS opposition research on Trump before the DNC continued it, eventually producing the Steele dossier.",
    role: "Conservative Media",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "washington-post",
    slug: "washington-post",
    name: "The Washington Post",
    type: "corporation",
    description: "Newspaper acquired by Jeff Bezos in 2013. Questions about editorial independence given Amazon's government contracts. Bezos killed endorsement of Kamala Harris in 2024.",
    role: "News Media",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "worldcom",
    slug: "worldcom",
    name: "WorldCom",
    type: "corporation",
    description: "Perpetrated $11 billion accounting fraud, the largest in history at the time. CEO Bernard Ebbers sentenced to 25 years. 20,000 employees lost jobs and pensions.",
    role: "Telecommunications (Dissolved)",
    investigationCount: 1,
    riskLevel: "extreme",
  },
];

export default function CorporationsPage() {
  const [searchQuery, setSearchQuery] = useState("");
  
  const filteredCorporations = corporations.filter((corp) =>
    corp.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Breadcrumb - Sharp */}
        <nav className="flex items-center gap-2 text-sm text-zinc-500 mb-6 pt-4">
          <Link href="/" className="hover:text-blood-600 transition-colors">Home</Link>
          <ChevronRight className="w-4 h-4" />
          <Link href="/entities" className="hover:text-blood-600 transition-colors">Entities</Link>
          <ChevronRight className="w-4 h-4" />
          <span className="text-blood-600">Corporations</span>
        </nav>

        {/* Header - Crystal Clear */}
        <div className="py-8">
          <div className="border-2 border-blood-800/60 bg-black/60 p-6 lg:p-8 mb-8">
            {/* Top decorative line */}
            <div className="flex items-center gap-4 mb-6">
              <span className="h-[2px] flex-1 bg-gradient-to-r from-blood-700 to-transparent" />
              <Building2 className="w-6 h-6 text-blood-600" />
              <span className="h-[2px] flex-1 bg-gradient-to-l from-blood-700 to-transparent" />
            </div>

            <div className="text-center mb-6">
              <h1 className="text-3xl lg:text-4xl font-black text-white uppercase tracking-wider mb-2">
                CORPORATIONS
              </h1>
              <p className="text-lg text-blood-600 font-bold uppercase tracking-[0.15em]">
                Profit Over People
              </p>
              <p className="text-sm text-zinc-500 mt-2">
                {corporations.length} entities documented in the archive
              </p>
            </div>

            <p className="text-zinc-400 text-center max-w-2xl mx-auto leading-relaxed">
              Companies that have placed shareholder value above human life. Big Pharma, 
              Big Tech, defense contractors, and more. Their crimes documented, their 
              connections exposed.
            </p>
          </div>
        </div>

        {/* Search - Sharp */}
        <div className="mb-8">
          <div className="relative max-w-md">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-zinc-500" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search corporations..."
              className="w-full pl-12 pr-4 py-3 bg-black/60 border-2 border-zinc-800 text-white placeholder-zinc-600 focus:outline-none focus:border-blood-700 transition-colors"
            />
          </div>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredCorporations.map((corp) => (
            <EntityCard key={corp.id} entity={corp} />
          ))}
        </div>

        {filteredCorporations.length === 0 && (
          <div className="border border-zinc-800 bg-black/60 p-12 text-center">
            <div className="w-16 h-16 border-2 border-zinc-700 flex items-center justify-center mx-auto mb-4">
              <Skull className="w-8 h-8 text-zinc-600" />
            </div>
            <h3 className="text-xl font-bold text-white mb-2 uppercase tracking-wider">No Corporations Found</h3>
            <p className="text-zinc-500">No corporations match your search criteria.</p>
          </div>
        )}
      </div>
    </div>
  );
}
