'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, AlertTriangle, Users, Calendar, FileText, ExternalLink, Scale, ShieldAlert, Skull } from 'lucide-react';
import GlitchText from '@/components/effects/GlitchText';

const investigation = {
  title: 'Health Insurance Industry Deaths',
  subtitle: '68,000+ Americans Die Annually So Insurance Companies Can Post Record Profits',
  severity: 'critical',
  status: 'ONGOING MASS CASUALTY',
  summary: 'The United States is the only wealthy nation where people routinely die because they cannot afford healthcare. An estimated 68,000 Americans die every year due to lack of health insurance — a number that does not include the tens of thousands more who die from delayed care, claim denials, prior authorization delays, medication rationing, and medical debt-induced poverty. The for-profit health insurance industry in America is not a healthcare system — it is a death-by-spreadsheet apparatus designed to maximize shareholder returns by denying, delaying, and minimizing care. Insurance companies employ thousands of people whose sole job is to find reasons to deny claims. Prior authorization requirements — bureaucratic permission slips that force doctors to beg insurance companies before treating patients — kill an estimated 34% of physicians\' patients who experience adverse outcomes during delays. Americans ration insulin because they cannot afford the $300+ monthly cost for a drug that costs $3-$6 to manufacture. Medical debt is the leading cause of personal bankruptcy in America — 62% of all bankruptcies are medical-related, affecting an estimated 530,000 families annually. Meanwhile, the five largest health insurance companies — UnitedHealth Group, Elevance Health (formerly Anthem), Cigna, Humana, and Centene — reported combined revenues exceeding $1 trillion and combined profits over $40 billion in 2023. Their CEOs collectively earned over $150 million in compensation while their companies denied millions of claims. The health insurance industry has spent over $700 million lobbying Congress since 1998, making it one of the most powerful lobbying forces in Washington, ensuring that any meaningful reform — from the public option to Medicare for All — is killed before reaching a vote.',
  keyFigures: [
    { name: 'Andrew Witty', role: 'CEO of UnitedHealth Group — the largest health insurance company in the world with $371.6B in revenue (2023). UnitedHealth\'s subsidiary Optum employs more physicians than any other entity in the U.S., creating a vertical monopoly over both insurance and care delivery.', href: '/entities/individuals/andrew-witty', status: 'Current CEO, UnitedHealth' },
    { name: 'David Cordani', role: 'CEO of Cigna Group (2009-2023). Under his leadership, Cigna expanded its denial rates and prior authorization requirements while posting record profits. Cigna\'s algorithm-based claim denial system rejected hundreds of thousands of claims in bulk without medical review.', href: '/entities/individuals/david-cordani', status: 'Former CEO, Cigna' },
    { name: 'Martin Shkreli', role: '"Pharma Bro." As CEO of Turing Pharmaceuticals, raised the price of Daraprim — a life-saving anti-parasitic drug — from $13.50 to $750 per pill overnight (a 5,455% increase). Became the public face of pharmaceutical price gouging.', href: '/entities/individuals/martin-shkreli', status: 'Convicted — Released 2023' },
    { name: 'Heather Bresch', role: 'CEO of Mylan (2012-2020). Presided over the EpiPen price increase from $100 to $608 — a 500%+ increase for a life-saving allergy medication that costs approximately $1 to manufacture. Simultaneously lobbied to make EpiPens mandatory in schools.', href: '/entities/individuals/heather-bresch', status: 'Former CEO, Mylan' },
    { name: 'Albert Bourla', role: 'CEO of Pfizer. Quadrupled the price of the COVID-19 vaccine from $19.50 to $110-$130 per dose after the pandemic — a product developed with $2.5B in taxpayer funding. Pfizer\'s revenue reached $100.3B in 2022.', href: '/entities/individuals/albert-bourla', status: 'Current CEO, Pfizer' },
    { name: 'Rick Scott', role: 'Former CEO of Columbia/HCA, the largest for-profit hospital chain. Under his leadership, HCA committed the largest Medicare fraud in history, settling for $1.7B. Scott was never charged personally. Later became Governor of Florida and U.S. Senator.', href: '/entities/individuals/rick-scott', status: 'U.S. Senator (R-FL)' },
    { name: 'Mitch McConnell', role: 'Senate Minority/Majority Leader. Has received over $4 million in healthcare industry campaign contributions. Led opposition to the Affordable Care Act and every subsequent reform effort, including drug price negotiation.', href: '/entities/individuals/mitch-mcconnell', status: 'U.S. Senator (R-KY)' },
    { name: 'Joe Manchin', role: 'U.S. Senator (D-WV). His daughter Heather Bresch was the Mylan CEO who raised EpiPen prices 500%+. Manchin blocked the Build Back Better Act\'s drug pricing provisions and opposed Medicare expansion, protecting the industry that enriched his family.', href: '/entities/individuals/joe-manchin', status: 'Former U.S. Senator' },
    { name: 'Donald Trump', role: 'Promised to replace the ACA with "something terrific" and to lower drug prices. Instead, his administration expanded short-term junk insurance plans, attempted to eliminate ACA protections, and abandoned drug pricing reforms after industry lobbying.', href: '/entities/individuals/donald-trump', status: 'Current President' },
    { name: 'Richard Sackler', role: 'Former Chairman of Purdue Pharma. Oversaw the aggressive marketing of OxyContin that fueled the opioid crisis, killing over 500,000 Americans. The Sackler family extracted $10.7B from Purdue while the company pled guilty to criminal charges.', href: '/entities/individuals/richard-sackler', status: 'Sackler Family Settlement' },
    { name: 'John Kapoor', role: 'Founder and former Chairman of Insys Therapeutics. Convicted of racketeering for bribing doctors to prescribe a powerful fentanyl spray to patients who did not need it, including cancer patients, contributing to the opioid epidemic.', href: '/entities/individuals/john-kapoor', status: 'Convicted — 66 months' },
    { name: 'Alex Gorsky', role: 'Former CEO of Johnson & Johnson (2012-2022). J&J knew for decades that its talc-based baby powder contained asbestos and caused cancer. The company used a "Texas two-step" bankruptcy maneuver to limit victim payouts to $8.9 billion.', href: '/entities/individuals/alex-gorsky', status: 'Former CEO, J&J' },
    { name: 'Stephen Hemsley', role: 'Former CEO of UnitedHealth Group (2006-2017). Oversaw UnitedHealth\'s transformation into a healthcare monopoly acquiring physician practices, pharmacy benefit managers, and data analytics firms while tightening claim denials. Compensation exceeded $300M during tenure.', href: '/entities/individuals/stephen-hemsley', status: 'Executive Chairman' },
    { name: 'Karen Lynch', role: 'CEO of CVS Health (which acquired Aetna). CVS/Aetna controls insurance, pharmacy benefits, and retail pharmacy — a vertical monopoly that profits at every stage of healthcare delivery while patients pay ever-increasing out-of-pocket costs.', href: '/entities/individuals/karen-lynch', status: 'Former CEO, CVS Health' },
  ],
  timeline: [
    { date: '1929', event: 'Baylor Hospital in Dallas creates the first group hospital insurance plan — the precursor to Blue Cross. Healthcare begins its transformation from a public good to a commercial product.' },
    { date: '1945', event: 'President Truman proposes a national health insurance program. The AMA brands it "socialized medicine" and spends $1.5 million (equivalent to $23M today) to defeat it — the insurance industry\'s first major lobbying victory.' },
    { date: '1965', event: 'Medicare and Medicaid signed into law by President Johnson. The private insurance industry successfully lobbies to ensure the programs supplement rather than replace commercial insurance.' },
    { date: '1973', event: 'Nixon signs the HMO Act, encouraging the growth of for-profit Health Maintenance Organizations. His advisor John Ehrlichman\'s recorded White House conversation reveals the model: "all the incentives are toward less medical care."' },
    { date: '1993-1994', event: 'The Clinton health reform effort — led by Hillary Clinton — is defeated after the insurance industry spends $100M+ on the "Harry and Louise" advertising campaign. The industry consolidates its grip on the political system.' },
    { date: '1998', event: 'Pfizer launches direct-to-consumer advertising for Viagra, opening the floodgates of pharmaceutical marketing that drives Americans to demand expensive brand-name medications.' },
    { date: '2003', event: 'Medicare Part D prescription drug benefit signed by Bush. The law explicitly prohibits Medicare from negotiating drug prices — a provision written by pharmaceutical industry lobbyist Billy Tauzin, who then became PhRMA\'s $2M/year president.' },
    { date: '2007', event: 'CIGNA denies a liver transplant to 17-year-old Nataline Sarkisyan, overruling her doctors\' recommendations. She dies hours after CIGNA reverses its decision under public pressure — but too late for the transplant to occur.' },
    { date: '2010', event: 'Affordable Care Act signed by Obama. Expands coverage to 20 million people but preserves the for-profit insurance model, mandating that Americans purchase private insurance. The public option is killed by industry lobbying and Senate opposition.' },
    { date: '2015', event: 'Martin Shkreli raises the price of Daraprim from $13.50 to $750 per pill. Congressional outrage produces hearings but no legislation. Drug pricing reform dies in Congress year after year.' },
    { date: '2016', event: 'EpiPen price scandal: Mylan CEO Heather Bresch raises the price of the life-saving allergy injector from $100 to $608 while her company reclassifies the device to avoid Medicaid rebates, costing taxpayers an additional $1.27B.' },
    { date: '2018', event: 'A study in The Lancet estimates 68,000 Americans die annually due to lack of health insurance. Millions more delay or forgo care due to cost, resulting in preventable suffering and death.' },
    { date: '2019', event: 'Americans owe over $140 billion in medical debt. A study finds that 62% of all personal bankruptcies are medical-related. GoFundMe becomes the largest healthcare fundraising platform in America, with one-third of campaigns related to medical costs.' },
    { date: '2022', event: 'Inflation Reduction Act allows Medicare to negotiate prices for 10 drugs (expanding to 20 by 2029) — a tiny fraction of the thousands of drugs on the market. Industry challenges the law in court.' },
    { date: '2023', event: 'ProPublica investigation reveals Cigna\'s system of automatically denying claims using an algorithm, with doctors rejecting claims at a rate of 60,000 per day without reviewing patient files.' },
    { date: '2023', event: 'UnitedHealth Group reports $22.4B in profit. The top five insurers report combined profits exceeding $40B. Insurance CEO compensation totals over $150M combined while an estimated 27.6 million Americans remain uninsured.' },
    { date: '2024', event: 'The American Medical Association reports that 34% of physicians say prior authorization delays have led to serious adverse events for their patients, including hospitalization and death. The average practice spends 14 hours per week on prior authorization paperwork.' },
    { date: 'December 4, 2024', event: 'UnitedHealthcare CEO Brian Thompson shot and killed in Manhattan. The suspect\'s bullet casings are engraved with "deny," "defend," and "depose" — the insurance industry\'s notorious playbook for avoiding claims. Public response reveals deep rage against the industry.' },
  ],
  legalOutcomes: [
    { defendant: 'Columbia/HCA (Rick Scott, CEO)', charge: 'Largest Medicare fraud in history — systematic overbilling, kickbacks, and false claims', outcome: '$1.7B settlement. Rick Scott personally took the Fifth 75 times. Never charged. Became Governor and Senator.' },
    { defendant: 'Purdue Pharma / Sackler Family', charge: 'Fraudulent marketing of OxyContin, fueling opioid epidemic that killed 500,000+ Americans', outcome: 'Purdue pled guilty to criminal charges twice. Sacklers paid $6B but received personal immunity. No family member imprisoned.' },
    { defendant: 'Insys Therapeutics / John Kapoor', charge: 'RICO — bribing doctors to prescribe fentanyl spray to patients who did not need it', outcome: 'Kapoor convicted, sentenced to 66 months. Company filed for bankruptcy after $225M settlement.' },
    { defendant: 'Johnson & Johnson', charge: 'Concealing asbestos contamination in talc products for decades, causing cancer', outcome: '$8.9B proposed settlement using "Texas two-step" bankruptcy maneuver to limit payouts. No executive charged.' },
    { defendant: 'Martin Shkreli / Turing Pharmaceuticals', charge: 'Price gouging of life-saving medication (Daraprim: $13.50 to $750)', outcome: 'Convicted of securities fraud (separate matter). Barred from pharmaceutical industry. Drug pricing remains legal.' },
    { defendant: 'Mylan / Heather Bresch', charge: 'EpiPen price gouging (500%+ increase) and Medicaid rebate fraud', outcome: '$465M DOJ settlement for misclassifying EpiPen to underpay Medicaid rebates. No personal charges against Bresch.' },
    { defendant: 'Cigna', charge: 'Algorithm-based claim denials without medical review — rejecting 60,000 claims per day', outcome: 'Class action lawsuits pending. No executive charged. Practice continues industry-wide.' },
    { defendant: 'UnitedHealth Group', charge: 'Monopolistic practices, systematic claim denials, and vertical integration eliminating competition', outcome: 'DOJ antitrust investigation ongoing. No charges to date. Company continues acquiring competitors.' },
  ],
  charges: [
    { statute: '18 U.S.C. § 1347 — Healthcare Fraud', description: 'Insurance companies systematically deny legitimate claims, delay prior authorizations, and use algorithmic denial systems designed to avoid paying for covered medical care — constituting a scheme to defraud policyholders of benefits they have paid for.', count: 'Hundreds of millions of claims denied annually across the industry' },
    { statute: '18 U.S.C. § 1962 — RICO (Racketeer Influenced and Corrupt Organizations)', description: 'The health insurance industry operates as a coordinated enterprise engaging in a pattern of fraud, bribery (lobbying), and obstruction to maintain a system that extracts maximum revenue while minimizing care delivery, resulting in preventable deaths.', count: 'Industry-wide pattern spanning decades' },
    { statute: '18 U.S.C. § 1112 — Involuntary Manslaughter', description: 'Claim denials and prior authorization delays that result in patient deaths constitute involuntary manslaughter when insurance companies know that denial of timely care creates a substantial risk of death.', count: 'Estimated 68,000+ deaths annually attributable to lack of insurance; additional thousands from claim denials' },
    { statute: '15 U.S.C. § 2 — Sherman Act (Monopolization)', description: 'Health insurance companies have engaged in systematic acquisition of competitors, physician practices, pharmacy benefit managers, and healthcare delivery systems to create vertical monopolies that eliminate competition and consumer choice.', count: 'UnitedHealth, CVS/Aetna, and Cigna control over 50% of the commercial insurance market' },
    { statute: '18 U.S.C. § 201 — Bribery of Public Officials', description: 'The health insurance and pharmaceutical industries have spent over $700M lobbying Congress since 1998, purchasing legislative outcomes including the Medicare Part D prohibition on drug price negotiation and the defeat of the public option.', count: '$700M+ in documented lobbying expenditures; millions more in campaign contributions' },
    { statute: '42 U.S.C. § 300gg — ACA Violations', description: 'Insurance companies have systematically violated ACA requirements including essential health benefits mandates, mental health parity requirements, and prohibitions on rescission through creative reinterpretation and inadequate enforcement.', count: 'Thousands of documented violations across the industry' },
    { statute: '18 U.S.C. § 1341/1343 — Mail/Wire Fraud', description: 'Insurance companies make material misrepresentations about coverage, benefits, and provider networks to sell policies, then systematically deny claims for care that policyholders reasonably believed was covered.', count: 'Millions of policyholders sold coverage that does not perform as represented' },
    { statute: '18 U.S.C. § 1951 — Hobbs Act (Extortion)', description: 'The system of employer-sponsored insurance — where loss of employment means loss of healthcare — functions as economic coercion, trapping workers in jobs under threat of losing access to life-sustaining medical treatment.', count: 'An estimated 157 million Americans dependent on employer-sponsored insurance' },
    { statute: '15 U.S.C. § 13 — Robinson-Patman Act (Price Discrimination)', description: 'Pharmaceutical companies charge American consumers 2-3 times what they charge patients in other countries for identical medications, constituting price discrimination enabled by the lobbied prohibition on Medicare negotiation and drug importation.', count: 'Americans pay the highest drug prices in the world — an estimated $1,500/person/year vs. $749 in comparable nations' },
  ],
  coverup: [
    'The health insurance industry spent over $100 million defeating Clinton\'s 1993 health reform through the "Harry and Louise" ad campaign, then spent hundreds of millions more over the following decades ensuring no universal healthcare system was ever adopted in America.',
    'Medicare Part D, signed by George W. Bush in 2003, explicitly prohibited the federal government from negotiating drug prices — a provision written by pharmaceutical lobbyist Billy Tauzin, who left Congress to become president of PhRMA at $2 million per year.',
    'During the ACA debate, the Obama administration made a secret deal with PhRMA: the industry would support the bill in exchange for the administration dropping the public option and drug importation provisions. The deal guaranteed industry profits would be protected.',
    'Insurance companies classify their claim denial algorithms and prior authorization criteria as "proprietary trade secrets," preventing patients, doctors, and regulators from understanding why care is denied. ProPublica revealed Cigna doctors were denying 60,000 claims per day without reviewing files.',
    'The insurance industry funds and controls patient advocacy groups, think tanks, and medical associations that oppose reform. The Partnership for America\'s Healthcare Future — funded by insurers and hospitals — spent millions opposing Medicare for All.',
    'Pharmacy Benefit Managers (PBMs) — the middlemen controlling drug pricing — operate with virtually zero transparency. Three PBMs (CVS Caremark, Express Scripts/Cigna, and OptumRx/UnitedHealth) control 80% of the market and keep secret the rebates they negotiate, pocketing the difference.',
    'The "revolving door" between the insurance industry and government regulators ensures industry-friendly oversight. Former CMS administrators, FDA officials, and HHS secretaries routinely move to lucrative private industry positions after leaving government.',
    'Medical debt collection practices — including lawsuits, wage garnishment, and credit destruction — are deliberately designed to extract maximum payment from financially devastated patients. Hospitals, many of them "nonprofit," sue thousands of their own patients annually.',
    'Insulin — a century-old drug that costs $3-$6 to manufacture — is priced at $300+ per vial in the United States. Three companies (Eli Lilly, Novo Nordisk, and Sanofi) control 90% of the global insulin market and have been found to coordinate price increases.', 
    'The insurance industry has systematically opposed mental health parity laws and, when forced to comply, has used narrower provider networks, higher prior authorization barriers, and lower reimbursement rates to effectively deny mental healthcare while technically meeting legal requirements.',
  ],
  sources: [
    { title: 'The Lancet: Health Insurance and Mortality in US Adults (68,000 Annual Deaths)', url: 'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(19)33019-3/fulltext', date: 'February 15, 2020' },
    { title: 'American Journal of Public Health: Medical Bankruptcy and the Economy', url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2556047/', date: '2009' },
    { title: 'ProPublica: How Cigna Saves Millions by Having Its Doctors Reject Claims Without Reading Them', url: 'https://www.propublica.org/article/cigna-pxdx-medical-health-insurance-rejection-claims', date: 'March 25, 2023' },
    { title: 'Kaiser Family Foundation: Health Insurance Coverage of the Total Population', url: 'https://www.kff.org/other/state-indicator/total-population/', date: '2024' },
    { title: 'Commonwealth Fund: U.S. Health System Ranks Last Among 11 Countries', url: 'https://www.commonwealthfund.org/publications/fund-reports/2024/sep/mirror-mirror-2024', date: 'September 2024' },
    { title: 'OpenSecrets: Health Sector Lobbying Profile', url: 'https://www.opensecrets.org/federal-lobbying/sectors/summary?cycle=2023&id=H', date: '2023' },
    { title: 'AMA: 2023 Prior Authorization Physician Survey — Harms and Delays', url: 'https://www.ama-assn.org/system/files/prior-authorization-survey.pdf', date: '2023' },
    { title: 'T1International: Insulin Rationing in the United States', url: 'https://www.t1international.com/insulin-and-supply-survey/', date: '2020' },
    { title: 'Wendell Potter, "Deadly Spin: An Insurance Company Insider Speaks Out"', url: 'https://www.simonandschuster.com/books/Deadly-Spin/Wendell-Potter/9781608192816', date: '2010' },
    { title: 'New York Times: A Hospital Charged $18,000 for a Cough. This Is Our Healthcare System.', url: 'https://www.nytimes.com/interactive/2019/09/26/health/hospitals-emergency-room-cost.html', date: 'September 26, 2019' },
  ],
};

export default function HealthInsuranceDeathsPage() {
  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/investigations" className="inline-flex items-center gap-2 text-zinc-400 hover:text-blood-500 transition-colors mb-6 pt-4"><ArrowLeft className="w-4 h-4" />Back to Investigations</Link>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="border-2 border-blood-800/60 bg-black/80 p-6 lg:p-8 mb-8">
          <div className="flex items-center gap-3 mb-4"><span className="px-3 py-1 text-xs font-bold uppercase border border-red-500/30 bg-red-500/20 text-red-400">{investigation.severity}</span><span className="px-3 py-1 text-xs font-bold uppercase border border-zinc-500/30 bg-zinc-500/20 text-zinc-400">{investigation.status}</span></div>
          <h1 className="text-3xl lg:text-4xl font-black text-white uppercase tracking-wider mb-2"><GlitchText text={investigation.title} /></h1>
          <p className="text-lg text-blood-500 font-bold mb-4">{investigation.subtitle}</p>
          <p className="text-zinc-400 leading-relaxed">{investigation.summary}</p>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="glass-card p-6 mb-8 border-l-4 border-blood-600">
          <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-blood-500" />The Cover-Up</h2>
          <div className="space-y-3">{investigation.coverup.map((item, idx) => (<div key={idx} className="p-3 bg-red-950/20 border border-red-500/30"><p className="text-sm text-zinc-300">{item}</p></div>))}</div>
        </motion.div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Users className="w-5 h-5 text-blood-500" />Key Figures</h2>
              <div className="space-y-3">{investigation.keyFigures.map((figure, idx) => (<div key={idx} className="flex items-start justify-between p-3 bg-zinc-900/50 border border-zinc-800"><div className="flex-1">{figure.href ? (<Link href={figure.href} className="font-bold text-blood-400 hover:text-blood-300 transition-colors">{figure.name}</Link>) : (<span className="font-bold text-white">{figure.name}</span>)}<p className="text-sm text-zinc-400 mt-1">{figure.role}</p></div><span className="text-xs px-2 py-1 bg-zinc-800 text-zinc-400 border border-zinc-700 whitespace-nowrap ml-2">{figure.status}</span></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Applicable Charges &amp; Statutes</h2>
              <div className="space-y-3">{investigation.charges.map((charge, idx) => (<div key={idx} className="p-4 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-blood-400 text-sm font-mono">{charge.statute}</p><p className="text-sm text-zinc-300 mt-1">{charge.description}</p><p className="text-xs text-red-400 mt-1">{charge.count}</p></div>))}</div>
            </motion.div>
          </div>
          <div className="space-y-6">
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Calendar className="w-4 h-4 text-blood-500" />Timeline</h3>
              <div className="space-y-4">{investigation.timeline.map((item, idx) => (<div key={idx} className="relative pl-4 border-l-2 border-zinc-800"><div className="absolute -left-[5px] top-0 w-2 h-2 rounded-full bg-blood-500" /><p className="text-xs text-blood-500 font-mono">{item.date}</p><p className="text-sm text-zinc-300">{item.event}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Legal Outcomes</h3>
              <div className="space-y-3">{investigation.legalOutcomes.map((item, idx) => (<div key={idx} className="p-3 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-white text-sm">{item.defendant}</p><p className="text-xs text-zinc-400 mt-1">{item.charge}</p><p className="text-xs text-blood-400 mt-1">{item.outcome}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4">Sources</h3>
              <div className="space-y-2">{investigation.sources.map((source, idx) => (<a key={idx} href={source.url} target="_blank" rel="noopener noreferrer" className="flex items-start gap-2 p-2 text-sm text-zinc-400 hover:text-blood-400 hover:bg-zinc-900/50 transition-colors"><ExternalLink className="w-4 h-4 mt-0.5 flex-shrink-0" /><div><span>{source.title}</span><span className="text-zinc-600 ml-2">({source.date})</span></div></a>))}</div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
