'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, AlertTriangle, Users, Calendar, FileText, ExternalLink, Scale, ShieldAlert, Skull } from 'lucide-react';
import GlitchText from '@/components/effects/GlitchText';

const investigation = {
  title: '1973 Chile Coup',
  subtitle: 'CIA Overthrow of Democracy — Pinochet\'s 17-Year Reign of Terror, 3,200+ Murdered, 40,000+ Tortured',
  severity: 'critical',
  status: 'DECLASSIFIED — U.S. ROLE CONFIRMED',
  summary: 'On September 11, 1973, the Chilean military — with direct support from the CIA and the Nixon administration — overthrew the democratically elected government of President Salvador Allende in a violent coup d\'état. Allende died during the assault on La Moneda presidential palace. General Augusto Pinochet seized power and established a brutal military dictatorship that would last 17 years (1973-1990). The regime murdered over 3,200 people, tortured at least 40,000, and drove 200,000 into exile. Pinochet created DINA, a secret police force modeled on the Gestapo, which carried out assassinations across three continents — including a car bombing on Embassy Row in Washington, D.C. The Nixon administration had ordered the CIA to "make the economy scream" to destabilize Allende\'s government, spending millions on covert operations, propaganda, and bribing Chilean politicians and military officers. The "Chicago Boys" — Chilean economists trained at the University of Chicago under Milton Friedman — were installed to implement radical free-market policies that enriched the elite while impoverishing workers. The Caravan of Death, a military death squad, traveled by helicopter to cities across Chile executing political prisoners. Declassified U.S. documents confirm that Nixon and Kissinger personally directed the campaign to overthrow Chilean democracy.',
  keyFigures: [
    { name: 'Salvador Allende', role: 'Democratically elected socialist President of Chile (1970-1973). Died during the military coup on September 11, 1973 in La Moneda presidential palace. His election triggered Nixon\'s order for CIA to prevent him from taking power at any cost', href: '/entities/individuals/salvador-allende', status: 'Died in Coup' },
    { name: 'Augusto Pinochet', role: 'Chilean Army Commander who led the coup and ruled as dictator for 17 years. His regime murdered 3,200+, tortured 40,000+, operated concentration camps, and carried out assassinations on three continents including in Washington, D.C.', href: '/entities/individuals/augusto-pinochet', status: 'Died 2006 — No Conviction' },
    { name: 'Richard Nixon', role: 'U.S. President who personally ordered the CIA to overthrow Allende. Told CIA Director Helms to "make the economy scream." Authorized $10 million for covert operations. His handwritten notes from the September 15, 1970 meeting are declassified', href: '/entities/individuals/richard-nixon', status: 'Resigned 1974' },
    { name: 'Henry Kissinger', role: 'National Security Advisor and Secretary of State who orchestrated U.S. intervention in Chile. Stated: "I don\'t see why we need to stand by and watch a country go communist due to the irresponsibility of its own people." Personally directed Track I and Track II operations', href: '/entities/individuals/henry-kissinger', status: 'Never Charged' },
    { name: 'Manuel Contreras', role: 'Director of DINA (Dirección de Inteligencia Nacional), Chile\'s secret police. CIA asset who received payments from the agency. Oversaw the systematic torture, disappearance, and murder of thousands. Ordered the Letelier assassination in D.C.', href: '/entities/individuals/manuel-contreras', status: 'Convicted — Died in Prison 2015' },
    { name: 'Allen Dulles', role: 'Former CIA Director who established the institutional culture of regime change in Latin America. The 1954 Guatemala coup he directed became the blueprint for the Chile operation', href: '/entities/individuals/allen-dulles', status: 'Died 1969' },
    { name: 'Richard Helms', role: 'CIA Director who received Nixon\'s direct order to prevent Allende from taking power. His handwritten notes from the meeting: "1 in 10 chance perhaps, but save Chile! Not concerned risks involved. $10,000,000 available. Make the economy scream"', href: '/entities/individuals/richard-helms', status: 'Pled No Contest — Perjury' },
    { name: 'Milton Friedman', role: 'University of Chicago economist who trained the "Chicago Boys" — Chilean economists who implemented radical free-market "shock therapy" under Pinochet, privatizing public services, destroying labor protections, and enriching the elite while workers suffered', href: '/entities/individuals/milton-friedman', status: 'Nobel Prize 1976' },
    { name: 'Orlando Letelier', role: 'Former Chilean Ambassador to the U.S. and Allende cabinet minister. Assassinated by a DINA car bomb on Embassy Row in Washington, D.C. on September 21, 1976. His American colleague Ronni Moffitt was also killed', href: '/entities/individuals/orlando-letelier', status: 'Assassinated in D.C.' },
    { name: 'Carlos Prats', role: 'Chilean Army Commander-in-Chief who remained loyal to constitutional government and refused to participate in the coup. Assassinated with his wife by a DINA car bomb in Buenos Aires, September 30, 1974', href: '/entities/individuals/carlos-prats', status: 'Assassinated' },
    { name: 'Margaret Thatcher', role: 'British Prime Minister who publicly supported Pinochet, called him a friend, and opposed his extradition from London to face trial in Spain for crimes against humanity in 1998', href: '/entities/individuals/margaret-thatcher', status: 'Pinochet Defender' },
    { name: 'Gerald Ford', role: 'U.S. President who continued support for the Pinochet regime after Nixon\'s resignation. Under Ford, Kissinger continued as Secretary of State, maintaining U.S. backing for the dictatorship', href: '/entities/individuals/gerald-ford', status: 'Continued Support' },
    { name: 'Edward Korry', role: 'U.S. Ambassador to Chile (1967-1971) who cabled Washington: "Not a nut or bolt shall reach Chile under Allende." Later claimed he was deceived about the extent of CIA covert operations in Chile', href: '/entities/individuals/edward-korry', status: 'Ambassador' },
    { name: 'Michael Townley', role: 'American-born DINA operative who built and detonated the car bomb that killed Orlando Letelier in Washington, D.C. Also involved in other Condor assassinations in Europe and South America', href: '/entities/individuals/michael-townley', status: 'Convicted — 5 Years' },
    { name: 'Sergio Arellano Stark', role: 'Chilean general who led the "Caravan of Death" — a military death squad that traveled by helicopter to cities across Chile in October 1973, summarily executing at least 97 political prisoners who had already surrendered', href: '/entities/individuals/sergio-arellano-stark', status: 'Convicted' },
    { name: 'René Schneider', role: 'Chilean Army Commander-in-Chief who upheld the constitution and refused to block Allende\'s inauguration. Assassinated in a CIA-backed kidnapping attempt on October 22, 1970 — the Agency provided weapons and $50,000 to the plotters', href: '/entities/individuals/rene-schneider', status: 'Assassinated by CIA Plot' },
  ],
  timeline: [
    { date: 'September 4, 1970', event: 'Salvador Allende wins Chilean presidential election with plurality of votes, becoming the first democratically elected Marxist head of state in the Western Hemisphere' },
    { date: 'September 15, 1970', event: 'Nixon meets with Kissinger, AG Mitchell, and CIA Director Helms. Orders CIA to prevent Allende from taking power. Authorizes $10 million. "Make the economy scream." Two tracks launched: Track I (political) and Track II (military coup)' },
    { date: 'October 22, 1970', event: 'CIA-backed plotters attempt to kidnap Army Commander René Schneider to trigger a military coup before Allende\'s inauguration. Schneider is shot and dies three days later. CIA had provided weapons and $50,000' },
    { date: 'November 3, 1970', event: 'Allende inaugurated despite CIA efforts. Nixon and Kissinger shift to long-term destabilization: economic warfare, covert funding of opposition media and political parties, and cultivating military coup plotters' },
    { date: '1970-1973', event: 'CIA spends over $8 million on covert operations in Chile: funding opposition newspapers (El Mercurio), bribing politicians, organizing truckers\' strikes, and establishing relationships with military officers willing to coup' },
    { date: 'June 29, 1973', event: 'Failed coup attempt (the "Tanquetazo") by a Chilean tank regiment. Though unsuccessful, it reveals the military is increasingly willing to act and emboldens coup plotters' },
    { date: 'September 11, 1973', event: 'Military coup begins at dawn. Navy seizes Valparaíso. Air Force bombs La Moneda presidential palace. Army surrounds the capital. Allende\'s last radio address to the nation. Allende dies in the palace. Junta seizes power' },
    { date: 'September 11-30, 1973', event: 'Mass arrests begin immediately. The National Stadium in Santiago converted into a concentration camp holding 7,000+ prisoners. Summary executions, torture, and disappearances begin. Folksinger Víctor Jara tortured for days, hands broken, then shot 44 times' },
    { date: 'October 1973', event: 'General Arellano Stark leads the "Caravan of Death" — a military death squad traveling by helicopter to northern Chilean cities. At least 97 political prisoners executed without trial, many mutilated. Bodies hidden in mass graves' },
    { date: 'June 1974', event: 'DINA (Dirección de Inteligencia Nacional) formally established under Colonel Manuel Contreras. Modeled on the Gestapo, DINA operates a network of secret prisons and torture centers across Chile, with direct CIA liaison' },
    { date: 'September 30, 1974', event: 'DINA car bomb assassinates former Army Commander Carlos Prats and his wife Sofia in Buenos Aires — eliminating a key figure who could have rallied democratic opposition' },
    { date: 'October 6, 1975', event: 'DINA-linked operative shoots former Chilean Vice President Bernardo Leighton and his wife in Rome, Italy. Both survive but are permanently disabled. Condor operations extend to Europe' },
    { date: 'September 21, 1976', event: 'DINA agent Michael Townley detonates a car bomb on Embassy Row in Washington, D.C., killing Orlando Letelier and American colleague Ronni Moffitt — the most brazen act of state terrorism in the U.S. capital' },
    { date: '1975-1989', event: 'The "Chicago Boys" implement radical free-market economics: privatizing social security, healthcare, education, water, and state enterprises. Unions crushed. Inequality skyrockets. Chile becomes the neoliberal experiment for the world' },
    { date: 'October 5, 1988', event: 'Chileans vote "NO" in a plebiscite on whether Pinochet should remain in power for another 8 years. 55.99% vote against him. Pinochet reluctantly agrees to democratic transition after military commanders refuse to support continued rule' },
    { date: 'March 11, 1990', event: 'Pinochet hands power to democratically elected President Patricio Aylwin but remains Commander-in-Chief of the Army until 1998 and a senator-for-life, retaining immunity from prosecution' },
    { date: 'October 16, 1998', event: 'Pinochet arrested in London on a Spanish international arrest warrant for crimes against humanity. Held for 503 days. Released on "health grounds" in March 2000 and returns to Chile' },
    { date: 'December 10, 2006', event: 'Pinochet dies in Santiago at age 91 without being convicted of any crime, despite over 300 criminal complaints. Simultaneously, forensic investigations reveal he stashed at least $28 million in secret foreign bank accounts' },
  ],
  legalOutcomes: [
    { defendant: 'Augusto Pinochet', charge: 'Over 300 criminal complaints including murder, torture, kidnapping, tax evasion, corruption', outcome: 'Arrested in London 1998, released on "health grounds" 2000. Immunity stripped in multiple Chilean cases. Died December 2006 without full trial' },
    { defendant: 'Manuel Contreras', charge: 'Ordering the assassination of Orlando Letelier, overseeing hundreds of murders and disappearances as DINA chief', outcome: 'Convicted in U.S. and Chile — sentences totaling 500+ years. Died in prison August 2015' },
    { defendant: 'Michael Townley', charge: 'Murder of Orlando Letelier and Ronni Moffitt in Washington, D.C.', outcome: 'Pled guilty — sentenced to only 5 years in exchange for testimony. Given new identity under U.S. witness protection' },
    { defendant: 'Richard Helms (CIA Director)', charge: 'Lying to Congress about CIA involvement in Chile during Senate testimony', outcome: 'Pled no contest to misdemeanor charges of failing to testify "fully and completely." Fined $2,000. No prison time' },
    { defendant: 'Henry Kissinger', charge: 'Directing covert operations to overthrow Chilean democracy, complicity in the Schneider assassination, approving support for Pinochet regime', outcome: 'Never charged. French and Argentine judges sought his testimony — he refused. Died November 2023 with total impunity' },
    { defendant: 'Sergio Arellano Stark', charge: 'Leading the Caravan of Death — summary execution of 97+ political prisoners across northern Chile', outcome: 'Convicted of kidnapping and murder in 2008. House arrest due to "health reasons." Died 2016' },
    { defendant: 'Pedro Espinoza Bravo', charge: 'DINA deputy director involved in Letelier assassination and multiple murders', outcome: 'Convicted in Chile — sentenced to life imprisonment for Letelier murder' },
    { defendant: 'Rettig Commission (1991)', charge: 'Official Chilean truth commission investigating Pinochet-era human rights violations', outcome: 'Documented 2,279 deaths and disappearances. Later Valech Commission documented 40,018 torture victims. Led to reparations but limited criminal accountability' },
  ],
  charges: [
    { statute: 'Rome Statute — Crimes Against Humanity (Article 7)', description: 'Systematic and widespread attack against the civilian population including murder, torture, enforced disappearance, imprisonment, and persecution on political grounds. The Pinochet regime\'s 17-year campaign of terror constitutes one of the clearest cases of crimes against humanity in Latin American history', count: '3,200+ killed, 40,000+ tortured, 200,000+ exiled, 1,200+ disappeared' },
    { statute: 'Geneva Conventions — Common Article 3', description: 'During and after the coup, thousands of prisoners were summarily executed, tortured, and subjected to cruel treatment. The use of the National Stadium as a concentration camp, the Caravan of Death executions, and systematic torture in DINA facilities all constitute grave breaches', count: '7,000+ held in National Stadium, 97+ executed by Caravan of Death' },
    { statute: '18 U.S.C. § 1116 — Murder of Internationally Protected Person', description: 'The assassination of Chilean diplomat Orlando Letelier by car bomb in Washington D.C. constitutes murder of an internationally protected person on U.S. soil by a foreign intelligence service operating with the knowledge of U.S. officials', count: '2 killed on U.S. soil: Orlando Letelier and Ronni Moffitt' },
    { statute: 'Convention Against Torture (CAT)', description: 'The Pinochet regime employed systematic torture including electric shock (the "parrilla"), sexual violence, suspension from poles ("pau de arara"), simulated drowning, and confinement in cramped spaces. Torture was policy, not aberration', count: '40,018 victims documented by the Valech Commission' },
    { statute: 'International Convention for the Protection of All Persons from Enforced Disappearance', description: 'Over 1,200 persons were forcibly disappeared — kidnapped by state agents, tortured, murdered, and their remains hidden. Families were told nothing. Many remains have never been found', count: '1,200+ persons forcibly disappeared under the Pinochet regime' },
    { statute: 'OAS Charter / UN Charter — Prohibition on Intervention in Internal Affairs', description: 'The United States spent over $8 million on covert operations to destabilize and overthrow the democratically elected government of Chile, constituting illegal intervention in the internal affairs of a sovereign state in violation of international law', count: '$8+ million in CIA covert operations, plus economic warfare' },
    { statute: 'U.S. Foreign Assistance Act § 502B', description: 'The U.S. continued providing military and economic assistance to the Pinochet regime despite overwhelming evidence of gross human rights violations, in direct violation of statutory requirements', count: 'Millions in continued U.S. aid throughout the dictatorship' },
    { statute: 'Executive Order 11905 / 12333 — Prohibition on Assassination', description: 'CIA involvement in the assassination of General René Schneider and attempted coup operations that led directly to the deaths of thousands violated the prohibition on U.S. government participation in assassinations', count: 'CIA provided weapons and $50,000 to Schneider plotters; facilitated conditions for 3,200+ deaths' },
  ],
  coverup: [
    'Richard Nixon and Henry Kissinger personally ordered the CIA to prevent Allende from taking power through "Track II" — a covert military coup operation — while publicly maintaining the U.S. had no role in Chilean internal affairs. The September 15, 1970 meeting notes, declassified decades later, prove the operation was authorized at the highest levels of the U.S. government.',
    'CIA Director Richard Helms lied to the Senate Foreign Relations Committee about CIA involvement in Chile, testifying that the Agency had not attempted to overthrow Allende. He was convicted of failing to testify "fully and completely" but received only a $2,000 fine — and was celebrated by CIA colleagues who paid the fine as a hero for protecting the Agency.',
    'After the Letelier assassination — an act of state terrorism committed on American soil — the U.S. government slow-walked the FBI investigation for years to protect its relationship with the Pinochet regime and avoid exposing CIA connections to DINA. The CIA knew Contreras ordered the hit but withheld intelligence from investigators.',
    'The U.S. government classified tens of thousands of documents about its role in the Chilean coup for decades. When finally declassified in 1999-2000 under the Clinton Chile Declassification Project, they confirmed that the CIA had provided millions of dollars to coup plotters, funded anti-Allende propaganda, and maintained close relationships with DINA officials who carried out torture and murder.',
    'The CIA knew that DINA director Manuel Contreras was a paid CIA asset and that DINA was systematically torturing and murdering civilians, yet continued its intelligence relationship with Contreras and provided no meaningful warning to potential victims or to Congress.',
    'The "Chicago Boys" economic experiment was presented to the world as a free-market success story, with Milton Friedman and the University of Chicago taking credit for Chile\'s economic "miracle." This narrative deliberately concealed that the reforms were only possible because of military dictatorship — workers were forbidden from striking, unions were destroyed, dissidents were tortured and killed, and the population was terrorized into compliance. The "miracle" produced GDP growth while 45% of Chileans lived below the poverty line.',
    'Pinochet constructed an elaborate legal framework to guarantee his own immunity: a 1978 amnesty law covering all crimes from 1973-1978, a constitution written by his allies, and a senator-for-life position. This legal architecture was designed from the start to prevent accountability for mass murder.',
    'The Chilean military destroyed evidence of its crimes for years — burning documents, moving bodies from mass graves to secret locations, and threatening witnesses. The "Rettig Report" (1991) documented 2,279 deaths but acknowledged that the true number was certainly higher due to systematic evidence destruction.',
  ],
  sources: [
    { title: 'CIA Activities in Chile — U.S. Senate Select Committee on Intelligence', url: 'https://www.intelligence.senate.gov/sites/default/files/hearings/ciaactivitiesinchile.pdf', date: 'September 18, 2000' },
    { title: 'National Security Archive — Chile Documentation Project (24,000 declassified documents)', url: 'https://nsarchive.gwu.edu/project/chile-documentation-project', date: '1999-2010' },
    { title: 'Hinchey Report: CIA Activities in Chile (Report to Congress)', url: 'https://www.intelligence.senate.gov/sites/default/files/hearings/ciaactivitiesinchile.pdf', date: 'September 18, 2000' },
    { title: 'The Pinochet File: A Declassified Dossier on Atrocity and Accountability — Peter Kornbluh', url: 'https://thenewpress.com/books/pinochet-file', date: '2003, Updated 2013' },
    { title: 'Report of the Chilean National Commission on Truth and Reconciliation (Rettig Report)', url: 'https://www.usip.org/sites/default/files/resources/collections/truth_commissions/Chile90-Report/Chile90-Report.pdf', date: 'February 8, 1991' },
    { title: 'National Commission on Political Imprisonment and Torture Report (Valech Report)', url: 'https://web.archive.org/web/2011/http://www.gobiernodechile.cl/comision_valech/', date: 'November 2004' },
    { title: 'Kissinger and Chile: The Declassified Record on Regime Change — National Security Archive', url: 'https://nsarchive.gwu.edu/briefing-book/chile/2020-09-11/kissinger-chile-declassified-record-regime-change', date: 'September 11, 2020' },
    { title: 'The Trial of Henry Kissinger — Christopher Hitchens', url: 'https://www.versobooks.com/products/1946-the-trial-of-henry-kissinger', date: '2001' },
    { title: 'The Shock Doctrine: The Rise of Disaster Capitalism — Naomi Klein (Chapter: The Shock of the Coup)', url: 'https://naomiklein.org/the-shock-doctrine/', date: '2007' },
    { title: 'Human Rights Watch — Chile: The Pinochet Case', url: 'https://www.hrw.org/legacy/campaigns/chile98/', date: '1998-2006' },
    { title: 'The Condor Years: How Pinochet and His Allies Brought Terrorism to Three Continents — John Dinges', url: 'https://thenewpress.com/books/condor-years', date: '2004' },
  ],
};

export default function ChileCoupPage() {
  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/investigations" className="inline-flex items-center gap-2 text-zinc-400 hover:text-blood-500 transition-colors mb-6 pt-4"><ArrowLeft className="w-4 h-4" />Back to Investigations</Link>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="border-2 border-blood-800/60 bg-black/80 p-6 lg:p-8 mb-8">
          <div className="flex items-center gap-3 mb-4"><span className="px-3 py-1 text-xs font-bold uppercase border border-red-500/30 bg-red-500/20 text-red-400">{investigation.severity}</span><span className="px-3 py-1 text-xs font-bold uppercase border border-zinc-500/30 bg-zinc-500/20 text-zinc-400">{investigation.status}</span></div>
          <h1 className="text-3xl lg:text-4xl font-black text-white uppercase tracking-wider mb-2"><GlitchText text={investigation.title} /></h1>
          <p className="text-lg text-blood-500 font-bold mb-4">{investigation.subtitle}</p>
          <p className="text-zinc-400 leading-relaxed">{investigation.summary}</p>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="glass-card p-6 mb-8 border-l-4 border-blood-600">
          <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-blood-500" />The Cover-Up</h2>
          <div className="space-y-3">{investigation.coverup.map((item, idx) => (<div key={idx} className="p-3 bg-red-950/20 border border-red-500/30"><p className="text-sm text-zinc-300">{item}</p></div>))}</div>
        </motion.div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Users className="w-5 h-5 text-blood-500" />Key Figures</h2>
              <div className="space-y-3">{investigation.keyFigures.map((figure, idx) => (<div key={idx} className="flex items-start justify-between p-3 bg-zinc-900/50 border border-zinc-800"><div className="flex-1">{figure.href ? (<Link href={figure.href} className="font-bold text-blood-400 hover:text-blood-300 transition-colors">{figure.name}</Link>) : (<span className="font-bold text-white">{figure.name}</span>)}<p className="text-sm text-zinc-400 mt-1">{figure.role}</p></div><span className="text-xs px-2 py-1 bg-zinc-800 text-zinc-400 border border-zinc-700 whitespace-nowrap ml-2">{figure.status}</span></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Applicable Charges &amp; Statutes</h2>
              <div className="space-y-3">{investigation.charges.map((charge, idx) => (<div key={idx} className="p-4 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-blood-400 text-sm font-mono">{charge.statute}</p><p className="text-sm text-zinc-300 mt-1">{charge.description}</p><p className="text-xs text-red-400 mt-1">{charge.count}</p></div>))}</div>
            </motion.div>
          </div>
          <div className="space-y-6">
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Calendar className="w-4 h-4 text-blood-500" />Timeline</h3>
              <div className="space-y-4">{investigation.timeline.map((item, idx) => (<div key={idx} className="relative pl-4 border-l-2 border-zinc-800"><div className="absolute -left-[5px] top-0 w-2 h-2 rounded-full bg-blood-500" /><p className="text-xs text-blood-500 font-mono">{item.date}</p><p className="text-sm text-zinc-300">{item.event}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Legal Outcomes</h3>
              <div className="space-y-3">{investigation.legalOutcomes.map((item, idx) => (<div key={idx} className="p-3 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-white text-sm">{item.defendant}</p><p className="text-xs text-zinc-400 mt-1">{item.charge}</p><p className="text-xs text-blood-400 mt-1">{item.outcome}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4">Sources</h3>
              <div className="space-y-2">{investigation.sources.map((source, idx) => (<a key={idx} href={source.url} target="_blank" rel="noopener noreferrer" className="flex items-start gap-2 p-2 text-sm text-zinc-400 hover:text-blood-400 hover:bg-zinc-900/50 transition-colors"><ExternalLink className="w-4 h-4 mt-0.5 flex-shrink-0" /><div><span>{source.title}</span><span className="text-zinc-600 ml-2">({source.date})</span></div></a>))}</div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
