"use client";

import { useState } from "react";
import Link from "next/link";
import { Users, ChevronRight, Search, Skull } from "lucide-react";
import EntityCard, { Entity } from "@/components/cards/EntityCard";

// Placeholder data
const individuals: Entity[] = [
  {
    id: "trump-1",
    slug: "donald-trump",
    name: "Donald J. Trump",
    type: "individual",
    description: "45th & 47th President of the United States. Currently serving as 47th President (2025-Present). Convicted felon (34 counts). Subject of criminal indictments, civil judgments, and investigations spanning election interference, financial crimes, human trafficking complicity, classified document mishandling, and incitement of insurrection.",
    role: "47th President, Convicted Felon",
    investigationCount: 39,
    riskLevel: "extreme",
  },
  {
    id: "epstein-1",
    slug: "jeffrey-epstein",
    name: "Jeffrey Epstein",
    type: "individual",
    description: "Convicted sex offender and financier who operated a sex trafficking network targeting minors. Connected to numerous powerful individuals including Trump, Clinton, Prince Andrew. Died in custody August 2019 under disputed circumstances.",
    role: "Convicted Sex Trafficker",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "maxwell-1",
    slug: "ghislaine-maxwell",
    name: "Ghislaine Maxwell",
    type: "individual",
    description: "Convicted sex trafficker and Epstein co-conspirator. Found guilty of recruiting, grooming, and trafficking underage girls. Currently serving 20-year federal prison sentence.",
    role: "Convicted Sex Trafficker",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "giuliani-1",
    slug: "rudy-giuliani",
    name: "Rudy Giuliani",
    type: "individual",
    description: "Disbarred attorney, former NYC Mayor, Trump personal lawyer. Georgia RICO defendant. $148 million defamation judgment. Filed bankruptcy. Key figure in Ukraine pressure campaign and election overturn efforts.",
    role: "Disbarred Attorney, RICO Defendant",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "manafort-1",
    slug: "paul-manafort",
    name: "Paul Manafort",
    type: "individual",
    description: "Convicted felon, Trump 2016 campaign chairman. Shared polling data with Russian intelligence asset. Convicted of tax fraud, bank fraud, FBAR violations. Pardoned by Trump.",
    role: "Convicted Felon, Pardoned",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "stone-1",
    slug: "roger-stone",
    name: "Roger Stone",
    type: "individual",
    description: "Convicted felon, political consultant, Trump advisor. Coordinated with WikiLeaks during 2016 campaign. Convicted of lying, obstruction, witness tampering. Pardoned by Trump.",
    role: "Convicted Felon, Pardoned",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "flynn-1",
    slug: "michael-flynn",
    name: "Michael Flynn",
    type: "individual",
    description: "Convicted felon, former National Security Advisor (24 days). Lied to FBI about Russian contacts. Pleaded guilty. Pardoned by Trump. Called for martial law to overturn 2020 election.",
    role: "Convicted Felon, Pardoned",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "bannon-1",
    slug: "steve-bannon",
    name: "Steve Bannon",
    type: "individual",
    description: "Convicted felon. We Build the Wall fraud (pardoned). Contempt of Congress (served prison). Former White House Chief Strategist. Breitbart executive. Cambridge Analytica vice president.",
    role: "Convicted Felon, Served Prison",
    investigationCount: 4,
    riskLevel: "extreme",
  },
  {
    id: "kushner-1",
    slug: "jared-kushner",
    name: "Jared Kushner",
    type: "individual",
    description: "Trump son-in-law, former Senior Advisor. Received $2 billion from Saudi sovereign wealth fund after leaving office. Security clearance initially denied. Oversaw Cambridge Analytica relationship.",
    role: "Former Senior Advisor",
    investigationCount: 3,
    riskLevel: "high",
  },
  {
    id: "ivanka-1",
    slug: "ivanka-trump",
    name: "Ivanka Trump",
    type: "individual",
    description: "Trump daughter, former Senior Advisor. Received Chinese trademarks while serving in White House. Testified to January 6 Committee and in NY fraud trial.",
    role: "Former Senior Advisor",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "djtjr-1",
    slug: "donald-trump-jr",
    name: "Donald Trump Jr.",
    type: "individual",
    description: "Trump eldest son, Trump Organization executive. Arranged June 2016 Trump Tower meeting with Russians offering Clinton dirt. 'I love it' email.",
    role: "Trump Organization Executive",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "eric-1",
    slug: "eric-trump",
    name: "Eric Trump",
    type: "individual",
    description: "Trump son, Trump Organization executive. Testified in NY civil fraud trial. Liable in $454 million fraud judgment.",
    role: "Trump Organization Executive",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "weisselberg-1",
    slug: "allen-weisselberg",
    name: "Allen Weisselberg",
    type: "individual",
    description: "Convicted felon (twice). Former Trump Organization CFO. Convicted of tax fraud (2022) and perjury (2024). Served time at Rikers Island twice. Refused to fully cooperate against Trump.",
    role: "Convicted Felon, Multiple Times",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "cohen-1",
    slug: "michael-cohen",
    name: "Michael Cohen",
    type: "individual",
    description: "Convicted felon, former Trump personal attorney and 'fixer'. Made hush money payments to Stormy Daniels. Became key witness against Trump leading to 34 felony convictions.",
    role: "Convicted Felon, Key Witness",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "putin-1",
    slug: "vladimir-putin",
    name: "Vladimir Putin",
    type: "individual",
    description: "President of Russia. Ordered 2016 election interference operation per Mueller Report. Internet Research Agency, GRU hacking. Trump defended over US intelligence at Helsinki.",
    role: "Russian President",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "mbs-1",
    slug: "mohammed-bin-salman",
    name: "Mohammed bin Salman",
    type: "individual",
    description: "Saudi Crown Prince. Ordered Khashoggi murder per CIA. $110B Trump arms deal enabling Yemen genocide (400,000+ deaths). $2B investment in Kushner fund.",
    role: "Saudi Crown Prince",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "meadows-1",
    slug: "mark-meadows",
    name: "Mark Meadows",
    type: "individual",
    description: "Former White House Chief of Staff. Georgia RICO defendant. Present on 'find 11,780 votes' call. Refused January 6 Committee testimony.",
    role: "RICO Defendant",
    investigationCount: 3,
    riskLevel: "extreme",
  },
  {
    id: "eastman-1",
    slug: "john-eastman",
    name: "John Eastman",
    type: "individual",
    description: "Disbarred attorney. Authored 'Eastman memos' providing roadmap to overturn 2020 election. Georgia RICO defendant. Fake electors scheme architect.",
    role: "Disbarred Attorney, RICO Defendant",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "powell-1",
    slug: "sidney-powell",
    name: "Sidney Powell",
    type: "individual",
    description: "Attorney who spread false election fraud claims. 'Release the Kraken' conspiracy theories. Pleaded guilty in Georgia RICO case (6 misdemeanors).",
    role: "Pled Guilty",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "chesebro-1",
    slug: "kenneth-chesebro",
    name: "Kenneth Chesebro",
    type: "individual",
    description: "Attorney who devised fake electors scheme. Wrote memos outlining strategy to submit false electors. Pleaded guilty in Georgia RICO case.",
    role: "Pled Guilty",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "clark-1",
    slug: "jeffrey-clark",
    name: "Jeffrey Clark",
    type: "individual",
    description: "Former DOJ official. Trump attempted to install as Acting AG to overturn election. Drafted false election fraud letter. Georgia RICO defendant.",
    role: "RICO Defendant",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "barr-1",
    slug: "bill-barr",
    name: "Bill Barr",
    type: "individual",
    description: "Former Attorney General. Misrepresented Mueller Report findings. Declared 'no collusion' before report released. Ordered Lafayette Square tear gas incident.",
    role: "Former Attorney General",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "pruitt-1",
    slug: "scott-pruitt",
    name: "Scott Pruitt",
    type: "individual",
    description: "Former EPA Administrator. Rolled back 100+ environmental regulations. Multiple ethics scandals. $43,000 soundproof booth. Resigned amid corruption.",
    role: "Resigned, Ethics Violations",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "price-1",
    slug: "tom-price",
    name: "Tom Price",
    type: "individual",
    description: "Former HHS Secretary. Resigned after $400,000+ private jet travel scandal. Stock trading in healthcare companies while legislating.",
    role: "Resigned, Ethics Violations",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "perry-1",
    slug: "rick-perry",
    name: "Rick Perry",
    type: "individual",
    description: "Former Energy Secretary. Implicated in Ukraine 'Three Amigos' scheme. Climate change skepticism. Previously wanted to eliminate department he led.",
    role: "Former Energy Secretary",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "schwab-1",
    slug: "klaus-schwab",
    name: "Klaus Schwab",
    type: "individual",
    description: "Founder and Executive Chairman of the World Economic Forum. Architect of 'The Great Reset' initiative and Young Global Leaders program influencing world governments.",
    role: "WEF Founder & Chairman",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "gates-1",
    slug: "bill-gates",
    name: "Bill Gates",
    type: "individual",
    description: "Co-founder of Microsoft and co-chair of the Bill & Melinda Gates Foundation. Influential figure in global health policy, vaccine development, and agricultural investment.",
    role: "Foundation Co-Chair",
    investigationCount: 3,
    riskLevel: "high",
  },
  {
    id: "soros-1",
    slug: "george-soros",
    name: "George Soros",
    type: "individual",
    description: "Founder of Open Society Foundations. Known for currency speculation and funding political advocacy groups worldwide.",
    role: "OSF Founder",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "parnas-1",
    slug: "lev-parnas",
    name: "Lev Parnas",
    type: "individual",
    description: "Convicted felon, Giuliani associate. Key figure in Ukraine pressure campaign. Convicted of campaign finance crimes. Cooperated with Congress.",
    role: "Convicted Felon",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "fruman-1",
    slug: "igor-fruman",
    name: "Igor Fruman",
    type: "individual",
    description: "Convicted felon, Giuliani associate. Partnered with Parnas in Ukraine scheme. Convicted of soliciting foreign campaign contributions.",
    role: "Convicted Felon",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "kilimnik-1",
    slug: "konstantin-kilimnik",
    name: "Konstantin Kilimnik",
    type: "individual",
    description: "Russian intelligence asset identified by Senate Intelligence Committee. Received polling data from Manafort. Sanctioned by US Treasury.",
    role: "Russian Intelligence Asset",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "wexner-1",
    slug: "les-wexner",
    name: "Les Wexner",
    type: "individual",
    description: "Billionaire, L Brands founder. Gave Epstein power of attorney, transferred $77M mansion. Claimed Epstein 'misappropriated' funds.",
    role: "Epstein Financial Connection",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "andrew-1",
    slug: "prince-andrew",
    name: "Prince Andrew",
    type: "individual",
    description: "Duke of York. Settled Virginia Giuffre lawsuit. Photographed with Epstein victims. BBC interview disaster. Stripped of royal duties.",
    role: "British Royal, Epstein Associate",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "clinton-1",
    slug: "bill-clinton",
    name: "Bill Clinton",
    type: "individual",
    description: "42nd US President. Multiple Epstein flights documented. Visited Epstein island (per victim testimony). Denied knowing of Epstein crimes.",
    role: "Former President, Epstein Associate",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "kolfage-1",
    slug: "brian-kolfage",
    name: "Brian Kolfage",
    type: "individual",
    description: "Convicted felon. Triple amputee veteran who founded 'We Build the Wall' crowdfunding scam. Sentenced to 51 months. Defrauded donors of millions.",
    role: "Convicted Felon",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "assange-1",
    slug: "julian-assange",
    name: "Julian Assange",
    type: "individual",
    description: "WikiLeaks founder. Released DNC emails in coordination with Russian intelligence. Roger Stone intermediary to Trump campaign. Now free after plea deal.",
    role: "WikiLeaks Founder",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "corsi-1",
    slug: "jerome-corsi",
    name: "Jerome Corsi",
    type: "individual",
    description: "Right-wing author and conspiracy theorist. Claimed advance knowledge of WikiLeaks releases. Suspected intermediary between Stone and WikiLeaks.",
    role: "Stone Associate",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "yanukovych-1",
    slug: "viktor-yanukovych",
    name: "Viktor Yanukovych",
    type: "individual",
    description: "Former Ukraine President. Putin ally ousted in 2014 revolution. Paid Manafort $12.7 million via secret ledger. Living in exile in Russia.",
    role: "Former Ukraine President",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "deripaska-1",
    slug: "oleg-deripaska",
    name: "Oleg Deripaska",
    type: "individual",
    description: "Russian oligarch close to Putin. Manafort owed him millions. Sanctioned by US Treasury. Indicted for sanctions violations.",
    role: "Russian Oligarch, Sanctioned",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "kislyak-1",
    slug: "sergey-kislyak",
    name: "Sergey Kislyak",
    type: "individual",
    description: "Former Russian Ambassador to US. Met with Flynn, Sessions, Kushner. Flynn lied to FBI about their conversations. Key figure in sanctions discussions.",
    role: "Former Russian Ambassador",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "sondland-1",
    slug: "gordon-sondland",
    name: "Gordon Sondland",
    type: "individual",
    description: "EU Ambassador. $1 million inaugural donation. Key impeachment witness. 'Everyone was in the loop.' Confirmed quid pro quo with Ukraine.",
    role: "Former Ambassador, Key Witness",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "volker-1",
    slug: "kurt-volker",
    name: "Kurt Volker",
    type: "individual",
    description: "Former Ukraine Special Envoy. Part of 'Three Amigos' with Sondland and Perry. Resigned during impeachment. Testified about shadow diplomacy.",
    role: "Former Ukraine Envoy",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "miller-1",
    slug: "stephen-miller",
    name: "Stephen Miller",
    type: "individual",
    description: "White House Senior Advisor. Architect of family separation policy. Zero tolerance designer. Leaked emails showed white nationalist ties.",
    role: "Senior Advisor, Policy Architect",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "nielsen-1",
    slug: "kirstjen-nielsen",
    name: "Kirstjen Nielsen",
    type: "individual",
    description: "Former DHS Secretary. Implemented family separation. Denied knowledge of policy. 'We do not have a policy of separating families' - proven lie.",
    role: "Former DHS Secretary",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "sessions-1",
    slug: "jeff-sessions",
    name: "Jeff Sessions",
    type: "individual",
    description: "Former Attorney General. Recused from Russia probe. Implemented zero tolerance policy. Fired by Trump for recusal. Lied to Congress about Russian contacts.",
    role: "Former Attorney General",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "papadopoulos-1",
    slug: "george-papadopoulos",
    name: "George Papadopoulos",
    type: "individual",
    description: "Former campaign advisor. Learned of Russian Clinton dirt before public. Told Australian diplomat, triggering FBI investigation. Pled guilty to lying to FBI.",
    role: "Convicted Felon",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "gates-r-1",
    slug: "rick-gates",
    name: "Rick Gates",
    type: "individual",
    description: "Deputy campaign chairman. Manafort associate. Pled guilty to conspiracy and lying. Cooperated extensively with Mueller. Key witness in multiple trials.",
    role: "Convicted Felon, Cooperating Witness",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "hicks-1",
    slug: "hope-hicks",
    name: "Hope Hicks",
    type: "individual",
    description: "Former Communications Director. Close Trump aide. Testified in hush money trial (cried on stand). Present during cover story creation. January 6 Committee witness.",
    role: "Key Witness",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "carroll-1",
    slug: "e-jean-carroll",
    name: "E. Jean Carroll",
    type: "individual",
    description: "Journalist and author who won $83.3 million defamation judgment against Trump after he denied raping her. Jury found Trump liable for sexual abuse in 2023.",
    role: "Sexual Assault Survivor, $88M Judgment",
    investigationCount: 2,
    riskLevel: "low",
  },
  {
    id: "daniels-1",
    slug: "stormy-daniels",
    name: "Stormy Daniels",
    type: "individual",
    description: "Adult film actress paid $130,000 in hush money before 2016 election. Key witness in Trump criminal trial that resulted in 34 felony convictions.",
    role: "Key Witness, Hush Money Recipient",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "freeman-1",
    slug: "ruby-freeman",
    name: "Ruby Freeman",
    type: "individual",
    description: "Georgia election worker defamed by Trump and Giuliani. $148 million defamation judgment against Giuliani. Trump mentioned her 18 times in Georgia call.",
    role: "Defamation Victim, $148M Judgment",
    investigationCount: 3,
    riskLevel: "low",
  },
  {
    id: "moss-1",
    slug: "shaye-moss",
    name: "Shaye Moss",
    type: "individual",
    description: "Georgia election worker, daughter of Ruby Freeman. Gave powerful January 6 Committee testimony about racist harassment. $148 million judgment with mother.",
    role: "Defamation Victim, Key Witness",
    investigationCount: 3,
    riskLevel: "low",
  },
  {
    id: "hutchinson-1",
    slug: "cassidy-hutchinson",
    name: "Cassidy Hutchinson",
    type: "individual",
    description: "Former Mark Meadows aide who provided explosive January 6 Committee testimony. Testified about Trump's knowledge, limo incident, ketchup on wall.",
    role: "Key January 6 Witness",
    investigationCount: 2,
    riskLevel: "low",
  },
  {
    id: "smith-1",
    slug: "jack-smith",
    name: "Jack Smith",
    type: "individual",
    description: "Special Counsel who indicted Trump on classified documents and January 6 charges. Forced to dismiss cases after Trump won 2024 election.",
    role: "Former Special Counsel",
    investigationCount: 2,
    riskLevel: "low",
  },
  {
    id: "willis-1",
    slug: "fani-willis",
    name: "Fani Willis",
    type: "individual",
    description: "Fulton County DA prosecuting Trump and 18 co-defendants under Georgia RICO statute. Case complicated by relationship with special prosecutor.",
    role: "Georgia RICO Prosecutor",
    investigationCount: 1,
    riskLevel: "low",
  },
  {
    id: "pence-1",
    slug: "mike-pence",
    name: "Mike Pence",
    type: "individual",
    description: "Former Vice President who refused Trump's pressure to reject electoral votes on January 6. Evacuated as mob chanted 'Hang Mike Pence.'",
    role: "Former Vice President, January 6 Target",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "raffensperger-1",
    slug: "brad-raffensperger",
    name: "Brad Raffensperger",
    type: "individual",
    description: "Georgia Secretary of State who refused Trump's demand to 'find 11,780 votes.' Recorded the call. Key witness in Georgia RICO case.",
    role: "Georgia SOS, Key Witness",
    investigationCount: 2,
    riskLevel: "low",
  },
  {
    id: "comey-1",
    slug: "james-comey",
    name: "James Comey",
    type: "individual",
    description: "FBI Director fired by Trump over 'this Russia thing.' His firing led to Mueller appointment. Documented Trump obstruction in memos.",
    role: "Fired FBI Director",
    investigationCount: 3,
    riskLevel: "moderate",
  },
  {
    id: "mueller-1",
    slug: "robert-mueller",
    name: "Robert Mueller",
    type: "individual",
    description: "Special Counsel who documented Russian interference and 10 instances of Trump obstruction. Report could not exonerate Trump but declined to charge.",
    role: "Former Special Counsel",
    investigationCount: 2,
    riskLevel: "low",
  },
  {
    id: "tarrio-1",
    slug: "enrique-tarrio",
    name: "Enrique Tarrio",
    type: "individual",
    description: "Former Proud Boys chairman convicted of seditious conspiracy for January 6. Sentenced to 22 years - longest January 6 sentence.",
    role: "Convicted Seditious Conspirator, 22 Years",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "rhodes-1",
    slug: "stewart-rhodes",
    name: "Stewart Rhodes",
    type: "individual",
    description: "Oath Keepers founder convicted of seditious conspiracy for January 6. Coordinated 'stack' breach and armed QRF teams. 18 years in prison.",
    role: "Convicted Seditious Conspirator, 18 Years",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "fauci-1",
    slug: "anthony-fauci",
    name: "Anthony Fauci",
    type: "individual",
    description: "Former NIAID Director who contradicted Trump's COVID misinformation. Received death threats. Required security detail. Retired after 54 years.",
    role: "Former Chief Medical Advisor",
    investigationCount: 2,
    riskLevel: "low",
  },
  {
    id: "dejoy-1",
    slug: "louis-dejoy",
    name: "Louis DeJoy",
    type: "individual",
    description: "Postmaster General who removed mail sorting machines before 2020 election. Major Trump donor ($2.5M+). Still in office despite controversy.",
    role: "Postmaster General, Trump Donor",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "navarro-1",
    slug: "peter-navarro",
    name: "Peter Navarro",
    type: "individual",
    description: "Former White House trade advisor. Developed 'Green Bay Sweep' plan to overturn election. Convicted of contempt of Congress. Served 4 months in prison.",
    role: "Convicted, Served Prison",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "pecker-1",
    slug: "david-pecker",
    name: "David Pecker",
    type: "individual",
    description: "Former AMI/National Enquirer CEO. Ran catch-and-kill operation for Trump. First witness in criminal trial. Paid $150K to Karen McDougal.",
    role: "Catch-and-Kill Operator",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "mcdougal-1",
    slug: "karen-mcdougal",
    name: "Karen McDougal",
    type: "individual",
    description: "Former Playboy model who had affair with Trump. Paid $150,000 by AMI to keep quiet before 2016 election. Catch-and-kill victim.",
    role: "Hush Money Recipient",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "giuffre-1",
    slug: "virginia-giuffre",
    name: "Virginia Giuffre",
    type: "individual",
    description: "Epstein trafficking survivor. Recruited at Mar-a-Lago at 16. Sued and forced Prince Andrew settlement ($12M+). Led document unsealing efforts.",
    role: "Epstein Survivor, Key Accuser",
    investigationCount: 2,
    riskLevel: "low",
  },
  {
    id: "r-mercer-1",
    slug: "robert-mercer",
    name: "Robert Mercer",
    type: "individual",
    description: "Billionaire who funded Cambridge Analytica ($15M+) and Breitbart. Data harvesting operation affected 87 million Facebook users.",
    role: "Cambridge Analytica Funder",
    investigationCount: 3,
    riskLevel: "high",
  },
  {
    id: "rebekah-mercer-1",
    slug: "rebekah-mercer",
    name: "Rebekah Mercer",
    type: "individual",
    description: "Robert Mercer's daughter. Cambridge Analytica board member. Trump transition team. Major funder of Breitbart and right-wing causes.",
    role: "Cambridge Analytica Board, Trump Transition",
    investigationCount: 3,
    riskLevel: "high",
  },
  {
    id: "melania-1",
    slug: "melania-trump",
    name: "Melania Trump",
    type: "individual",
    description: "First Lady who wore 'I Really Don't Care, Do U?' jacket to visit detained children. Einstein Visa despite no qualifications. Plagiarized Michelle Obama. Largely absent during Trump's crimes.",
    role: "First Lady, Einstein Visa Recipient",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "cipollone-1",
    slug: "pat-cipollone",
    name: "Pat Cipollone",
    type: "individual",
    description: "White House Counsel who warned Trump that January 6 schemes were illegal. Testified to January 6 Committee about trying to prevent unconstitutional actions.",
    role: "Former White House Counsel",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "birx-1",
    slug: "deborah-birx",
    name: "Deborah Birx",
    type: "individual",
    description: "COVID task force coordinator who admitted 30-40% of deaths could have been prevented. 'Scarf lady' who regretted not being more forceful against Trump's misinformation.",
    role: "Former COVID-19 Coordinator",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "rosenstein-1",
    slug: "rod-rosenstein",
    name: "Rod Rosenstein",
    type: "individual",
    description: "Deputy AG who appointed Mueller, wrote Comey firing memo. Discussed wearing wire to record Trump and invoking 25th Amendment.",
    role: "Former Deputy Attorney General",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "mccabe-1",
    slug: "andrew-mccabe",
    name: "Andrew McCabe",
    type: "individual",
    description: "Acting FBI Director fired 26 hours before pension vested. Opened obstruction investigation into Trump. DOJ investigation later dropped, pension restored.",
    role: "Former Acting FBI Director",
    investigationCount: 2,
    riskLevel: "moderate",
  },
  {
    id: "c-kushner-1",
    slug: "charles-kushner",
    name: "Charles Kushner",
    type: "individual",
    description: "Jared's father convicted of 18 felonies including hiring prostitute to entrap witness. Pardoned by Trump. Nominated as Ambassador to France despite criminal history.",
    role: "Convicted Felon, Pardoned, Amb. Nominee",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "nauta-1",
    slug: "walt-nauta",
    name: "Walt Nauta",
    type: "individual",
    description: "Trump valet indicted for moving classified documents and lying to FBI. Caught on surveillance moving boxes. Case dismissed by Judge Cannon, DOJ appealing.",
    role: "Documents Co-Defendant",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "deoliveira-1",
    slug: "carlos-de-oliveira",
    name: "Carlos De Oliveira",
    type: "individual",
    description: "Mar-a-Lago property manager indicted for trying to delete security footage and lying to FBI. Asked employee to erase evidence. Case dismissed.",
    role: "Documents Co-Defendant",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "barrack-1",
    slug: "tom-barrack",
    name: "Tom Barrack",
    type: "individual",
    description: "Billionaire Trump friend who chaired inaugural committee that raised $107M. Charged as unregistered UAE agent but acquitted. Inaugural spending under investigation.",
    role: "Inaugural Chair, Acquitted Foreign Agent",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "r-murdoch-1",
    slug: "rupert-murdoch",
    name: "Rupert Murdoch",
    type: "individual",
    description: "Media mogul who built Fox News. Dominion lawsuit revealed he knew election lies were false but allowed them. $787.5M settlement. Texted 'I hate him passionately' about Trump.",
    role: "Fox Chairman Emeritus, Disinformation Enabler",
    investigationCount: 2,
    riskLevel: "extreme",
  },
  {
    id: "l-murdoch-1",
    slug: "lachlan-murdoch",
    name: "Lachlan Murdoch",
    type: "individual",
    description: "Fox Corporation CEO who oversaw network during 2020 election disinformation. Deposed in Dominion lawsuit. Approved Tucker Carlson firing after settlement.",
    role: "Fox CEO, Disinformation Enabler",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "carlson-1",
    slug: "tucker-carlson",
    name: "Tucker Carlson",
    type: "individual",
    description: "Former Fox host who privately texted election claims were 'absurd' and he 'passionately hated' Trump while promoting lies on air. Fired after Dominion settlement. Interviewed Putin.",
    role: "Fired Fox Host, Putin Interviewer",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "hannity-1",
    slug: "sean-hannity",
    name: "Sean Hannity",
    type: "individual",
    description: "Fox News host who functioned as Trump's informal advisor with regular phone calls. Texted Mark Meadows during January 6. Privately doubted election claims while promoting them.",
    role: "Fox Host, Trump Informal Advisor",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "bartiromo-1",
    slug: "maria-bartiromo",
    name: "Maria Bartiromo",
    type: "individual",
    description: "Fox Business host who first aired Sidney Powell's Dominion conspiracy theory. Named defendant in Dominion lawsuit. Continued spreading claims after being told they were false.",
    role: "Fox Host, Disinformation Spreader",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "dobbs-1",
    slug: "lou-dobbs",
    name: "Lou Dobbs",
    type: "individual",
    description: "Fox Business host whose show was cancelled after Smartmatic lawsuit. Repeatedly promoted false election claims. Called 'true believer' in Trump conspiracies. Died 2024.",
    role: "Cancelled Fox Host (Deceased)",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "ornato-1",
    slug: "tony-ornato",
    name: "Tony Ornato",
    type: "individual",
    description: "Secret Service agent detailed to White House as deputy chief of staff. Present during January 6 events. Text messages from Jan 5-6 deleted. Disputed Hutchinson testimony.",
    role: "January 6 Key Figure",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "nix-1",
    slug: "alexander-nix",
    name: "Alexander Nix",
    type: "individual",
    description: "Cambridge Analytica CEO who oversaw harvesting of 87 million Facebook profiles. Caught on camera discussing bribes and honey traps. Banned as company director.",
    role: "Data Harvesting Architect",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "wylie-1",
    slug: "christopher-wylie",
    name: "Christopher Wylie",
    type: "individual",
    description: "Cambridge Analytica whistleblower who exposed the company's harvesting of 87 million Facebook users' data. Testified to UK Parliament and US Congress.",
    role: "Whistleblower",
    investigationCount: 1,
    riskLevel: "low",
  },
  {
    id: "vrablic-1",
    slug: "rosemary-vrablic",
    name: "Rosemary Vrablic",
    type: "individual",
    description: "Trump's personal banker at Deutsche Bank who approved $300M+ in loans when no other bank would. Resigned amid investigation into personal investments in Kushner-connected company.",
    role: "Trump's Personal Banker",
    investigationCount: 2,
    riskLevel: "high",
  },
  {
    id: "wade-1",
    slug: "nathan-wade",
    name: "Nathan Wade",
    type: "individual",
    description: "Special prosecutor appointed by Fani Willis for Trump RICO case. Romantic relationship with Willis disclosed. Paid $654K+. Resigned from case after controversy.",
    role: "Former Georgia Special Prosecutor",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "howard-1",
    slug: "dylan-howard",
    name: "Dylan Howard",
    type: "individual",
    description: "Former AMI Chief Content Officer who orchestrated catch-and-kill operations for Trump. Coordinated Karen McDougal payment with Cohen. Received immunity for cooperation.",
    role: "Catch-and-Kill Operator",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "g-conway-1",
    slug: "george-conway",
    name: "George Conway",
    type: "individual",
    description: "Conservative attorney and Trump critic. Lincoln Project co-founder. Ex-husband of Kellyanne Conway. Publicly diagnosed Trump with narcissistic personality disorder.",
    role: "Trump Critic, Attorney",
    investigationCount: 0,
    riskLevel: "low",
  },
  {
    id: "mcgahn-1",
    slug: "don-mcgahn",
    name: "Don McGahn",
    type: "individual",
    description: "Former White House Counsel who refused Trump's order to fire Mueller. Provided 30+ hours testimony documenting obstruction attempts. Key Mueller witness.",
    role: "Former White House Counsel",
    investigationCount: 1,
    riskLevel: "moderate",
  },
  {
    id: "nunes-1",
    slug: "devin-nunes",
    name: "Devin Nunes",
    type: "individual",
    description: "Trump Media CEO, former Congressman. Famous 'Midnight Run' to White House with classified info. Authored misleading memo attacking Russia probe. Sued critics extensively.",
    role: "TMTG CEO, Former Congressman",
    investigationCount: 1,
    riskLevel: "high",
  },
  {
    id: "patel-1",
    slug: "kash-patel",
    name: "Kash Patel",
    type: "individual",
    description: "Trump's FBI Director nominee. Co-authored Nunes memo. Published enemies list. Vowed to dismantle FBI. Witness in classified documents case. 'Deep state' conspiracy promoter.",
    role: "FBI Director Nominee",
    investigationCount: 1,
    riskLevel: "extreme",
  },
  {
    id: "k-conway-1",
    slug: "kellyanne-conway",
    name: "Kellyanne Conway",
    type: "individual",
    description: "Trump campaign manager and Senior Counselor. Coined 'alternative facts.' Multiple Hatch Act violations. OSC recommended removal. Ex-wife of George Conway.",
    role: "Former Senior Counselor",
    investigationCount: 0,
    riskLevel: "high",
  },
  {
    id: "gaetz-1",
    slug: "matt-gaetz",
    name: "Matt Gaetz",
    type: "individual",
    description: "Former AG nominee, ex-Congressman. Withdrew amid sex trafficking investigation. DOJ declined prosecution but House Ethics probe continued. Close associate Joel Greenberg convicted.",
    role: "Former AG Nominee, Ex-Congressman",
    investigationCount: 0,
    riskLevel: "extreme",
  },
  {
    id: "hegseth-1",
    slug: "pete-hegseth",
    name: "Pete Hegseth",
    type: "individual",
    description: "Secretary of Defense confirmed despite sexual assault allegations, drinking concerns, no senior leadership experience. Former Fox host. Advocated pardoning war criminals.",
    role: "Secretary of Defense",
    investigationCount: 0,
    riskLevel: "high",
  },
];

export default function IndividualsPage() {
  const [searchQuery, setSearchQuery] = useState("");
  
  const filteredIndividuals = individuals.filter((person) =>
    person.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Breadcrumb - Sharp */}
        <nav className="flex items-center gap-2 text-sm text-zinc-500 mb-6 pt-4">
          <Link href="/" className="hover:text-blood-600 transition-colors">Home</Link>
          <ChevronRight className="w-4 h-4" />
          <Link href="/entities" className="hover:text-blood-600 transition-colors">Entities</Link>
          <ChevronRight className="w-4 h-4" />
          <span className="text-blood-600">Individuals</span>
        </nav>

        {/* Header - Crystal Clear */}
        <div className="py-8">
          <div className="border-2 border-blood-800/60 bg-black/60 p-6 lg:p-8 mb-8">
            {/* Top decorative line */}
            <div className="flex items-center gap-4 mb-6">
              <span className="h-[2px] flex-1 bg-gradient-to-r from-blood-700 to-transparent" />
              <Users className="w-6 h-6 text-blood-600" />
              <span className="h-[2px] flex-1 bg-gradient-to-l from-blood-700 to-transparent" />
            </div>

            <div className="text-center mb-6">
              <h1 className="text-3xl lg:text-4xl font-black text-white uppercase tracking-wider mb-2">
                KEY INDIVIDUALS
              </h1>
              <p className="text-lg text-blood-600 font-bold uppercase tracking-[0.15em]">
                The Names Behind The Crimes
              </p>
              <p className="text-sm text-zinc-500 mt-2">
                {individuals.length} individuals documented in the archive
              </p>
            </div>

            <p className="text-zinc-400 text-center max-w-2xl mx-auto leading-relaxed">
              Decision-makers, executives, officials, and operatives whose actions have caused 
              harm. Politicians, CEOs, bureaucrats, and the faces behind the policies of death.
            </p>
          </div>
        </div>

        {/* Search - Sharp */}
        <div className="mb-8">
          <div className="relative max-w-md">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-zinc-500" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search individuals..."
              className="w-full pl-12 pr-4 py-3 bg-black/60 border-2 border-zinc-800 text-white placeholder-zinc-600 focus:outline-none focus:border-blood-700 transition-colors"
            />
          </div>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredIndividuals.map((person) => (
            <EntityCard key={person.id} entity={person} />
          ))}
        </div>

        {filteredIndividuals.length === 0 && (
          <div className="border border-zinc-800 bg-black/60 p-12 text-center">
            <div className="w-16 h-16 border-2 border-zinc-700 flex items-center justify-center mx-auto mb-4">
              <Skull className="w-8 h-8 text-zinc-600" />
            </div>
            <h3 className="text-xl font-bold text-white mb-2 uppercase tracking-wider">No Individuals Found</h3>
            <p className="text-zinc-500">No individuals match your search criteria.</p>
          </div>
        )}
      </div>
    </div>
  );
}
