// Extended workspace data - Part 2 (Workspaces 8-12)
// Corporate Crime, Boeing, Clarence Thomas, Dark Money, Fox/Dominion

import { 
  Workspace, 
  WorkspaceMember, 
  WorkspaceMessage, 
  Evidence, 
  WorkspaceDocument,
  WorkspaceTimeline,
  ResearchTask,
} from '@/types/workspace';
import { investigators, getTeam } from './workspaceData';

// ==================== WORKSPACE 8: BOEING WHISTLEBLOWER DEATHS ====================
const boeingMessages: WorkspaceMessage[] = [
  {
    id: 'bm1',
    authorId: 'kyle-anderson',
    authorName: 'Kyle Anderson',
    content: 'The timing of John Barnett\'s death is deeply suspicious. He was scheduled to continue testimony against Boeing the day he was found dead.',
    type: 'text',
    timestamp: new Date('2024-03-12T07:30:00'),
    isPinned: true,
  },
  {
    id: 'bm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'This is now two Boeing whistleblowers dead in two months. Josh Dean in April. Both raised concerns about 737 MAX quality control.',
    type: 'text',
    timestamp: new Date('2024-05-02T09:15:00'),
  },
  {
    id: 'bm3',
    authorId: 'casey-morgan',
    authorName: 'Casey Morgan',
    content: 'I\'ve obtained internal Boeing documents from Barnett\'s lawsuit. The quality control failures he documented are even worse than publicly known.',
    type: 'text',
    timestamp: new Date('2024-05-02T09:45:00'),
  },
  {
    id: 'bm4',
    authorId: 'kyle-anderson',
    authorName: 'Kyle Anderson',
    content: 'The 787 Dreamliner issues he documented: metal shavings in wiring, defective ladder assemblies, emergency oxygen systems installed incorrectly. All documented, all ignored.',
    type: 'text',
    timestamp: new Date('2024-05-02T10:23:00'),
  },
  {
    id: 'bm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Casey Morgan uploaded: Boeing_Internal_QC_Reports_2017-2023.zip',
    type: 'system',
    timestamp: new Date('2024-05-02T10:30:00'),
  },
  {
    id: 'bm6',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'Barnett\'s death was ruled suicide. But his friends and attorneys say he was in good spirits and committed to seeing the case through. Dean died of a "sudden fast-spreading infection." Both need independent investigation.',
    type: 'text',
    timestamp: new Date('2024-05-02T11:15:00'),
  },
  {
    id: 'bm7',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Connecting to the larger pattern: the 346 people killed in 737 MAX crashes. Boeing knew about MCAS issues, pushed the planes through certification anyway.',
    type: 'text',
    timestamp: new Date('2024-05-02T13:00:00'),
  },
  {
    id: 'bm8',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The DOJ deferred prosecution agreement from January 2021 is key. Boeing admitted criminally deceiving the FAA. $2.5B fine but no executives charged. That deal is now back in play.',
    type: 'text',
    timestamp: new Date('2024-05-02T14:20:00'),
    isPinned: true,
  },
  {
    id: 'bm9',
    authorId: 'kyle-anderson',
    authorName: 'Kyle Anderson',
    content: 'The January 5, 2024 door plug blowout on Alaska Airlines Flight 1282 proves nothing was fixed. Boeing\'s culture prioritizes stock price over safety.',
    type: 'text',
    timestamp: new Date('2024-05-02T15:45:00'),
  },
  {
    id: 'bm10',
    authorId: 'casey-morgan',
    authorName: 'Casey Morgan',
    content: 'CEO Dave Calhoun announced resignation but gets to stay through end of year. His stock compensation: $33M in 2023 alone. No accountability.',
    type: 'text',
    timestamp: new Date('2024-05-03T09:00:00'),
  },
  {
    id: 'bm11',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'We need to find other whistleblowers. Barnett was not alone - there were others who raised concerns and were silenced. We need their stories.',
    type: 'text',
    timestamp: new Date('2024-05-03T10:30:00'),
  },
  {
    id: 'bm12',
    authorId: 'alex-reyes',
    authorName: 'Alex Reyes',
    content: 'Working on it. I have a contact who worked at the Charleston plant. Says there are at least 10 more employees who saw what Barnett saw but were afraid to speak up.',
    type: 'text',
    timestamp: new Date('2024-05-03T11:15:00'),
  },
];

const boeingEvidence: Evidence[] = [
  {
    id: 'be1',
    title: 'Boeing Internal QC Reports (2017-2023)',
    description: 'Internal quality control reports documenting manufacturing defects ignored by management',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'Barnett Lawsuit Discovery',
    addedAt: new Date('2024-05-02'),
    addedBy: 'casey-morgan',
    addedByName: 'Casey Morgan',
    tags: ['Boeing', 'Quality Control', 'Whistleblower'],
    connections: ['be2', 'be3'],
    verifiedBy: ['kyle-anderson', 'sarah-chen'],
    position: { x: 100, y: 100 },
  },
  {
    id: 'be2',
    title: '737 MAX MCAS Documentation',
    description: 'Internal documents showing Boeing knew of MCAS risks before crashes',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Congressional Investigation / DOJ',
    addedAt: new Date('2024-05-02'),
    addedBy: 'kyle-anderson',
    addedByName: 'Kyle Anderson',
    tags: ['737 MAX', 'MCAS', 'FAA'],
    connections: ['be1', 'be4'],
    position: { x: 300, y: 150 },
  },
  {
    id: 'be3',
    title: 'Barnett Lawsuit Filing',
    description: 'Complete legal filing including whistleblower retaliation claims',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'South Carolina Court Records',
    addedAt: new Date('2024-03-15'),
    addedBy: 'marcus-rivera',
    addedByName: 'Marcus Rivera',
    tags: ['Barnett', 'Lawsuit', 'Retaliation'],
    connections: ['be1'],
    position: { x: 200, y: 300 },
  },
  {
    id: 'be4',
    title: 'DOJ Deferred Prosecution Agreement',
    description: 'January 2021 agreement admitting criminal deception of FAA',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Department of Justice',
    addedAt: new Date('2024-05-02'),
    addedBy: 'marcus-rivera',
    addedByName: 'Marcus Rivera',
    tags: ['DOJ', 'DPA', 'Criminal'],
    connections: ['be2'],
    position: { x: 400, y: 200 },
  },
];

// ==================== WORKSPACE 9: CLARENCE THOMAS GIFT REGISTRY ====================
const thomasMessages: WorkspaceMessage[] = [
  {
    id: 'ctm1',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'ProPublica just dropped another bomb. Thomas took over $4M in undisclosed gifts from Harlan Crow over two decades. This is unprecedented judicial corruption.',
    type: 'text',
    timestamp: new Date('2023-04-06T08:00:00'),
    isPinned: true,
  },
  {
    id: 'ctm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Breaking down the gifts: Luxury trips on superyacht and private jet, real estate transaction for Thomas\'s mother\'s house, tuition for Thomas\'s grandnephew. Pattern over 25 years.',
    type: 'text',
    timestamp: new Date('2023-04-06T08:45:00'),
  },
  {
    id: 'ctm3',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'The real estate transaction is particularly damning. Crow bought properties in Savannah from Thomas, including one where his mother lived. He then renovated them while she continued living there. Never disclosed.',
    type: 'text',
    timestamp: new Date('2023-04-06T09:30:00'),
  },
  {
    id: 'ctm4',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'Under federal ethics law, justices must disclose gifts. Thomas didn\'t disclose these trips. His excuse: "personal hospitality." That exemption does not apply to private jet travel.',
    type: 'text',
    timestamp: new Date('2023-04-06T10:15:00'),
  },
  {
    id: 'ctm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Sarah Chen uploaded: Thomas_Crow_Gift_Timeline_1991-2023.xlsx',
    type: 'system',
    timestamp: new Date('2023-04-06T10:20:00'),
  },
  {
    id: 'ctm6',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Crow\'s political activities matter. He funds dark money groups, collects Nazi memorabilia, has business before the court. This isn\'t just a friendship - it\'s influence.',
    type: 'text',
    timestamp: new Date('2023-04-06T11:00:00'),
  },
  {
    id: 'ctm7',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Following the money: Crow\'s company had an amicus brief in a case Thomas ruled on. Direct conflict of interest. Thomas did not recuse.',
    type: 'text',
    timestamp: new Date('2023-04-06T13:30:00'),
  },
  {
    id: 'ctm8',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'New development: NYT reports Thomas accepted trips from the Koch network. Attended donor events where judicial strategy was discussed. This is even worse.',
    type: 'text',
    timestamp: new Date('2023-06-22T09:00:00'),
    isPinned: true,
  },
  {
    id: 'ctm9',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'The Koch seminars included briefings on cases coming before the court. Thomas had advance knowledge of donor priorities. This is textbook corruption.',
    type: 'text',
    timestamp: new Date('2023-06-22T09:45:00'),
  },
  {
    id: 'ctm10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Let\'s not forget Ginni Thomas. She was paid $680,000 by conservative groups while her husband ruled on cases affecting those groups. Collective corruption.',
    type: 'text',
    timestamp: new Date('2023-06-22T11:15:00'),
  },
  {
    id: 'ctm11',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Senate Judiciary has subpoenaed Crow and Leonard Leo. This is the first step toward accountability. We need to document every connection.',
    type: 'text',
    timestamp: new Date('2023-09-01T10:00:00'),
  },
  {
    id: 'ctm12',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'I\'m mapping the network. Crow to Leonard Leo to Federalist Society to judicial appointments. It\'s a closed loop of money and influence.',
    type: 'text',
    timestamp: new Date('2023-09-01T14:30:00'),
  },
];

const thomasEvidence: Evidence[] = [
  {
    id: 'cte1',
    title: 'Thomas-Crow Gift Documentation',
    description: 'Comprehensive timeline of undisclosed gifts from Harlan Crow to Clarence Thomas',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'ProPublica Investigation',
    addedAt: new Date('2023-04-06'),
    addedBy: 'sarah-chen',
    addedByName: 'Sarah Chen',
    tags: ['Thomas', 'Crow', 'Gifts', 'Ethics'],
    connections: ['cte2', 'cte3'],
    verifiedBy: ['marcus-rivera', 'rachel-torres'],
    position: { x: 100, y: 100 },
  },
  {
    id: 'cte2',
    title: 'Real Estate Transaction Records',
    description: 'Property records showing Crow purchase of Thomas family properties',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Chatham County Property Records',
    addedAt: new Date('2023-04-10'),
    addedBy: 'rachel-torres',
    addedByName: 'Rachel Torres',
    tags: ['Real Estate', 'Savannah', 'Property'],
    connections: ['cte1'],
    position: { x: 300, y: 150 },
  },
  {
    id: 'cte3',
    title: 'Koch Network Event Documentation',
    description: 'Evidence of Thomas attendance at Koch donor seminars',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'New York Times Investigation',
    addedAt: new Date('2023-06-22'),
    addedBy: 'sarah-chen',
    addedByName: 'Sarah Chen',
    tags: ['Koch', 'Donors', 'Seminars'],
    connections: ['cte1', 'cte4'],
    position: { x: 200, y: 300 },
  },
  {
    id: 'cte4',
    title: 'Ginni Thomas Payment Records',
    description: 'Documentation of payments to Ginni Thomas from conservative groups',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Tax Records / 990 Filings',
    addedAt: new Date('2023-06-25'),
    addedBy: 'marcus-rivera',
    addedByName: 'Marcus Rivera',
    tags: ['Ginni Thomas', 'Payments', 'Conflicts'],
    connections: ['cte3'],
    position: { x: 400, y: 250 },
  },
];

// ==================== WORKSPACE 10: LEONARD LEO DARK MONEY NETWORK ====================
const leonardLeoMessages: WorkspaceMessage[] = [
  {
    id: 'llm1',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'The Leonard Leo network is the most sophisticated dark money operation in American history. I\'ve been mapping the flows for months. It\'s staggering.',
    type: 'text',
    timestamp: new Date('2022-08-15T09:00:00'),
    isPinned: true,
  },
  {
    id: 'llm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Start with the basics. Who is Leonard Leo and why does he matter?',
    type: 'text',
    timestamp: new Date('2022-08-15T09:15:00'),
  },
  {
    id: 'llm3',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Leo runs the Federalist Society. More importantly, he advises on judicial nominations. Every Trump SCOTUS pick came through him. He\'s personally responsible for the courts\' conservative swing.',
    type: 'text',
    timestamp: new Date('2022-08-15T09:35:00'),
  },
  {
    id: 'llm4',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'The money is the key. Leo controls a network of nonprofits that have funneled over $1.6 BILLION to conservative legal causes since 2014. All dark money - donors anonymous.',
    type: 'text',
    timestamp: new Date('2022-08-15T10:00:00'),
  },
  {
    id: 'llm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Rachel Torres uploaded: Leo_Network_Money_Flow_Analysis.pdf',
    type: 'system',
    timestamp: new Date('2022-08-15T10:05:00'),
  },
  {
    id: 'llm6',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Key entities: Federalist Society, Judicial Crisis Network, Concord Fund (formerly Judicial Education Project), Honest Elections Project. All connected, all funneling money.',
    type: 'text',
    timestamp: new Date('2022-08-15T10:30:00'),
  },
  {
    id: 'llm7',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Broke: NYT reports Leo received $1.6B from Barre Seid, electronics magnate. Single largest donation to political advocacy group in US history.',
    type: 'text',
    timestamp: new Date('2022-08-22T08:00:00'),
    isPinned: true,
  },
  {
    id: 'llm8',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'The structure is genius from a tax avoidance perspective. Seid donated stock to a nonprofit controlled by Leo, which then sold it. No capital gains tax on $1.6B.',
    type: 'text',
    timestamp: new Date('2022-08-22T08:45:00'),
  },
  {
    id: 'llm9',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Now for the corruption angle. Leo has ties to Thomas and Alito. He arranged trips. He\'s been to both their homes. These relationships raise serious ethics concerns.',
    type: 'text',
    timestamp: new Date('2022-08-22T10:00:00'),
  },
  {
    id: 'llm10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The Alito flag story is connected. The woman who reported seeing an upside-down flag at Alito\'s house? Her husband got into a dispute with Martha-Ann Alito. Leonard Leo was at that party.',
    type: 'text',
    timestamp: new Date('2024-05-20T11:30:00'),
  },
  {
    id: 'llm11',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'We need to map every connection. Leo to judges, Leo to donors, Leo to cases. This network has reshaped American law without any democratic accountability.',
    type: 'text',
    timestamp: new Date('2024-05-20T14:00:00'),
  },
  {
    id: 'llm12',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Senate Judiciary subpoenaed Leo. He\'s refusing to comply. Claims attorney-client privilege. This will be a major legal fight.',
    type: 'text',
    timestamp: new Date('2024-05-21T09:00:00'),
  },
];

// ==================== WORKSPACE 11: FOX-DOMINION DISINFORMATION ====================
const foxDominionMessages: WorkspaceMessage[] = [
  {
    id: 'fdm1',
    authorId: 'alex-reyes',
    authorName: 'Alex Reyes',
    content: 'The discovery materials from the Dominion lawsuit are extraordinary. Internal Fox communications prove they knew the election fraud claims were lies but aired them anyway.',
    type: 'text',
    timestamp: new Date('2023-02-16T09:00:00'),
    isPinned: true,
  },
  {
    id: 'fdm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Key Murdoch quote from his deposition: "It\'s been clear from conversations with Powell, Giuliani and the president that the election fraud claims are false." Then Fox kept airing them.',
    type: 'text',
    timestamp: new Date('2023-02-16T09:30:00'),
  },
  {
    id: 'fdm3',
    authorId: 'mira-novak',
    authorName: 'Mira Novak',
    content: 'Tucker Carlson texts are damning: "Sidney Powell is lying" "I\'ve come to hate [Trump] passionately" - while on air he was promoting Trump\'s claims.',
    type: 'text',
    timestamp: new Date('2023-02-16T10:15:00'),
  },
  {
    id: 'fdm4',
    authorId: 'system',
    authorName: 'System',
    content: 'Alex Reyes uploaded: Fox_Dominion_Discovery_Excerpts.pdf',
    type: 'system',
    timestamp: new Date('2023-02-16T10:20:00'),
  },
  {
    id: 'fdm5',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The legal standard for defamation against a public figure is "actual malice" - knowledge of falsity. These documents prove actual malice beyond any doubt.',
    type: 'text',
    timestamp: new Date('2023-02-16T11:00:00'),
  },
  {
    id: 'fdm6',
    authorId: 'alex-reyes',
    authorName: 'Alex Reyes',
    content: 'Laura Ingraham called Sidney Powell\'s claims "insane" in private texts. Sean Hannity said he didn\'t believe the fraud narrative. But they all kept lying to their audience.',
    type: 'text',
    timestamp: new Date('2023-02-16T13:45:00'),
  },
  {
    id: 'fdm7',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'This is the clearest documented case of deliberate mass disinformation from a major media outlet. They sacrificed democracy for ratings.',
    type: 'text',
    timestamp: new Date('2023-02-16T14:30:00'),
  },
  {
    id: 'fdm8',
    authorId: 'system',
    authorName: 'System',
    content: 'BREAKING: Fox News settles with Dominion for $787.5 million. No trial.',
    type: 'system',
    timestamp: new Date('2023-04-18T14:00:00'),
    isPinned: true,
  },
  {
    id: 'fdm9',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The settlement is massive - nearly $800M. But no admission of wrongdoing, no apology, no on-air correction. Dominion got paid but Fox viewers never learned the truth.',
    type: 'text',
    timestamp: new Date('2023-04-18T14:30:00'),
  },
  {
    id: 'fdm10',
    authorId: 'alex-reyes',
    authorName: 'Alex Reyes',
    content: 'Smartmatic lawsuit still pending. $2.7B damages claimed. More discovery coming. The story isn\'t over.',
    type: 'text',
    timestamp: new Date('2023-04-18T15:00:00'),
  },
  {
    id: 'fdm11',
    authorId: 'mira-novak',
    authorName: 'Mira Novak',
    content: 'The larger question: what does it mean when a propaganda network can pay its way out of accountability? They\'re still spreading lies today.',
    type: 'text',
    timestamp: new Date('2023-04-18T16:30:00'),
  },
];

// ==================== WORKSPACE 12: FLINT WATER CRISIS COVER-UP ====================
const flintMessages: WorkspaceMessage[] = [
  {
    id: 'fwm1',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'The EPA\'s Region 5 office knew about the lead contamination in February 2015. They sat on the information for months while children were being poisoned.',
    type: 'text',
    timestamp: new Date('2016-01-21T09:00:00'),
    isPinned: true,
  },
  {
    id: 'fwm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Let\'s build the timeline. April 2014: water supply switched to Flint River. Immediately residents complained about color, smell, taste.',
    type: 'text',
    timestamp: new Date('2016-01-21T09:30:00'),
  },
  {
    id: 'fwm3',
    authorId: 'tess-bennett',
    authorName: 'Tess Bennett',
    content: 'The switch was made without adding corrosion control treatment. This was a violation of federal law. MDEQ knew but didn\'t act.',
    type: 'text',
    timestamp: new Date('2016-01-21T10:00:00'),
  },
  {
    id: 'fwm4',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'Dr. Mona Hanna-Attisha\'s research is crucial. She documented elevated blood lead levels in children after the switch. The state tried to discredit her.',
    type: 'text',
    timestamp: new Date('2016-01-21T10:45:00'),
  },
  {
    id: 'fwm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Tess Bennett uploaded: MDEQ_Internal_Emails_2014-2015.zip',
    type: 'system',
    timestamp: new Date('2016-01-21T11:00:00'),
  },
  {
    id: 'fwm6',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The emails show state officials knew about Legionella outbreaks linked to the water. At least 12 people died. This was covered up.',
    type: 'text',
    timestamp: new Date('2016-01-21T13:30:00'),
  },
  {
    id: 'fwm7',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Governor Snyder\'s emergency manager made the decision. Flint residents had no say - their elected officials had been stripped of power. This is environmental racism.',
    type: 'text',
    timestamp: new Date('2016-01-21T14:15:00'),
    isPinned: true,
  },
  {
    id: 'fwm8',
    authorId: 'tess-bennett',
    authorName: 'Tess Bennett',
    content: 'I\'ve obtained the cost-benefit analysis. Switching to the Flint River saved about $5 million. The lead pipe replacement is now costing over $400 million.',
    type: 'text',
    timestamp: new Date('2016-01-21T15:00:00'),
  },
  {
    id: 'fwm9',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'The long-term health effects: cognitive impairment, behavioral problems, kidney damage. These children will suffer for life because officials wanted to save money.',
    type: 'text',
    timestamp: new Date('2016-01-21T16:30:00'),
  },
  {
    id: 'fwm10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Criminal charges coming. Michigan AG is investigating. We need to document every official who knew and failed to act.',
    type: 'text',
    timestamp: new Date('2016-02-05T09:00:00'),
  },
  {
    id: 'fwm11',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Update: Rick Snyder and 8 others charged with involuntary manslaughter. But accountability is slow - many charges later dropped.',
    type: 'text',
    timestamp: new Date('2021-01-14T10:00:00'),
  },
  {
    id: 'fwm12',
    authorId: 'tess-bennett',
    authorName: 'Tess Bennett',
    content: 'The systemic failure continues. Flint still doesn\'t have full lead pipe replacement. Eight years later. This is ongoing environmental injustice.',
    type: 'text',
    timestamp: new Date('2022-04-25T11:00:00'),
  },
];

const flintEvidence: Evidence[] = [
  {
    id: 'fwe1',
    title: 'MDEQ Internal Communications',
    description: 'Emails showing state knowledge of contamination and cover-up',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'FOIA Request / Investigation',
    addedAt: new Date('2016-01-21'),
    addedBy: 'tess-bennett',
    addedByName: 'Tess Bennett',
    tags: ['MDEQ', 'Emails', 'Cover-up'],
    connections: ['fwe2', 'fwe3'],
    verifiedBy: ['emily-watson', 'marcus-rivera'],
    position: { x: 100, y: 100 },
  },
  {
    id: 'fwe2',
    title: 'Blood Lead Level Data',
    description: 'Dr. Hanna-Attisha\'s research documenting elevated lead in children',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Hurley Medical Center / Peer Reviewed',
    addedAt: new Date('2016-01-25'),
    addedBy: 'emily-watson',
    addedByName: 'Dr. Emily Watson',
    tags: ['Lead', 'Children', 'Health'],
    connections: ['fwe1'],
    position: { x: 300, y: 150 },
  },
  {
    id: 'fwe3',
    title: 'Emergency Manager Decision Documents',
    description: 'Records showing cost-based decision to switch water sources',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'State Records / Supreme Court Filing',
    addedAt: new Date('2016-02-01'),
    addedBy: 'sarah-chen',
    addedByName: 'Sarah Chen',
    tags: ['Emergency Manager', 'Decision', 'Cost'],
    connections: ['fwe1'],
    position: { x: 200, y: 300 },
  },
  {
    id: 'fwe4',
    title: 'Legionella Outbreak Records',
    description: 'Hospital records linking Legionnaires\' disease deaths to water supply',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Hospital Records / CDC',
    addedAt: new Date('2016-02-10'),
    addedBy: 'emily-watson',
    addedByName: 'Dr. Emily Watson',
    tags: ['Legionella', 'Deaths', 'Outbreak'],
    connections: ['fwe1'],
    position: { x: 400, y: 250 },
  },
];

// Export workspaces 8-12
export const extendedWorkspaces2: Workspace[] = [
  // Workspace 8: Boeing Whistleblower Deaths
  {
    id: 'ws8',
    name: 'Boeing Whistleblower Investigation',
    description: 'Investigation into suspicious deaths of Boeing whistleblowers and systemic safety failures at Boeing. Documenting 737 MAX crashes, quality control failures, and corporate cover-up.',
    investigation: 'boeing-whistleblowers',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-05-10'),
    createdBy: 'kyle-anderson',
    members: getTeam('kyle-anderson', 'sarah-chen', 'casey-morgan', 'emily-watson', 'marcus-rivera', 'alex-reyes'),
    messages: boeingMessages,
    evidence: boeingEvidence,
    documents: [
      {
        id: 'bd1',
        name: 'Boeing_Internal_QC_Reports_2017-2023.zip',
        type: 'application/zip',
        size: 45678901,
        url: '#',
        uploadedBy: 'casey-morgan',
        uploadedByName: 'Casey Morgan',
        uploadedAt: new Date('2024-05-02'),
        folder: 'Internal Documents',
        category: 'Internal Documents',
        description: 'Internal quality control reports from Barnett lawsuit',
        downloads: 345,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'bt1', date: new Date('2018-10-29'), title: 'Lion Air 610 Crash', description: '189 killed due to MCAS malfunction', evidenceIds: ['be2'], addedBy: 'kyle-anderson', importance: 'major' },
      { id: 'bt2', date: new Date('2019-03-10'), title: 'Ethiopian Airlines 302', description: '157 killed in similar MCAS failure', evidenceIds: ['be2'], addedBy: 'kyle-anderson', importance: 'major' },
      { id: 'bt3', date: new Date('2024-01-05'), title: 'Alaska 1282 Blowout', description: 'Door plug blows out mid-flight', evidenceIds: [], addedBy: 'kyle-anderson', importance: 'major' },
      { id: 'bt4', date: new Date('2024-03-09'), title: 'Barnett Found Dead', description: 'Whistleblower dies during testimony', evidenceIds: ['be3'], addedBy: 'casey-morgan', importance: 'major' },
    ],
    tasks: [
      { id: 'btask1', title: 'Identify additional whistleblowers', description: 'Find and secure other Boeing employees willing to speak', assignedTo: ['alex-reyes'], status: 'in-progress', priority: 'critical', createdBy: 'sarah-chen', createdAt: new Date('2024-05-03') },
    ],
    tags: ['Boeing', '737 MAX', 'Whistleblower', 'Safety', 'Deaths'],
    isPublic: false,
    viewCount: 8765,
    lastActivity: new Date('2024-05-10'),
    milestones: [
      { id: 'bms1', title: 'QC Failure Documentation', description: 'Compiled comprehensive safety failure evidence', isCompleted: true, completedAt: new Date('2024-05-02') },
      { id: 'bms2', title: 'Whistleblower Network', description: 'Establish secure contacts with current employees', isCompleted: false },
    ],
  },
  // Workspace 9: Clarence Thomas Gift Registry
  {
    id: 'ws9',
    name: 'SCOTUS Ethics Investigation',
    description: 'Documenting undisclosed gifts to Supreme Court Justice Clarence Thomas from Harlan Crow and other billionaire donors. Examining pattern of corruption and influence on Court decisions.',
    investigation: 'scotus-corruption',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2023-04-06'),
    updatedAt: new Date('2024-05-25'),
    createdBy: 'marcus-rivera',
    members: getTeam('marcus-rivera', 'sarah-chen', 'rachel-torres', 'michael-brooks'),
    messages: thomasMessages,
    evidence: thomasEvidence,
    documents: [
      {
        id: 'ctd1',
        name: 'Thomas_Crow_Gift_Timeline_1991-2023.xlsx',
        type: 'application/vnd.ms-excel',
        size: 2345678,
        url: '#',
        uploadedBy: 'sarah-chen',
        uploadedByName: 'Sarah Chen',
        uploadedAt: new Date('2023-04-06'),
        folder: 'Financial Records',
        category: 'Financial Records',
        description: 'Complete timeline of documented gifts',
        downloads: 1234,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'ctt1', date: new Date('1991-10-15'), title: 'Thomas Confirmed', description: 'Clarence Thomas confirmed to Supreme Court', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
      { id: 'ctt2', date: new Date('2008-01-01'), title: 'Crow Real Estate Deal', description: 'Crow purchases Thomas family properties', evidenceIds: ['cte2'], addedBy: 'rachel-torres', importance: 'major' },
      { id: 'ctt3', date: new Date('2023-04-06'), title: 'ProPublica Investigation', description: 'Undisclosed gifts revealed publicly', evidenceIds: ['cte1'], addedBy: 'sarah-chen', importance: 'major' },
    ],
    tasks: [
      { id: 'cttask1', title: 'Map Crow network connections', description: 'Document all Crow-Leo-Thomas relationships', assignedTo: ['rachel-torres'], status: 'in-progress', priority: 'high', createdBy: 'marcus-rivera', createdAt: new Date('2023-04-10') },
    ],
    tags: ['Supreme Court', 'Thomas', 'Crow', 'Ethics', 'Corruption'],
    isPublic: false,
    viewCount: 15678,
    lastActivity: new Date('2024-05-25'),
    milestones: [
      { id: 'ctms1', title: 'Gift Registry Complete', description: 'Documented all known gifts 1991-2023', isCompleted: true, completedAt: new Date('2023-06-01') },
    ],
  },
  // Workspace 10: Leonard Leo Dark Money Network
  {
    id: 'ws10',
    name: 'Dark Money Judicial Network',
    description: 'Investigation into Leonard Leo\'s network of dark money organizations reshaping the federal judiciary. Tracing billions in anonymous donations funding conservative legal movement.',
    investigation: 'dark-money-courts',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2022-08-15'),
    updatedAt: new Date('2024-05-21'),
    createdBy: 'rachel-torres',
    members: getTeam('rachel-torres', 'sarah-chen', 'michael-brooks', 'marcus-rivera'),
    messages: leonardLeoMessages,
    evidence: [
      {
        id: 'lle1',
        title: 'Leo Network Money Flow Analysis',
        description: 'Mapping of funds between Leo-controlled nonprofits',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'IRS 990 Filings / Court Records',
        addedAt: new Date('2022-08-15'),
        addedBy: 'rachel-torres',
        addedByName: 'Rachel Torres',
        tags: ['Leo', 'Dark Money', 'Nonprofits'],
        connections: [],
        verifiedBy: ['sarah-chen'],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'lld1',
        name: 'Leo_Network_Money_Flow_Analysis.pdf',
        type: 'application/pdf',
        size: 8765432,
        url: '#',
        uploadedBy: 'rachel-torres',
        uploadedByName: 'Rachel Torres',
        uploadedAt: new Date('2022-08-15'),
        folder: 'Financial Analysis',
        category: 'Financial Analysis',
        description: 'Comprehensive dark money flow analysis',
        downloads: 567,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'llt1', date: new Date('2022-08-22'), title: '$1.6B Donation Revealed', description: 'Barre Seid donation to Leo network exposed', evidenceIds: ['lle1'], addedBy: 'sarah-chen', importance: 'major' },
    ],
    tasks: [],
    tags: ['Leonard Leo', 'Dark Money', 'Federalist Society', 'Judiciary'],
    isPublic: false,
    viewCount: 8901,
    lastActivity: new Date('2024-05-21'),
    milestones: [],
  },
  // Workspace 11: Fox-Dominion Disinformation
  {
    id: 'ws11',
    name: 'Fox News Disinformation Probe',
    description: 'Analysis of Fox News internal communications proving deliberate broadcast of election lies. Documenting the Dominion lawsuit and cultivation of mass disinformation.',
    investigation: 'fox-dominion',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2023-02-16'),
    updatedAt: new Date('2023-04-20'),
    createdBy: 'alex-reyes',
    members: getTeam('alex-reyes', 'sarah-chen', 'mira-novak', 'marcus-rivera'),
    messages: foxDominionMessages,
    evidence: [
      {
        id: 'fde1',
        title: 'Fox Internal Communications',
        description: 'Discovery materials proving hosts knew claims were false',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Dominion v. Fox Lawsuit Discovery',
        addedAt: new Date('2023-02-16'),
        addedBy: 'alex-reyes',
        addedByName: 'Alex Reyes',
        tags: ['Fox', 'Discovery', 'Defamation'],
        connections: [],
        verifiedBy: ['marcus-rivera'],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'fdd1',
        name: 'Fox_Dominion_Discovery_Excerpts.pdf',
        type: 'application/pdf',
        size: 12345678,
        url: '#',
        uploadedBy: 'alex-reyes',
        uploadedByName: 'Alex Reyes',
        uploadedAt: new Date('2023-02-16'),
        folder: 'Legal Documents',
        category: 'Legal Documents',
        description: 'Key excerpts from discovery materials',
        downloads: 2345,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'fdt1', date: new Date('2023-04-18'), title: 'Fox Settles', description: '$787.5M settlement, no admission', evidenceIds: ['fde1'], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [],
    tags: ['Fox News', 'Dominion', 'Defamation', 'Disinformation', 'Election'],
    isPublic: false,
    viewCount: 18765,
    lastActivity: new Date('2023-04-20'),
    milestones: [],
  },
  // Workspace 12: Flint Water Crisis
  {
    id: 'ws12',
    name: 'Flint Water Crisis Investigation',
    description: 'Documenting government failure and cover-up in Flint water contamination. Tracing decisions that led to mass lead poisoning and the officials who knew.',
    investigation: 'flint-water-crisis',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2016-01-21'),
    updatedAt: new Date('2022-04-25'),
    createdBy: 'emily-watson',
    members: getTeam('emily-watson', 'sarah-chen', 'tess-bennett', 'marcus-rivera'),
    messages: flintMessages,
    evidence: flintEvidence,
    documents: [
      {
        id: 'fwd1',
        name: 'MDEQ_Internal_Emails_2014-2015.zip',
        type: 'application/zip',
        size: 34567890,
        url: '#',
        uploadedBy: 'tess-bennett',
        uploadedByName: 'Tess Bennett',
        uploadedAt: new Date('2016-01-21'),
        folder: 'Government Records',
        category: 'Government Records',
        description: 'Internal state communications on water crisis',
        downloads: 876,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'fwt1', date: new Date('2014-04-25'), title: 'Water Switch', description: 'Flint switches to Flint River', evidenceIds: ['fwe3'], addedBy: 'sarah-chen', importance: 'major' },
      { id: 'fwt2', date: new Date('2015-09-24'), title: 'Lead Data Published', description: 'Dr. Hanna-Attisha releases findings', evidenceIds: ['fwe2'], addedBy: 'emily-watson', importance: 'major' },
      { id: 'fwt3', date: new Date('2021-01-14'), title: 'Snyder Charged', description: 'Former governor charged with manslaughter', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [],
    tags: ['Flint', 'Water', 'Lead', 'Environmental Racism', 'Cover-up'],
    isPublic: false,
    viewCount: 12345,
    lastActivity: new Date('2022-04-25'),
    milestones: [],
  },
];
