// Extended workspace data - Part 3 (Workspaces 13-18)
// NSA Surveillance, CIA Torture, Opioid Crisis, Private Prisons, Family Separation, Police Brutality

import { 
  Workspace, 
  WorkspaceMessage, 
  Evidence, 
} from '@/types/workspace';
import { getTeam } from './workspaceData';

// ==================== WORKSPACE 13: NSA MASS SURVEILLANCE ====================
const nsaMessages: WorkspaceMessage[] = [
  {
    id: 'nsam1',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'Ten years since Snowden and the surveillance state is bigger than ever. New documents show NSA expanded domestic collection after "reforms."',
    type: 'text',
    timestamp: new Date('2023-06-06T09:00:00'),
    isPinned: true,
  },
  {
    id: 'nsam2',
    authorId: 'jake-thompson',
    authorName: 'Jake Thompson',
    content: 'Section 702 is up for reauthorization. They\'re claiming they need to expand it. Meanwhile, FBI admitted to 200,000+ improper searches of Americans in the database.',
    type: 'text',
    timestamp: new Date('2023-06-06T09:30:00'),
  },
  {
    id: 'nsam3',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Let\'s document the full scope. PRISM, upstream collection, XKeyscore, Boundless Informant. What do we know about current capabilities?',
    type: 'text',
    timestamp: new Date('2023-06-06T10:15:00'),
  },
  {
    id: 'nsam4',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'Current capabilities far exceed what Snowden revealed. The Five Eyes network now processes exabytes of data daily. Every digital communication is captured somewhere.',
    type: 'text',
    timestamp: new Date('2023-06-06T10:45:00'),
  },
  {
    id: 'nsam5',
    authorId: 'system',
    authorName: 'System',
    content: 'David Kim uploaded: NSA_Collection_Programs_2013-2023.pdf',
    type: 'system',
    timestamp: new Date('2023-06-06T11:00:00'),
  },
  {
    id: 'nsam6',
    authorId: 'jake-thompson',
    authorName: 'Jake Thompson',
    content: 'The data broker loophole is key. Government can\'t collect your location data without a warrant, but they can BUY it from brokers. Complete 4th Amendment workaround.',
    type: 'text',
    timestamp: new Date('2023-06-06T13:30:00'),
    isPinned: true,
  },
  {
    id: 'nsam7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'FISA court is a rubber stamp. Out of 34,000 applications since 1979, they\'ve denied 12. That\'s 0.03%. No adversarial process, no accountability.',
    type: 'text',
    timestamp: new Date('2023-06-06T14:20:00'),
  },
  {
    id: 'nsam8',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'We should also document the targeting of journalists, activists, and political opponents. The infrastructure built for "terrorism" is routinely abused.',
    type: 'text',
    timestamp: new Date('2023-06-06T15:45:00'),
  },
  {
    id: 'nsam9',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'The Pegasus revelations are part of this story. NSO Group\'s spyware used to hack journalists and activists worldwide. US government both condemns and uses these tools.',
    type: 'text',
    timestamp: new Date('2023-06-06T16:30:00'),
  },
  {
    id: 'nsam10',
    authorId: 'jake-thompson',
    authorName: 'Jake Thompson',
    content: 'I have contacts at EFF who can help us understand current legal challenges. The surveillance-industrial complex is fighting every reform attempt.',
    type: 'text',
    timestamp: new Date('2023-06-07T09:00:00'),
  },
];

// ==================== WORKSPACE 14: CIA TORTURE PROGRAM ====================
const ciaTortureMessages: WorkspaceMessage[] = [
  {
    id: 'ctm1',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The Senate Torture Report remains the most comprehensive documentation of US war crimes in the 21st century. 6,700 pages. Only 525 released. We need the full report.',
    type: 'text',
    timestamp: new Date('2014-12-09T10:00:00'),
    isPinned: true,
  },
  {
    id: 'ctm2',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'The summary alone is damning. Rectal feeding. Waterboarding 183 times. Detainees died in custody. And the CIA lied to Congress about all of it.',
    type: 'text',
    timestamp: new Date('2014-12-09T10:30:00'),
  },
  {
    id: 'ctm3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Key finding: The torture program produced no actionable intelligence. They waterboarded KSM 183 times. He gave them NOTHING useful. The program was pure sadism.',
    type: 'text',
    timestamp: new Date('2014-12-09T11:15:00'),
  },
  {
    id: 'ctm4',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The contractors - James Mitchell and Bruce Jessen - made $81 million for designing the program. Psychologists who reverse-engineered SERE training to torture people.',
    type: 'text',
    timestamp: new Date('2014-12-09T13:00:00'),
  },
  {
    id: 'ctm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Layla Hassan uploaded: Senate_Torture_Report_Executive_Summary.pdf',
    type: 'system',
    timestamp: new Date('2014-12-09T13:15:00'),
  },
  {
    id: 'ctm6',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The black sites: Poland, Romania, Lithuania, Thailand, Afghanistan. Countries that hosted torture chambers. Some have faced ECHR rulings, none have provided full accountability.',
    type: 'text',
    timestamp: new Date('2014-12-09T14:45:00'),
  },
  {
    id: 'ctm7',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'And no one was prosecuted. Not Gina Haspel who ran a black site. She became CIA Director. Jose Rodriguez destroyed the torture tapes. He got promoted.',
    type: 'text',
    timestamp: new Date('2014-12-09T15:30:00'),
    isPinned: true,
  },
  {
    id: 'ctm8',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The Guantanamo trials are a related scandal. They can\'t use evidence from torture. So they built a system designed to convict without real evidence. Military commissions are a sham.',
    type: 'text',
    timestamp: new Date('2014-12-09T16:30:00'),
  },
  {
    id: 'ctm9',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Khalid Sheikh Mohammed is still at Gitmo. 22 years without trial. The torture makes prosecution almost impossible. We created this mess.',
    type: 'text',
    timestamp: new Date('2023-09-11T09:00:00'),
  },
  {
    id: 'ctm10',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The ICC should investigate. But US threatens sanctions against ICC judges who investigate Americans. We are officially above international law.',
    type: 'text',
    timestamp: new Date('2023-09-11T10:30:00'),
  },
];

// ==================== WORKSPACE 15: OPIOID MANUFACTURER LIABILITY ====================
const opioidMessages: WorkspaceMessage[] = [
  {
    id: 'om1',
    authorId: 'yuki-tanaka',
    authorName: 'Dr. Yuki Tanaka',
    content: 'Purdue Pharma\'s internal documents are devastating. They KNEW OxyContin was addictive. They trained sales reps to lie about addiction rates. 500,000 dead.',
    type: 'text',
    timestamp: new Date('2019-05-20T09:00:00'),
    isPinned: true,
  },
  {
    id: 'om2',
    authorId: 'casey-morgan',
    authorName: 'Casey Morgan',
    content: 'The Sackler family extracted $10 billion from Purdue before the lawsuits. They knew this day was coming and planned for it. Now they want immunity.',
    type: 'text',
    timestamp: new Date('2019-05-20T09:45:00'),
  },
  {
    id: 'om3',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'The marketing strategy was predatory. Target doctors. Claim addiction risk was "less than 1%." The actual rate was 25-35%. They lied and people died.',
    type: 'text',
    timestamp: new Date('2019-05-20T10:30:00'),
  },
  {
    id: 'om4',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'It wasn\'t just Purdue. Johnson & Johnson grew poppies in Tasmania. McKesson and Cardinal Health distributed billions of pills to pill mills. It\'s a criminal enterprise.',
    type: 'text',
    timestamp: new Date('2019-05-20T11:15:00'),
  },
  {
    id: 'om5',
    authorId: 'system',
    authorName: 'System',
    content: 'Dr. Yuki Tanaka uploaded: Purdue_Internal_Marketing_Documents.pdf',
    type: 'system',
    timestamp: new Date('2019-05-20T11:30:00'),
  },
  {
    id: 'om6',
    authorId: 'casey-morgan',
    authorName: 'Casey Morgan',
    content: 'Congress was complicit. The "Ensuring Patient Access Act" weakened DEA enforcement - passed unanimously. Tom Marino and Marsha Blackburn were pharma puppets.',
    type: 'text',
    timestamp: new Date('2019-05-20T13:00:00'),
  },
  {
    id: 'om7',
    authorId: 'yuki-tanaka',
    authorName: 'Dr. Yuki Tanaka',
    content: 'West Virginia got more opioids per capita than anywhere. Small towns drowning in pills. And the distributors kept shipping. They knew exactly what was happening.',
    type: 'text',
    timestamp: new Date('2019-05-20T14:30:00'),
  },
  {
    id: 'om8',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The bankruptcy settlement is a travesty. Sacklers pay $6B, get immunity, keep their remaining billions. No criminal charges. No admission of wrongdoing.',
    type: 'text',
    timestamp: new Date('2022-03-10T10:00:00'),
    isPinned: true,
  },
  {
    id: 'om9',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'The individual stories are heartbreaking. Parents who lost children. Communities destroyed. And the Sacklers are still among the richest families in America.',
    type: 'text',
    timestamp: new Date('2022-03-10T11:30:00'),
  },
  {
    id: 'om10',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'We need to document every executive who made these decisions. The pills didn\'t distribute themselves. People made choices that killed half a million Americans.',
    type: 'text',
    timestamp: new Date('2022-03-10T14:00:00'),
  },
];

// ==================== WORKSPACE 16: PRIVATE PRISON PROFITEERING ====================
const privatePrisonMessages: WorkspaceMessage[] = [
  {
    id: 'ppm1',
    authorId: 'robert-hayes',
    authorName: 'Dr. Robert Hayes',
    content: 'CoreCivic and GEO Group spent $25 million lobbying for policies that increase incarceration. They profit directly from human suffering. This is a moral obscenity.',
    type: 'text',
    timestamp: new Date('2017-09-15T09:00:00'),
    isPinned: true,
  },
  {
    id: 'ppm2',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'The immigrant detention system is their growth industry. ICE detention grew 442% since 2002. Private prisons hold 73% of detained immigrants.',
    type: 'text',
    timestamp: new Date('2017-09-15T09:45:00'),
  },
  {
    id: 'ppm3',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Let\'s document the "kids for cash" scandal pattern. Private facilities paying judges for referrals. Happens in juvenile detention, immigration, everywhere.',
    type: 'text',
    timestamp: new Date('2017-09-15T10:30:00'),
  },
  {
    id: 'ppm4',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The contracts include occupancy guarantees. States must keep prisons at 80-90% capacity or pay the company anyway. Built-in incentive to imprison people.',
    type: 'text',
    timestamp: new Date('2017-09-15T11:15:00'),
  },
  {
    id: 'ppm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Dr. Robert Hayes uploaded: Private_Prison_Lobbying_Analysis_2010-2017.pdf',
    type: 'system',
    timestamp: new Date('2017-09-15T11:30:00'),
  },
  {
    id: 'ppm6',
    authorId: 'robert-hayes',
    authorName: 'Dr. Robert Hayes',
    content: 'Prison labor is modern slavery. Inmates paid $0.23-1.15/hour making products for major corporations. Forced labor for private profit.',
    type: 'text',
    timestamp: new Date('2017-09-15T13:00:00'),
  },
  {
    id: 'ppm7',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'The conditions in these facilities are abhorrent. Understaffing, violence, lack of medical care. People die preventable deaths while shareholders profit.',
    type: 'text',
    timestamp: new Date('2017-09-15T14:30:00'),
    isPinned: true,
  },
  {
    id: 'ppm8',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Biden promised to end federal private prison contracts. But ICE detention is still largely private. The loophole swallowed the policy.',
    type: 'text',
    timestamp: new Date('2021-02-01T10:00:00'),
  },
  {
    id: 'ppm9',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'GEO Group and CoreCivic are pivoting to "community reentry" facilities. Same company, different name. The profit motive remains.',
    type: 'text',
    timestamp: new Date('2021-02-01T11:30:00'),
  },
  {
    id: 'ppm10',
    authorId: 'robert-hayes',
    authorName: 'Dr. Robert Hayes',
    content: 'We need to track every death in custody, every complaint, every lawsuit. These companies hide behind NDAs and sealed settlements.',
    type: 'text',
    timestamp: new Date('2021-02-01T14:00:00'),
  },
];

// ==================== WORKSPACE 17: FAMILY SEPARATION DOCUMENTATION ====================
const familySeparationMessages: WorkspaceMessage[] = [
  {
    id: 'fsm1',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'The scope is worse than acknowledgedm Over 5,500 children separated. Many still not reunited. This is a deliberate cruelty designed to deter asylum seekers.',
    type: 'text',
    timestamp: new Date('2018-06-20T08:00:00'),
    isPinned: true,
  },
  {
    id: 'fsm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Jeff Sessions announced "zero tolerance" in April 2018. But DHS was quietly separating families since 2017. This was planned, not reactive.',
    type: 'text',
    timestamp: new Date('2018-06-20T08:45:00'),
  },
  {
    id: 'fsm3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The legal framework: Prosecute parents for misdemeanor border crossing, declare them criminals, take their children. Weaponizing immigration law against families.',
    type: 'text',
    timestamp: new Date('2018-06-20T09:30:00'),
  },
  {
    id: 'fsm4',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'CBP didn\'t track which children belonged to which parents. No system for reunification. They separated a breastfeeding infant from her mother.',
    type: 'text',
    timestamp: new Date('2018-06-20T10:15:00'),
  },
  {
    id: 'fsm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Nina Patel uploaded: Family_Separation_Timeline_2017-2018.pdf',
    type: 'system',
    timestamp: new Date('2018-06-20T10:30:00'),
  },
  {
    id: 'fsm6',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'The psychological damage is incalculable. Children as young as 4 months. Long-term trauma, attachment disorders. This meets the UN definition of torture.',
    type: 'text',
    timestamp: new Date('2018-06-20T11:45:00'),
    isPinned: true,
  },
  {
    id: 'fsm7',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The ProPublica audio of children crying in detention - "Mami, mami" - that audio should be played in court. These are human rights crimes.',
    type: 'text',
    timestamp: new Date('2018-06-20T13:30:00'),
  },
  {
    id: 'fsm8',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Stephen Miller was the architect. His emails show explicit intent to use cruelty as deterrence. "My mantra is when it comes to children..."',
    type: 'text',
    timestamp: new Date('2018-06-20T14:30:00'),
  },
  {
    id: 'fsm9',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'Update 2021: The Biden task force has reunited about 600 families. 1,000+ children still separated. Many parents were deported without their kids.',
    type: 'text',
    timestamp: new Date('2021-06-15T10:00:00'),
  },
  {
    id: 'fsm10',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'No criminal charges for the officials who designed and implemented this. Sessions, Nielsen, Miller - all walking free. Zero accountability.',
    type: 'text',
    timestamp: new Date('2021-06-15T11:30:00'),
  },
];

// ==================== WORKSPACE 18: POLICE BRUTALITY PATTERNS ====================
const policeBrutalityMessages: WorkspaceMessage[] = [
  {
    id: 'pbm1',
    authorId: 'robert-hayes',
    authorName: 'Dr. Robert Hayes',
    content: 'George Floyd\'s murder was not an isolated incident. The database shows 1,100+ people killed by police annually. Black Americans killed at 2.5x the rate of white Americans.',
    type: 'text',
    timestamp: new Date('2020-05-27T08:00:00'),
    isPinned: true,
  },
  {
    id: 'pbm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Let\'s build the most comprehensive database possible. Mapping Police Violence has some data. We need to verify and expand it.',
    type: 'text',
    timestamp: new Date('2020-05-27T08:30:00'),
  },
  {
    id: 'pbm3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The legal protection is the story. Qualified immunity shields officers from civil suits. Prosecutors won\'t charge. Union contracts hide misconduct records.',
    type: 'text',
    timestamp: new Date('2020-05-27T09:15:00'),
  },
  {
    id: 'pbm4',
    authorId: 'robert-hayes',
    authorName: 'Dr. Robert Hayes',
    content: 'The pattern: Officer has history of complaints. Gets promoted anyway. Kills someone. Department settles with taxpayer money. Officer moves to new department.',
    type: 'text',
    timestamp: new Date('2020-05-27T10:00:00'),
  },
  {
    id: 'pbm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Dr. Robert Hayes uploaded: Police_Killings_Database_2013-2020.xlsx',
    type: 'system',
    timestamp: new Date('2020-05-27T10:15:00'),
  },
  {
    id: 'pbm6',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Derek Chauvin had 18 prior complaints before he murdered Floyd. Only 2 resulted in discipline - both written reprimands. The system protected him.',
    type: 'text',
    timestamp: new Date('2020-05-27T11:45:00'),
  },
  {
    id: 'pbm7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The DOJ consent decrees show patterns: Baltimore, Ferguson, Minneapolis. Same problems everywhere. Systemic racism isn\'t a controversial claim - it\'s documented.',
    type: 'text',
    timestamp: new Date('2020-05-27T13:30:00'),
    isPinned: true,
  },
  {
    id: 'pbm8',
    authorId: 'robert-hayes',
    authorName: 'Dr. Robert Hayes',
    content: 'We need to track the settlements. Chicago paid $700M+ in police misconduct settlements over 10 years. Taxpayers fund brutality.',
    type: 'text',
    timestamp: new Date('2020-05-27T14:30:00'),
  },
  {
    id: 'pbm9',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The body camera footage is critical evidence. But departments control release. Chicago sat on Laquan McDonald video for over a year.',
    type: 'text',
    timestamp: new Date('2020-05-27T15:30:00'),
  },
  {
    id: 'pbm10',
    authorId: 'aiden-obrien',
    authorName: 'Aiden O\'Brien',
    content: 'Social media is changing documentation. Cell phone video, bystanders filming, bodycam leaks. The public can see what was always hidden.',
    type: 'text',
    timestamp: new Date('2020-05-27T16:30:00'),
  },
  {
    id: 'pbm11',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The Chauvin conviction was exceptional, not typical. Most officers are never charged. When charged, they\'re rarely convicted. Justice is the exception.',
    type: 'text',
    timestamp: new Date('2021-04-21T10:00:00'),
  },
];

// Export workspaces 13-18
export const extendedWorkspaces3: Workspace[] = [
  // Workspace 13: NSA Mass Surveillance
  {
    id: 'ws13',
    name: 'NSA Domestic Surveillance Archive',
    description: 'Documentation of NSA mass surveillance programs targeting American citizens. Tracking capabilities from Snowden revelations through current Section 702 abuses.',
    investigation: 'nsa-surveillance',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2013-06-06'),
    updatedAt: new Date('2023-12-15'),
    createdBy: 'david-kim',
    members: getTeam('david-kim', 'jake-thompson', 'sarah-chen', 'marcus-rivera'),
    messages: nsaMessages,
    evidence: [
      {
        id: 'nse1',
        title: 'NSA Collection Programs Overview',
        description: 'Comprehensive documentation of surveillance programs 2013-2023',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Snowden Documents / FOIA',
        addedAt: new Date('2023-06-06'),
        addedBy: 'david-kim',
        addedByName: 'David Kim',
        tags: ['NSA', 'PRISM', 'Surveillance'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'nsd1',
        name: 'NSA_Collection_Programs_2013-2023.pdf',
        type: 'application/pdf',
        size: 9876543,
        url: '#',
        uploadedBy: 'david-kim',
        uploadedByName: 'David Kim',
        uploadedAt: new Date('2023-06-06'),
        folder: 'Intelligence',
        category: 'Intelligence',
        description: 'Overview of NSA capabilities and programs',
        downloads: 567,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'nst1', date: new Date('2013-06-06'), title: 'Snowden Revelations', description: 'NSA surveillance programs exposed', evidenceIds: ['nse1'], addedBy: 'david-kim', importance: 'major' },
    ],
    tasks: [],
    tags: ['NSA', 'Surveillance', 'Privacy', 'FISA', 'Section 702'],
    isPublic: false,
    viewCount: 7654,
    lastActivity: new Date('2023-12-15'),
    milestones: [],
  },
  // Workspace 14: CIA Torture Program
  {
    id: 'ws14',
    name: 'CIA Enhanced Interrogation Documentation',
    description: 'Archive of CIA torture program documentation including black sites, contractor involvement, and the Senate Torture Report analysis.',
    investigation: 'cia-torture-program',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2014-12-09'),
    updatedAt: new Date('2023-09-15'),
    createdBy: 'layla-hassan',
    members: getTeam('layla-hassan', 'nina-patel', 'marcus-rivera', 'sarah-chen'),
    messages: ciaTortureMessages,
    evidence: [
      {
        id: 'cte1',
        title: 'Senate Torture Report Summary',
        description: 'Executive Summary of Senate Select Committee on Intelligence study',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Senate Select Committee on Intelligence',
        addedAt: new Date('2014-12-09'),
        addedBy: 'layla-hassan',
        addedByName: 'Layla Hassan',
        tags: ['Torture', 'Senate Report', 'CIA'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'ctd1',
        name: 'Senate_Torture_Report_Executive_Summary.pdf',
        type: 'application/pdf',
        size: 34567890,
        url: '#',
        uploadedBy: 'layla-hassan',
        uploadedByName: 'Layla Hassan',
        uploadedAt: new Date('2014-12-09'),
        folder: 'Government Reports',
        category: 'Government Reports',
        description: 'Official declassified executive summary',
        downloads: 2345,
        isPublic: true,
      },
    ],
    timeline: [
      { id: 'ctt1', date: new Date('2002-08-01'), title: 'Torture Program Authorized', description: 'OLC memos authorize "enhanced interrogation"', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
      { id: 'ctt2', date: new Date('2014-12-09'), title: 'Report Released', description: 'Senate publishes torture report summary', evidenceIds: ['cte1'], addedBy: 'layla-hassan', importance: 'major' },
    ],
    tasks: [],
    tags: ['CIA', 'Torture', 'Black Sites', 'War Crimes', 'Guantanamo'],
    isPublic: false,
    viewCount: 9876,
    lastActivity: new Date('2023-09-15'),
    milestones: [],
  },
  // Workspace 15: Opioid Crisis
  {
    id: 'ws15',
    name: 'Opioid Epidemic Corporate Liability',
    description: 'Investigation into pharmaceutical companies\' role in the opioid crisis. Documenting Purdue Pharma\'s deceptive marketing and the Sackler family\'s extraction of billions.',
    investigation: 'opioid-crisis',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2019-05-20'),
    updatedAt: new Date('2022-03-15'),
    createdBy: 'yuki-tanaka',
    members: getTeam('yuki-tanaka', 'casey-morgan', 'emily-watson', 'sarah-chen', 'marcus-rivera'),
    messages: opioidMessages,
    evidence: [
      {
        id: 'oe1',
        title: 'Purdue Marketing Documents',
        description: 'Internal sales training materials showing deceptive claims',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'State AG Litigation Discovery',
        addedAt: new Date('2019-05-20'),
        addedBy: 'yuki-tanaka',
        addedByName: 'Dr. Yuki Tanaka',
        tags: ['Purdue', 'OxyContin', 'Marketing'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'od1',
        name: 'Purdue_Internal_Marketing_Documents.pdf',
        type: 'application/pdf',
        size: 23456789,
        url: '#',
        uploadedBy: 'yuki-tanaka',
        uploadedByName: 'Dr. Yuki Tanaka',
        uploadedAt: new Date('2019-05-20'),
        folder: 'Corporate Records',
        category: 'Corporate Records',
        description: 'Internal Purdue Pharma marketing materials',
        downloads: 1234,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'ot1', date: new Date('1996-12-01'), title: 'OxyContin Launch', description: 'Purdue launches OxyContin with aggressive marketing', evidenceIds: ['oe1'], addedBy: 'yuki-tanaka', importance: 'major' },
      { id: 'ot2', date: new Date('2022-03-03'), title: 'Bankruptcy Settlement', description: 'Sacklers get immunity in exchange for $6B', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [],
    tags: ['Opioid', 'Purdue', 'Sackler', 'OxyContin', 'Pharmaceutical'],
    isPublic: false,
    viewCount: 11234,
    lastActivity: new Date('2022-03-15'),
    milestones: [],
  },
  // Workspace 16: Private Prisons
  {
    id: 'ws16',
    name: 'Private Prison Industry Analysis',
    description: 'Exposing the private prison industry\'s lobbying, profit motives, and human rights abuses. Documenting CoreCivic, GEO Group, and the carceral state.',
    investigation: 'private-prisons',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2017-09-15'),
    updatedAt: new Date('2021-02-10'),
    createdBy: 'robert-hayes',
    members: getTeam('robert-hayes', 'nina-patel', 'sarah-chen', 'marcus-rivera'),
    messages: privatePrisonMessages,
    evidence: [
      {
        id: 'ppe1',
        title: 'Private Prison Lobbying Analysis',
        description: 'Documentation of lobbying spending and policy influence',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'OpenSecrets / Lobbying Disclosures',
        addedAt: new Date('2017-09-15'),
        addedBy: 'robert-hayes',
        addedByName: 'Dr. Robert Hayes',
        tags: ['Lobbying', 'CoreCivic', 'GEO Group'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'ppd1',
        name: 'Private_Prison_Lobbying_Analysis_2010-2017.pdf',
        type: 'application/pdf',
        size: 12345678,
        url: '#',
        uploadedBy: 'robert-hayes',
        uploadedByName: 'Dr. Robert Hayes',
        uploadedAt: new Date('2017-09-15'),
        folder: 'Research',
        category: 'Research',
        description: 'Comprehensive lobbying analysis',
        downloads: 456,
        isPublic: false,
      },
    ],
    timeline: [],
    tasks: [],
    tags: ['Private Prison', 'CoreCivic', 'GEO Group', 'Mass Incarceration'],
    isPublic: false,
    viewCount: 6543,
    lastActivity: new Date('2021-02-10'),
    milestones: [],
  },
  // Workspace 17: Family Separation
  {
    id: 'ws17',
    name: 'Family Separation Documentation Project',
    description: 'Documenting the Trump administration\'s family separation policy. Tracking separated children, reunification efforts, and the officials responsible.',
    investigation: 'family-separation',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2018-06-20'),
    updatedAt: new Date('2021-06-20'),
    createdBy: 'nina-patel',
    members: getTeam('nina-patel', 'sarah-chen', 'marcus-rivera', 'emily-watson'),
    messages: familySeparationMessages,
    evidence: [
      {
        id: 'fse1',
        title: 'Separation Policy Timeline',
        description: 'Chronological documentation of policy implementation',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Court Records / OIG Reports',
        addedAt: new Date('2018-06-20'),
        addedBy: 'nina-patel',
        addedByName: 'Nina Patel',
        tags: ['Family Separation', 'Immigration', 'DHS'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'fsd1',
        name: 'Family_Separation_Timeline_2017-2018.pdf',
        type: 'application/pdf',
        size: 8765432,
        url: '#',
        uploadedBy: 'nina-patel',
        uploadedByName: 'Nina Patel',
        uploadedAt: new Date('2018-06-20'),
        folder: 'Immigration',
        category: 'Immigration',
        description: 'Complete separation policy timeline',
        downloads: 987,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'fst1', date: new Date('2018-04-06'), title: 'Zero Tolerance Announced', description: 'Sessions announces policy', evidenceIds: ['fse1'], addedBy: 'sarah-chen', importance: 'major' },
      { id: 'fst2', date: new Date('2018-06-20'), title: 'Executive Order', description: 'Trump signs order under pressure', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [],
    tags: ['Family Separation', 'Immigration', 'Children', 'Human Rights'],
    isPublic: false,
    viewCount: 8901,
    lastActivity: new Date('2021-06-20'),
    milestones: [],
  },
  // Workspace 18: Police Brutality
  {
    id: 'ws18',
    name: 'Police Violence Pattern Database',
    description: 'Comprehensive database of police killings and brutality in America. Tracking systemic racism, lack of accountability, and reform efforts post-George Floyd.',
    investigation: 'police-brutality',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2020-05-27'),
    updatedAt: new Date('2024-01-15'),
    createdBy: 'robert-hayes',
    members: getTeam('robert-hayes', 'sarah-chen', 'marcus-rivera', 'aiden-obrien'),
    messages: policeBrutalityMessages,
    evidence: [
      {
        id: 'pbe1',
        title: 'Police Killings Database',
        description: 'Comprehensive database tracking police-involved deaths',
        type: 'link',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Mapping Police Violence / Fatal Encounters',
        addedAt: new Date('2020-05-27'),
        addedBy: 'robert-hayes',
        addedByName: 'Dr. Robert Hayes',
        tags: ['Police', 'Killings', 'Database'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'pbd1',
        name: 'Police_Killings_Database_2013-2020.xlsx',
        type: 'application/vnd.ms-excel',
        size: 45678901,
        url: '#',
        uploadedBy: 'robert-hayes',
        uploadedByName: 'Dr. Robert Hayes',
        uploadedAt: new Date('2020-05-27'),
        folder: 'Database',
        category: 'Database',
        description: 'Police killings data with demographics',
        downloads: 2345,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'pbt1', date: new Date('2020-05-25'), title: 'George Floyd Murdered', description: 'Minneapolis police kill Floyd', evidenceIds: [], addedBy: 'robert-hayes', importance: 'major' },
      { id: 'pbt2', date: new Date('2021-04-20'), title: 'Chauvin Convicted', description: 'Rare conviction of officer', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [],
    tags: ['Police', 'Brutality', 'Racism', 'Accountability', 'Floyd'],
    isPublic: false,
    viewCount: 19876,
    lastActivity: new Date('2024-01-15'),
    milestones: [],
  },
];
