// Extended workspace data - Part 4 (Workspaces 19-25+)
// Financial Crisis, Climate Denial, Voter Suppression, Afghanistan Papers, FTX, Mar-a-Lago, Georgia RICO

import { 
  Workspace, 
  WorkspaceMessage, 
  Evidence, 
} from '@/types/workspace';
import { getTeam } from './workspaceData';

// ==================== WORKSPACE 19: 2008 FINANCIAL CRISIS ====================
const financialCrisisMessages: WorkspaceMessage[] = [
  {
    id: 'fcm1',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'We\'re building the definitive archive of the 2008 crisis. The fraud was systemic. And no top executives went to prison. Not one.',
    type: 'text',
    timestamp: new Date('2012-08-15T09:00:00'),
    isPinned: true,
  },
  {
    id: 'fcm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The pattern: Banks issued mortgages they knew were bad, packaged them into securities, got rating agencies to bless them AAA, sold them to pension funds. When it collapsed, taxpayers bailed them out.',
    type: 'text',
    timestamp: new Date('2012-08-15T09:30:00'),
  },
  {
    id: 'fcm3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The FCIC report identified fraud at every level. Countrywide\'s "Friends of Angelo" loans to politicians. Goldman betting against their own clients. It was organized crime in suits.',
    type: 'text',
    timestamp: new Date('2012-08-15T10:15:00'),
  },
  {
    id: 'fcm4',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'The internal emails are damning. Goldman execs calling their products "shitty deals" while selling them. This is textbook fraud.',
    type: 'text',
    timestamp: new Date('2012-08-15T11:00:00'),
  },
  {
    id: 'fcm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Rachel Torres uploaded: Goldman_Sachs_Internal_Emails_2006-2008.pdf',
    type: 'system',
    timestamp: new Date('2012-08-15T11:15:00'),
  },
  {
    id: 'fcm6',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Eric Holder\'s "too big to jail" policy was the ultimate betrayal. DOJ decided prosecuting banks would hurt the economy. So they paid fines - cost of doing business.',
    type: 'text',
    timestamp: new Date('2012-08-15T13:30:00'),
    isPinned: true,
  },
  {
    id: 'fcm7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The human cost: 10 million foreclosures. 8.7 million jobs lost. $19 trillion in household wealth destroyed. And the bankers got bonuses.',
    type: 'text',
    timestamp: new Date('2012-08-15T14:30:00'),
  },
  {
    id: 'fcm8',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Kareem Serageldin was the only Wall Street executive jailed. ONE person. For a crisis that was industry-wide and destroyed millions of lives.',
    type: 'text',
    timestamp: new Date('2012-08-15T15:45:00'),
  },
  {
    id: 'fcm9',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The settlements totaled over $100 billion. Sounds like a lot until you realize the banks\' profits from the fraud were much higher. Crime paid handsomely.',
    type: 'text',
    timestamp: new Date('2012-08-16T09:00:00'),
  },
  {
    id: 'fcm10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'And now we\'re seeing the same patterns emerge again. Deregulation under Trump rolled back Dodd-Frank. They\'re already pushing the limits again.',
    type: 'text',
    timestamp: new Date('2019-05-10T10:00:00'),
  },
];

// ==================== WORKSPACE 20: CLIMATE DENIAL FUNDING ====================
const climateDenialMessages: WorkspaceMessage[] = [
  {
    id: 'cdm1',
    authorId: 'tess-bennett',
    authorName: 'Tess Bennett',
    content: 'ExxonMobil knew about climate change in 1977. Their own scientists warned them. Instead of acting, they funded denial for 40 years. This may be the greatest corporate crime in history.',
    type: 'text',
    timestamp: new Date('2015-10-28T09:00:00'),
    isPinned: true,
  },
  {
    id: 'cdm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The InsideClimate News investigation is comprehensive. Internal documents show Exxon\'s scientists accurately predicted global warming. Company buried the findings.',
    type: 'text',
    timestamp: new Date('2015-10-28T09:45:00'),
  },
  {
    id: 'cdm3',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'It\'s not just Exxon. The entire fossil fuel industry coordinated denial through the Global Climate Coalition. They used the tobacco playbook: manufacture doubt.',
    type: 'text',
    timestamp: new Date('2015-10-28T10:30:00'),
  },
  {
    id: 'cdm4',
    authorId: 'tess-bennett',
    authorName: 'Tess Bennett',
    content: 'The think tank network: Heartland Institute, Heritage Foundation, Cato Institute. All funded by fossil fuel money. All pushed climate denial.',
    type: 'text',
    timestamp: new Date('2015-10-28T11:15:00'),
  },
  {
    id: 'cdm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Tess Bennett uploaded: ExxonMobil_Climate_Research_1977-2000.pdf',
    type: 'system',
    timestamp: new Date('2015-10-28T11:30:00'),
  },
  {
    id: 'cdm6',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The cost is existential. We\'ve lost 40 years of action. Current projections: 2°C+ warming locked in. Billions will suffer because corporations protected profits.',
    type: 'text',
    timestamp: new Date('2015-10-28T13:00:00'),
    isPinned: true,
  },
  {
    id: 'cdm7',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'The disinformation continues. Koch network still funds denial. Facebook is full of fossil fuel propaganda. They\'re still fighting action on climate.',
    type: 'text',
    timestamp: new Date('2015-10-28T14:30:00'),
  },
  {
    id: 'cdm8',
    authorId: 'tess-bennett',
    authorName: 'Tess Bennett',
    content: 'Legal accountability is coming. State AGs investigating. Shareholder lawsuits. Climate liability litigation. They can\'t hide the evidence anymore.',
    type: 'text',
    timestamp: new Date('2019-06-15T10:00:00'),
  },
  {
    id: 'cdm9',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The UN special rapporteur called climate denial a violation of human rights. We need to document every executive, every lobby dollar, every lie.',
    type: 'text',
    timestamp: new Date('2019-06-15T11:30:00'),
  },
  {
    id: 'cdm10',
    authorId: 'emily-watson',
    authorName: 'Dr. Emily Watson',
    content: 'This is genocide by corporation. Future generations will judge how we documented this moment and whether we held the perpetrators accountable.',
    type: 'text',
    timestamp: new Date('2019-06-15T14:00:00'),
  },
];

// ==================== WORKSPACE 21: VOTER SUPPRESSION ====================
const voterSuppressionMessages: WorkspaceMessage[] = [
  {
    id: 'vsm1',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'Shelby County v. Holder gutted the Voting Rights Act in 2013. Since then, states have closed 1,700+ polling places in Black and Latino communities. This is the new Jim Crow.',
    type: 'text',
    timestamp: new Date('2020-08-15T09:00:00'),
    isPinned: true,
  },
  {
    id: 'vsm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Georgia is ground zero. Brian Kemp purged 340,000 voters before the 2018 election he was running in. He was Secretary of State - in charge of his own election.',
    type: 'text',
    timestamp: new Date('2020-08-15T09:45:00'),
  },
  {
    id: 'vsm3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The tactics: strict ID laws, reduced early voting, purged voter rolls, fewer polling places, gerrymandering. Every method targets Democratic voters.',
    type: 'text',
    timestamp: new Date('2020-08-15T10:30:00'),
  },
  {
    id: 'vsm4',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'Texas has ONE drop-off location per county. Harris County (Houston): 4.7 million people, one drop box. Loving County: 169 people, one drop box. That\'s not accidental.',
    type: 'text',
    timestamp: new Date('2020-08-15T11:15:00'),
  },
  {
    id: 'vsm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Dr. Michael Brooks uploaded: Voter_Suppression_Laws_2013-2020.pdf',
    type: 'system',
    timestamp: new Date('2020-08-15T11:30:00'),
  },
  {
    id: 'vsm6',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The Heritage Foundation has drafted model suppression legislation. ALEC distributes it to state legislatures. This is a coordinated national strategy.',
    type: 'text',
    timestamp: new Date('2020-08-15T13:00:00'),
  },
  {
    id: 'vsm7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'After 2020, the backlash was swift. Georgia SB 202 criminalized giving water to voters in line. Arizona conducting fraudulent audits. The assault continues.',
    type: 'text',
    timestamp: new Date('2021-03-25T10:00:00'),
    isPinned: true,
  },
  {
    id: 'vsm8',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'Between 2021-2023, states passed 94 laws restricting voting access. This is the most sustained attack on voting rights since Reconstruction.',
    type: 'text',
    timestamp: new Date('2023-06-10T09:00:00'),
  },
  {
    id: 'vsm9',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The For the People Act and John Lewis Act are dead in Senate. Manchin and Sinema protected the filibuster over voting rights. History will judge harshly.',
    type: 'text',
    timestamp: new Date('2023-06-10T10:30:00'),
  },
  {
    id: 'vsm10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'We need to document every law, every purge, every closure. This is the record of how American democracy was strangled.',
    type: 'text',
    timestamp: new Date('2023-06-10T14:00:00'),
  },
];

// ==================== WORKSPACE 22: AFGHANISTAN PAPERS ====================
const afghanistanMessages: WorkspaceMessage[] = [
  {
    id: 'apm1',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The Washington Post\'s Afghanistan Papers prove what we suspected: Officials lied for 18 years about whether the war was winnable. They KNEW we were losing and said the opposite.',
    type: 'text',
    timestamp: new Date('2019-12-09T08:00:00'),
    isPinned: true,
  },
  {
    id: 'apm2',
    authorId: 'james-mitchell',
    authorName: 'James Mitchell',
    content: 'The SIGAR interviews are devastating. Three-star generals admitting privately what they denied publicly. "We didn\'t have the foggiest notion of what we were undertaking."',
    type: 'text',
    timestamp: new Date('2019-12-09T08:45:00'),
  },
  {
    id: 'apm3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The parallels to the Pentagon Papers are exact. Government knew the war was unwinnable. Continued sending troops to die anyway. Protected their careers over soldiers\' lives.',
    type: 'text',
    timestamp: new Date('2019-12-09T09:30:00'),
  },
  {
    id: 'apm4',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The waste is staggering. $2.3 TRILLION spent. Roads built to nowhere. Ghost soldiers on the Afghan payroll. Contractors walking away with billions.',
    type: 'text',
    timestamp: new Date('2019-12-09T10:15:00'),
  },
  {
    id: 'apm5',
    authorId: 'system',
    authorName: 'System',
    content: 'James Mitchell uploaded: SIGAR_Lessons_Learned_Interviews_Complete.zip',
    type: 'system',
    timestamp: new Date('2019-12-09T10:30:00'),
  },
  {
    id: 'apm6',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The metrics were manipulated. "Success" was measured by school construction, paved roads - meaningless in a war. The Taliban controlled more territory each year.',
    type: 'text',
    timestamp: new Date('2019-12-09T13:00:00'),
  },
  {
    id: 'apm7',
    authorId: 'james-mitchell',
    authorName: 'James Mitchell',
    content: 'Every administration lied. Bush, Obama, Trump. Democrats and Republicans equally culpable. The bipartisan consensus was to keep lying.',
    type: 'text',
    timestamp: new Date('2019-12-09T14:30:00'),
    isPinned: true,
  },
  {
    id: 'apm8',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'And then it ended exactly as the papers predicted. Taliban took Kabul in days. 20 years of lies collapsed in 20 days.',
    type: 'text',
    timestamp: new Date('2021-08-15T08:00:00'),
  },
  {
    id: 'apm9',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The withdrawal was chaos, but let\'s be clear: the failure was the 20 years before. No one will be held accountable for America\'s longest war.',
    type: 'text',
    timestamp: new Date('2021-08-15T10:00:00'),
  },
  {
    id: 'apm10',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'We need to document every lie, every false metric, every official who knew the truth. The soldiers who died deserved better.',
    type: 'text',
    timestamp: new Date('2021-08-15T14:00:00'),
  },
];

// ==================== WORKSPACE 23: FTX CRYPTO FRAUD ====================
const ftxMessages: WorkspaceMessage[] = [
  {
    id: 'ftxm1',
    authorId: 'omar-farooq',
    authorName: 'Omar Farooq',
    content: 'FTX collapse is the biggest financial fraud since Enron. $8 billion in customer funds missing. Sam Bankman-Fried was sending customer money to Alameda Research the whole time.',
    type: 'text',
    timestamp: new Date('2022-11-11T08:00:00'),
    isPinned: true,
  },
  {
    id: 'ftxm2',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'The red flags were everywhere. FTX had no CFO. Alameda was run by his ex-girlfriend. They used QuickBooks for billions in transactions. This wasn\'t sophisticated fraud - it was chaos.',
    type: 'text',
    timestamp: new Date('2022-11-11T08:45:00'),
  },
  {
    id: 'ftxm3',
    authorId: 'casey-morgan',
    authorName: 'Casey Morgan',
    content: 'The fraud structure: Customer deposits went to Alameda. Alameda made risky bets. When customers wanted withdrawals, FTX minted FTT tokens to fake collateral. Ponzi mechanics.',
    type: 'text',
    timestamp: new Date('2022-11-11T09:30:00'),
  },
  {
    id: 'ftxm4',
    authorId: 'omar-farooq',
    authorName: 'Omar Farooq',
    content: 'The celebrity endorsements were part of it. Tom Brady, Steph Curry, Larry David - all promoting what turned out to be a fraud. Retail investors trusted celebrities over due diligence.',
    type: 'text',
    timestamp: new Date('2022-11-11T10:15:00'),
  },
  {
    id: 'ftxm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Omar Farooq uploaded: FTX_Alameda_Fund_Flow_Analysis.xlsx',
    type: 'system',
    timestamp: new Date('2022-11-11T10:30:00'),
  },
  {
    id: 'ftxm6',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'The political donations are suspicious. SBF was #2 Democratic donor in 2022. His colleagues donated to Republicans. They were buying influence from both parties.',
    type: 'text',
    timestamp: new Date('2022-11-11T13:00:00'),
  },
  {
    id: 'ftxm7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The bankruptcy filing shows cash management via Slack emoji. Real quote: "There is no money at FTX... just a meme on Slack." Billions managed like a college startup.',
    type: 'text',
    timestamp: new Date('2022-11-11T14:30:00'),
    isPinned: true,
  },
  {
    id: 'ftxm8',
    authorId: 'casey-morgan',
    authorName: 'Casey Morgan',
    content: 'The Bahamas compound was a $40 million real estate purchase using customer funds. They were living large while customers\' money evaporated.',
    type: 'text',
    timestamp: new Date('2022-11-11T15:30:00'),
  },
  {
    id: 'ftxm9',
    authorId: 'omar-farooq',
    authorName: 'Omar Farooq',
    content: 'Criminal charges filed. SBF facing 115 years. His inner circle cooperating. Caroline Ellison provided devastating testimony. The house of cards collapsed completely.',
    type: 'text',
    timestamp: new Date('2023-10-10T09:00:00'),
  },
  {
    id: 'ftxm10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'GUILTY on all 7 counts. Maximum 110 years. Finally, a white collar criminal facing real consequences. This should be the template, not the exception.',
    type: 'text',
    timestamp: new Date('2023-11-02T18:00:00'),
  },
];

// ==================== WORKSPACE 24: MAR-A-LAGO DOCUMENTS ====================
const marALagoMessages: WorkspaceMessage[] = [
  {
    id: 'mam1',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'The FBI search warrant inventory is staggering. 11,179 government documents at Mar-a-Lago. 103 classified documents including TOP SECRET/SCI material in a bathroom closet.',
    type: 'text',
    timestamp: new Date('2022-08-12T09:00:00'),
    isPinned: true,
  },
  {
    id: 'mam2',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The classification levels found: 18 TOP SECRET, 54 SECRET, 31 CONFIDENTIAL. Some marked HUMINT - human intelligence sources. People could die if this was compromised.',
    type: 'text',
    timestamp: new Date('2022-08-12T09:45:00'),
  },
  {
    id: 'mam3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The obstruction is the key. NARA requested return in 2021. Subpoena issued in May 2022. Trump\'s lawyer certified all documents returned - they weren\'t. Consciousness of guilt.',
    type: 'text',
    timestamp: new Date('2022-08-12T10:30:00'),
  },
  {
    id: 'mam4',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'The surveillance footage showed documents being moved AFTER the subpoena. Someone instructed staff to relocate boxes. This is textbook obstruction of justice.',
    type: 'text',
    timestamp: new Date('2022-08-12T11:15:00'),
  },
  {
    id: 'mam5',
    authorId: 'system',
    authorName: 'System',
    content: 'David Kim uploaded: Mar_a_Lago_Search_Warrant_Documents.pdf',
    type: 'system',
    timestamp: new Date('2022-08-12T11:30:00'),
  },
  {
    id: 'mam6',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The national security implications are severe. Counterintelligence assessment ongoing. We don\'t know who had access to these documents at a public club.',
    type: 'text',
    timestamp: new Date('2022-08-12T13:00:00'),
  },
  {
    id: 'mam7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Jack Smith indicted June 2023. 37 counts. Willful retention, conspiracy, false statements. The evidence is overwhelming.',
    type: 'text',
    timestamp: new Date('2023-06-09T14:00:00'),
    isPinned: true,
  },
  {
    id: 'mam8',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'Judge Cannon is slow-walking the case. Indefinitely postponed trial. She was appointed by Trump. The appearance of judicial bias is severe.',
    type: 'text',
    timestamp: new Date('2024-05-07T10:00:00'),
  },
  {
    id: 'mam9',
    authorId: 'layla-hassan',
    authorName: 'Layla Hassan',
    content: 'The audio recording of Trump showing classified documents is damning: "This is secret information. Look, look at this. I could have declassified it. Now I can\'t." Admission on tape.',
    type: 'text',
    timestamp: new Date('2024-05-07T11:30:00'),
  },
  {
    id: 'mam10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'If this case doesn\'t result in conviction, the Espionage Act is meaningless. Anyone else would already be in prison.',
    type: 'text',
    timestamp: new Date('2024-05-07T14:00:00'),
  },
];

// ==================== WORKSPACE 25: GEORGIA RICO ====================
const georgiaRicoMessages: WorkspaceMessage[] = [
  {
    id: 'grm1',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'Fani Willis charged Trump and 18 co-defendants under Georgia RICO. This is the most comprehensive case - charges the entire conspiracy to overturn the election.',
    type: 'text',
    timestamp: new Date('2023-08-14T21:00:00'),
    isPinned: true,
  },
  {
    id: 'grm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The Fulton County indictment is 98 pages. 161 overt acts. From the "perfect phone call" to fake electors to Rudy\'s drunk testimony. They documented everything.',
    type: 'text',
    timestamp: new Date('2023-08-14T21:30:00'),
  },
  {
    id: 'grm3',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Key defendants: Trump, Giuliani, Meadows, Eastman, Sidney Powell, Jenna Ellis, Jeffrey Clark. The entire coup apparatus charged together.',
    type: 'text',
    timestamp: new Date('2023-08-14T22:15:00'),
  },
  {
    id: 'grm4',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'The "perfect phone call" to Raffensperger is the centerpiece. Trump asking to "find" exactly 11,780 votes - one more than Biden\'s margin. Recorded. Undeniable.',
    type: 'text',
    timestamp: new Date('2023-08-15T09:00:00'),
  },
  {
    id: 'grm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Dr. Michael Brooks uploaded: Fulton_County_RICO_Indictment_Full.pdf',
    type: 'system',
    timestamp: new Date('2023-08-15T09:15:00'),
  },
  {
    id: 'grm6',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The Coffee County breach is chilling. Trump allies gained unauthorized access to voting systems with the help of county officials. Actual election interference documented.',
    type: 'text',
    timestamp: new Date('2023-08-15T10:30:00'),
  },
  {
    id: 'grm7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Plea deals coming in. Sidney Powell pled guilty. Jenna Ellis pled guilty. Kenneth Chesebro pled guilty. The cooperating witnesses are multiplying.',
    type: 'text',
    timestamp: new Date('2023-10-20T10:00:00'),
    isPinned: true,
  },
  {
    id: 'grm8',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'The Willis-Wade situation is politically damaging but legally irrelevant. The evidence doesn\'t change. Focus on the crimes, not the drama.',
    type: 'text',
    timestamp: new Date('2024-02-15T09:00:00'),
  },
  {
    id: 'grm9',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Appeals court considering if Willis should be disqualified. Regardless of outcome, this case laid out the conspiracy in detail. The historical record is established.',
    type: 'text',
    timestamp: new Date('2024-06-10T10:00:00'),
  },
  {
    id: 'grm10',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Georgia RICO is the backstop. State charges - no federal pardon possible. Even if Trump wins, Georgia can still pursue justice.',
    type: 'text',
    timestamp: new Date('2024-06-10T14:00:00'),
  },
];

// Export workspaces 19-25
export const extendedWorkspaces4: Workspace[] = [
  // Workspace 19: 2008 Financial Crisis
  {
    id: 'ws19',
    name: '2008 Financial Crisis Accountability',
    description: 'Documentation of the 2008 financial crisis, bank fraud, and the absence of criminal prosecution. Tracking how Wall Street crashed the economy and escaped justice.',
    investigation: 'financial-crisis-2008',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2012-08-15'),
    updatedAt: new Date('2019-05-15'),
    createdBy: 'rachel-torres',
    members: getTeam('rachel-torres', 'sarah-chen', 'marcus-rivera'),
    messages: financialCrisisMessages,
    evidence: [
      {
        id: 'fce1',
        title: 'Goldman Sachs Internal Emails',
        description: 'Internal communications showing executives knew products were "shitty deals"',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Senate PSI Investigation',
        addedAt: new Date('2012-08-15'),
        addedBy: 'rachel-torres',
        addedByName: 'Rachel Torres',
        tags: ['Goldman Sachs', 'Fraud', 'MBS'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'fcd1',
        name: 'Goldman_Sachs_Internal_Emails_2006-2008.pdf',
        type: 'application/pdf',
        size: 23456789,
        url: '#',
        uploadedBy: 'rachel-torres',
        uploadedByName: 'Rachel Torres',
        uploadedAt: new Date('2012-08-15'),
        folder: 'Bank Records',
        category: 'Bank Records',
        description: 'Internal Goldman communications during crisis',
        downloads: 1234,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'fct1', date: new Date('2008-09-15'), title: 'Lehman Collapse', description: 'Lehman Brothers files bankruptcy', evidenceIds: [], addedBy: 'sarah-chen', importance: 'major' },
    ],
    tasks: [],
    tags: ['Financial Crisis', 'Wall Street', 'Fraud', 'Banks'],
    isPublic: false,
    viewCount: 8765,
    lastActivity: new Date('2019-05-15'),
    milestones: [],
  },
  // Workspace 20: Climate Denial
  {
    id: 'ws20',
    name: 'Climate Denial Disinformation Trail',
    description: 'Tracking 40+ years of fossil fuel industry disinformation on climate change. Documenting internal knowledge, denial funding, and obstruction of climate action.',
    investigation: 'climate-denial',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2015-10-28'),
    updatedAt: new Date('2023-06-20'),
    createdBy: 'tess-bennett',
    members: getTeam('tess-bennett', 'sarah-chen', 'emily-watson'),
    messages: climateDenialMessages,
    evidence: [
      {
        id: 'cde1',
        title: 'ExxonMobil Climate Research',
        description: 'Internal documents showing Exxon knew about climate change since 1977',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'InsideClimate News / LA Times',
        addedAt: new Date('2015-10-28'),
        addedBy: 'tess-bennett',
        addedByName: 'Tess Bennett',
        tags: ['Exxon', 'Climate', 'Denial'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'cdd1',
        name: 'ExxonMobil_Climate_Research_1977-2000.pdf',
        type: 'application/pdf',
        size: 34567890,
        url: '#',
        uploadedBy: 'tess-bennett',
        uploadedByName: 'Tess Bennett',
        uploadedAt: new Date('2015-10-28'),
        folder: 'Corporate Records',
        category: 'Corporate Records',
        description: 'Internal Exxon climate research documents',
        downloads: 2345,
        isPublic: false,
      },
    ],
    timeline: [],
    tasks: [],
    tags: ['Climate', 'Exxon', 'Denial', 'Fossil Fuel'],
    isPublic: false,
    viewCount: 11234,
    lastActivity: new Date('2023-06-20'),
    milestones: [],
  },
  // Workspace 21: Voter Suppression
  {
    id: 'ws21',
    name: 'Voter Suppression Tracking Project',
    description: 'Monitoring systematic voter suppression across states post-Shelby County. Documenting poll closures, voter purges, and restrictive laws targeting minority voters.',
    investigation: 'voter-suppression',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2020-08-15'),
    updatedAt: new Date('2024-01-20'),
    createdBy: 'michael-brooks',
    members: getTeam('michael-brooks', 'sarah-chen', 'marcus-rivera'),
    messages: voterSuppressionMessages,
    evidence: [
      {
        id: 'vse1',
        title: 'Voter Suppression Laws Database',
        description: 'Comprehensive tracking of restrictive voting laws 2013-2023',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Brennan Center / State Legislatures',
        addedAt: new Date('2020-08-15'),
        addedBy: 'michael-brooks',
        addedByName: 'Dr. Michael Brooks',
        tags: ['Voting', 'Suppression', 'Laws'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'vsd1',
        name: 'Voter_Suppression_Laws_2013-2020.pdf',
        type: 'application/pdf',
        size: 12345678,
        url: '#',
        uploadedBy: 'michael-brooks',
        uploadedByName: 'Dr. Michael Brooks',
        uploadedAt: new Date('2020-08-15'),
        folder: 'Legal Research',
        category: 'Legal Research',
        description: 'State-by-state suppression law analysis',
        downloads: 876,
        isPublic: false,
      },
    ],
    timeline: [],
    tasks: [],
    tags: ['Voting', 'Suppression', 'Democracy', 'Civil Rights'],
    isPublic: false,
    viewCount: 9876,
    lastActivity: new Date('2024-01-20'),
    milestones: [],
  },
  // Workspace 22: Afghanistan Papers
  {
    id: 'ws22',
    name: 'Afghanistan Papers Analysis',
    description: 'Investigation into 18 years of government lies about the Afghanistan war. Analyzing SIGAR interviews and official deception about war progress.',
    investigation: 'afghanistan-papers',
    status: 'active',
    priority: 'high',
    visibility: 'private',
    createdAt: new Date('2019-12-09'),
    updatedAt: new Date('2021-08-20'),
    createdBy: 'layla-hassan',
    members: getTeam('layla-hassan', 'james-mitchell', 'marcus-rivera', 'sarah-chen'),
    messages: afghanistanMessages,
    evidence: [
      {
        id: 'ape1',
        title: 'SIGAR Lessons Learned Interviews',
        description: 'Full set of internal interviews revealing official deception',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Washington Post FOIA / SIGAR',
        addedAt: new Date('2019-12-09'),
        addedBy: 'james-mitchell',
        addedByName: 'James Mitchell',
        tags: ['Afghanistan', 'SIGAR', 'Pentagon Papers'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'apd1',
        name: 'SIGAR_Lessons_Learned_Interviews_Complete.zip',
        type: 'application/zip',
        size: 567890123,
        url: '#',
        uploadedBy: 'james-mitchell',
        uploadedByName: 'James Mitchell',
        uploadedAt: new Date('2019-12-09'),
        folder: 'Government Documents',
        category: 'Government Documents',
        description: 'Complete SIGAR interview archive',
        downloads: 1543,
        isPublic: false,
      },
    ],
    timeline: [],
    tasks: [],
    tags: ['Afghanistan', 'War', 'Pentagon Papers', 'SIGAR'],
    isPublic: false,
    viewCount: 7654,
    lastActivity: new Date('2021-08-20'),
    milestones: [],
  },
  // Workspace 23: FTX Fraud
  {
    id: 'ws23',
    name: 'FTX Cryptocurrency Fraud Investigation',
    description: 'Documenting the collapse of FTX and the $8 billion fraud orchestrated by Sam Bankman-Fried. Tracking fund flows, political donations, and criminal prosecution.',
    investigation: 'ftx-fraud',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2022-11-11'),
    updatedAt: new Date('2023-11-05'),
    createdBy: 'omar-farooq',
    members: getTeam('omar-farooq', 'rachel-torres', 'casey-morgan', 'marcus-rivera'),
    messages: ftxMessages,
    evidence: [
      {
        id: 'ftxe1',
        title: 'FTX-Alameda Fund Flow Analysis',
        description: 'Tracing customer funds from FTX to Alameda Research',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Bankruptcy Filing / DOJ Indictment',
        addedAt: new Date('2022-11-11'),
        addedBy: 'omar-farooq',
        addedByName: 'Omar Farooq',
        tags: ['FTX', 'Alameda', 'Crypto', 'Fraud'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'ftxd1',
        name: 'FTX_Alameda_Fund_Flow_Analysis.xlsx',
        type: 'application/vnd.ms-excel',
        size: 8765432,
        url: '#',
        uploadedBy: 'omar-farooq',
        uploadedByName: 'Omar Farooq',
        uploadedAt: new Date('2022-11-11'),
        folder: 'Financial Analysis',
        category: 'Financial Analysis',
        description: 'Fund flow tracing between FTX entities',
        downloads: 2345,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'ftxt1', date: new Date('2022-11-11'), title: 'FTX Bankruptcy', description: 'FTX files Chapter 11 bankruptcy', evidenceIds: ['ftxe1'], addedBy: 'omar-farooq', importance: 'major' },
      { id: 'ftxt2', date: new Date('2023-11-02'), title: 'SBF Guilty', description: 'Bankman-Fried convicted on all 7 counts', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [],
    tags: ['FTX', 'Crypto', 'Fraud', 'Bankman-Fried'],
    isPublic: false,
    viewCount: 15432,
    lastActivity: new Date('2023-11-05'),
    milestones: [],
  },
  // Workspace 24: Mar-a-Lago Documents
  {
    id: 'ws24',
    name: 'Classified Documents Investigation',
    description: 'Investigation into Trump\'s retention of classified documents at Mar-a-Lago. Documenting obstruction, national security risks, and judicial proceedings.',
    investigation: 'mar-a-lago-documents',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2022-08-12'),
    updatedAt: new Date('2024-05-10'),
    createdBy: 'david-kim',
    members: getTeam('david-kim', 'layla-hassan', 'marcus-rivera'),
    messages: marALagoMessages,
    evidence: [
      {
        id: 'mae1',
        title: 'Mar-a-Lago Search Warrant Documents',
        description: 'FBI search warrant and inventory of recovered documents',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Department of Justice / SDFL',
        addedAt: new Date('2022-08-12'),
        addedBy: 'david-kim',
        addedByName: 'David Kim',
        tags: ['Mar-a-Lago', 'Classified', 'FBI'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'mad1',
        name: 'Mar_a_Lago_Search_Warrant_Documents.pdf',
        type: 'application/pdf',
        size: 5678901,
        url: '#',
        uploadedBy: 'david-kim',
        uploadedByName: 'David Kim',
        uploadedAt: new Date('2022-08-12'),
        folder: 'Legal Documents',
        category: 'Legal Documents',
        description: 'Complete search warrant package',
        downloads: 3456,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'mat1', date: new Date('2022-08-08'), title: 'FBI Search', description: 'FBI executes search warrant at Mar-a-Lago', evidenceIds: ['mae1'], addedBy: 'david-kim', importance: 'major' },
      { id: 'mat2', date: new Date('2023-06-09'), title: 'Trump Indicted', description: '37 federal charges filed', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [],
    tags: ['Mar-a-Lago', 'Classified', 'Trump', 'Espionage Act'],
    isPublic: false,
    viewCount: 23456,
    lastActivity: new Date('2024-05-10'),
    milestones: [],
  },
  // Workspace 25: Georgia RICO
  {
    id: 'ws25',
    name: 'Georgia Election RICO Investigation',
    description: 'Tracking the Fulton County RICO prosecution of Trump and co-defendants for conspiracy to overturn the 2020 election in Georgia.',
    investigation: 'georgia-rico',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2023-08-14'),
    updatedAt: new Date('2024-06-15'),
    createdBy: 'michael-brooks',
    members: getTeam('michael-brooks', 'sarah-chen', 'marcus-rivera'),
    messages: georgiaRicoMessages,
    evidence: [
      {
        id: 'gre1',
        title: 'Fulton County RICO Indictment',
        description: 'Full 98-page indictment with 161 overt acts',
        type: 'document',
        category: 'primary',
        verificationStatus: 'verified',
        source: 'Fulton County Superior Court',
        addedAt: new Date('2023-08-15'),
        addedBy: 'michael-brooks',
        addedByName: 'Dr. Michael Brooks',
        tags: ['RICO', 'Georgia', 'Election'],
        connections: [],
        position: { x: 100, y: 100 },
      },
    ],
    documents: [
      {
        id: 'grd1',
        name: 'Fulton_County_RICO_Indictment_Full.pdf',
        type: 'application/pdf',
        size: 12345678,
        url: '#',
        uploadedBy: 'michael-brooks',
        uploadedByName: 'Dr. Michael Brooks',
        uploadedAt: new Date('2023-08-15'),
        folder: 'Legal Documents',
        category: 'Legal Documents',
        description: 'Complete RICO indictment',
        downloads: 5678,
        isPublic: true,
      },
    ],
    timeline: [
      { id: 'grt1', date: new Date('2021-01-02'), title: 'Raffensperger Call', description: 'Trump asks to "find" 11,780 votes', evidenceIds: [], addedBy: 'michael-brooks', importance: 'major' },
      { id: 'grt2', date: new Date('2023-08-14'), title: 'RICO Indictment', description: '19 defendants indicted under Georgia RICO', evidenceIds: ['gre1'], addedBy: 'sarah-chen', importance: 'major' },
    ],
    tasks: [],
    tags: ['Georgia', 'RICO', 'Election', 'Trump', 'Fani Willis'],
    isPublic: false,
    viewCount: 28765,
    lastActivity: new Date('2024-06-15'),
    milestones: [],
  },
];
