// Extended workspace data for ArkHive platform
// This file contains detailed workspaces with full chat histories

import { 
  Workspace, 
  WorkspaceMember, 
  WorkspaceMessage, 
  Evidence, 
  WorkspaceDocument,
  WorkspaceTimeline,
  ResearchTask,
} from '@/types/workspace';

// ==================== INVESTIGATOR POOL ====================
// These investigators are assigned to various workspaces

const investigators: Record<string, WorkspaceMember> = {
  'sarah-chen': {
    id: 'sarah-chen',
    name: 'Sarah Chen',
    role: 'owner',
    joinedAt: new Date('2009-03-15'),
    lastActive: new Date(),
    contributions: 2847,
    isOnline: true,
    expertise: ['Data Analysis', 'FOIA Requests', 'Financial Records'],
  },
  'marcus-rivera': {
    id: 'marcus-rivera',
    name: 'Marcus Rivera',
    role: 'admin',
    joinedAt: new Date('2010-06-01'),
    lastActive: new Date(),
    contributions: 2189,
    isOnline: true,
    expertise: ['Government Affairs', 'Legal Research', 'Court Records'],
  },
  'emily-watson': {
    id: 'emily-watson',
    name: 'Dr. Emily Watson',
    role: 'investigator',
    joinedAt: new Date('2011-02-15'),
    lastActive: new Date(Date.now() - 3600000),
    contributions: 1856,
    isOnline: false,
    expertise: ['Toxicology', 'Environmental Science', 'Medical Records'],
  },
  'james-mitchell': {
    id: 'james-mitchell',
    name: 'James Mitchell',
    role: 'investigator',
    joinedAt: new Date('2012-08-01'),
    lastActive: new Date(Date.now() - 7200000),
    contributions: 1489,
    isOnline: true,
    expertise: ['Open Source Intelligence', 'Document Analysis', 'Satellite Imagery'],
  },
  'rachel-torres': {
    id: 'rachel-torres',
    name: 'Rachel Torres',
    role: 'admin',
    joinedAt: new Date('2013-04-20'),
    lastActive: new Date(),
    contributions: 1634,
    isOnline: true,
    expertise: ['Financial Crimes', 'Money Laundering', 'Corporate Records'],
  },
  'david-kim': {
    id: 'david-kim',
    name: 'David Kim',
    role: 'investigator',
    joinedAt: new Date('2014-01-10'),
    lastActive: new Date(Date.now() - 1800000),
    contributions: 1247,
    isOnline: true,
    expertise: ['Cybersecurity', 'Digital Forensics', 'Metadata Analysis'],
  },
  'michael-brooks': {
    id: 'michael-brooks',
    name: 'Dr. Michael Brooks',
    role: 'investigator',
    joinedAt: new Date('2015-07-15'),
    lastActive: new Date(Date.now() - 86400000),
    contributions: 987,
    isOnline: false,
    expertise: ['Political Science', 'Campaign Finance', 'Election Law'],
  },
  'nina-patel': {
    id: 'nina-patel',
    name: 'Nina Patel',
    role: 'investigator',
    joinedAt: new Date('2016-03-01'),
    lastActive: new Date(),
    contributions: 1123,
    isOnline: true,
    expertise: ['Human Rights', 'International Law', 'Immigration'],
  },
  'alex-reyes': {
    id: 'alex-reyes',
    name: 'Alex Reyes',
    role: 'researcher',
    joinedAt: new Date('2017-09-12'),
    lastActive: new Date(Date.now() - 3600000),
    contributions: 876,
    isOnline: false,
    expertise: ['Investigative Journalism', 'Source Development', 'Verification'],
  },
  'casey-morgan': {
    id: 'casey-morgan',
    name: 'Casey Morgan',
    role: 'investigator',
    joinedAt: new Date('2018-05-20'),
    lastActive: new Date(),
    contributions: 734,
    isOnline: true,
    expertise: ['Corporate Law', 'Securities Fraud', 'Whistleblowers'],
  },
  'robert-hayes': {
    id: 'robert-hayes',
    name: 'Dr. Robert Hayes',
    role: 'investigator',
    joinedAt: new Date('2019-02-01'),
    lastActive: new Date(Date.now() - 172800000),
    contributions: 623,
    isOnline: false,
    expertise: ['Criminal Justice', 'Police Procedures', 'Civil Rights'],
  },
  'layla-hassan': {
    id: 'layla-hassan',
    name: 'Layla Hassan',
    role: 'researcher',
    joinedAt: new Date('2020-01-15'),
    lastActive: new Date(),
    contributions: 534,
    isOnline: true,
    expertise: ['Middle East Affairs', 'Arms Trade', 'Intelligence'],
  },
  'jake-thompson': {
    id: 'jake-thompson',
    name: 'Jake Thompson',
    role: 'investigator',
    joinedAt: new Date('2020-08-01'),
    lastActive: new Date(Date.now() - 7200000),
    contributions: 445,
    isOnline: true,
    expertise: ['Tech Industry', 'Privacy', 'Surveillance'],
  },
  'mira-novak': {
    id: 'mira-novak',
    name: 'Mira Novak',
    role: 'researcher',
    joinedAt: new Date('2021-03-10'),
    lastActive: new Date(),
    contributions: 389,
    isOnline: true,
    expertise: ['Eastern Europe', 'Russian Affairs', 'Disinformation'],
  },
  'yuki-tanaka': {
    id: 'yuki-tanaka',
    name: 'Dr. Yuki Tanaka',
    role: 'investigator',
    joinedAt: new Date('2021-11-01'),
    lastActive: new Date(Date.now() - 3600000),
    contributions: 312,
    isOnline: false,
    expertise: ['Medical Ethics', 'Pharmaceutical Industry', 'Clinical Trials'],
  },
  'omar-farooq': {
    id: 'omar-farooq',
    name: 'Omar Farooq',
    role: 'researcher',
    joinedAt: new Date('2022-04-15'),
    lastActive: new Date(),
    contributions: 267,
    isOnline: true,
    expertise: ['Financial Analysis', 'Cryptocurrency', 'Fraud Detection'],
  },
  'tess-bennett': {
    id: 'tess-bennett',
    name: 'Tess Bennett',
    role: 'investigator',
    joinedAt: new Date('2022-09-01'),
    lastActive: new Date(Date.now() - 1800000),
    contributions: 198,
    isOnline: true,
    expertise: ['Environmental Law', 'EPA Regulations', 'Corporate Pollution'],
  },
  'kyle-anderson': {
    id: 'kyle-anderson',
    name: 'Kyle Anderson',
    role: 'researcher',
    joinedAt: new Date('2023-01-20'),
    lastActive: new Date(),
    contributions: 156,
    isOnline: true,
    expertise: ['Aviation', 'FAA Regulations', 'Safety Systems'],
  },
  'priya-sharma': {
    id: 'priya-sharma',
    name: 'Dr. Priya Sharma',
    role: 'investigator',
    joinedAt: new Date('2023-06-01'),
    lastActive: new Date(Date.now() - 86400000),
    contributions: 123,
    isOnline: false,
    expertise: ['Public Health', 'Epidemiology', 'FDA Policy'],
  },
  'aiden-obrien': {
    id: 'aiden-obrien',
    name: 'Aiden O\'Brien',
    role: 'researcher',
    joinedAt: new Date('2024-02-01'),
    lastActive: new Date(),
    contributions: 87,
    isOnline: true,
    expertise: ['Social Media Analysis', 'Network Mapping', 'OSINT'],
  },
};

// Helper function to get team members
const getTeam = (...ids: string[]): WorkspaceMember[] => 
  ids.map(id => investigators[id]).filter(Boolean);

// ==================== WORKSPACE 5: TRUMP-RUSSIA MONEY TRAIL ====================
const trumpRussiaMessages: WorkspaceMessage[] = [
  {
    id: 'trm1',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Team, I\'ve spent the last three weeks analyzing Deutsche Bank\'s subpoenaed records. The pattern of loans to Trump Organization between 2011-2015 is... unusual to say the least.',
    type: 'text',
    timestamp: new Date('2017-08-14T09:23:00'),
    isPinned: true,
  },
  {
    id: 'trm2',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'What kind of unusual? Red flags for money laundering or just poor lending practices?',
    type: 'text',
    timestamp: new Date('2017-08-14T09:31:00'),
  },
  {
    id: 'trm3',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Both. DB approved loans to Trump after he defaulted on previous obligations. No other major bank would touch him. The question is WHY Deutsche Bank kept lending. Their Russian unit was simultaneously being fined for $10B mirror trading scheme.',
    type: 'text',
    timestamp: new Date('2017-08-14T09:45:00'),
  },
  {
    id: 'trm4',
    authorId: 'mira-novak',
    authorName: 'Mira Novak',
    content: 'I can add context here. The VTB Bank connections are significant. Russian oligarchs were using DB as a bridge to Western financial systems during the same period. I have documentation on the Agalarov family transactions.',
    type: 'text',
    timestamp: new Date('2017-08-14T10:12:00'),
  },
  {
    id: 'trm5',
    authorId: 'system',
    authorName: 'System',
    content: 'Mira Novak uploaded: VTB_Bank_Wire_Analysis_2012-2015.xlsx',
    type: 'system',
    timestamp: new Date('2017-08-14T10:15:00'),
  },
  {
    id: 'trm6',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'The Bayrock connections need more attention. Felix Sater\'s background is documented - convicted felon with Russian organized crime ties, yet he had a Trump Organization business card and office in Trump Tower.',
    type: 'text',
    timestamp: new Date('2017-08-14T11:03:00'),
  },
  {
    id: 'trm7',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The Trump SoHo deal is the key example. Bayrock structured it, Sater brought in Kazakh money through Tevfik Arif. Trump\'s only contribution was his name, yet he took 18% equity. Classic money laundering vehicle.',
    type: 'text',
    timestamp: new Date('2017-08-14T11:28:00'),
  },
  {
    id: 'trm8',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Legal question: Do we have enough to allege active participation or just willful blindness? The distinction matters for framing.',
    type: 'text',
    timestamp: new Date('2017-08-14T13:45:00'),
  },
  {
    id: 'trm9',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Given the repeated pattern across multiple properties - Trump Toronto, Trump Panama, Trump Baku - willful blindness at minimum. But the 2013 Miss Universe Moscow trip and subsequent Trump Tower Moscow negotiations suggest active participation.',
    type: 'text',
    timestamp: new Date('2017-08-14T14:12:00'),
  },
  {
    id: 'trm10',
    authorId: 'mira-novak',
    authorName: 'Mira Novak',
    content: 'Speaking of which - I\'ve obtained the LOI for Trump Tower Moscow signed in October 2015. Trump was negotiating this deal while running for president and publicly denying any Russia business. This directly contradicts his statements.',
    type: 'text',
    timestamp: new Date('2017-08-14T15:30:00'),
    isPinned: true,
  },
  {
    id: 'trm11',
    authorId: 'system',
    authorName: 'System',
    content: 'Mira Novak uploaded: Trump_Tower_Moscow_LOI_Oct2015.pdf',
    type: 'system',
    timestamp: new Date('2017-08-14T15:32:00'),
  },
  {
    id: 'trm12',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'This is significant. The deal required Putin\'s personal approval for the site. Michael Cohen was emailing the Kremlin directly. We need to map out every communication.',
    type: 'text',
    timestamp: new Date('2017-08-14T16:05:00'),
  },
  {
    id: 'trm13',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'I\'ve been tracking the digital trail. Cohen\'s emails to Dmitry Peskov\'s office, the timing of Trump\'s public praise of Putin - it all correlates. Creating a timeline visualization now.',
    type: 'text',
    timestamp: new Date('2017-08-14T16:43:00'),
  },
  {
    id: 'trm14',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Let\'s also document the post-election behavior. Firing Comey, the Oval Office meeting with Lavrov, sharing classified intel - these actions are consistent with kompromat.',
    type: 'text',
    timestamp: new Date('2017-08-14T17:20:00'),
  },
  {
    id: 'trm15',
    authorId: 'rachel-torres',
    authorName: 'Rachel Torres',
    content: 'Agreed. I\'m adding a section on the pattern of financial leverage as potential blackmail. Between the loans, the failed deals, and the taxes, Russia had multiple vectors.',
    type: 'text',
    timestamp: new Date('2017-08-14T17:55:00'),
  },
];

const trumpRussiaEvidence: Evidence[] = [
  {
    id: 'tre1',
    title: 'Deutsche Bank Loan Records (2011-2015)',
    description: 'Complete loan documentation showing pattern of lending to Trump Organization despite defaults',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Congressional Subpoena / Whistleblower',
    addedAt: new Date('2017-08-10'),
    addedBy: 'rachel-torres',
    addedByName: 'Rachel Torres',
    tags: ['Deutsche Bank', 'Loans', 'Financial Records'],
    connections: ['tre2', 'tre3'],
    verifiedBy: ['sarah-chen', 'marcus-rivera'],
    position: { x: 100, y: 100 },
  },
  {
    id: 'tre2',
    title: 'Trump Tower Moscow LOI (October 2015)',
    description: 'Signed letter of intent for Trump Tower Moscow project during presidential campaign',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'BuzzFeed News / Cohen Investigation',
    addedAt: new Date('2017-08-14'),
    addedBy: 'mira-novak',
    addedByName: 'Mira Novak',
    tags: ['Trump Tower Moscow', 'Russia', 'Campaign'],
    connections: ['tre1', 'tre4'],
    verifiedBy: ['sarah-chen'],
    position: { x: 300, y: 150 },
  },
  {
    id: 'tre3',
    title: 'VTB Bank Wire Analysis',
    description: 'Analysis of wire transfers between VTB Bank and Deutsche Bank during relevant period',
    type: 'document',
    category: 'supporting',
    verificationStatus: 'verified',
    source: 'FinCEN Files / OCCRP',
    addedAt: new Date('2017-08-14'),
    addedBy: 'mira-novak',
    addedByName: 'Mira Novak',
    tags: ['VTB Bank', 'Wire Transfers', 'Money Flow'],
    connections: ['tre1'],
    position: { x: 200, y: 300 },
  },
  {
    id: 'tre4',
    title: 'Cohen-Kremlin Email Correspondence',
    description: 'Emails between Michael Cohen and Kremlin officials regarding Trump Tower Moscow',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'Mueller Investigation',
    addedAt: new Date('2017-08-20'),
    addedBy: 'david-kim',
    addedByName: 'David Kim',
    tags: ['Cohen', 'Kremlin', 'Email', 'Communications'],
    connections: ['tre2'],
    position: { x: 400, y: 200 },
  },
  {
    id: 'tre5',
    title: 'Bayrock Group Corporate Records',
    description: 'Corporate structure and ownership documents for Bayrock Group',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'NY AG / SEC Filings',
    addedAt: new Date('2017-08-25'),
    addedBy: 'rachel-torres',
    addedByName: 'Rachel Torres',
    tags: ['Bayrock', 'Felix Sater', 'Corporate Records'],
    connections: ['tre1', 'tre6'],
    position: { x: 150, y: 400 },
  },
  {
    id: 'tre6',
    title: 'Felix Sater Background Documentation',
    description: 'Criminal history and government cooperation records for Felix Sater',
    type: 'document',
    category: 'supporting',
    verificationStatus: 'verified',
    source: 'Court Records / FBI Files',
    addedAt: new Date('2017-09-01'),
    addedBy: 'marcus-rivera',
    addedByName: 'Marcus Rivera',
    tags: ['Sater', 'Criminal History', 'Informant'],
    connections: ['tre5'],
    position: { x: 350, y: 450 },
  },
];

const trumpRussiaDocuments: WorkspaceDocument[] = [
  {
    id: 'trd1',
    name: 'Deutsche_Bank_Loan_Analysis_2011-2015.xlsx',
    type: 'application/vnd.ms-excel',
    size: 3456789,
    url: '#',
    uploadedBy: 'rachel-torres',
    uploadedByName: 'Rachel Torres',
    uploadedAt: new Date('2017-08-10'),
    folder: 'Financial Records',
    category: 'Financial Records',
    description: 'Complete analysis of Deutsche Bank loans to Trump Organization',
    downloads: 234,
    isPublic: false,
  },
  {
    id: 'trd2',
    name: 'Trump_Tower_Moscow_LOI_Oct2015.pdf',
    type: 'application/pdf',
    size: 1234567,
    url: '#',
    uploadedBy: 'mira-novak',
    uploadedByName: 'Mira Novak',
    uploadedAt: new Date('2017-08-14'),
    folder: 'Primary Documents',
    category: 'Primary Documents',
    description: 'Signed letter of intent for Trump Tower Moscow',
    downloads: 567,
    isPublic: false,
  },
  {
    id: 'trd3',
    name: 'VTB_Bank_Wire_Analysis_2012-2015.xlsx',
    type: 'application/vnd.ms-excel',
    size: 2345678,
    url: '#',
    uploadedBy: 'mira-novak',
    uploadedByName: 'Mira Novak',
    uploadedAt: new Date('2017-08-14'),
    folder: 'Financial Records',
    category: 'Financial Records',
    description: 'Analysis of VTB Bank wire transfers',
    downloads: 189,
    isPublic: false,
  },
  {
    id: 'trd4',
    name: 'Bayrock_Corporate_Structure.pdf',
    type: 'application/pdf',
    size: 4567890,
    url: '#',
    uploadedBy: 'rachel-torres',
    uploadedByName: 'Rachel Torres',
    uploadedAt: new Date('2017-08-25'),
    folder: 'Corporate Records',
    category: 'Corporate Records',
    description: 'Bayrock Group corporate documents and ownership',
    downloads: 145,
    isPublic: false,
  },
];

const trumpRussiaTimeline: WorkspaceTimeline[] = [
  {
    id: 'trt1',
    date: new Date('2005-01-01'),
    title: 'Bayrock Partnership Begins',
    description: 'Trump Organization enters partnership with Bayrock Group, Felix Sater gets office in Trump Tower',
    evidenceIds: ['tre5'],
    addedBy: 'rachel-torres',
    importance: 'major',
  },
  {
    id: 'trt2',
    date: new Date('2008-09-15'),
    title: 'Global Financial Crisis',
    description: 'Financial crash leaves Trump unable to secure traditional financing',
    evidenceIds: [],
    addedBy: 'sarah-chen',
    importance: 'major',
  },
  {
    id: 'trt3',
    date: new Date('2011-03-01'),
    title: 'Deutsche Bank Resumes Lending',
    description: 'Despite previous defaults, Deutsche Bank resumes lending to Trump Organization',
    evidenceIds: ['tre1'],
    addedBy: 'rachel-torres',
    importance: 'major',
  },
  {
    id: 'trt4',
    date: new Date('2013-11-09'),
    title: 'Miss Universe Moscow',
    description: 'Trump hosts Miss Universe in Moscow, meets Agalarov family',
    evidenceIds: [],
    addedBy: 'mira-novak',
    importance: 'major',
  },
  {
    id: 'trt5',
    date: new Date('2015-10-28'),
    title: 'Trump Tower Moscow LOI Signed',
    description: 'Letter of intent signed during presidential campaign',
    evidenceIds: ['tre2'],
    addedBy: 'mira-novak',
    importance: 'major',
  },
  {
    id: 'trt6',
    date: new Date('2016-01-14'),
    title: 'Cohen Emails Kremlin',
    description: 'Michael Cohen emails Dmitry Peskov office seeking Putin\'s help',
    evidenceIds: ['tre4'],
    addedBy: 'david-kim',
    importance: 'major',
  },
];

const trumpRussiaTasks: ResearchTask[] = [
  {
    id: 'trtask1',
    title: 'Map all Deutsche Bank loans',
    description: 'Create comprehensive timeline of all DB loans to Trump entities',
    assignedTo: ['rachel-torres'],
    status: 'completed',
    priority: 'critical',
    createdBy: 'sarah-chen',
    createdAt: new Date('2017-08-01'),
    completedAt: new Date('2017-08-10'),
  },
  {
    id: 'trtask2',
    title: 'Trace VTB Bank connections',
    description: 'Document money flows between VTB and entities connected to Trump deals',
    assignedTo: ['mira-novak'],
    status: 'completed',
    priority: 'high',
    createdBy: 'rachel-torres',
    createdAt: new Date('2017-08-05'),
    completedAt: new Date('2017-08-14'),
  },
  {
    id: 'trtask3',
    title: 'Interview former Bayrock employees',
    description: 'Develop sources within Bayrock Group for additional documentation',
    assignedTo: ['alex-reyes'],
    status: 'in-progress',
    priority: 'high',
    createdBy: 'sarah-chen',
    createdAt: new Date('2017-08-15'),
  },
];

// ==================== WORKSPACE 6: EPSTEIN FLIGHT LOG ANALYSIS ====================
const epsteinFlightMessages: WorkspaceMessage[] = [
  {
    id: 'efm1',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'I\'ve finally compiled the complete flight logs from 1995 to 2019. Over 2,000 individual flight records. The passenger manifests tell a disturbing story.',
    type: 'text',
    timestamp: new Date('2019-07-10T08:15:00'),
    isPinned: true,
  },
  {
    id: 'efm2',
    authorId: 'james-mitchell',
    authorName: 'James Mitchell',
    content: 'How complete are the manifests? I know there were allegations of off-book flights.',
    type: 'text',
    timestamp: new Date('2019-07-10T08:32:00'),
  },
  {
    id: 'efm3',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'These are the official FAA records and pilot logs. There are gaps - the estate is fighting release of additional records. But what we have is damning enough.',
    type: 'text',
    timestamp: new Date('2019-07-10T08:45:00'),
  },
  {
    id: 'efm4',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'I\'ve been cross-referencing the dates with victim testimony from the Miami Herald investigation. Multiple victims describe trips that match these flight records.',
    type: 'text',
    timestamp: new Date('2019-07-10T09:12:00'),
  },
  {
    id: 'efm5',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Names I\'m seeing repeatedly: Prince Andrew, Alan Dershowitz, Bill Clinton (26 flights recorded), Kevin Spacey. And yes, Donald Trump on several flights in the late 90s.',
    type: 'text',
    timestamp: new Date('2019-07-10T09:45:00'),
  },
  {
    id: 'efm6',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Let\'s be careful here. Flight logs alone don\'t prove wrongdoing. We need to correlate with property records for the island and testimony about what happened at destinations.',
    type: 'text',
    timestamp: new Date('2019-07-10T10:02:00'),
  },
  {
    id: 'efm7',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'Agreed. But the pattern is clear - flights to USVI, New Mexico ranch, Paris apartment. All locations where abuse is documented. The flights establish presence.',
    type: 'text',
    timestamp: new Date('2019-07-10T10:23:00'),
  },
  {
    id: 'efm8',
    authorId: 'system',
    authorName: 'System',
    content: 'Sarah Chen uploaded: Epstein_Flight_Logs_Complete_1995-2019.xlsx',
    type: 'system',
    timestamp: new Date('2019-07-10T10:30:00'),
  },
  {
    id: 'efm9',
    authorId: 'james-mitchell',
    authorName: 'James Mitchell',
    content: 'I\'ve been mapping the Little St. James island development. Satellite imagery shows construction of additional structures starting in 1998 - during the period of heaviest flight activity.',
    type: 'text',
    timestamp: new Date('2019-07-10T11:15:00'),
  },
  {
    id: 'efm10',
    authorId: 'system',
    authorName: 'System',
    content: 'James Mitchell uploaded: Little_St_James_Satellite_Analysis_1995-2019.zip',
    type: 'system',
    timestamp: new Date('2019-07-10T11:18:00'),
  },
  {
    id: 'efm11',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The 2008 plea deal is central to this. Acosta gave immunity to "any potential co-conspirators." That language was designed to protect everyone on these flight logs.',
    type: 'text',
    timestamp: new Date('2019-07-10T13:05:00'),
    isPinned: true,
  },
  {
    id: 'efm12',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'Julie K. Brown\'s reporting confirmed the victims were never notified of the plea deal - a violation of the Crime Victims Rights Act. That\'s now being litigated.',
    type: 'text',
    timestamp: new Date('2019-07-10T13:28:00'),
  },
  {
    id: 'efm13',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'We need to document everyone who benefited from that immunity. Cross-reference the flight logs with the sealed court documents from Virginia Giuffre\'s cases.',
    type: 'text',
    timestamp: new Date('2019-07-10T14:45:00'),
  },
  {
    id: 'efm14',
    authorId: 'james-mitchell',
    authorName: 'James Mitchell',
    content: 'Working on it. There are 167 names in the sealed documents according to court records. I\'m building a database to correlate with flight passengers and known associates.',
    type: 'text',
    timestamp: new Date('2019-07-10T15:30:00'),
  },
  {
    id: 'efm15',
    authorId: 'nina-patel',
    authorName: 'Nina Patel',
    content: 'Also important: Ghislaine Maxwell\'s role. She\'s on more flights than almost anyone. Every victim describes her as the recruiter and handler.',
    type: 'text',
    timestamp: new Date('2019-07-10T16:12:00'),
  },
  {
    id: 'efm16',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Maxwell disappeared after Epstein\'s arrest. We should track her last known locations and any property holdings.',
    type: 'text',
    timestamp: new Date('2019-07-10T16:45:00'),
  },
  {
    id: 'efm17',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'Breaking: Just heard Epstein was found unconscious in his cell. Suspicious circumstances. We need to preserve everything we have - there may be efforts to destroy evidence.',
    type: 'text',
    timestamp: new Date('2019-07-23T19:30:00'),
    isPinned: true,
  },
];

const epsteinFlightEvidence: Evidence[] = [
  {
    id: 'efe1',
    title: 'Complete Flight Logs (1995-2019)',
    description: 'FAA records and pilot logs for all Epstein aircraft including passenger manifests',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'FAA Records / Court Subpoena',
    addedAt: new Date('2019-07-10'),
    addedBy: 'sarah-chen',
    addedByName: 'Sarah Chen',
    tags: ['Flight Logs', 'Passengers', 'Lolita Express'],
    connections: ['efe2', 'efe3'],
    verifiedBy: ['marcus-rivera', 'james-mitchell'],
    position: { x: 100, y: 100 },
  },
  {
    id: 'efe2',
    title: 'Little St. James Satellite Analysis',
    description: 'Time-series satellite imagery showing island development and activity',
    type: 'image',
    category: 'supporting',
    verificationStatus: 'verified',
    source: 'Commercial Satellite Providers / USGS',
    addedAt: new Date('2019-07-10'),
    addedBy: 'james-mitchell',
    addedByName: 'James Mitchell',
    tags: ['Satellite', 'Island', 'Construction'],
    connections: ['efe1'],
    position: { x: 300, y: 150 },
  },
  {
    id: 'efe3',
    title: '2008 Plea Agreement Analysis',
    description: 'Legal analysis of non-prosecution agreement and immunity provisions',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'Southern District of Florida Court Records',
    addedAt: new Date('2019-07-10'),
    addedBy: 'marcus-rivera',
    addedByName: 'Marcus Rivera',
    tags: ['Plea Deal', 'Acosta', 'Immunity'],
    connections: ['efe1', 'efe4'],
    verifiedBy: ['nina-patel'],
    position: { x: 200, y: 300 },
  },
  {
    id: 'efe4',
    title: 'Victim Testimony Correlation',
    description: 'Cross-reference of victim statements with flight records and locations',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'Miami Herald Investigation / Court Depositions',
    addedAt: new Date('2019-07-12'),
    addedBy: 'nina-patel',
    addedByName: 'Nina Patel',
    tags: ['Victims', 'Testimony', 'Locations'],
    connections: ['efe1', 'efe3'],
    position: { x: 400, y: 250 },
  },
];

// ==================== WORKSPACE 7: JANUARY 6 COMMAND STRUCTURE ====================
const jan6CommandMessages: WorkspaceMessage[] = [
  {
    id: 'j6m1',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'The House Committee just released new documents. The coordination between Trump\'s inner circle and militia groups is more direct than we thought.',
    type: 'text',
    timestamp: new Date('2022-06-15T09:00:00'),
    isPinned: true,
  },
  {
    id: 'j6m2',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'I\'ve been analyzing the encrypted Signal messages recovered from Proud Boys leadership. They were explicitly waiting for Trump\'s signal. The phrase "stand back and stand by" was understood as an activation code.',
    type: 'text',
    timestamp: new Date('2022-06-15T09:23:00'),
  },
  {
    id: 'j6m3',
    authorId: 'alex-reyes',
    authorName: 'Alex Reyes',
    content: 'My source within DOJ says they\'re building seditious conspiracy charges against Tarrio and Rhodes. The evidence of pre-planning is overwhelming.',
    type: 'text',
    timestamp: new Date('2022-06-15T09:45:00'),
  },
  {
    id: 'j6m4',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The Eastman memos are key. He laid out the exact plan to use Pence to reject electoral votes. This wasn\'t a spontaneous riot - it was a coordinated coup attempt.',
    type: 'text',
    timestamp: new Date('2022-06-15T10:12:00'),
  },
  {
    id: 'j6m5',
    authorId: 'system',
    authorName: 'System',
    content: 'David Kim uploaded: Proud_Boys_Signal_Messages_Analysis.pdf',
    type: 'system',
    timestamp: new Date('2022-06-15T10:15:00'),
  },
  {
    id: 'j6m6',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'The timeline is critical. Trump knew by December 14 that he had lost. Everything after that was obstruction. The fake electors scheme was already in motion by December 6.',
    type: 'text',
    timestamp: new Date('2022-06-15T10:45:00'),
  },
  {
    id: 'j6m7',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'Cassidy Hutchinson\'s testimony is explosive. Trump knew the crowd was armed ("they\'re not here to hurt me") and still directed them to march to the Capitol.',
    type: 'text',
    timestamp: new Date('2022-06-28T15:30:00'),
    isPinned: true,
  },
  {
    id: 'j6m8',
    authorId: 'alex-reyes',
    authorName: 'Alex Reyes',
    content: 'The Secret Service deleted their text messages from January 5-6. That\'s consciousness of guilt. We need to document what we know about the missing communications.',
    type: 'text',
    timestamp: new Date('2022-07-01T09:00:00'),
  },
  {
    id: 'j6m9',
    authorId: 'david-kim',
    authorName: 'David Kim',
    content: 'I\'ve mapped the command structure. At the top: Trump, Meadows, Giuliani, Eastman. Below them: Stone connected to Proud Boys, Flynn connected to Oath Keepers. The "war room" at Willard Hotel was the operational hub.',
    type: 'text',
    timestamp: new Date('2022-07-01T11:23:00'),
  },
  {
    id: 'j6m10',
    authorId: 'system',
    authorName: 'System',
    content: 'David Kim uploaded: J6_Command_Structure_Network_Map.png',
    type: 'system',
    timestamp: new Date('2022-07-01T11:25:00'),
  },
  {
    id: 'j6m11',
    authorId: 'sarah-chen',
    authorName: 'Sarah Chen',
    content: 'The 187 minutes of inaction is damning. Trump watched the violence on TV and refused to act. Aides begged him to call off the mob. He enjoyed watching it.',
    type: 'text',
    timestamp: new Date('2022-07-21T14:00:00'),
  },
  {
    id: 'j6m12',
    authorId: 'michael-brooks',
    authorName: 'Dr. Michael Brooks',
    content: 'Important context: The National Guard request was delayed for hours. Someone in the chain of command blocked deployment. The Pentagon is stonewalling on who made that call.',
    type: 'text',
    timestamp: new Date('2022-07-21T14:34:00'),
  },
  {
    id: 'j6m13',
    authorId: 'marcus-rivera',
    authorName: 'Marcus Rivera',
    content: 'DOJ has now charged over 900 people. Seditious conspiracy convictions for Proud Boys and Oath Keepers leadership. But the question remains: will they charge Trump?',
    type: 'text',
    timestamp: new Date('2023-05-05T10:00:00'),
  },
  {
    id: 'j6m14',
    authorId: 'alex-reyes',
    authorName: 'Alex Reyes',
    content: 'Jack Smith is moving fast. Target letters have gone out. My sources say an indictment is imminent.',
    type: 'text',
    timestamp: new Date('2023-07-15T16:00:00'),
  },
  {
    id: 'j6m15',
    authorId: 'system',
    authorName: 'System',
    content: 'BREAKING: Trump indicted on 4 counts related to January 6. Conspiracy to defraud the United States, obstruction, conspiracy against rights.',
    type: 'system',
    timestamp: new Date('2023-08-01T19:30:00'),
    isPinned: true,
  },
];

const jan6Evidence: Evidence[] = [
  {
    id: 'j6e1',
    title: 'Eastman Coup Memos',
    description: 'Legal memoranda outlining strategy to use VP Pence to overturn election',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'January 6 Committee / Court Records',
    addedAt: new Date('2022-06-15'),
    addedBy: 'sarah-chen',
    addedByName: 'Sarah Chen',
    tags: ['Eastman', 'Coup', 'Legal Strategy'],
    connections: ['j6e2', 'j6e3'],
    verifiedBy: ['marcus-rivera', 'michael-brooks'],
    position: { x: 100, y: 100 },
  },
  {
    id: 'j6e2',
    title: 'Proud Boys Signal Communications',
    description: 'Encrypted messaging showing coordination and references to Trump signals',
    type: 'document',
    category: 'verified',
    verificationStatus: 'verified',
    source: 'DOJ Evidence / Trial Exhibits',
    addedAt: new Date('2022-06-15'),
    addedBy: 'david-kim',
    addedByName: 'David Kim',
    tags: ['Proud Boys', 'Communications', 'Coordination'],
    connections: ['j6e1', 'j6e4'],
    position: { x: 300, y: 150 },
  },
  {
    id: 'j6e3',
    title: 'Hutchinson Testimony Transcript',
    description: 'Complete transcript of Cassidy Hutchinson\'s testimony including limo incident',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'January 6 Committee Hearing',
    addedAt: new Date('2022-06-28'),
    addedBy: 'marcus-rivera',
    addedByName: 'Marcus Rivera',
    tags: ['Hutchinson', 'Testimony', 'White House'],
    connections: ['j6e1'],
    position: { x: 200, y: 300 },
  },
  {
    id: 'j6e4',
    title: 'Command Structure Network Map',
    description: 'Visual mapping of relationships between Trump inner circle and militia groups',
    type: 'image',
    category: 'supporting',
    verificationStatus: 'verified',
    source: 'Investigative Analysis',
    addedAt: new Date('2022-07-01'),
    addedBy: 'david-kim',
    addedByName: 'David Kim',
    tags: ['Network', 'Structure', 'Coordination'],
    connections: ['j6e1', 'j6e2'],
    position: { x: 400, y: 250 },
  },
  {
    id: 'j6e5',
    title: 'Trump J6 Federal Indictment',
    description: '45-page indictment charging Trump with conspiracy and obstruction',
    type: 'document',
    category: 'primary',
    verificationStatus: 'verified',
    source: 'Department of Justice',
    addedAt: new Date('2023-08-01'),
    addedBy: 'marcus-rivera',
    addedByName: 'Marcus Rivera',
    tags: ['Indictment', 'Trump', 'DOJ'],
    connections: ['j6e1', 'j6e3'],
    position: { x: 250, y: 450 },
  },
];

// Export all extended workspaces
export const extendedWorkspaces: Workspace[] = [
  // Workspace 5: Trump-Russia Money Trail
  {
    id: 'ws5',
    name: 'Trump-Russia Financial Investigation',
    description: 'Comprehensive analysis of financial connections between Trump Organization, Deutsche Bank, Russian oligarchs, and Kremlin-linked entities. Tracing money flows and documenting patterns of potential money laundering.',
    investigation: 'trump-russia',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2017-06-01'),
    updatedAt: new Date('2024-01-15'),
    createdBy: 'sarah-chen',
    members: getTeam('sarah-chen', 'rachel-torres', 'mira-novak', 'david-kim', 'marcus-rivera', 'alex-reyes'),
    messages: trumpRussiaMessages,
    evidence: trumpRussiaEvidence,
    documents: trumpRussiaDocuments,
    timeline: trumpRussiaTimeline,
    tasks: trumpRussiaTasks,
    tags: ['Trump', 'Russia', 'Deutsche Bank', 'Money Laundering', 'Financial Crimes'],
    isPublic: false,
    viewCount: 8934,
    lastActivity: new Date('2024-01-15'),
    milestones: [
      { id: 'trms1', title: 'Deutsche Bank Records Obtained', description: 'Secured complete loan documentation', isCompleted: true, completedAt: new Date('2017-08-10') },
      { id: 'trms2', title: 'Trump Tower Moscow LOI Verified', description: 'Authenticated the letter of intent', isCompleted: true, completedAt: new Date('2017-08-14') },
      { id: 'trms3', title: 'Money Flow Analysis Complete', description: 'Mapped all financial connections', isCompleted: true, completedAt: new Date('2018-03-01') },
      { id: 'trms4', title: 'Source Network Developed', description: 'Established contacts in relevant institutions', isCompleted: false },
    ],
  },
  // Workspace 6: Epstein Flight Log Analysis
  {
    id: 'ws6',
    name: 'Epstein Network Flight Analysis',
    description: 'Systematic analysis of Jeffrey Epstein\'s flight records, passenger manifests, and property visits. Cross-referencing with victim testimony and sealed court documents.',
    investigation: 'epstein-network',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2019-07-01'),
    updatedAt: new Date('2024-02-10'),
    createdBy: 'sarah-chen',
    members: getTeam('sarah-chen', 'james-mitchell', 'nina-patel', 'marcus-rivera'),
    messages: epsteinFlightMessages,
    evidence: epsteinFlightEvidence,
    documents: [
      {
        id: 'efd1',
        name: 'Epstein_Flight_Logs_Complete_1995-2019.xlsx',
        type: 'application/vnd.ms-excel',
        size: 5678901,
        url: '#',
        uploadedBy: 'sarah-chen',
        uploadedByName: 'Sarah Chen',
        uploadedAt: new Date('2019-07-10'),
        folder: 'Flight Records',
        category: 'Flight Records',
        description: 'Complete flight log compilation with passenger manifests',
        downloads: 1247,
        isPublic: false,
      },
      {
        id: 'efd2',
        name: 'Little_St_James_Satellite_Analysis_1995-2019.zip',
        type: 'application/zip',
        size: 234567890,
        url: '#',
        uploadedBy: 'james-mitchell',
        uploadedByName: 'James Mitchell',
        uploadedAt: new Date('2019-07-10'),
        folder: 'Visual Evidence',
        category: 'Visual Evidence',
        description: 'Satellite imagery package for island analysis',
        downloads: 456,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'eft1', date: new Date('1995-01-01'), title: 'Flight Operations Begin', description: 'Epstein begins using private aircraft for travel', evidenceIds: ['efe1'], addedBy: 'sarah-chen', importance: 'major' },
      { id: 'eft2', date: new Date('1998-06-01'), title: 'Island Development Expands', description: 'Major construction begins on Little St. James', evidenceIds: ['efe2'], addedBy: 'james-mitchell', importance: 'major' },
      { id: 'eft3', date: new Date('2008-06-30'), title: 'Plea Deal Signed', description: 'Acosta approves sweetheart deal with immunity clause', evidenceIds: ['efe3'], addedBy: 'marcus-rivera', importance: 'major' },
      { id: 'eft4', date: new Date('2019-07-06'), title: 'Epstein Arrested', description: 'Arrested on federal sex trafficking charges', evidenceIds: [], addedBy: 'sarah-chen', importance: 'major' },
      { id: 'eft5', date: new Date('2019-08-10'), title: 'Epstein Found Dead', description: 'Found dead in cell under suspicious circumstances', evidenceIds: [], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [
      { id: 'eftask1', title: 'Complete passenger database', description: 'Build comprehensive database of all flight passengers', assignedTo: ['sarah-chen'], status: 'completed', priority: 'critical', createdBy: 'marcus-rivera', createdAt: new Date('2019-07-05'), completedAt: new Date('2019-07-10') },
      { id: 'eftask2', title: 'Correlate with victim testimony', description: 'Match flight dates with victim accounts', assignedTo: ['nina-patel'], status: 'completed', priority: 'high', createdBy: 'sarah-chen', createdAt: new Date('2019-07-08'), completedAt: new Date('2019-07-15') },
      { id: 'eftask3', title: 'Track Maxwell locations', description: 'Document Ghislaine Maxwell movements post-arrest', assignedTo: ['james-mitchell'], status: 'in-progress', priority: 'high', createdBy: 'marcus-rivera', createdAt: new Date('2019-08-15') },
    ],
    tags: ['Epstein', 'Flight Logs', 'Sex Trafficking', 'Maxwell', 'Island'],
    isPublic: false,
    viewCount: 15678,
    lastActivity: new Date('2024-02-10'),
    milestones: [
      { id: 'efms1', title: 'Flight Logs Compiled', description: 'Complete 1995-2019 flight record compilation', isCompleted: true, completedAt: new Date('2019-07-10') },
      { id: 'efms2', title: 'Victim Correlation Complete', description: 'Cross-referenced with all known victim statements', isCompleted: true, completedAt: new Date('2019-09-01') },
      { id: 'efms3', title: 'Sealed Documents Analysis', description: 'Awaiting release of additional sealed materials', isCompleted: false },
    ],
  },
  // Workspace 7: January 6 Command Structure
  {
    id: 'ws7',
    name: 'January 6 Command Structure Analysis',
    description: 'Mapping the coordination between Trump\'s inner circle, militia groups, and the planning of the Capitol attack. Documenting the seditious conspiracy from rally to riot.',
    investigation: 'january-6-insurrection',
    status: 'active',
    priority: 'critical',
    visibility: 'private',
    createdAt: new Date('2021-01-07'),
    updatedAt: new Date('2024-02-15'),
    createdBy: 'marcus-rivera',
    members: getTeam('marcus-rivera', 'sarah-chen', 'david-kim', 'alex-reyes', 'michael-brooks'),
    messages: jan6CommandMessages,
    evidence: jan6Evidence,
    documents: [
      {
        id: 'j6d1',
        name: 'Proud_Boys_Signal_Messages_Analysis.pdf',
        type: 'application/pdf',
        size: 3456789,
        url: '#',
        uploadedBy: 'david-kim',
        uploadedByName: 'David Kim',
        uploadedAt: new Date('2022-06-15'),
        folder: 'Communications',
        category: 'Communications',
        description: 'Analysis of Proud Boys encrypted communications',
        downloads: 567,
        isPublic: false,
      },
      {
        id: 'j6d2',
        name: 'J6_Command_Structure_Network_Map.png',
        type: 'image/png',
        size: 12345678,
        url: '#',
        uploadedBy: 'david-kim',
        uploadedByName: 'David Kim',
        uploadedAt: new Date('2022-07-01'),
        folder: 'Analysis',
        category: 'Visual Analysis',
        description: 'Network visualization of command structure',
        downloads: 892,
        isPublic: false,
      },
    ],
    timeline: [
      { id: 'j6t1', date: new Date('2020-09-29'), title: '"Stand Back and Stand By"', description: 'Trump issues coded message to Proud Boys during debate', evidenceIds: ['j6e2'], addedBy: 'david-kim', importance: 'major' },
      { id: 'j6t2', date: new Date('2020-12-14'), title: 'Fake Electors Convene', description: 'Fraudulent electors meet in 7 states', evidenceIds: [], addedBy: 'michael-brooks', importance: 'major' },
      { id: 'j6t3', date: new Date('2021-01-04'), title: 'Willard Hotel War Room', description: 'Trump allies establish command center', evidenceIds: ['j6e4'], addedBy: 'alex-reyes', importance: 'major' },
      { id: 'j6t4', date: new Date('2021-01-06'), title: 'Capitol Attack', description: 'Coordinated assault on U.S. Capitol', evidenceIds: ['j6e1', 'j6e2', 'j6e3'], addedBy: 'marcus-rivera', importance: 'major' },
      { id: 'j6t5', date: new Date('2023-08-01'), title: 'Trump Indicted', description: 'Federal indictment on 4 counts', evidenceIds: ['j6e5'], addedBy: 'marcus-rivera', importance: 'major' },
    ],
    tasks: [
      { id: 'j6task1', title: 'Map militia coordination', description: 'Document links between Trump team and militia leaders', assignedTo: ['david-kim'], status: 'completed', priority: 'critical', createdBy: 'marcus-rivera', createdAt: new Date('2021-01-10'), completedAt: new Date('2022-07-01') },
      { id: 'j6task2', title: 'Track deleted Secret Service texts', description: 'Document the deletion and recovery efforts', assignedTo: ['alex-reyes'], status: 'in-progress', priority: 'high', createdBy: 'sarah-chen', createdAt: new Date('2022-07-15') },
    ],
    tags: ['January 6', 'Insurrection', 'Proud Boys', 'Oath Keepers', 'Trump', 'Sedition'],
    isPublic: false,
    viewCount: 23456,
    lastActivity: new Date('2024-02-15'),
    milestones: [
      { id: 'j6ms1', title: 'Command Structure Mapped', description: 'Complete network analysis of coup participants', isCompleted: true, completedAt: new Date('2022-07-01') },
      { id: 'j6ms2', title: 'Committee Evidence Reviewed', description: 'Analyzed all public January 6 Committee materials', isCompleted: true, completedAt: new Date('2022-12-20') },
      { id: 'j6ms3', title: 'Trial Documentation', description: 'Track all related criminal proceedings', isCompleted: false },
    ],
  },
];

// Export investigators for use in other workspaces
export { investigators, getTeam };
