// ═══════════════════════════════════════════════════════════════════
//  ARKHIVE SWARM INTELLIGENCE — BOT FACTORY
//  Self-replication: the swarm spawns its own specialized agents
// ═══════════════════════════════════════════════════════════════════

const fs = require('fs');
const path = require('path');
const { fork } = require('child_process');
const config = require('./config');
const logger = require('./logger').child('FACTORY');
const utils = require('./utils');

class BotFactory {
  constructor() {
    this.spawnedBots = new Map(); // botId -> { process, type, spawnedAt, status }
    this.spawnCount = 0;
    this.lastSpawnTime = 0;
    this.lastNetworkSpawn = 0; // throttle repeated network-weaver spawns
  }

  /**
   * Evaluate whether to spawn a new specialized bot
   * Called by the daemon based on swarm conditions
   */
  async evaluate(swarmStatus) {
    if (!config.replication.enabled) return;
    if (this.spawnedBots.size >= config.replication.maxSpawnedBots) return;
    if (Date.now() - this.lastSpawnTime < config.replication.spawnCooldown) return;

    const rules = config.replication.autoSpawnRules;
    const scanStats = swarmStatus.scanner || {};

    // Check each specialization rule
    for (const [type, rule] of Object.entries(rules)) {
      if (this._hasActiveBot(type)) continue;

      let shouldSpawn = false;

      switch (type) {
        case 'link-validator':
          shouldSpawn = (scanStats.totalBrokenLinks || 0) > 50;
          break;
        case 'network-weaver':
          // only spawn if enough orphans and network-weaver hasn't run recently
          const now = Date.now();
          const nwCooldown = 60 * 60 * 1000; // 1 hour
          if ((scanStats.totalOrphans || 0) > 20 && now - this.lastNetworkSpawn > nwCooldown) {
            shouldSpawn = true;
          }
          break;
        case 'quality-checker':
          shouldSpawn = (swarmStatus.stats?.totalTasksFailed || 0) > 10;
          break;
        case 'stub-seeder':
          shouldSpawn = (scanStats.totalMissing || 0) > 100;
          break;
        case 'source-hunter':
          shouldSpawn = (scanStats.totalSparse || 0) > 50;
          break;
        case 'timeline-builder':
          shouldSpawn = (scanStats.totalSparse || 0) > 30;
          break;
      }

      if (shouldSpawn) {
        await this.spawn(type);
      }
    }
  }

  /**
   * Spawn a specialized bot
   */
  async spawn(type) {
    if (this.spawnedBots.size >= config.replication.maxSpawnedBots) {
      logger.warn(`Cannot spawn ${type}: max spawned bots reached (${config.replication.maxSpawnedBots})`);
      return null;
    }

    // track network-weaver spawn time for cooldown logic
    if (type === 'network-weaver') {
      this.lastNetworkSpawn = Date.now();
    }

    this.spawnCount++;
    const botId = `SB-${type}-${this.spawnCount}`;

    logger.spawn(`Spawning specialized bot: ${botId}`);

    // Generate the bot script
    const scriptPath = this._getOrCreateBotScript(type);
    if (!scriptPath) {
      logger.error(`No script available for bot type: ${type}`);
      return null;
    }

    const child = fork(scriptPath, [], {
      env: { ...process.env, BOT_ID: botId, BOT_TYPE: type },
      stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
    });

    const botInfo = {
      process: child,
      id: botId,
      type,
      pid: child.pid,
      status: 'running',
      spawnedAt: Date.now(),
      tasksCompleted: 0,
    };

    this.spawnedBots.set(botId, botInfo);
    this.lastSpawnTime = Date.now();

    // Forward output
    child.stdout?.on('data', (data) => process.stdout.write(data));
    child.stderr?.on('data', (data) => process.stderr.write(data));

    // Handle IPC
    child.on('message', (msg) => {
      if (msg.type === 'complete') {
        botInfo.tasksCompleted = msg.tasksCompleted || 0;
        botInfo.status = 'completed';
        logger.spawn(`Bot ${botId} completed: ${msg.summary || 'no summary'}`);
      }
    });

    // Handle exit
    child.on('exit', (code) => {
      logger.spawn(`Bot ${botId} exited (code: ${code})`);
      this.spawnedBots.delete(botId);
    });

    return botId;
  }

  /**
   * Get or create the script file for a specialized bot type
   */
  _getOrCreateBotScript(type) {
    const scriptPath = path.join(config.paths.spawned, `${type}.js`);

    // If script already exists, use it
    if (fs.existsSync(scriptPath)) return scriptPath;

    // Generate the specialized bot script
    const script = this._generateBotScript(type);
    if (!script) return null;

    fs.writeFileSync(scriptPath, script);
    logger.spawn(`Generated bot script: ${type}.js`);

    return scriptPath;
  }

  /**
   * Generate a specialized bot script for the given type
   */
  _generateBotScript(type) {
    const header = `// Auto-generated by ArkHive Bot Factory
// Type: ${type}
// Generated: ${new Date().toISOString()}
const path = require('path');
const fs = require('fs');
const config = require(path.join(__dirname, '..', 'config'));
const { Logger } = require(path.join(__dirname, '..', 'logger'));
const utils = require(path.join(__dirname, '..', 'utils'));
const botId = process.env.BOT_ID || '${type}';
const log = new Logger('BOT-' + botId);
`;

    switch (type) {
      case 'link-validator':
        return `${header}
// Link Validator Bot: checks all source URLs and known associate hrefs
async function run() {
  log.info('Link Validator bot starting...');
  const content = utils.readFileSafe(config.paths.individuals);
  if (!content) { log.error('Cannot read individuals file'); process.exit(1); }

  const urlRegex = /url:\\s*'(https?:\\/\\/[^']+)'/g;
  const urls = [];
  let match;
  while ((match = urlRegex.exec(content)) !== null) {
    urls.push(match[1]);
  }

  log.info('Found ' + urls.length + ' URLs to validate');
  let broken = 0;
  let checked = 0;

  // Check URLs in batches of 10
  for (let i = 0; i < urls.length; i += 10) {
    const batch = urls.slice(i, i + 10);
    const results = await Promise.allSettled(
      batch.map(url => checkUrl(url))
    );

    for (let j = 0; j < results.length; j++) {
      checked++;
      if (results[j].status === 'rejected' || (results[j].value && !results[j].value.ok)) {
        broken++;
        log.warn('Broken URL: ' + batch[j]);
      }
    }

    if (checked % 100 === 0) {
      log.info('Checked ' + checked + '/' + urls.length + ' (' + broken + ' broken)');
    }
  }

  log.info('Link validation complete: ' + checked + ' checked, ' + broken + ' broken');

  if (process.send) {
    process.send({ type: 'complete', tasksCompleted: checked, summary: checked + ' URLs checked, ' + broken + ' broken' });
  }
}

function checkUrl(url) {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith('https') ? require('https') : require('http');
    const req = lib.request(url, { method: 'HEAD', timeout: 10000 }, (res) => {
      resolve({ ok: res.statusCode < 400, status: res.statusCode });
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('timeout')); });
    req.end();
  });
}

run().catch(e => { log.error('Bot crashed: ' + e.message); process.exit(1); });
`;

      case 'network-weaver':
        return `${header}
// Network Weaver Bot: maps entity connections and creates cross-links
async function run() {
  log.info('Network Weaver bot starting...');
  const shardManager = require(path.join(__dirname, '..', 'shard-manager'));
  let content;
  if (shardManager.isActive()) {
    content = shardManager.getCombinedContent();
    log.info('Reading from sharded individual files');
  } else {
    content = utils.readFileSafe(config.paths.individuals);
  }
  if (!content) { log.error('Cannot read individuals data'); process.exit(1); }

  const slugs = utils.extractExistingIndividualSlugs(content);
  const associates = utils.extractKnownAssociateLinks(content);

  // Build adjacency graph
  const graph = new Map();
  for (const [slug, data] of associates) {
    if (!graph.has(slug)) graph.set(slug, new Set());
    for (const ref of data.referencedBy) {
      graph.get(slug).add(ref);
      if (!graph.has(ref)) graph.set(ref, new Set());
      graph.get(ref).add(slug);
    }
  }

  // Find clusters
  const visited = new Set();
  const clusters = [];
  for (const [slug] of graph) {
    if (visited.has(slug)) continue;
    const cluster = [];
    const stack = [slug];
    while (stack.length > 0) {
      const current = stack.pop();
      if (visited.has(current)) continue;
      visited.add(current);
      cluster.push(current);
      for (const neighbor of (graph.get(current) || [])) {
        if (!visited.has(neighbor)) stack.push(neighbor);
      }
    }
    clusters.push(cluster);
  }

  log.info('Network analysis: ' + graph.size + ' nodes, ' + clusters.length + ' clusters');
  log.info('Largest cluster: ' + Math.max(...clusters.map(c => c.length)) + ' entities');

  // Save network report
  const report = {
    nodes: graph.size,
    clusters: clusters.length,
    largestCluster: Math.max(...clusters.map(c => c.length)),
    isolatedNodes: clusters.filter(c => c.length === 1).length,
    generatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(config.paths.logs, 'network-report.json'), JSON.stringify(report, null, 2));

  if (process.send) {
    process.send({ type: 'complete', tasksCompleted: graph.size, summary: graph.size + ' nodes mapped, ' + clusters.length + ' clusters' });
  }
}

run().catch(e => { log.error('Bot crashed: ' + e.message); process.exit(1); });
`;

      case 'quality-checker':
        return `${header}
// Quality Checker Bot: audits profile completeness and data quality
async function run() {
  log.info('Quality Checker bot starting...');
  const content = utils.readFileSafe(config.paths.individuals);
  if (!content) { log.error('Cannot read individuals file'); process.exit(1); }

  const slugs = utils.extractExistingIndividualSlugs(content);
  log.info('Auditing ' + slugs.length + ' profiles...');

  const issues = [];
  let audited = 0;

  for (const slug of slugs) {
    // Find profile block boundaries
    const start = content.indexOf("'" + slug + "': {");
    if (start === -1) continue;

    const chunk = content.substring(start, start + 5000);

    // Check for required fields
    const profileIssues = [];

    if (!/description:\\s*'/.test(chunk)) profileIssues.push('missing description');
    if (/description:\\s*''/.test(chunk)) profileIssues.push('empty description');
    if (/controversies:\\s*\\[\\s*\\]/.test(chunk)) profileIssues.push('empty controversies');
    if (/sources:\\s*\\[\\s*\\]/.test(chunk)) profileIssues.push('empty sources');
    if (/knownAssociates:\\s*\\[\\s*\\]/.test(chunk)) profileIssues.push('no known associates');
    if (/timeline:\\s*\\[\\s*\\]/.test(chunk)) profileIssues.push('empty timeline');

    if (profileIssues.length > 0) {
      issues.push({ slug, issues: profileIssues });
    }

    audited++;
    if (audited % 200 === 0) {
      log.info('Audited ' + audited + '/' + slugs.length + ' (' + issues.length + ' with issues)');
    }
  }

  log.info('Quality audit complete: ' + audited + ' audited, ' + issues.length + ' with issues');

  // Save audit report
  const report = {
    audited,
    withIssues: issues.length,
    cleanRate: ((audited - issues.length) / audited * 100).toFixed(1) + '%',
    issues: issues.slice(0, 100),
    generatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(config.paths.logs, 'quality-report.json'), JSON.stringify(report, null, 2));

  if (process.send) {
    process.send({ type: 'complete', tasksCompleted: audited, summary: audited + ' audited, ' + issues.length + ' issues found' });
  }
}

run().catch(e => { log.error('Bot crashed: ' + e.message); process.exit(1); });
`;

      case 'stub-seeder':
        return `${header}
// Stub Seeder Bot: creates minimal profile stubs for missing entities
async function run() {
  log.info('Stub Seeder bot starting...');
  const content = utils.readFileSafe(config.paths.individuals);
  if (!content) { log.error('Cannot read individuals file'); process.exit(1); }

  const existingSlugs = new Set(utils.extractExistingIndividualSlugs(content));
  const associates = utils.extractKnownAssociateLinks(content);

  // Find missing profiles
  const missing = [];
  for (const [slug, data] of associates) {
    if (!existingSlugs.has(slug)) {
      missing.push({ slug, ...data });
    }
  }

  log.info('Found ' + missing.length + ' missing profiles — generating stubs');

  // Generate and save stubs to generated directory
  let generated = 0;
  for (const entry of missing) {
    const profile = utils.generateProfileTemplate(entry.slug, {
      name: entry.name,
      referencedBy: entry.referencedBy,
      relationships: entry.relationships,
    });

    const outPath = path.join(config.paths.generated, entry.slug + '.json');
    fs.writeFileSync(outPath, JSON.stringify(profile, null, 2));
    generated++;
  }

  log.info('Generated ' + generated + ' stub profiles');

  if (process.send) {
    process.send({ type: 'complete', tasksCompleted: generated, summary: generated + ' stubs generated' });
  }
}

run().catch(e => { log.error('Bot crashed: ' + e.message); process.exit(1); });
`;

      case 'source-hunter':
        return `${header}
// Source Hunter Bot: finds and suggests sources for sparse profiles
async function run() {
  log.info('Source Hunter bot starting...');
  // This bot identifies profiles that need better sourcing
  const content = utils.readFileSafe(config.paths.individuals);
  if (!content) process.exit(1);

  const slugs = utils.extractExistingIndividualSlugs(content);
  const needsSources = [];

  for (const slug of slugs) {
    const start = content.indexOf("'" + slug + "': {");
    if (start === -1) continue;
    const chunk = content.substring(start, start + 3000);

    // Count sources
    const sourceMatches = chunk.match(/url:\\s*'/g);
    const sourceCount = sourceMatches ? sourceMatches.length : 0;

    if (sourceCount < 3) {
      needsSources.push({ slug, name: utils.slugToName(slug), currentSources: sourceCount });
    }
  }

  log.info('Found ' + needsSources.length + ' profiles needing more sources');

  const report = {
    total: needsSources.length,
    profiles: needsSources.slice(0, 200),
    generatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(config.paths.logs, 'source-report.json'), JSON.stringify(report, null, 2));

  if (process.send) {
    process.send({ type: 'complete', tasksCompleted: needsSources.length, summary: needsSources.length + ' profiles need sources' });
  }
}

run().catch(e => { log.error('Bot crashed: ' + e.message); process.exit(1); });
`;

      case 'timeline-builder':
        return `${header}
// Timeline Builder Bot: constructs chronological event timelines
async function run() {
  log.info('Timeline Builder bot starting...');
  const content = utils.readFileSafe(config.paths.individuals);
  if (!content) process.exit(1);

  const slugs = utils.extractExistingIndividualSlugs(content);
  const needsTimeline = [];

  for (const slug of slugs) {
    const start = content.indexOf("'" + slug + "': {");
    if (start === -1) continue;
    const chunk = content.substring(start, start + 3000);

    if (/timeline:\\s*\\[\\s*\\]/.test(chunk)) {
      needsTimeline.push(slug);
    }
  }

  log.info('Found ' + needsTimeline.length + ' profiles with empty timelines');

  const report = {
    total: needsTimeline.length,
    profiles: needsTimeline.slice(0, 200),
    generatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(path.join(config.paths.logs, 'timeline-report.json'), JSON.stringify(report, null, 2));

  if (process.send) {
    process.send({ type: 'complete', tasksCompleted: needsTimeline.length, summary: needsTimeline.length + ' profiles need timelines' });
  }
}

run().catch(e => { log.error('Bot crashed: ' + e.message); process.exit(1); });
`;

      default:
        return null;
    }
  }

  /**
   * Check if a bot of given type is already active
   */
  _hasActiveBot(type) {
    for (const [, bot] of this.spawnedBots) {
      if (bot.type === type && bot.status === 'running') return true;
    }
    return false;
  }

  /**
   * Kill all spawned bots
   */
  async killAll() {
    logger.spawn(`Killing ${this.spawnedBots.size} spawned bots...`);
    for (const [id, bot] of this.spawnedBots) {
      try {
        bot.process.kill('SIGTERM');
      } catch (_) {}
    }
    this.spawnedBots.clear();
  }

  /**
   * Get status of all spawned bots
   */
  getStatus() {
    return Array.from(this.spawnedBots.entries()).map(([id, bot]) => ({
      id,
      type: bot.type,
      pid: bot.pid,
      status: bot.status,
      uptime: utils.formatDuration(Date.now() - bot.spawnedAt),
      tasksCompleted: bot.tasksCompleted,
    }));
  }
}

module.exports = new BotFactory();
module.exports.BotFactory = BotFactory;
