'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, AlertTriangle, Users, Calendar, FileText, ExternalLink, Scale, ShieldAlert, Skull } from 'lucide-react';
import GlitchText from '@/components/effects/GlitchText';

const investigation = {
  title: 'Vietnam War Crimes',
  subtitle: 'My Lai, Operation Speedy Express, Tiger Force, Phoenix Program, Agent Orange, and the Systematic Slaughter of Millions in America\'s Longest War of Deception',
  severity: 'critical',
  status: 'EXPOSED — ACCOUNTABILITY DENIED',
  summary: 'The Vietnam War was the defining moral catastrophe of 20th-century American foreign policy — a war built on lies, sustained by lies, and concluded in disgrace. From the fabricated Gulf of Tonkin incident that Congress used to authorize military force in 1964, through the systematic deception revealed by the Pentagon Papers in 1971, the United States prosecuted a war that killed an estimated 2 to 3 million Vietnamese civilians, 1.1 million North Vietnamese and Viet Cong fighters, and 58,220 American service members. The war featured some of the most horrific war crimes in modern history: the My Lai Massacre, where U.S. soldiers murdered 504 unarmed civilians including women, children, and infants over four hours; Operation Speedy Express, where the 9th Infantry Division claimed 10,899 "enemy" kills against only 748 weapons recovered — meaning thousands of unarmed civilians were counted as enemy combatants; Tiger Force, a reconnaissance unit that tortured and murdered hundreds of civilians, collected ears and scalps as trophies, and was investigated by the Army for years with no charges filed; and the Phoenix Program, a CIA-directed assassination and torture program that killed between 20,000 and 40,000 suspected Viet Cong sympathizers, many of whom were civilians identified by corrupt local officials with personal grudges. The U.S. dropped more bombs on Vietnam, Laos, and Cambodia than all bombs dropped by all sides in World War II combined — including 388,000 tons of napalm that burned villages and people alive, and 20 million gallons of Agent Orange that poisoned the land, water, and genetic code of millions. Generations of Vietnamese children continue to be born with severe birth defects from dioxin contamination. Of all the war crimes committed, only one soldier — Lt. William Calley — was convicted. He served 3.5 years of house arrest. Henry Kissinger won the Nobel Peace Prize.',
  keyFigures: [
    { name: 'Henry Kissinger', role: 'National Security Advisor and Secretary of State who secretly expanded the war into Cambodia and Laos, orchestrated the carpet bombing of Cambodia that killed an estimated 150,000-500,000 civilians, sabotaged the 1968 Paris Peace Talks to help Nixon win the election, and delayed the war\'s end by four years to serve political interests. Awarded the Nobel Peace Prize in 1973.', href: '/entities/individuals/henry-kissinger', status: 'Deceased (2023) — Never charged' },
    { name: 'Richard Nixon', role: 'President who campaigned on a "secret plan to end the war" while secretly expanding it into Cambodia and Laos. Authorized the illegal bombing of Cambodia (Operation Menu), sabotaged the 1968 peace talks through backchannel communications with South Vietnam (the "Chennault Affair"), and prolonged the war by four years — during which 22,000 additional Americans and hundreds of thousands of Vietnamese died.', href: '/entities/individuals/richard-nixon', status: 'Resigned 1974 — Never charged for war crimes' },
    { name: 'Robert McNamara', role: 'Secretary of Defense (1961-1968) who escalated U.S. involvement from 16,000 advisors to 535,000 combat troops while privately knowing the war was unwinnable. The Pentagon Papers revealed he commissioned a secret study confirming the war could not be won — while publicly insisting victory was imminent. In his 1995 memoir "In Retrospect," he admitted "we were wrong, terribly wrong."', href: '/entities/individuals/robert-mcnamara', status: 'Deceased (2009) — Admitted error' },
    { name: 'Lyndon B. Johnson', role: 'President who used the fabricated Gulf of Tonkin incident to obtain congressional authorization for unlimited military force. Escalated from 16,000 advisors to 535,000 troops. Privately expressed doubts about the war while publicly committing hundreds of thousands of young Americans to fight and die.', href: '/entities/individuals/lyndon-b-johnson', status: 'Deceased (1973)' },
    { name: 'William Westmoreland', role: 'Commander of U.S. forces in Vietnam (1964-1968) who repeatedly demanded more troops, promised victory was near, and systematically underestimated enemy strength to maintain political support. The "Westmoreland v. CBS" trial revealed he had capped enemy estimates at politically acceptable numbers — deceiving the president, Congress, and the public.', href: '/entities/individuals/william-westmoreland', status: 'Deceased (2005) — Never charged' },
    { name: 'William Calley', role: 'Lieutenant who led Charlie Company into My Lai on March 16, 1968, ordering his soldiers to kill every living thing in the village. 504 unarmed civilians — men, women, children, and infants — were systematically murdered over four hours. The only U.S. soldier convicted of any crime in the massacre.', href: '/entities/individuals/william-calley', status: 'Convicted — Served 3.5 years house arrest' },
    { name: 'Ernest Medina', role: 'Captain and Charlie Company commander who gave the orders that led to My Lai. Witnesses testified he instructed troops to "kill everything that moves." Acquitted at court-martial despite overwhelming evidence — the jury bought his claim that he didn\'t know the massacre was happening.', href: '/entities/individuals/ernest-medina', status: 'Acquitted — Died 2018' },
    { name: 'Hugh Thompson Jr.', role: 'Army helicopter pilot who intervened to stop the My Lai massacre by landing his helicopter between American soldiers and fleeing civilians, ordering his crew to fire on U.S. troops if they continued killing. He was initially vilified and received death threats — not recognized as a hero until 30 years later.', href: '/entities/individuals/hugh-thompson-jr', status: 'Deceased (2006) — Belated recognition' },
    { name: 'Samuel Koster', role: 'Major General commanding the Americal Division during My Lai. Suppressed the initial investigation, lied about what happened, and helped cover up the massacre for over a year. Reduced in rank but never prosecuted.', href: '/entities/individuals/samuel-koster', status: 'Demoted — Never prosecuted' },
    { name: 'Colin Powell', role: 'Young Army Major assigned to investigate the initial My Lai allegations in 1968 — his investigation concluded that "relations between American soldiers and the Vietnamese people are excellent," helping to suppress the massacre for another year until Seymour Hersh broke the story.', href: '/entities/individuals/colin-powell', status: 'Deceased (2021)' },
    { name: 'William Colby', role: 'CIA officer who directed the Phoenix Program — a systematic assassination campaign that killed between 20,000 and 40,000 suspected Viet Cong sympathizers. Many victims were civilians identified by corrupt local officials. Later became CIA Director.', href: '/entities/individuals/william-colby', status: 'Deceased (1996)' },
    { name: 'Daniel Ellsberg', role: 'RAND Corporation analyst and former Pentagon official who leaked the 7,000-page Pentagon Papers to the press in 1971 — revealing that four presidential administrations had systematically lied to the public about the war. Charged under the Espionage Act; charges dropped due to government misconduct.', href: '/entities/individuals/daniel-ellsberg', status: 'Deceased (2023) — Charges dropped' },
    { name: 'McGeorge Bundy', role: 'National Security Advisor to Kennedy and Johnson who was one of the principal architects of escalation. Advocated for bombing North Vietnam and committing combat troops while privately harboring doubts about success.', href: '/entities/individuals/mcgeorge-bundy', status: 'Deceased (1996)' },
    { name: 'Dean Rusk', role: 'Secretary of State under Kennedy and Johnson who was one of the most hawkish voices in the administration, consistently advocating for escalation and opposing any compromise with North Vietnam.', href: '/entities/individuals/dean-rusk', status: 'Deceased (1994)' },
    { name: 'Curtis LeMay', role: 'Air Force Chief of Staff who advocated for bombing Vietnam "back to the Stone Age." His strategic bombing doctrine led to the massive aerial campaigns that dropped more tonnage on Vietnam than all of World War II combined.', href: '/entities/individuals/curtis-lemay', status: 'Deceased (1990)' },
    { name: 'Creighton Abrams', role: 'Commander of U.S. forces in Vietnam (1968-1972) who oversaw the "Vietnamization" program and the secret bombing of Cambodia. Under his command, Operation Speedy Express killed thousands of civilians who were counted as enemy combatants.', href: '/entities/individuals/creighton-abrams', status: 'Deceased (1974)' },
    { name: 'Seymour Hersh', role: 'Investigative journalist who broke the My Lai massacre story in November 1969, over a year after it occurred. His reporting — based on interviews with participants — forced the Army to acknowledge the atrocity and won the Pulitzer Prize.', href: '/entities/individuals/seymour-hersh', status: 'Active — Journalist' },
  ],
  timeline: [
    { date: '1955-11-01', event: 'U.S. Military Assistance Advisory Group takes over training of South Vietnamese forces — beginning 20 years of American military involvement in Vietnam' },
    { date: '1961-05-11', event: 'President Kennedy authorizes sending 400 Special Forces troops and 100 additional military advisors to South Vietnam — the first significant escalation beyond Eisenhower-era commitments' },
    { date: '1963-11-02', event: 'South Vietnamese President Ngo Dinh Diem assassinated in CIA-backed coup — the U.S. helped overthrow its own ally, creating political chaos that justified further American intervention' },
    { date: '1964-08-02', event: 'Gulf of Tonkin incident — USS Maddox reports being attacked by North Vietnamese torpedo boats. The second alleged attack on August 4 almost certainly never happened, but is used to obtain congressional authorization for war' },
    { date: '1964-08-07', event: 'Gulf of Tonkin Resolution passes Congress with only 2 dissenting votes — granting the president unlimited authority to use military force in Southeast Asia without a formal declaration of war' },
    { date: '1965-03-02', event: 'Operation Rolling Thunder begins — sustained aerial bombing campaign against North Vietnam that will continue for over three years, dropping 864,000 tons of bombs' },
    { date: '1965-03-08', event: 'First U.S. combat troops — 3,500 Marines — land at Da Nang. Within three years, 535,000 American soldiers will be deployed to Vietnam' },
    { date: '1965-11-14', event: 'Battle of Ia Drang Valley — first major engagement between U.S. and North Vietnamese forces. 234 Americans killed. The battle proves the war will be a long, bloody ground war, not a quick intervention' },
    { date: '1967-01-08', event: 'Operation Cedar Falls — largest U.S. ground operation of the war. The "Iron Triangle" near Saigon is designated a "free-fire zone" — meaning any Vietnamese in the area can be killed as a suspected enemy combatant' },
    { date: '1967-10-01', event: 'Pentagon Papers internal study commissioned by McNamara — 7,000 pages documenting systematic government lies about the war. McNamara does not reveal the study publicly' },
    { date: '1967-11-17', event: 'Westmoreland tells the National Press Club: "I am absolutely certain that whereas in 1965 the enemy was winning, today he is certainly losing" — three months before the Tet Offensive proves him catastrophically wrong' },
    { date: '1968-01-30', event: 'Tet Offensive — North Vietnamese and Viet Cong launch massive coordinated attack on every major South Vietnamese city, the U.S. embassy in Saigon, and 100+ military targets. The offensive shatters the claim that the U.S. is winning' },
    { date: '1968-03-16', event: 'My Lai Massacre — Charlie Company, 1st Battalion, 20th Infantry, enters My Lai village and systematically murders 504 unarmed civilians over four hours. Women are raped, children bayoneted, bodies mutilated. The Army covers it up for over a year' },
    { date: '1968-10-31', event: 'Nixon\'s campaign, through Anna Chennault, secretly contacts South Vietnam to sabotage LBJ\'s Paris Peace Talks — promising better terms under a Nixon presidency. The war continues for four more years, killing 22,000 more Americans' },
    { date: '1968-12-01', event: 'Operation Speedy Express begins — the 9th Infantry Division\'s campaign in the Mekong Delta claims 10,899 "enemy" kills against only 748 weapons recovered, indicating thousands of unarmed civilians were counted as combatants' },
    { date: '1969-03-18', event: 'Operation Menu begins — Nixon and Kissinger authorize the secret bombing of Cambodia without congressional knowledge or approval. Over 14 months, 3,875 B-52 sorties drop 108,823 tons of bombs on a neutral country' },
    { date: '1969-06-08', event: 'Nixon announces "Vietnamization" — beginning withdrawal of U.S. troops while secretly expanding the war into Cambodia and Laos. The policy is designed to reduce American casualties while continuing the war indefinitely' },
    { date: '1969-11-12', event: 'Seymour Hersh breaks the My Lai massacre story — more than 20 months after the event. The Army had successfully suppressed the atrocity until Hersh\'s reporting forced public acknowledgment' },
    { date: '1970-04-30', event: 'Nixon announces the invasion of Cambodia — sparking massive protests at home. Four students are killed by National Guard at Kent State on May 4. Two students killed at Jackson State on May 15' },
    { date: '1971-06-13', event: 'New York Times begins publishing the Pentagon Papers — Daniel Ellsberg\'s leak reveals that four presidential administrations systematically lied to the public about the war\'s progress and purpose' },
    { date: '1971-03-29', event: 'Lt. William Calley convicted of murdering 22 civilians at My Lai — the only person convicted of any crime despite the massacre of 504 people. His life sentence is reduced to 3.5 years of house arrest by Nixon' },
    { date: '1972-06-08', event: 'Nine-year-old Phan Thi Kim Phuc runs naked down a road, her body burning from napalm — Nick Ut\'s photograph becomes the defining image of the war\'s brutality against civilians' },
    { date: '1972-12-18', event: 'Operation Linebacker II — the "Christmas Bombings" — Nixon orders 12 days of intensive B-52 bombing of Hanoi and Haiphong, dropping 20,000 tons of bombs on North Vietnam\'s most populated areas' },
    { date: '1973-01-27', event: 'Paris Peace Accords signed — the agreement is virtually identical to what was available in 1968 before Nixon sabotaged the peace talks. An additional 22,000 Americans and hundreds of thousands of Vietnamese died in the intervening four years' },
    { date: '1975-04-30', event: 'Fall of Saigon — North Vietnamese forces capture the South Vietnamese capital. The last Americans are evacuated by helicopter from the U.S. Embassy roof. The war ends in total defeat for U.S. objectives' },
    { date: '2003-08-22', event: 'Toledo Blade publishes investigation of Tiger Force war crimes — the Army\'s own investigation had found evidence of war crimes including murder, torture, and mutilation, but no charges were ever filed' },
  ],
  legalOutcomes: [
    { defendant: 'Lt. William Calley', charge: 'Murder of 22 civilians at My Lai — the only person convicted of any crime in the massacre of 504 unarmed men, women, children, and infants', outcome: 'Convicted and sentenced to life in prison — reduced to 20 years by military review, then to 10 years by Nixon. Served 3.5 years of house arrest. Paroled in 1974.' },
    { defendant: 'Capt. Ernest Medina', charge: 'Overall responsibility for My Lai massacre as Charlie Company commander — witnesses testified he ordered troops to "kill everything that moves"', outcome: 'Acquitted at court-martial in 1971 despite extensive testimony and evidence' },
    { defendant: 'Maj. Gen. Samuel Koster', charge: 'Suppressing and covering up the initial My Lai investigation as commanding officer of the Americal Division', outcome: 'Reduced in rank, stripped of Distinguished Service Medal. No criminal prosecution.' },
    { defendant: '25 Other My Lai Officers & Soldiers', charge: 'Various charges related to My Lai massacre — murder, assault, dereliction of duty, and cover-up', outcome: 'All charges dropped or acquitted. Not a single other soldier was convicted. The Army effectively chose to sacrifice Calley alone.' },
    { defendant: 'Tiger Force War Crimes', charge: 'Months-long campaign of murder, torture, mutilation, and trophy-taking (ears, scalps) by Army reconnaissance unit in the Central Highlands — Army\'s own CID investigation confirmed crimes', outcome: 'Army investigated for 4.5 years, identified 18 soldiers who committed war crimes — then quietly closed the investigation without filing a single charge' },
    { defendant: 'Operation Speedy Express', charge: 'Systematic killing of civilians counted as enemy combatants — 10,899 "enemy" kills but only 748 weapons recovered, indicating thousands of civilian murders', outcome: 'Newsweek reported on the operation in 1972. The Army acknowledged the investigation but never released findings. No charges filed.' },
    { defendant: 'Phoenix Program', charge: 'CIA-directed assassination program that killed 20,000-40,000 suspected Viet Cong sympathizers, many of them civilians identified by corrupt local officials', outcome: 'No investigation, no charges. William Colby testified before Congress in 1971 but defended the program. He was later appointed CIA Director.' },
    { defendant: 'Agent Orange / Dow Chemical', charge: 'Manufacturing and deploying 20 million gallons of herbicide containing dioxin — one of the most toxic substances known — causing birth defects, cancers, and environmental devastation across generations', outcome: '1984 class-action settlement: $180 million for American veterans. Vietnamese victims received nothing. Dow Chemical and Monsanto have never accepted responsibility. Birth defects continue to this day.' },
    { defendant: 'Henry Kissinger / Richard Nixon', charge: 'Secret, illegal bombing of Cambodia without congressional authorization — killing an estimated 150,000-500,000 Cambodian civilians and destabilizing the country, contributing to the Khmer Rouge genocide', outcome: 'Never charged. Kissinger awarded the Nobel Peace Prize in 1973. Nixon resigned over Watergate, not war crimes. Both died without facing accountability.' },
    { defendant: 'Daniel Ellsberg (Whistleblower)', charge: 'Charged under the Espionage Act for leaking the Pentagon Papers — the 7,000-page study proving the government systematically lied about the war', outcome: 'All charges dismissed in 1973 due to government misconduct — Nixon\'s "Plumbers" unit had burglarized Ellsberg\'s psychiatrist\'s office and wiretapped him illegally' },
  ],
  charges: [
    { statute: 'Geneva Convention IV — Protection of Civilian Persons in Time of War', description: 'Systematic killing of civilians in designated "free-fire zones," Phoenix Program assassinations, My Lai massacre, Operation Speedy Express, and Tiger Force atrocities all constitute grave breaches of the Geneva Conventions', count: 'Estimated 2-3 million Vietnamese civilians killed; multiple documented massacre events' },
    { statute: 'Hague Convention IV — Laws and Customs of War on Land', description: 'Destruction of civilian property, forced relocations (Strategic Hamlet Program), use of prohibited weapons (napalm on civilian areas), and failure to distinguish between combatants and civilians', count: 'Systematic violations across the entire theater of operations for over a decade' },
    { statute: '18 U.S.C. § 2441 — War Crimes Act', description: 'Murder and torture of civilians and prisoners of war constitute federal crimes under the War Crimes Act — applicable to My Lai, Tiger Force, Phoenix Program, and Operation Speedy Express', count: 'Thousands of documented instances of murder, torture, and abuse of civilians and POWs' },
    { statute: '18 U.S.C. § 1111 — Murder', description: 'Deliberate killing of unarmed civilians — 504 at My Lai alone, thousands in Operation Speedy Express, tens of thousands in Phoenix Program assassinations', count: 'Tens of thousands of documented civilian murders' },
    { statute: 'UN Charter Article 2(4) — Prohibition on Use of Force', description: 'The secret bombing of Cambodia (a neutral country) without congressional authorization or UN Security Council approval constituted illegal use of force against a sovereign nation', count: '3,875+ B-52 sorties dropping 108,823+ tons of bombs on Cambodia; estimated 150,000-500,000 civilian deaths' },
    { statute: 'Chemical and Biological Weapons — 1925 Geneva Protocol', description: 'Deployment of 20 million gallons of Agent Orange and other defoliants containing dioxin — a chemical weapon that has caused multi-generational birth defects, cancers, and environmental devastation', count: '20 million gallons of herbicide sprayed; 4.8 million Vietnamese exposed; birth defects continuing to 2025' },
    { statute: '18 U.S.C. § 1505 — Obstruction of Congressional Proceedings', description: 'The Nixon administration concealed the bombing of Cambodia from Congress, classified the operations, and created false records to hide the air campaign — systematic deception of oversight bodies', count: 'Over 14 months of secret bombing hidden from Congress through falsified records' },
    { statute: '18 U.S.C. § 371 — Conspiracy', description: 'Multi-administration conspiracy to deceive the American public and Congress about the progress, purpose, and conduct of the war — documented in the 7,000-page Pentagon Papers', count: 'Four presidential administrations engaged in systematic deception from 1945-1975' },
    { statute: '18 U.S.C. § 1001 — False Statements', description: 'Systematic lies to Congress about enemy strength (Westmoreland\'s capped estimates), Gulf of Tonkin second attack (which likely never happened), and the war\'s progress', count: 'Decades of false statements to Congress, press, and public' },
    { statute: 'Logan Act (18 U.S.C. § 953) — Private Diplomacy', description: 'Nixon campaign\'s backchannel communications with South Vietnam through Anna Chennault to sabotage the 1968 Paris Peace Talks constituted unauthorized private diplomacy undermining the sitting president', count: 'Direct sabotage of peace negotiations that prolonged the war by four years' },
    { statute: 'Convention Against Torture — Articles 1-4', description: 'Systematic torture of prisoners and detainees — Phoenix Program interrogation centers used electrocution, water torture, beatings, and sexual violence against detainees', count: 'Thousands of detainees tortured in Phoenix Program interrogation centers' },
  ],
  coverup: [
    'The My Lai massacre was covered up by the U.S. Army for over 20 months. Initial reports described the operation as a "fierce firefight" in which 128 "Viet Cong" were killed. The truth — that 504 unarmed civilians were systematically murdered — only emerged when soldier Ron Ridenhour wrote letters to Congress and Seymour Hersh broke the story.',
    'The Pentagon Papers — a 7,000-page classified study commissioned by Defense Secretary McNamara — revealed that four presidential administrations had systematically lied to the American public and Congress about the war\'s origins, progress, and prospects. The government tried to suppress publication through prior restraint — the Supreme Court ruled 6-3 in favor of the press.',
    'The secret bombing of Cambodia (Operation Menu) was concealed from Congress and the American public for over a year through falsified military records. When the bombing became public, Nixon and Kissinger claimed it was targeting North Vietnamese sanctuaries — while B-52s were carpet-bombing Cambodian villages.',
    'The Tiger Force war crimes — murder, torture, mutilation, trophy-taking of ears and scalps — were investigated by the Army\'s Criminal Investigation Division for 4.5 years. The investigation identified 18 soldiers who committed war crimes. The Army then quietly closed the case without filing a single charge and classified the findings.',
    'The Gulf of Tonkin "second attack" on August 4, 1964 almost certainly never happened — NSA documents declassified in 2005 revealed that signals intelligence was manipulated and misrepresented to justify the resolution that authorized the war. McNamara knew the evidence was questionable and suppressed doubts.',
    'Operation Speedy Express killed 10,899 "enemy" fighters but recovered only 748 weapons — a ratio indicating that thousands of unarmed civilians were killed and counted as enemy combatants. The Army investigated but never released findings. Kevin Buckley\'s Newsweek investigation was heavily edited before publication.',
    'The Phoenix Program\'s assassination quotas and torture methods were hidden behind euphemisms like "neutralization" and "pacification." When William Colby testified before Congress in 1971, he acknowledged 20,587 kills but claimed they were all "combatants" — despite extensive evidence that thousands were civilians.',
    'Nixon\'s sabotage of the 1968 Paris Peace Talks through the "Chennault Affair" — contacting South Vietnam through Anna Chennault to convince them to refuse negotiations — was known to the Johnson administration through FBI wiretaps. LBJ chose not to expose the treason for fear of the political consequences. The war continued for four more years.',
    'Agent Orange manufacturers (Dow Chemical, Monsanto) knew dioxin was toxic to humans but concealed internal studies showing the dangers. The U.S. government continued spraying for years after evidence of harm emerged. Vietnamese victims have received no compensation. The dioxin continues to cause birth defects more than 50 years later.',
    'The body count metric — used by Westmoreland to measure "progress" — created systematic incentives to inflate kill numbers and count civilians as enemy combatants. The pressure to produce high body counts led directly to atrocities as soldiers killed civilians to meet performance quotas.',
  ],
  sources: [
    { title: 'Seymour Hersh — "My Lai 4: A Report on the Massacre and Its Aftermath" (Random House, 1970)', url: 'https://www.pulitzer.org/winners/seymour-m-hersh', date: '1970' },
    { title: 'The Pentagon Papers — National Archives Declassified Documents', url: 'https://www.archives.gov/research/pentagon-papers', date: '1971/2011' },
    { title: 'Nick Turse — "Kill Anything That Moves: The Real American War in Vietnam" (Metropolitan Books, 2013)', url: 'https://www.penguinrandomhouse.com/books/209529/kill-anything-that-moves-by-nick-turse/', date: '2013' },
    { title: 'Toledo Blade — "Tiger Force" Investigation (Pulitzer Prize Winner)', url: 'https://www.pulitzer.org/winners/toledo-blade', date: '2003' },
    { title: 'Robert McNamara — "In Retrospect: The Tragedy and Lessons of Vietnam"', url: 'https://www.penguinrandomhouse.com/books/163475/in-retrospect-by-robert-s-mcnamara/', date: '1995' },
    { title: 'Daniel Ellsberg — "Secrets: A Memoir of Vietnam and the Pentagon Papers"', url: 'https://www.penguinrandomhouse.com/books/163464/secrets-by-daniel-ellsberg/', date: '2002' },
    { title: 'The New York Times — Pentagon Papers Publication (1971)', url: 'https://www.nytimes.com/interactive/2021/06/09/us/pentagon-papers-50th-anniversary.html', date: '2021-06-09' },
    { title: 'Ken Burns & Lynn Novick — "The Vietnam War" (PBS Documentary, 2017)', url: 'https://www.pbs.org/kenburns/the-vietnam-war/', date: '2017' },
    { title: 'NSA Declassified Gulf of Tonkin Documents', url: 'https://www.nsa.gov/Helpful-Links/NSA-FOIA/Declassification-Transparency-Initiatives/Historical-Releases/Gulf-of-Tonkin/', date: '2005-11-30' },
    { title: 'Errol Morris — "The Fog of War: Eleven Lessons from the Life of Robert S. McNamara" (Documentary, 2003)', url: 'https://www.imdb.com/title/tt0317910/', date: '2003' },
    { title: 'The Intercept — "The Phoenix Program and How the U.S. Conducted Secret Assassinations in Vietnam"', url: 'https://theintercept.com/2017/01/09/the-crimes-of-seal-team-6/', date: '2017-01-09' },
    { title: 'Agent Orange Record — Vietnamese Victims and Ongoing Impact', url: 'https://www.aspeninstitute.org/programs/agent-orange-in-vietnam-program/', date: '2023' },
  ],
};

export default function VietnamWarCrimesPage() {
  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/investigations" className="inline-flex items-center gap-2 text-zinc-400 hover:text-blood-500 transition-colors mb-6 pt-4"><ArrowLeft className="w-4 h-4" />Back to Investigations</Link>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="border-2 border-blood-800/60 bg-black/80 p-6 lg:p-8 mb-8">
          <div className="flex items-center gap-3 mb-4"><span className="px-3 py-1 text-xs font-bold uppercase border border-red-500/30 bg-red-500/20 text-red-400">{investigation.severity}</span><span className="px-3 py-1 text-xs font-bold uppercase border border-zinc-500/30 bg-zinc-500/20 text-zinc-400">{investigation.status}</span></div>
          <h1 className="text-3xl lg:text-4xl font-black text-white uppercase tracking-wider mb-2"><GlitchText text={investigation.title} /></h1>
          <p className="text-lg text-blood-500 font-bold mb-4">{investigation.subtitle}</p>
          <p className="text-zinc-400 leading-relaxed">{investigation.summary}</p>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="glass-card p-6 mb-8 border-l-4 border-blood-600">
          <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-blood-500" />The Cover-Up</h2>
          <div className="space-y-3">{investigation.coverup.map((item, idx) => (<div key={idx} className="p-3 bg-red-950/20 border border-red-500/30"><p className="text-sm text-zinc-300">{item}</p></div>))}</div>
        </motion.div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Users className="w-5 h-5 text-blood-500" />Key Figures</h2>
              <div className="space-y-3">{investigation.keyFigures.map((figure, idx) => (<div key={idx} className="flex items-start justify-between p-3 bg-zinc-900/50 border border-zinc-800"><div className="flex-1">{figure.href ? (<Link href={figure.href} className="font-bold text-blood-400 hover:text-blood-300 transition-colors">{figure.name}</Link>) : (<span className="font-bold text-white">{figure.name}</span>)}<p className="text-sm text-zinc-400 mt-1">{figure.role}</p></div><span className="text-xs px-2 py-1 bg-zinc-800 text-zinc-400 border border-zinc-700 whitespace-nowrap ml-2">{figure.status}</span></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Applicable Charges &amp; Statutes</h2>
              <div className="space-y-3">{investigation.charges.map((charge, idx) => (<div key={idx} className="p-4 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-blood-400 text-sm font-mono">{charge.statute}</p><p className="text-sm text-zinc-300 mt-1">{charge.description}</p><p className="text-xs text-red-400 mt-1">{charge.count}</p></div>))}</div>
            </motion.div>
          </div>
          <div className="space-y-6">
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Calendar className="w-4 h-4 text-blood-500" />Timeline</h3>
              <div className="space-y-4">{investigation.timeline.map((item, idx) => (<div key={idx} className="relative pl-4 border-l-2 border-zinc-800"><div className="absolute -left-[5px] top-0 w-2 h-2 rounded-full bg-blood-500" /><p className="text-xs text-blood-500 font-mono">{item.date}</p><p className="text-sm text-zinc-300">{item.event}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Legal Outcomes</h3>
              <div className="space-y-3">{investigation.legalOutcomes.map((item, idx) => (<div key={idx} className="p-3 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-white text-sm">{item.defendant}</p><p className="text-xs text-zinc-400 mt-1">{item.charge}</p><p className="text-xs text-blood-400 mt-1">{item.outcome}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4">Sources</h3>
              <div className="space-y-2">{investigation.sources.map((source, idx) => (<a key={idx} href={source.url} target="_blank" rel="noopener noreferrer" className="flex items-start gap-2 p-2 text-sm text-zinc-400 hover:text-blood-400 hover:bg-zinc-900/50 transition-colors"><ExternalLink className="w-4 h-4 mt-0.5 flex-shrink-0" /><div><span>{source.title}</span><span className="text-zinc-600 ml-2">({source.date})</span></div></a>))}</div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
