'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, AlertTriangle, Users, Calendar, FileText, ExternalLink, Scale, ShieldAlert, Skull } from 'lucide-react';
import GlitchText from '@/components/effects/GlitchText';

const investigation = {
  title: '1953 Iran Coup (Operation Ajax)',
  subtitle: 'CIA/MI6 Overthrow of Democracy — Installation of the Shah, SAVAK Terror, and the Blowback That Shaped the Modern Middle East',
  severity: 'critical',
  status: 'DECLASSIFIED — CIA ADMITTED ROLE IN 2013',
  summary: 'In August 1953, the CIA and British MI6 orchestrated a coup d\'état (Operation TPAJAX/Operation Boot) that overthrew the democratically elected Prime Minister of Iran, Mohammad Mosaddegh, and restored the autocratic rule of Shah Mohammad Reza Pahlavi. Mosaddegh\'s crime was nationalizing Iran\'s oil industry, which had been controlled by the Anglo-Iranian Oil Company (later BP) under terms that gave Iran only 16% of profits from its own oil. The coup was planned after Mosaddegh refused to accept a 50/50 profit split and moved to audit the company\'s books. CIA officer Kermit Roosevelt Jr. (grandson of Theodore Roosevelt) directed the operation from Tehran, bribing military officers, hiring mobs, planting propaganda in Iranian newspapers, and orchestrating street violence to create the appearance of popular opposition. After an initial failed coup attempt on August 15, 1953, the Shah fled to Rome. A second attempt on August 19 succeeded when CIA-paid mobs and bribed military units seized key buildings and arrested Mosaddegh. The Shah returned and, with U.S. support, established an increasingly autocratic regime backed by SAVAK — a secret police force trained by the CIA and Mossad that tortured and killed thousands of political dissidents over 25 years. The profound Iranian resentment toward the U.S. and Britain for destroying their democracy directly fueled the 1979 Islamic Revolution, the hostage crisis, and decades of hostility that continue to shape Middle Eastern geopolitics today. The CIA did not officially acknowledge its role until 2013, sixty years after the coup.',
  keyFigures: [
    { name: 'Mohammad Mosaddegh', role: 'Democratically elected Prime Minister of Iran (1951-1953). TIME Magazine\'s Man of the Year 1951. Nationalized Iran\'s oil industry to reclaim sovereignty over natural resources. Overthrown by CIA/MI6 coup. Imprisoned for 3 years, then held under house arrest until his death in 1967', href: '/entities/individuals/mohammad-mosaddegh', status: 'Overthrown — Died Under House Arrest 1967' },
    { name: 'Shah Mohammad Reza Pahlavi', role: 'Shah of Iran who was reinstalled by the CIA coup. Ruled as autocrat for 25 years with U.S. military and intelligence support. His regime\'s SAVAK secret police tortured and killed thousands. Fled Iran during the 1979 Revolution. Died in exile in Egypt, 1980', href: '/entities/individuals/shah-pahlavi', status: 'Deposed 1979 — Died in Exile' },
    { name: 'Kermit Roosevelt Jr.', role: 'CIA officer who directed Operation Ajax from inside Tehran. Grandson of President Theodore Roosevelt. Bribed military officers, organized street mobs, planted anti-Mosaddegh propaganda, and orchestrated both coup attempts. Later worked for Gulf Oil — profiting from the regime he installed', href: '/entities/individuals/kermit-roosevelt', status: 'Never Charged' },
    { name: 'Allen Dulles', role: 'CIA Director who authorized and oversaw Operation Ajax. Brother of Secretary of State John Foster Dulles. Both Dulles brothers had personal financial ties to companies with interests in Iranian oil through their law firm Sullivan & Cromwell', href: '/entities/individuals/allen-dulles', status: 'CIA Director 1953-1961' },
    { name: 'John Foster Dulles', role: 'U.S. Secretary of State who pushed for the coup, framing Mosaddegh as a communist threat despite lack of evidence. His law firm Sullivan & Cromwell had represented Anglo-Iranian Oil Company', href: '/entities/individuals/john-foster-dulles', status: 'Secretary of State 1953-1959' },
    { name: 'Henry Kissinger', role: 'Later Secretary of State who maintained close relationship with the Shah, sold massive quantities of U.S. weapons to Iran, and encouraged the Shah\'s authoritarian rule as a "pillar" of U.S. Middle East strategy — contributing to the conditions that produced the 1979 Revolution', href: '/entities/individuals/henry-kissinger', status: 'Shah Supporter' },
    { name: 'Richard Nixon', role: 'As Vice President, visited Tehran after the coup to congratulate the Shah. Later as President, the "Nixon Doctrine" made Iran a key U.S. proxy, providing blank-check weapons sales that fueled the Shah\'s megalomania and repression', href: '/entities/individuals/richard-nixon', status: 'Enabled Shah\'s Rule' },
    { name: 'Winston Churchill', role: 'British Prime Minister who pressured the Eisenhower administration to support the coup after the Truman administration refused. Framed the oil nationalization as a communist threat to secure American participation in what was fundamentally a British colonial resource grab', href: '/entities/individuals/winston-churchill', status: 'Initiated Coup Planning' },
    { name: 'Fazlollah Zahedi', role: 'Iranian general handpicked by MI6 and CIA to replace Mosaddegh. Installed as Prime Minister after the coup. Had been arrested by the British during WWII for pro-Nazi sympathies — yet was chosen to lead "democratic" Iran', href: '/entities/individuals/fazlollah-zahedi', status: 'Installed as PM 1953' },
    { name: 'Dwight D. Eisenhower', role: 'U.S. President who authorized Operation Ajax after being persuaded by the Dulles brothers that Mosaddegh would allow Iran to fall to communism. The Truman administration had rejected British requests for a coup — Eisenhower approved within months of taking office', href: '/entities/individuals/dwight-eisenhower', status: 'Authorized the Coup' },
    { name: 'Donald Wilber', role: 'CIA operative who wrote the classified after-action report on Operation Ajax ("Overthrow of Premier Mossadeq of Iran") — the detailed blueprint that was leaked to the New York Times in 2000, providing the first official confirmation of how the coup was planned and executed', href: '/entities/individuals/donald-wilber', status: 'Wrote Coup Plan' },
    { name: 'Nematollah Nassiri', role: 'Iranian colonel who delivered the Shah\'s firman (royal decree) dismissing Mosaddegh on August 15, 1953 — arrested by Mosaddegh\'s guards, triggering the initial failed coup. Later became head of SAVAK (1965-1978), overseeing systematic torture. Executed after the 1979 Revolution', href: '/entities/individuals/nematollah-nassiri', status: 'Executed 1979' },
  ],
  timeline: [
    { date: '1901', event: 'William Knox D\'Arcy obtains a 60-year oil concession covering most of Iran for a pittance. This concession becomes the foundation of the Anglo-Iranian Oil Company (AIOC, later BP) — Britain extracts vast wealth while Iran receives a fraction of the profits' },
    { date: '1941', event: 'Britain and the Soviet Union jointly invade and occupy Iran, forcing Reza Shah to abdicate in favor of his young son Mohammad Reza Pahlavi. British control over Iranian oil continues' },
    { date: '1949-1950', event: 'Iranian public outrage over the lopsided AIOC deal intensifies. Iran receives only 16% of oil profits. AIOC has never allowed Iran to audit its books. Saudi Arabia negotiates a 50/50 deal with ARAMCO, making Iran\'s terms even more humiliating' },
    { date: 'March 15, 1951', event: 'Iranian parliament (Majlis) votes unanimously to nationalize the oil industry. Mosaddegh becomes Prime Minister with a mandate to reclaim Iran\'s resources from British exploitation' },
    { date: 'April-October 1951', event: 'Britain responds to nationalization with an economic blockade, freezing Iranian assets, threatening military action, and organizing a worldwide boycott of Iranian oil — devastating the Iranian economy while refusing to negotiate fairly' },
    { date: 'October 1951', event: 'Mosaddegh named TIME Magazine "Man of the Year" for 1951. Addresses the UN Security Council and the International Court of Justice, arguing Iran\'s sovereign right to its own resources. He wins both cases' },
    { date: 'November 1952', event: 'Churchill and MI6 approach the newly elected Eisenhower administration about a joint coup. Reframe the issue from British oil interests to "communist threat" to win American support. Truman had refused to participate' },
    { date: 'June 1953', event: 'CIA and MI6 finalize coup plan (TPAJAX/Boot). $1 million budget allocated. Kermit Roosevelt deployed to Tehran. Strategy: bribe military officers, pay for anti-Mosaddegh mobs, plant propaganda, create chaos, then install General Zahedi' },
    { date: 'July-August 1953', event: 'CIA agents distribute $100,000+ to bribe Iranian newspaper editors, politicians, military officers, and street gang leaders. Fake "communist" propaganda planted to create fear. Mullahs paid to denounce Mosaddegh' },
    { date: 'August 15, 1953', event: 'First coup attempt fails. Colonel Nassiri delivers the Shah\'s decree dismissing Mosaddegh but is arrested. Mosaddegh announces the attempted coup on radio. The Shah panics and flees to Baghdad, then Rome' },
    { date: 'August 16-18, 1953', event: 'CIA initially considers the operation a failure. Kermit Roosevelt decides to proceed with a second attempt. Organizes larger street mobs, pays military commanders, and coordinates a propaganda blitz claiming Iran is on the brink of communist takeover' },
    { date: 'August 19, 1953', event: 'Second coup succeeds. CIA-paid mobs flood Tehran streets, creating appearance of popular uprising. Bribed military units seize key buildings. Tank columns roll through the capital. Mosaddegh\'s home is bombed and overrun. At least 300 people killed in street fighting. Mosaddegh is arrested' },
    { date: 'August 22, 1953', event: 'The Shah returns triumphantly from Rome to Tehran. Mosaddegh imprisoned. General Zahedi installed as Prime Minister. Iran\'s brief experiment with democracy is crushed' },
    { date: '1954', event: 'New oil consortium agreement: Iran gets 50% of profits but AIOC (renamed BP) retains 40% ownership alongside American companies who now get a 40% share. The coup\'s primary beneficiaries: British and American oil corporations' },
    { date: '1957', event: 'CIA and Mossad help establish SAVAK (Sazeman-e Ettela\'at va Amniyat-e Keshvar), Iran\'s secret police. SAVAK becomes one of the most feared intelligence agencies in the world, employing systematic torture, surveillance, and assassination of dissidents' },
    { date: '1963-1979', event: 'Shah\'s "White Revolution" modernization program implemented alongside increasing autocracy. SAVAK represses all opposition — liberal, leftist, and religious. Thousands tortured in Evin Prison. Political parties banned. Press censored. All dissent crushed' },
    { date: '1971', event: 'Amnesty International reports that Iran under the Shah has the "highest rate of death penalties in the world, no valid system of civilian courts, and a history of torture which is beyond belief." SAVAK methods include electric shock, nail extraction, boiling water, and rape' },
    { date: 'January 16, 1979', event: 'The Shah flees Iran amid massive popular revolution driven by 25 years of accumulated rage at his U.S.-backed dictatorship. Ayatollah Khomeini returns from exile. The Islamic Republic is established — direct blowback from the 1953 coup' },
    { date: 'November 4, 1979', event: 'Iranian students seize the U.S. Embassy in Tehran, taking 52 Americans hostage for 444 days. The students explicitly cite the 1953 coup as justification — demanding the U.S. return the Shah and acknowledge its role in destroying Iranian democracy' },
    { date: 'August 19, 2013', event: 'CIA officially acknowledges for the first time that it organized and executed the 1953 coup, releasing declassified documents 60 years after the operation. The documents confirm every detail long denied by the U.S. government' },
  ],
  legalOutcomes: [
    { defendant: 'Mohammad Mosaddegh', charge: 'Charged with "treason" by the Shah\'s military tribunal for resisting the coup', outcome: '3 years in prison followed by lifetime house arrest until death in 1967. The victim of the crime was the one punished' },
    { defendant: 'CIA / Kermit Roosevelt', charge: 'Organizing the overthrow of a democratically elected government, bribery, incitement to violence', outcome: 'No charges ever filed. Roosevelt received a National Security Medal. Later became a lobbyist and oil company consultant, profiting from the regime he installed' },
    { defendant: 'Allen Dulles / John Foster Dulles', charge: 'Authorizing coup with conflicts of interest (Sullivan & Cromwell ties to oil companies)', outcome: 'No charges. Both continued in their positions. Allen Dulles served as CIA Director until 1961' },
    { defendant: 'Shah Mohammad Reza Pahlavi', charge: 'Decades of human rights abuses through SAVAK, torture, political murder', outcome: 'Never tried. Fled Iran January 1979. Died in exile in Egypt, July 1980' },
    { defendant: 'SAVAK Officials', charge: 'Systematic torture, murder, and disappearance of political dissidents over 25 years', outcome: 'Many tried and executed after the 1979 Revolution by revolutionary tribunals. Head of SAVAK Nassiri executed February 15, 1979' },
    { defendant: 'Anglo-Iranian Oil Company (BP)', charge: 'Exploitative colonial resource extraction, complicity in coup, refusal to negotiate fair terms', outcome: 'No accountability. BP profited enormously from the post-coup oil consortium. Never compensated Iran for decades of resource extraction' },
    { defendant: 'United Kingdom / MI6', charge: 'Originating and planning the coup operation, economic warfare against Iran, colonial resource exploitation', outcome: 'No accountability. Britain maintained diplomatic relations. Never formally apologized for the coup or the oil exploitation that motivated it' },
    { defendant: 'U.S. Government', charge: 'Overthrowing a democratic government, supporting a dictatorship for 25 years, creating conditions for regional instability', outcome: 'CIA admitted role in 2013. Obama referenced the coup in his 2009 Cairo speech. No formal apology, no reparations, no accountability for 25 years of supporting Shah\'s tyranny' },
  ],
  charges: [
    { statute: 'UN Charter Article 2(4) — Prohibition on Use of Force Against Territorial Integrity', description: 'The covert overthrow of a sovereign nation\'s democratically elected government constitutes a violation of the prohibition on the use of force against the territorial integrity or political independence of any state. The coup fundamentally violated Iran\'s sovereignty', count: 'Complete overthrow of democratically elected government; $1+ million in bribery and covert operations' },
    { statute: 'OAS/UN Charter — Prohibition on Intervention in Internal Affairs', description: 'The United States and United Kingdom illegally intervened in Iran\'s domestic political affairs by organizing protests, bribing officials, planting propaganda, hiring mobs, and coordinating military units to overthrow a government the Iranian people had democratically chosen', count: 'Systematic subversion of democratic institutions over 2+ years' },
    { statute: 'International Covenant on Civil and Political Rights — Right to Self-Determination (Article 1)', description: 'The Iranian people exercised their right to self-determination by democratically electing Mosaddegh and supporting oil nationalization. The coup destroyed this exercise of popular sovereignty and imposed an autocrat who ruled against the will of the people for 25 years', count: 'Democratic self-governance eliminated for 25 years (1953-1979)' },
    { statute: 'Convention Against Torture (CAT)', description: 'The Shah\'s SAVAK — created with CIA and Mossad assistance — employed systematic torture including electric shock, nail and tooth extraction, boiling water, extended suspension, sexual violence, and psychological terror. The U.S. trained SAVAK agents and provided operational support', count: 'Thousands tortured by SAVAK over 25 years. Amnesty International documented "torture beyond belief"' },
    { statute: 'Geneva Conventions — Collective Punishment', description: 'Britain\'s economic blockade of Iran in response to oil nationalization constituted collective punishment of an entire civilian population for the lawful actions of their elected government. The blockade devastated the Iranian economy and caused widespread suffering', count: 'Entire Iranian population subjected to economic warfare 1951-1953' },
    { statute: 'Rome Statute — Crimes Against Humanity (Article 7)', description: 'The Shah\'s post-coup regime, installed and sustained by the U.S. and UK, committed systematic persecution, torture, murder, and imprisonment of political opponents constituting crimes against humanity. The U.S. and UK bear responsibility as enabling powers', count: 'Decades of systematic repression affecting millions of Iranians' },
    { statute: 'U.S. Constitution — Separation of Powers', description: 'The Eisenhower administration ordered the overthrow of a foreign government as a covert executive action without congressional authorization or oversight, establishing a dangerous precedent for unilateral executive war-making that bypassed democratic checks and balances', count: 'Unauthorized covert war operation — no congressional vote or oversight' },
    { statute: 'UN General Assembly Resolution 1803 — Permanent Sovereignty Over Natural Resources', description: 'Iran had the sovereign right to nationalize its own oil resources. The coup was executed to reverse a lawful exercise of national sovereignty over natural resources, substituting corporate profits for the rights of the Iranian people', count: 'Iran\'s sovereign decision to nationalize oil reversed by foreign coup' },
  ],
  coverup: [
    'The CIA denied any involvement in the 1953 coup for sixty years. It was not until August 19, 2013 — the 60th anniversary — that the Agency officially acknowledged its role by releasing declassified documents. For six decades, the U.S. government maintained the fiction that Mosaddegh fell due to internal Iranian political dynamics.',
    'The Dulles brothers — Allen (CIA Director) and John Foster (Secretary of State) — framed the coup as necessary to prevent Iran from falling to communism, despite the fact that Mosaddegh had actually suppressed the Iranian communist party (Tudeh) and was a nationalist, not a Marxist. The "communist threat" narrative was fabricated to justify what was fundamentally an oil grab.',
    'After the coup, the U.S. and Britain rewrote the history: Mosaddegh was portrayed as an unstable, weeping old man who was losing control of Iran. This character assassination of a democratically elected leader who had nationalized his country\'s resources was deliberately crafted to justify the destruction of Iranian democracy.',
    'The CIA\'s classified internal history of the operation ("Overthrow of Premier Mossadeq of Iran, November 1952-August 1953") by Donald Wilber was leaked to the New York Times in 2000, revealing the granular details of how the coup was planned: specific bribes paid, propaganda planted, mobs organized, and military officers recruited. The document had been suppressed for nearly 50 years.',
    'SAVAK\'s atrocities were systematically downplayed by successive U.S. administrations. Despite Amnesty International\'s 1971 report documenting routine torture, the Nixon, Ford, and Carter administrations continued providing arms, training, and support to the Shah, treating human rights concerns as secondary to strategic interests.',
    'Britain\'s role in originating the coup — and the colonial resource extraction that motivated it — has been consistently minimized in Western histories. AIOC (BP) had been extracting Iranian oil under terms that gave Iran 16% of profits, refused to allow auditing, and maintained segregated facilities where Iranian workers were treated as inferior. This exploitation was the root cause of the crisis.',
    'The post-coup oil consortium was presented as a fair deal, but in reality it was a division of spoils: American oil companies received a 40% share of Iranian oil — their reward for CIA participation in the coup. The strategic interest that drove the U.S. to overthrow Iranian democracy was ultimately corporate profit.',
    'The direct line from the 1953 coup to the 1979 Iranian Revolution, the hostage crisis, the rise of political Islam in the region, and decades of U.S.-Iran hostility has been systematically downplayed in American public discourse. The concept of "blowback" — unintended consequences of covert operations — was coined partly in reference to the Iran coup, yet mainstream political discourse continues to treat Iranian hostility toward the U.S. as inexplicable rather than as a predictable consequence of overthrowing their democracy.',
  ],
  sources: [
    { title: 'CIA Confirms Role in 1953 Iran Coup — National Security Archive Declassified Documents', url: 'https://nsarchive.gwu.edu/briefing-book/iran/2013-08-19/cia-confirms-role-1953-iran-coup', date: 'August 19, 2013' },
    { title: 'CIA Clandestine Service History: "Overthrow of Premier Mossadeq of Iran" (Wilber Document)', url: 'https://nsarchive.gwu.edu/document/iran-1953-coup-cia-clandestine-service-history-overthrow-premier-mossadeq-iran', date: 'March 1954 (Declassified 2000)' },
    { title: 'All the Shah\'s Men: An American Coup and the Roots of Middle East Terror — Stephen Kinzer', url: 'https://www.wiley.com/en-us/All+the+Shah%27s+Men-p-9780470185490', date: '2003, Updated 2008' },
    { title: 'The CIA in Iran — New York Times (Wilber Document Publication)', url: 'https://www.nytimes.com/library/world/mideast/041600iran-cia-index.html', date: 'April 16, 2000' },
    { title: 'Ervand Abrahamian: The Coup — 1953, the CIA, and the Roots of Modern U.S.-Iranian Relations', url: 'https://thenewpress.com/books/coup', date: '2013' },
    { title: 'MI6 and the 1953 Iran Coup — The Guardian Investigation', url: 'https://www.theguardian.com/uk/2000/aug/20/iran.richardnortontaylor', date: 'August 20, 2000' },
    { title: 'Obama Cairo Speech — References 1953 Coup', url: 'https://obamawhitehouse.archives.gov/the-press-office/remarks-president-cairo-university-6-04-09', date: 'June 4, 2009' },
    { title: 'Mark J. Gasiorowski: Mohammad Mosaddeq and the 1953 Coup in Iran', url: 'https://www.cambridge.org/core/journals/international-journal-of-middle-east-studies/article/1953-coup-detat-in-iran/E218E65133F19E1A305C72D2B9EA8FE8', date: 'August 1987' },
    { title: 'Amnesty International — Iran: Briefing on SAVAK Human Rights Violations', url: 'https://www.amnesty.org/en/documents/mde13/001/1976/en/', date: '1976' },
    { title: 'Foreign Relations of the United States (FRUS) — Iran, 1951-1954 (Official State Department History)', url: 'https://history.state.gov/historicaldocuments/frus1951-54Iran', date: 'June 2017' },
  ],
};

export default function IranCoupPage() {
  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/investigations" className="inline-flex items-center gap-2 text-zinc-400 hover:text-blood-500 transition-colors mb-6 pt-4"><ArrowLeft className="w-4 h-4" />Back to Investigations</Link>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="border-2 border-blood-800/60 bg-black/80 p-6 lg:p-8 mb-8">
          <div className="flex items-center gap-3 mb-4"><span className="px-3 py-1 text-xs font-bold uppercase border border-red-500/30 bg-red-500/20 text-red-400">{investigation.severity}</span><span className="px-3 py-1 text-xs font-bold uppercase border border-zinc-500/30 bg-zinc-500/20 text-zinc-400">{investigation.status}</span></div>
          <h1 className="text-3xl lg:text-4xl font-black text-white uppercase tracking-wider mb-2"><GlitchText text={investigation.title} /></h1>
          <p className="text-lg text-blood-500 font-bold mb-4">{investigation.subtitle}</p>
          <p className="text-zinc-400 leading-relaxed">{investigation.summary}</p>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="glass-card p-6 mb-8 border-l-4 border-blood-600">
          <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-blood-500" />The Cover-Up</h2>
          <div className="space-y-3">{investigation.coverup.map((item, idx) => (<div key={idx} className="p-3 bg-red-950/20 border border-red-500/30"><p className="text-sm text-zinc-300">{item}</p></div>))}</div>
        </motion.div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Users className="w-5 h-5 text-blood-500" />Key Figures</h2>
              <div className="space-y-3">{investigation.keyFigures.map((figure, idx) => (<div key={idx} className="flex items-start justify-between p-3 bg-zinc-900/50 border border-zinc-800"><div className="flex-1">{figure.href ? (<Link href={figure.href} className="font-bold text-blood-400 hover:text-blood-300 transition-colors">{figure.name}</Link>) : (<span className="font-bold text-white">{figure.name}</span>)}<p className="text-sm text-zinc-400 mt-1">{figure.role}</p></div><span className="text-xs px-2 py-1 bg-zinc-800 text-zinc-400 border border-zinc-700 whitespace-nowrap ml-2">{figure.status}</span></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Applicable Charges &amp; Statutes</h2>
              <div className="space-y-3">{investigation.charges.map((charge, idx) => (<div key={idx} className="p-4 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-blood-400 text-sm font-mono">{charge.statute}</p><p className="text-sm text-zinc-300 mt-1">{charge.description}</p><p className="text-xs text-red-400 mt-1">{charge.count}</p></div>))}</div>
            </motion.div>
          </div>
          <div className="space-y-6">
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Calendar className="w-4 h-4 text-blood-500" />Timeline</h3>
              <div className="space-y-4">{investigation.timeline.map((item, idx) => (<div key={idx} className="relative pl-4 border-l-2 border-zinc-800"><div className="absolute -left-[5px] top-0 w-2 h-2 rounded-full bg-blood-500" /><p className="text-xs text-blood-500 font-mono">{item.date}</p><p className="text-sm text-zinc-300">{item.event}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Legal Outcomes</h3>
              <div className="space-y-3">{investigation.legalOutcomes.map((item, idx) => (<div key={idx} className="p-3 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-white text-sm">{item.defendant}</p><p className="text-xs text-zinc-400 mt-1">{item.charge}</p><p className="text-xs text-blood-400 mt-1">{item.outcome}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4">Sources</h3>
              <div className="space-y-2">{investigation.sources.map((source, idx) => (<a key={idx} href={source.url} target="_blank" rel="noopener noreferrer" className="flex items-start gap-2 p-2 text-sm text-zinc-400 hover:text-blood-400 hover:bg-zinc-900/50 transition-colors"><ExternalLink className="w-4 h-4 mt-0.5 flex-shrink-0" /><div><span>{source.title}</span><span className="text-zinc-600 ml-2">({source.date})</span></div></a>))}</div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
