import AgencyContent from './AgencyContent';
import agencyDatabase from '@/data/agencies';

// Hardcoded slugs for agencies that have full inline profiles in AgencyContent
const inlineSlugs = [
  'afp',
  'africom',
  'army-corps',
  'atf',
  'baltimore-pd',
  'bia',
  'bop',
  'capitol-police',
  'cbp',
  'cdc',
  'cfpb',
  'cia',
  'cisa',
  'commerce-department',
  'congress',
  'dea',
  'department-of-defense',
  'department-of-state',
  'dhs',
  'dina',
  'dod',
  'doe',
  'doi',
  'doj',
  'doj-civil-rights',
  'easa',
  'epa',
  'ethiopian-aib',
  'faa',
  'fbi',
  'fcc',
  'fda',
  'fec',
  'federal-reserve',
  'fema',
  'fisa-court',
  'french-justice',
  'fsb',
  'fulton-county-da',
  'gru',
  'gsa',
  'hhs',
  'icc',
  'ice',
  'interior-department',
  'irs',
  'jsoc',
  'knkt',
  'lapd-ig',
  'manhattan-da',
  'metropolitan-police',
  'mi6',
  'michigan-deq',
  'ministry-of-state-security',
  'minneapolis-pd',
  'mossad',
  'national-archives',
  'national-guard',
  'nih',
  'noaa',
  'nsa',
  'ntsb',
  'office-of-legal-counsel',
  'osha',
  'oss',
  'palm-beach-pd',
  'park-police',
  'pentagon',
  'public-health-service',
  'saudi-arabia',
  'savak',
  'sec',
  'secret-service',
  'state-department',
  'supreme-court',
  'transport-canada',
  'treasury',
  'united-nations',
  'usaid',
  'us-army',
  'usda',
  'us-marshals',
  'usps',
  'us-senate',
  'usvi-ag',
  'war-relocation-authority',
];

export async function generateStaticParams() {
  const allSlugs = new Set([...inlineSlugs, ...Object.keys(agencyDatabase)]);
  return [...allSlugs].map((slug) => ({ slug }));
}

export default function AgencyDetailPage() {
  return <AgencyContent />;
}

