// AUTO-GENERATED by ArkHive Migration — DO NOT EDIT MANUALLY
import type { InvestigationData } from './types';

const investigations_h: Record<string, InvestigationData> = {
  'health-policy': {
 title: 'Global Health Policy Capture',
 subtitle: 'How unelected billionaires shape worldwide health priorities',
 severity: 'high',
 category: 'Global Health',
 date: 'June 27, 2015',
 lastUpdated: 'February 12, 2026',
 summary: 'The Gates Foundation exercises enormous influence over global health policy through funding of WHO, research institutions, universities, and health programs worldwide. This private, unelected influence over public health raises profound questions about democratic accountability, institutional capture, and whether priorities serve populations or donors.',
 content: [
 'WHO FUNDING POWER: The Gates Foundation is the second-largest funder of the World Health Organization. When the US reduced funding under Trump, Gates Foundation influence grew even larger. This funding gives an unelected private foundation extraordinary influence over global health priorities.',
 'AGENDA SETTING: Foundation funding shapes what health issues receive attention and resources. The Foundation has championed specific interventions (vaccines, GMO crops, technological solutions) while critics argue this comes at the expense of health system strengthening and addressing social determinants of health like poverty, clean water, and sanitation.',
 'INSTITUTIONAL CAPTURE: Gates Foundation funds major medical schools, research institutions, and health publications. This funding creates institutional dependency. Researchers who depend on Gates funding may be reluctant to criticize Foundation priorities or conflicts of interest.',
 'POLIO ERADICATION CONTROVERSY: The Foundation\'s flagship polio eradication campaign has cost billions and diverted resources from routine immunization in some countries. While polio cases are near zero, vaccine-derived polio variants have emerged, and critics question whether resources could have saved more lives elsewhere.',
 'ACCOUNTABILITY GAP: Unlike governments, private foundations face no electoral accountability. Bill and Melinda Gates made decisions affecting billions of people\'s health, answerable to no one except themselves. After their divorce, Melinda departed the Foundation, concentrating power further.',
 'COVID-19 RESPONSE INFLUENCE: During the pandemic, Gates Foundation positions on vaccine IP, distribution, and technology influenced global response. The Foundation\'s initial opposition to patent waivers may have delayed vaccine production in developing countries.',
 'RESEARCH PUBLICATION CONTROL: Gates Foundation funding of health journals and academic institutions creates potential conflicts. Research contradicting Foundation priorities may face publication barriers. The Foundation shapes what knowledge is produced and disseminated.',
 'AGRICULTURAL HEALTH INTERSECTION: Gates Foundation agricultural programs (promoting GMOs, synthetic fertilizers, and specific crop varieties) intersect with health. Critics argue these programs benefit agribusiness investors while not addressing underlying food insecurity causes.',
 'GAVI VACCINE ALLIANCE: Gates Foundation co-founded and funds GAVI, which purchases and distributes vaccines globally. While this has expanded vaccination, it also creates a market for pharmaceutical company products in which the Foundation holds investments.',
 'DEMOCRATIC DEFICIT: The most fundamental critique: health decisions should be made by affected populations through democratic processes, not by billionaire philanthropists. The Gates model of technocratic intervention bypasses democratic input and accountability.',
 ],
 tags: ['Global Health', 'WHO', 'Gates Foundation', 'Vaccines', 'Health Policy', 'Accountability', 'GAVI', 'Polio'],
 sources: [
 { title: 'WHO Funding Sources', url: 'https://www.who.int/about/funding', type: 'Official Source' },
 { title: 'Lancet Analysis of Gates Foundation', url: 'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(09)60885-0/fulltext', type: 'Academic' },
 { title: 'GAVI Funding Structure', url: 'https://www.gavi.org/investing-gavi/funding', type: 'Official Source' },
 ],
 affiliations: [
 { id: '1', name: 'Bill Gates', type: 'individual', relationship: 'Foundation co-chair', href: '/entities/individuals/bill-gates' },
 { id: '2', name: 'WHO', type: 'organization', relationship: 'Major funding recipient', href: '/entities/organizations/who' },
 { id: '3', name: 'CDC', type: 'agency', relationship: 'US health guidance', href: '/entities/agencies/cdc' },
 ],
 },
  'helsinki-summit': {
 title: 'Helsinki Summit - Trump Sides with Putin',
 subtitle: 'Trump publicly takes Putin\'s word over US intelligence agencies',
 severity: 'critical',
 category: 'National Security',
 date: 'July 16, 2018',
 lastUpdated: 'February 12, 2026',
 summary: 'At a joint press conference with Vladimir Putin in Helsinki, President Trump was asked whether he believed Russia interfered in the 2016 election. Standing beside Putin, Trump said he saw no reason why Russia"would"interfere, taking Putin\'s denial over the unanimous conclusion of U.S. intelligence agencies. Even Republicans called it shameful.',
 content: [
 'THE QUESTION: A reporter asked Trump if he believed his own intelligence agencies or Putin regarding Russian election interference. U.S. intelligence had unanimously concluded Russia interfered to help Trump.',
 'TRUMP\'S ANSWER:"President Putin says it\'s not Russia. I don\'t see any reason why it would be... I have great confidence in my intelligence people, but I will tell you that President Putin was extremely strong and powerful in his denial today."',
 'BIPARTISAN CONDEMNATION: Even Republicans were shocked. John McCain called it"one of the most disgraceful performances by an American president in memory."Paul Ryan said"Russia meddled in our elections."',
 'PRIVATE MEETING: Before the press conference, Trump met privately with Putin for over two hours with only interpreters present. Trump took the interpreter\'s notes and directed them not to discuss the conversation.',
 'WALK-BACK ATTEMPT: The next day, Trump claimed he meant to say"wouldn\'t"instead of"would"- a claim no one found credible given his fulsome praise of Putin.',
 'INTELLIGENCE COMMUNITY: Director of National Intelligence Dan Coats had just days earlier stated Russia continued to target U.S. elections. Trump contradicted his own appointee.',
 'PATTERN: Helsinki fit a pattern of Trump refusing to criticize Putin, questioning NATO, and advancing Russian foreign policy goals.',
 'UNANSWERED QUESTIONS: What was discussed in the private meeting remains unknown. Trump went to extraordinary lengths to prevent disclosure of his Putin conversations.',
 ],
 tags: ['Russia', 'Putin', 'Helsinki', 'Intelligence', 'National Security', 'Treason'],
 sources: [
 { title: 'Full Press Conference Video', url: 'https://www.c-span.org/video/?448333-1/president-trump-russian-president-putin-hold-joint-news-conference', type: 'Primary Source' },
 { title: 'ODNI Assessment', url: 'https://www.dni.gov/files/documents/ICA_2017_01.pdf', type: 'Government Report' },
 { title: 'Interpreter Notes Reporting', url: 'https://www.washingtonpost.com/world/national-security/trump-has-concealed-details-of-his-face-to-face-encounters-with-putin-from-senior-officials-in-administration/2019/01/12/65f6686c-1434-11e9-b6ad-9cfd62dbb0a8_story.html', type: 'Investigation' },
 ],
 affiliations: [
 { id: '1', name: 'Donald Trump', type: 'individual', relationship: 'Sided with Putin over US intelligence', href: '/entities/individuals/donald-trump' },
 { id: '2', name: 'Vladimir Putin', type: 'individual', relationship: 'Russian President, denied interference', href: '/entities/individuals/vladimir-putin' },
 { id: '3', name: 'Dan Coats', type: 'individual', relationship: 'DNI, publicly contradicted by Trump', href: '/entities/individuals/dan-coats' },
 ],
 },
  'hedge-fund-predation': {
 title: 'Hedge Fund Predatory Practices',
 subtitle: 'Wall Street\'s extraction machine targeting companies and markets',
 severity: 'high',
 category: 'Economic Exploitation',
 date: 'February 17, 2010',
 lastUpdated: 'February 15, 2026',
 summary: 'Hedge funds manage trillions of dollars with minimal regulation and maximum aggression. They engage in predatory short selling, drive companies into bankruptcy, manipulate markets, and extract wealth while producing nothing. From attacking currencies to raiding pension funds to destroying retailers, hedge funds exemplify finance capitalism at its most destructive, privatizing gains and socializing losses.',
 content: [
 'THE HEDGE FUND MODEL: Hedge funds are lightly regulated investment vehicles for wealthy investors. They charge"2 and 20"|2% of assets plus 20% of profits. This creates incentives for aggressive strategies that maximize manager compensation, not investor returns.',
 'PREDATORY SHORT SELLING: Short selling bets that stock prices will fall. While sometimes legitimate, hedge funds use short selling to attack companies, spreading negative research (sometimes false), coordinating selling pressure, and profiting from the destruction they cause.',
 'NAKED SHORTING: Illegal"naked"short selling, selling shares without actually borrowing them, creates artificial selling pressure. Despite being illegal, enforcement is rare and penalties weak. GameStop investors exposed the practice in 2021.',
 'CURRENCY ATTACKS: George Soros famously"broke the Bank of England"in 1992, profiting $1 billion by attacking the British pound. Hedge funds have attacked currencies of multiple countries, profiting from economic chaos they help create.',
 'ACTIVIST RAIDING:"Activist"hedge funds buy company stakes and pressure management for changes that boost short-term stock prices, often layoffs, asset sales, or debt-funded buybacks. Long-term damage to companies is irrelevant to quick profits.',
 'RETAIL DESTRUCTION: Hedge funds played key roles in destroying American retail. They loaded companies with debt through leveraged buyouts, extracted fees, then let companies collapse. Sears, Toys R Us, and others fell to this playbook.',
 'GAMESTOP SAGA: In January 2021, retail investors coordinated to buy GameStop stock, squeezing short-selling hedge funds. Melvin Capital lost 53% in a month. The incident revealed hedge fund vulnerability and sparked debate about market fairness.',
 'HIGH-FREQUENCY TRADING: Some hedge funds use high-frequency trading to front-run orders, essentially skimming pennies from every trade. They add no value to markets while extracting billions through speed advantages ordinary investors can\'t match.',
 'TAX AVOIDANCE: Hedge fund managers benefit from the"carried interest"loophole, paying capital gains rates (lower) on what is effectively ordinary income. This single loophole costs billions annually and persists due to lobbying.',
 'PENSION FUND EXTRACTION: Pension funds, seeking higher returns, invest heavily in hedge funds despite evidence that hedge funds underperform simple index funds. Hedge managers extract billions in fees from retirement savings.',
 'REGULATORY CAPTURE: Hedge funds spend heavily on lobbying and employ former regulators. The SEC rarely challenges hedge fund practices. When enforcement occurs, fines are typically far less than profits gained from violations.',
 'SYSTEMIC RISK: Hedge funds are so large and interconnected that their failures can threaten the financial system. Long-Term Capital Management\'s 1998 collapse required a Federal Reserve-organized bailout. The risk hasn\'t gone away.',
 ],
 tags: ['Hedge Funds', 'Short Selling', 'Wall Street', 'GameStop', 'Financial Predation', 'Market Manipulation', 'Carried Interest'],
 sources: [
 { title: 'SEC - Hedge Fund Oversight', url: 'https://www.sec.gov/spotlight/hedgefunds.htm', type: 'Government Resource' },
 { title: 'GameStop Congressional Hearing', url: 'http://web.archive.org/web/20221209105844/https://financialservices.house.gov/events/eventsingle.aspx?EventID=407107', type: 'Congressional' },
 { title: 'NYT - How Private Equity Killed Toys R Us', url: 'https://www.nytimes.com/2018/03/15/business/toys-r-us-bankruptcy.html', type: 'Investigation' },
 { title: 'Flash Boys by Michael Lewis', url: 'https://wwnorton.com/books/9780393351590', type: 'Book' },
 ],
 affiliations: [
 { id: '1', name: 'Citadel', type: 'corporation', relationship: 'Major hedge fund, GameStop involvement', href: '/entities/corporations/citadel' },
 { id: '2', name: 'Elliott Management', type: 'corporation', relationship: 'Aggressive activist fund', href: '/entities/corporations/elliott-management' },
 { id: '3', name: 'Paul Singer', type: 'individual', relationship: 'Elliott founder, vulture capitalist', href: '/entities/individuals/paul-singer' },
 { id: '4', name: 'SEC', type: 'agency', relationship: 'Weak regulatory oversight', href: '/entities/agencies/sec' },
 ],
 },
  'hate-crimes': {
 title: 'Hate Crimes',
 subtitle: 'Investigation into hate crimes.',
 severity: 'high',
 category: 'Financial Crime',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into hate crimes.',
 content: [
 'This investigation documents hate crimes and its impact.',
 ],
 tags: ['Financial Crime', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'healthcare-capture': {
 title: 'Healthcare Capture',
 subtitle: 'Investigation into healthcare capture.',
 severity: 'critical',
 category: 'Public Health',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into healthcare capture.',
 content: [
 'This investigation documents healthcare capture and its impact.',
 ],
 tags: ['Public Health', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'healthcare-profiteering': {
 title: 'Healthcare Profiteering',
 subtitle: 'Investigation into healthcare profiteering.',
 severity: 'critical',
 category: 'Public Health',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into healthcare profiteering.',
 content: [
 'This investigation documents healthcare profiteering and its impact.',
 ],
 tags: ['Public Health', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'hedge-fund-corruption': {
 title: 'Hedge Fund Corruption',
 subtitle: 'Investigation into hedge fund corruption.',
 severity: 'high',
 category: 'Financial Crime',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into hedge fund corruption.',
 content: [
 'This investigation documents hedge fund corruption and its impact.',
 ],
 tags: ['Financial Crime', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'hedge-fund-manipulation': {
 title: 'Hedge Fund Manipulation',
 subtitle: 'Investigation into hedge fund manipulation.',
 severity: 'high',
 category: 'Corporate Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into hedge fund manipulation.',
 content: [
 'This investigation documents hedge fund manipulation and its impact.',
 ],
 tags: ['Corporate Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'hollywood-abuse': {
 title: 'Hollywood Abuse',
 subtitle: 'Investigation into hollywood abuse.',
 severity: 'critical',
 category: 'Abuse & Exploitation',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into hollywood abuse.',
 content: [
 'This investigation documents hollywood abuse and its impact.',
 ],
 tags: ['Abuse & Exploitation', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'housing-crisis': {
 title: 'Housing Crisis',
 subtitle: 'Investigation into housing crisis.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into housing crisis.',
 content: [
 'This investigation documents housing crisis and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'housing-financialization': {
 title: 'Housing Financialization',
 subtitle: 'Investigation into housing financialization.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into housing financialization.',
 content: [
 'This investigation documents housing financialization and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'human-trafficking': {
 title: 'Human Trafficking',
 subtitle: 'Investigation into human trafficking.',
 severity: 'critical',
 category: 'Abuse & Exploitation',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into human trafficking.',
 content: [
 'This investigation documents human trafficking and its impact.',
 ],
 tags: ['Abuse & Exploitation', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
  'hedge-fund-market-manipulation': {
    title: 'Hedge Fund Market Manipulation',
    subtitle: 'Investigation into Hedge Fund Market Manipulation',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Hedge Fund Market Manipulation for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Hedge Fund Market Manipulation has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'human-trafficking-global-networks': {
    title: 'Human Trafficking Global Networks',
    subtitle: 'Investigation into Human Trafficking Global Networks',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Human Trafficking Global Networks for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Human Trafficking Global Networks has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'human-smuggling-cartel-operations': {
    title: 'Human Smuggling Cartel Operations',
    subtitle: 'Investigation into Human Smuggling Cartel Operations',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Human Smuggling Cartel Operations for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Human Smuggling Cartel Operations has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'hospital-price-transparency-failures': {
    title: 'Hospital Price Transparency Failures',
    subtitle: 'Investigation into Hospital Price Transparency Failures',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Hospital Price Transparency Failures for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Hospital Price Transparency Failures has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'hotel-industry-trafficking-complicity-report': {
    title: 'Hotel Industry Trafficking Complicity Report',
    subtitle: 'Investigation into Hotel Industry Trafficking Complicity Report',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Hotel Industry Trafficking Complicity Report for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Hotel Industry Trafficking Complicity Report has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'health-data-privacy-violation-patterns': {
    title: 'Health Data Privacy Violation Patterns',
    subtitle: 'Investigation into Health Data Privacy Violation Patterns',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Health Data Privacy Violation Patterns for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Health Data Privacy Violation Patterns has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },






 },
};

export default investigations_h;
