// AUTO-GENERATED by ArkHive Migration — DO NOT EDIT MANUALLY
import type { InvestigationData } from './types';

const investigations_j: Record<string, InvestigationData> = {
  'judicial-capture': {
 title: 'Judicial Capture by Federalist Society',
 subtitle: 'The systematic takeover of federal courts by conservative ideologues',
 severity: 'critical',
 category: 'Institutional Corruption',
 date: 'July 11, 2023',
 lastUpdated: 'February 15, 2026',
 summary: 'The Federalist Society has executed a 40-year campaign to capture the federal judiciary. Through vetting judicial nominees, training conservative lawyers, and building an ideological pipeline, the organization now effectively controls who becomes a federal judge for Republican presidents. The result is a judiciary hostile to regulation, voting rights, reproductive freedom, and separation of church and state.',
 content: [
 'FEDERALIST SOCIETY FOUNDING: Founded in 1982 at Yale, Harvard, and Chicago law schools, the Federalist Society built a network of conservative lawyers opposed to the"liberal"legal establishment. It became the dominant force in conservative legal circles.',
 'JUDICIAL PIPELINE: The Society identifies and grooms potential judges from law school through clerkships, government positions, and the federal bar. By the time someone is nominated, they have been vetted for ideological purity for decades.',
 'TRUMP OUTSOURCING: Trump openly outsourced judicial selection to the Federalist Society and Leonard Leo. He published lists of potential Supreme Court nominees created by the organization. No modern president has so completely delegated judicial appointments.',
 'THREE SUPREME COURT JUSTICES: Trump appointed Neil Gorsuch, Brett Kavanaugh, and Amy Coney Barrett - all Federalist Society members or affiliated - creating a 6-3 conservative supermajority that has transformed American law.',
 'OVERTURNING ROE: The conservative Court overturned Roe v. Wade in Dobbs v. Jackson (2022), ending 50 years of constitutional abortion rights. All three Trump justices voted to overturn despite suggesting respect for precedent during confirmation.',
 'GUTTING VOTING RIGHTS: In Shelby County v. Holder (2013), the Court gutted the Voting Rights Act. In Brnovich (2021), it further weakened voting protections. Republican states rushed to implement restrictions.',
 'EXPANDING GUN RIGHTS: In Bruen (2022), the Court dramatically expanded gun rights, striking down New York\'s concealed carry law and creating a new"historical tradition"test that threatens most gun regulations.',
 'SHRINKING REGULATION: The Court has systematically limited agency authority. West Virginia v. EPA (2022) created the"major questions doctrine"to limit regulation. Chevron deference, which had supported agency expertise, faces elimination.',
 'RELIGIOUS FAVORITISM: The Court has consistently ruled for religious claims over other rights. Kennedy v. Bremerton (2022) allowed public school coach prayer. Carson v. Makin (2022) required public funding for religious schools.',
 'CIRCUIT COURTS: Beyond the Supreme Court, Trump appointed over 50 circuit court judges - all Federalist Society vetted - creating conservative majorities on most circuit courts. These judges hear most federal appeals.',
 'DISTRICT COURTS: Trump appointed over 170 district court judges who will serve lifetime appointments. Many were rated"not qualified"by the ABA but confirmed anyway. Cases like Texas abortion and immigration rulings come from these courts.',
 'LIFETIME IMPACT: Federal judges serve for life. The Trump judges will shape law for decades regardless of future elections. The judicial capture is designed to outlast democratic accountability.',
 ],
 tags: ['Federalist Society', 'Supreme Court', 'Leonard Leo', 'Judicial Appointments', 'Trump Judges', 'Conservative Courts'],
 sources: [
 { title: 'Federalist Society Influence Study', url: 'https://www.americanprogress.org/article/the-federalist-society/', type: 'Research' },
 { title: 'Trump Judicial Appointments Analysis', url: 'https://www.pewresearch.org/short-reads/2021/01/13/how-trump-compares-with-other-recent-presidents-in-appointing-federal-judges/', type: 'Research' },
 { title: 'Dobbs v. Jackson Decision', url: 'https://www.supremecourt.gov/opinions/21pdf/19-1392_6j37.pdf', type: 'Court Opinion' },
 { title: 'Dark Money by Jane Mayer', url: 'https://www.penguinrandomhouse.com/books/215462/dark-money-by-jane-mayer/', type: 'Book' },
 { title: 'ABA Not Qualified Ratings', url: 'https://www.americanbar.org/groups/committees/federal_judiciary/ratings/', type: 'Professional Rating' },
 ],
 affiliations: [
 { id: '1', name: 'Federalist Society', type: 'organization', relationship: 'Judicial selection machine', href: '/entities/organizations/federalist-society' },
 { id: '2', name: 'Leonard Leo', type: 'individual', relationship: 'Network architect, $1.6B dark money', href: '/entities/individuals/leonard-leo' },
 { id: '3', name: 'Donald Trump', type: 'individual', relationship: 'Outsourced judicial selection', href: '/entities/individuals/donald-trump' },
 { id: '4', name: 'Clarence Thomas', type: 'individual', relationship: 'Federalist Society-connected justice', href: '/entities/individuals/clarence-thomas' },
 { id: '5', name: 'Samuel Alito', type: 'individual', relationship: 'Wrote Dobbs decision', href: '/entities/individuals/samuel-alito' },
 { id: '6', name: 'Neil Gorsuch', type: 'individual', relationship: 'Trump\'s first SCOTUS appointment', href: '/entities/individuals/neil-gorsuch' },
 { id: '7', name: 'Brett Kavanaugh', type: 'individual', relationship: 'Trump SCOTUS appointment', href: '/entities/individuals/brett-kavanaugh' },
 { id: '8', name: 'Amy Coney Barrett', type: 'individual', relationship: 'Trump SCOTUS appointment', href: '/entities/individuals/amy-coney-barrett' },
 { id: '9', name: 'Supreme Court', type: 'agency', relationship: 'Captured institution', href: '/entities/agencies/supreme-court' },
 ],
 },
  'january-6-investigation': {
 title: 'January 6 Investigation',
 subtitle: 'Investigation into january 6 investigation.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into january 6 investigation.',
 content: [
 'This investigation documents january 6 investigation and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'january-6th': {
 title: 'January 6th',
 subtitle: 'Investigation into january 6th.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into january 6th.',
 content: [
 'This investigation documents january 6th and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'jj-baby-powder': {
 title: 'JJ Baby Powder',
 subtitle: 'Investigation into jj baby powder.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into jj baby powder.',
 content: [
 'This investigation documents jj baby powder and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'juul-vaping-epidemic': {
 title: 'Juul Vaping Epidemic',
 subtitle: 'Investigation into juul vaping epidemic.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into juul vaping epidemic.',
 content: [
 'This investigation documents juul vaping epidemic and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'journalistic-source-protection-failures': {
    title: 'Journalistic Source Protection Failures',
    subtitle: 'Investigation into Journalistic Source Protection Failures',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Journalistic Source Protection Failures for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Journalistic Source Protection Failures has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'juvenile-justice-system-failures': {
    title: 'Juvenile Justice System Failures',
    subtitle: 'Investigation into Juvenile Justice System Failures',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Juvenile Justice System Failures for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Juvenile Justice System Failures has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },


};

export default investigations_j;
