// AUTO-GENERATED by ArkHive Migration — DO NOT EDIT MANUALLY
import type { InvestigationData } from './types';

const investigations_o: Record<string, InvestigationData> = {
  'oath-keepers': {
 title: 'Oath Keepers',
 subtitle: 'Investigation into oath keepers.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into oath keepers.',
 content: [
 'This investigation documents oath keepers and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'obesity-epidemic': {
 title: 'Obesity Epidemic',
 subtitle: 'Investigation into obesity epidemic.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into obesity epidemic.',
 content: [
 'This investigation documents obesity epidemic and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'ohio-state-abuse': {
 title: 'Ohio State Abuse',
 subtitle: 'Investigation into ohio state abuse.',
 severity: 'critical',
 category: 'Abuse & Exploitation',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into ohio state abuse.',
 content: [
 'This investigation documents ohio state abuse and its impact.',
 ],
 tags: ['Abuse & Exploitation', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'okc-bombing': {
 title: 'OKC Bombing',
 subtitle: 'Investigation into okc bombing.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into okc bombing.',
 content: [
 'This investigation documents okc bombing and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'opioid-distribution': {
 title: 'Opioid Distribution',
 subtitle: 'Investigation into opioid distribution.',
 severity: 'critical',
 category: 'Public Health',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into opioid distribution.',
 content: [
 'This investigation documents opioid distribution and its impact.',
 ],
 tags: ['Public Health', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'opioid-epidemic': {
 title: 'Opioid Epidemic',
 subtitle: 'Investigation into opioid epidemic.',
 severity: 'critical',
 category: 'Public Health',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into opioid epidemic.',
 content: [
 'This investigation documents opioid epidemic and its impact.',
 ],
 tags: ['Public Health', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'oversight-abuse': {
 title: 'Oversight Abuse',
 subtitle: 'Investigation into oversight abuse.',
 severity: 'critical',
 category: 'Abuse & Exploitation',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into oversight abuse.',
 content: [
 'This investigation documents oversight abuse and its impact.',
 ],
 tags: ['Abuse & Exploitation', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'oxford-shooting': {
 title: 'Oxford Shooting',
 subtitle: 'Investigation into oxford shooting.',
 severity: 'critical',
 category: 'Violence & Justice',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into oxford shooting.',
 content: [
 'This investigation documents oxford shooting and its impact.',
 ],
 tags: ['Violence & Justice', 'Gun Violence', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
  'offshore-tax-haven-architecture': {
    title: 'Offshore Tax Haven Architecture',
    subtitle: 'Investigation into Offshore Tax Haven Architecture',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Offshore Tax Haven Architecture for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Offshore Tax Haven Architecture has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'organized-crime-in-construction-industry': {
    title: 'Organized Crime in Construction Industry',
    subtitle: 'Investigation into Organized Crime in Construction Industry',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Organized Crime in Construction Industry for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Organized Crime in Construction Industry has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-chaos-domestic-spying': {
    title: 'Operation Chaos Domestic Spying',
    subtitle: 'Investigation into Operation Chaos Domestic Spying',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Chaos Domestic Spying for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Chaos Domestic Spying has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-mockingbird-media-infiltration': {
    title: 'Operation Mockingbird Media Infiltration',
    subtitle: 'Investigation into Operation Mockingbird Media Infiltration',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Mockingbird Media Infiltration for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Mockingbird Media Infiltration has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-northwoods-false-flag-planning': {
    title: 'Operation Northwoods False Flag Planning',
    subtitle: 'Investigation into Operation Northwoods False Flag Planning',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Northwoods False Flag Planning for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Northwoods False Flag Planning has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-paperclip-nazi-scientist-import': {
    title: 'Operation Paperclip Nazi Scientist Import',
    subtitle: 'Investigation into Operation Paperclip Nazi Scientist Import',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Paperclip Nazi Scientist Import for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Paperclip Nazi Scientist Import has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-condor-latin-america-terror': {
    title: 'Operation Condor Latin America Terror',
    subtitle: 'Investigation into Operation Condor Latin America Terror',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Condor Latin America Terror for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Condor Latin America Terror has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-gladio-stay-behind-networks': {
    title: 'Operation Gladio Stay-Behind Networks',
    subtitle: 'Investigation into Operation Gladio Stay-Behind Networks',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Gladio Stay-Behind Networks for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Gladio Stay-Behind Networks has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-fast-and-furious-gun-walking': {
    title: 'Operation Fast and Furious Gun Walking',
    subtitle: 'Investigation into Operation Fast and Furious Gun Walking',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Fast and Furious Gun Walking for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Fast and Furious Gun Walking has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-pbsuccess-guatemala-coup': {
    title: 'Operation PBSUCCESS Guatemala Coup',
    subtitle: 'Investigation into Operation PBSUCCESS Guatemala Coup',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation PBSUCCESS Guatemala Coup for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation PBSUCCESS Guatemala Coup has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'opioid-crisis-manufacturer-liability': {
    title: 'Opioid Crisis Manufacturer Liability',
    subtitle: 'Investigation into Opioid Crisis Manufacturer Liability',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Opioid Crisis Manufacturer Liability for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Opioid Crisis Manufacturer Liability has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-ajax-iran-coup-1953': {
    title: 'Operation Ajax Iran Coup 1953',
    subtitle: 'Investigation into Operation Ajax Iran Coup 1953',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Ajax Iran Coup 1953 for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Ajax Iran Coup 1953 has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'ocean-pollution-industrial-scale': {
    title: 'Ocean Pollution Industrial Scale',
    subtitle: 'Investigation into Ocean Pollution Industrial Scale',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Ocean Pollution Industrial Scale for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Ocean Pollution Industrial Scale has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'oil-spill-cover-up-history': {
    title: 'Oil Spill Cover-Up History',
    subtitle: 'Investigation into Oil Spill Cover-Up History',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Oil Spill Cover-Up History for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Oil Spill Cover-Up History has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'operation-mockingbird-modern-successors': {
    title: 'Operation Mockingbird Modern Successors',
    subtitle: 'Investigation into Operation Mockingbird Modern Successors',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Operation Mockingbird Modern Successors for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Operation Mockingbird Modern Successors has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'off-label-drug-promotion-violations': {
    title: 'Off-Label Drug Promotion Violations',
    subtitle: 'Investigation into Off-Label Drug Promotion Violations',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Off-Label Drug Promotion Violations for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Off-Label Drug Promotion Violations has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'online-radicalization-pipeline-architecture': {
    title: 'Online Radicalization Pipeline Architecture',
    subtitle: 'Investigation into Online Radicalization Pipeline Architecture',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Online Radicalization Pipeline Architecture for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Online Radicalization Pipeline Architecture has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },

















 },
};

export default investigations_o;
