// AUTO-GENERATED by ArkHive Migration — DO NOT EDIT MANUALLY
import type { InvestigationData } from './types';

const investigations_o: Record<string, InvestigationData> = {
  'oath-keepers': {
 title: 'Oath Keepers',
 subtitle: 'Investigation into oath keepers.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into oath keepers.',
 content: [
 'This investigation documents oath keepers and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'obesity-epidemic': {
 title: 'Obesity Epidemic',
 subtitle: 'Investigation into obesity epidemic.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into obesity epidemic.',
 content: [
 'This investigation documents obesity epidemic and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'ohio-state-abuse': {
 title: 'Ohio State Abuse',
 subtitle: 'Investigation into ohio state abuse.',
 severity: 'critical',
 category: 'Abuse & Exploitation',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into ohio state abuse.',
 content: [
 'This investigation documents ohio state abuse and its impact.',
 ],
 tags: ['Abuse & Exploitation', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'okc-bombing': {
 title: 'OKC Bombing',
 subtitle: 'Investigation into okc bombing.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into okc bombing.',
 content: [
 'This investigation documents okc bombing and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'opioid-distribution': {
 title: 'Opioid Distribution',
 subtitle: 'Investigation into opioid distribution.',
 severity: 'critical',
 category: 'Public Health',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into opioid distribution.',
 content: [
 'This investigation documents opioid distribution and its impact.',
 ],
 tags: ['Public Health', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'opioid-epidemic': {
 title: 'Opioid Epidemic',
 subtitle: 'Investigation into opioid epidemic.',
 severity: 'critical',
 category: 'Public Health',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into opioid epidemic.',
 content: [
 'This investigation documents opioid epidemic and its impact.',
 ],
 tags: ['Public Health', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'oversight-abuse': {
 title: 'Oversight Abuse',
 subtitle: 'Investigation into oversight abuse.',
 severity: 'critical',
 category: 'Abuse & Exploitation',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into oversight abuse.',
 content: [
 'This investigation documents oversight abuse and its impact.',
 ],
 tags: ['Abuse & Exploitation', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'oxford-shooting': {
 title: 'Oxford Shooting',
 subtitle: 'Investigation into oxford shooting.',
 severity: 'critical',
 category: 'Violence & Justice',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into oxford shooting.',
 content: [
 'This investigation documents oxford shooting and its impact.',
 ],
 tags: ['Violence & Justice', 'Gun Violence', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
  'offshore-tax-haven-architecture': {
    title: 'Offshore Tax Haven Architecture',
    subtitle: 'Investigation into Offshore Tax Haven Architecture',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Offshore Tax Haven Architecture for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Offshore Tax Haven Architecture has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },

 },
};

export default investigations_o;
