// AUTO-GENERATED by ArkHive Migration — DO NOT EDIT MANUALLY
import type { InvestigationData } from './types';

const investigations_q: Record<string, InvestigationData> = {
  'qatar-extortion': {
 title: 'Qatar Blockade Extortion',
 subtitle: 'How the Kushners leveraged a diplomatic crisis for personal profit',
 severity: 'critical',
 category: 'Corruption',
 date: 'June 5, 2017',
 lastUpdated: 'February 15, 2026',
 summary: 'In June 2017, Saudi Arabia and the UAE launched a blockade of Qatar. The Kushner family had been seeking Qatari investment to bail out their troubled 666 Fifth Avenue property. After Qatar declined to invest, Jared Kushner supported the blockade, and Trump initially endorsed it. Eventually, Qatar-linked investors rescued the Kushner building. Critics allege the Kushners used American foreign policy as leverage for personal financial gain, a quid pro quo of historic proportions.',
 content: [
 'THE KUSHNER CRISIS: The Kushner family\'s 666 Fifth Avenue property was a financial disaster. Purchased in 2007 for a record $1.8 billion just before the crash, it was hemorrhaging money. A $1.4 billion loan was coming due in 2019. The Kushners desperately sought foreign investment.',
 'APPROACHING QATAR: In April 2017, Charles Kushner met with Qatar\'s finance minister about investing in 666 Fifth Avenue. Qatar declined. Within weeks, Jared Kushner was reportedly supporting a blockade of Qatar pushed by Saudi Arabia and the UAE.',
 'THE BLOCKADE: On June 5, 2017, Saudi Arabia, UAE, Bahrain, and Egypt severed ties with Qatar. Trump initially enthusiastically endorsed the blockade, tweeting support and claiming credit, despite Qatar hosting the largest U.S. military base in the Middle East.',
 'JARED\'S ROLE: According to reporting, Jared Kushner sided with Saudi Arabia and UAE in internal White House debates. Secretary of State Tillerson and Defense Secretary Mattis opposed the blockade; Kushner supported it. His family had just been rejected for Qatari investment.',
 'TILLERSON MARGINALIZED: When Tillerson tried to mediate the crisis, he was undermined by Kushner\'s separate channel to MBZ and MBS. The New York Times reported Kushner was"running a shadow diplomacy"that contradicted official U.S. policy.',
 'THE 666 BAILOUT: In August 2018, Brookfield Asset Management agreed to a 99-year lease on 666 Fifth Avenue, rescuing the Kushners from their financial disaster. Brookfield received significant investment from the Qatar Investment Authority.',
 'THE QATAR CONNECTION: While Brookfield insisted the Qatar fund was a passive investor with no say in decisions, the timing was extraordinary. Qatar-linked money rescued Kushner\'s family from financial ruin after the blockade pressure.',
 'CONFLICTS OF INTEREST: Jared Kushner never fully divested from his family business while serving in the White House. His security clearance was initially denied due to foreign contacts and financial entanglements. Trump personally intervened to grant it.',
 'NO INVESTIGATION: Despite the apparent conflict between Kushner\'s official duties and family financial interests, no serious investigation occurred. The Trump DOJ showed no interest in examining the 666 Fifth Avenue connection.',
 'BROADER PATTERN: The Qatar situation exemplified Kushner\'s approach: mixing family business with government authority, conducting shadow diplomacy, siding with foreign autocrats, and benefiting financially from his position.',
 'MBS RELATIONSHIP: Kushner\'s relationship with Saudi Crown Prince MBS extended beyond Qatar. He reportedly shared intelligence with MBS, supported the Yemen war, and downplayed the Khashoggi murder. After leaving office, his firm received $2 billion from Saudi Arabia.',
 'UNANSWERED QUESTIONS: Did the Kushners use the blockade as leverage? Was the Brookfield deal a payoff? Why did Trump reverse course on Qatar? The full truth of the 666 Fifth Avenue saga remains hidden.',
 ],
 tags: ['Jared Kushner', 'Qatar', '666 Fifth Avenue', 'Conflict of Interest', 'Saudi Arabia', 'UAE', 'Corruption'],
 sources: [
 { title: 'NYT - 666 Fifth Avenue Bailout', url: 'https://www.nytimes.com/2018/08/03/nyregion/kushners-building-fifth-avenue-brookfield-lease.html', type: 'News Report' },
 { title: 'Brookfield Qatar Investment Connection', url: 'https://www.bloomberg.com/news/articles/2018-08-03/kushner-cos-deal-for-666-fifth-ave-is-said-to-be-near-close', type: 'News Report' },
 { title: 'Kushner Security Clearance Issues', url: 'https://www.washingtonpost.com/politics/2019/01/24/jared-kushners-security-clearance-was-initially-denied-due-concerns-about-foreign-influence/', type: 'Investigation' },
 ],
 affiliations: [
 { id: '1', name: 'Jared Kushner', type: 'individual', relationship: 'Central figure with conflicting interests', href: '/entities/individuals/jared-kushner' },
 { id: '2', name: 'Charles Kushner', type: 'individual', relationship: 'Sought Qatari investment for 666 Fifth Ave', href: '/entities/individuals/charles-kushner' },
 { id: '3', name: 'Donald Trump', type: 'individual', relationship: 'Initially endorsed blockade', href: '/entities/individuals/donald-trump' },
 { id: '4', name: 'Mohammed bin Salman', type: 'individual', relationship: 'Led Saudi side of blockade', href: '/entities/individuals/mohammed-bin-salman' },
 { id: '5', name: 'Mohammed bin Zayed', type: 'individual', relationship: 'Led UAE side of blockade', href: '/entities/individuals/mohammed-bin-zayed' },
 { id: '6', name: 'Kushner Companies', type: 'corporation', relationship: 'Benefited from resolution', href: '/entities/corporations/kushner-companies' },
 ],
 },
};

export default investigations_q;
