// AUTO-GENERATED by ArkHive Migration — DO NOT EDIT MANUALLY
import type { InvestigationData } from './types';

const investigations_v: Record<string, InvestigationData> = {
  'vulture-capitalism': {
 title: 'Vulture Fund Capitalism',
 subtitle: 'How billionaire investors prey on distressed nations and companies',
 severity: 'high',
 category: 'Economic Exploitation',
 date: 'October 13, 2009',
 lastUpdated: 'February 15, 2026',
 summary: 'Vulture funds are investment firms that buy distressed debt, from failing companies or impoverished nations, for pennies on the dollar, then use aggressive legal tactics to extract full payment. Paul Singer\'s Elliott Management is the most notorious practitioner, having sued Argentina for over a decade and seized an Argentine naval ship. Vulture capitalism extracts wealth from the desperate while contributing nothing productive.',
 content: [
 'THE VULTURE BUSINESS MODEL: Vulture funds buy debt of distressed entities at steep discounts, sometimes 10 cents on the dollar. They then refuse restructuring agreements and use litigation to demand full face value plus interest. Profits can exceed 1000%.',
 'PAUL SINGER AND ELLIOTT MANAGEMENT: Billionaire Paul Singer runs Elliott Management, the world\'s most aggressive vulture fund. Elliott has sued governments, seized state assets, and extracted billions from countries unable to defend themselves in court.',
 'ARGENTINA SAGA: When Argentina defaulted in 2001, most creditors accepted restructured debt. Elliott refused, sued, and won a U.S. court order blocking Argentina from paying other creditors. Argentina was shut out of credit markets for years.',
 'SEIZING A WARSHIP: In 2012, at Elliott\'s request, Ghana seized Argentina\'s naval training ship with 300 crew aboard. The crew was held for weeks. The spectacle of a hedge fund seizing a nation\'s warship illustrated vulture capitalism\'s power.',
 'TARGETING POOR COUNTRIES: Vulture funds have sued some of the world\'s poorest nations, Zambia, Congo, Liberia. They buy old debt from these countries\' creditors for nothing, then demand full payment, diverting resources from poverty reduction.',
 'CORPORATE VULTURES: Vulture funds also target distressed companies, buying debt to gain control through bankruptcy, stripping assets, and discarding workers. They profit from destroying rather than building.',
 'LEGAL ARBITRAGE: Vultures exploit differences between jurisdictions. Debt governed by New York law is particularly vulnerable because U.S. courts enforce creditor rights aggressively without considering consequences for debtor nations.',
 'HOLDOUT PROBLEM: When most creditors agree to restructure, vultures refuse and demand full payment. This"holdout"strategy lets them extract more than cooperative creditors, discouraging future restructurings.',
 'LOBBYING AGAINST REFORM: Vulture funds lobby intensively against legislation that would limit their tactics. They\'ve killed bills in Congress that would have required them to accept restructuring terms others accept.',
 'PUERTO RICO: When Puerto Rico faced debt crisis, vulture funds bought bonds cheap and demanded full payment despite the island\'s devastation. They opposed restructuring, prioritizing bondholder profits over school funding and healthcare.',
 'SINGER\'S POLITICAL INFLUENCE: Paul Singer is a major Republican donor. His political spending helps protect vulture fund business practices from reform. He funded opposition research on Trump before becoming a Trump supporter.',
 'WEALTH EXTRACTION: Vulture capitalism is wealth extraction, not creation. It produces nothing of value. It profits from misery. It represents finance capitalism at its most predatory, making money from others\' desperation.',
 ],
 tags: ['Vulture Funds', 'Paul Singer', 'Elliott Management', 'Argentina', 'Sovereign Debt', 'Hedge Funds', 'Predatory Finance'],
 sources: [
 { title: 'IMF on Holdout Creditors', url: 'https://www.imf.org/external/pubs/ft/sdn/2014/sdn1416.pdf', type: 'Research Paper' },
 { title: 'Jubilee USA - Vulture Funds', url: 'https://www.jubileeusa.org/vulture_funds', type: 'Advocacy Report' },
 { title: 'NYT - Elliott Management Profile', url: 'https://www.nytimes.com/2018/07/21/business/paul-singer-elliott-management.html', type: 'Profile' },
 ],
 affiliations: [
 { id: '1', name: 'Paul Singer', type: 'individual', relationship: 'Elliott Management founder, leading vulture', href: '/entities/individuals/paul-singer' },
 { id: '2', name: 'Elliott Management', type: 'corporation', relationship: 'Most aggressive vulture fund', href: '/entities/corporations/elliott-management' },
 { id: '3', name: 'Republican Party', type: 'organization', relationship: 'Singer major donor, lobbying recipient', href: '/entities/organizations/republican-party' },
 ],
 },
  'vietnam-war': {
 title: 'Vietnam War',
 subtitle: 'America\'s deadliest foreign policy disaster',
 severity: 'critical',
 category: 'War Crimes',
 date: 'October 12, 2009',
 lastUpdated: 'February 16, 2026',
 summary: 'The Vietnam War killed 58,000 Americans and 2-3 million Vietnamese, destabilized Southeast Asia, and was based on lies from the Gulf of Tonkin incident. Systematic war crimes including My Lai massacre, Operation Phoenix assassinations, and chemical warfare with Agent Orange devastated the region for generations.',
 content: [
 'GULF OF TONKIN DECEPTION: The war escalated based on a lie. The August 4, 1964"attack"on U.S. ships never happened. NSA documents released in 2005 confirmed it was fabricated to justify war.',
 'MY LAI MASSACRE: On March 16, 1968, U.S. soldiers murdered 504 unarmed Vietnamese civilians including women, children, and elderly. Only Lt. William Calley was convicted; he served 3 years house arrest.',
 'OPERATION PHOENIX: CIA assassination program killed an estimated 20,000-40,000 suspected Viet Cong. Many victims were innocent civilians. The program used torture, assassination, and terror.',
 'AGENT ORANGE: The U.S. sprayed 20 million gallons of herbicides including dioxin-contaminated Agent Orange. Birth defects and cancers continue today. The VA resisted compensating exposed veterans for decades.',
 'BOMBING CAMPAIGNS: Operation Rolling Thunder dropped more bombs on Vietnam than all of WWII combined. Cambodia and Laos were secretly bombed, destabilizing the region and enabling the Khmer Rouge.',
 'PENTAGON PAPERS: Daniel Ellsberg leaked documents showing administrations from Truman to Nixon systematically lied about the war. The government had known it was unwinnable.',
 'DEATH TOLL: 58,220 American service members died. 2-3 million Vietnamese died. 200,000-800,000 Cambodians died in subsequent genocide. Millions more injured or displaced.',
 ],
 tags: ['Vietnam War', 'War Crimes', 'Agent Orange', 'My Lai', 'Pentagon Papers', 'Gulf of Tonkin'],
 sources: [
 { title: 'Pentagon Papers', url: 'https://www.archives.gov/research/pentagon-papers', type: 'Government Documents' },
 { title: 'My Lai Massacre Documentation', url: 'https://www.law.umkc.edu/faculty/projects/ftrials/mylai/mylai.htm', type: 'Historical Archive' },
 ],
 affiliations: [
 { id: '1', name: 'Lyndon B. Johnson', type: 'individual', relationship: 'Escalated war based on lies', href: '/entities/individuals/lyndon-b-johnson' },
 { id: '2', name: 'Richard Nixon', type: 'individual', relationship: 'Secret bombing, war crimes', href: '/entities/individuals/richard-nixon' },
 { id: '3', name: 'Robert McNamara', type: 'individual', relationship: 'Secretary of Defense', href: '/entities/individuals/robert-mcnamara' },
 { id: '4', name: 'CIA', type: 'agency', relationship: 'Operation Phoenix', href: '/entities/agencies/cia' },
 { id: '5', name: 'Department of Defense', type: 'agency', relationship: 'War conduct', href: '/entities/agencies/dod' },
 ],
 },
  'vietnam-crimes': {
 title: 'Vietnam War Crimes',
 subtitle: 'Systematic atrocities and their cover-up',
 severity: 'critical',
 category: 'War Crimes',
 date: 'October 18, 2009',
 lastUpdated: 'February 16, 2026',
 summary: 'The Vietnam War saw systematic war crimes by U.S. forces including the My Lai massacre, Operation Phoenix assassinations, free-fire zones, and torture. Most perpetrators were never prosecuted. The Tiger Force atrocities, exposed decades later, showed the pattern was not isolated.',
 content: [
 'MY LAI: 504 civilians murdered. Women raped. Bodies mutilated. Only Lt. Calley convicted - served 3 years house arrest. Officers who ordered the assault and covered it up faced no charges.',
 'TIGER FORCE: Elite unit committed war crimes over seven months in 1967 including torture, execution of prisoners, and killing of civilians. Army investigation suppressed. No prosecutions.',
 'OPERATION PHOENIX: CIA-run program tortured and assassinated 20,000-40,000 suspected Viet Cong. Provincial Reconnaissance Units used torture chambers. Many victims were innocent.',
 'FREE FIRE ZONES: Entire regions designated where any Vietnamese could be killed."Kill anything that moves"was policy. Body counts incentivized indiscriminate killing.',
 'TORTURE: Water torture, electric shock, and other techniques were widespread. South Vietnamese interrogators trained by U.S. advisors used brutal methods at U.S. direction.',
 'COVER-UPS: The military systematically covered up atrocities. Officers who reported crimes were retaliated against. Hugh Thompson, who stopped My Lai, was initially ostracized.',
 ],
 tags: ['Vietnam', 'War Crimes', 'My Lai', 'Tiger Force', 'Phoenix Program', 'Torture'],
 sources: [
 { title: 'Toledo Blade Tiger Force Investigation', url: 'https://www.pulitzer.org/winners/michael-d-sallah-and-mitch-weiss', type: 'Investigation' },
 { title: 'Nick Turse - Kill Anything That Moves', url: 'https://www.amazon.com/Kill-Anything-That-Moves-American/dp/1250045061', type: 'Book' },
 ],
 affiliations: [
 { id: '1', name: 'William Calley', type: 'individual', relationship: 'My Lai commander, only one convicted', href: '/entities/individuals/william-calley' },
 { id: '2', name: 'CIA', type: 'agency', relationship: 'Operation Phoenix', href: '/entities/agencies/cia' },
 { id: '3', name: 'U.S. Army', type: 'agency', relationship: 'Committed and covered up atrocities', href: '/entities/agencies/us-army' },
 ],
 },
  'voting-rights': {
 title: 'Voting Rights Under Attack',
 subtitle: 'The war on democracy',
 severity: 'critical',
 category: 'Civil Rights',
 date: 'June 25, 2021',
 lastUpdated: 'February 16, 2026',
 summary: 'Since the Supreme Court gutted the Voting Rights Act in Shelby County v. Holder (2013), states have passed hundreds of laws restricting voting access. These laws disproportionately burden Black, Latino, and young voters - by design.',
 content: [
 'SHELBY COUNTY: The Supreme Court struck down VRA preclearance, opening the floodgates to suppression.',
 'RESTRICTIVE LAWS: Since 2013, states have imposed voter ID requirements, reduced early voting, purged rolls, and closed polling places.',
 'TARGETED: Studies show restrictions disproportionately affect Black and Latino voters. This is the intent.',
 'GERRYMANDERING: Extreme partisan gerrymandering ensures minority rule in many states.',
 'CONGRESS INACTION: The Freedom to Vote Act and John Lewis Voting Rights Act have been blocked by filibuster.',
 ],
 tags: ['Voting Rights', 'Shelby County', 'Voter Suppression', 'Gerrymandering', 'VRA'],
 sources: [
 { title: 'Brennan Center Voting Laws Roundup', url: 'https://www.brennancenter.org/our-work/research-reports', type: 'Research' },
 ],
 affiliations: [
 { id: '1', name: 'Supreme Court', type: 'agency', relationship: 'Gutted VRA', href: '/entities/agencies/supreme-court' },
 ],
 },
  'venezuela-election': {
 title: 'Venezuela Election',
 subtitle: 'Investigation into venezuela election.',
 severity: 'critical',
 category: 'Election Integrity',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into venezuela election.',
 content: [
 'This investigation documents venezuela election and its impact.',
 ],
 tags: ['Election Integrity', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'venezuela-human-rights': {
 title: 'Venezuela Human Rights',
 subtitle: 'Investigation into venezuela human rights.',
 severity: 'high',
 category: 'Civil Rights',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into venezuela human rights.',
 content: [
 'This investigation documents venezuela human rights and its impact.',
 ],
 tags: ['Civil Rights', 'Human Rights', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'vs-pipeline': {
 title: 'VS Pipeline',
 subtitle: 'Investigation into vs pipeline.',
 severity: 'high',
 category: 'Government Accountability',
 date: 'January 1, 2024',
 lastUpdated: 'March 1, 2026',
 summary: 'Investigation into vs pipeline.',
 content: [
 'This investigation documents vs pipeline and its impact.',
 ],
 tags: ['Government Accountability', 'Investigation', 'Accountability'],
 sources: [
 { title: 'Public Records', url: 'https://www.documentcloud.org/', type: 'Government' },
 ],
 affiliations: [],
 },
  'voter-roll-purges-and-suppression-tactics': {
    title: 'Voter Roll Purges and Suppression Tactics',
    subtitle: 'Investigation into Voter Roll Purges and Suppression Tactics',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Voter Roll Purges and Suppression Tactics for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Voter Roll Purges and Suppression Tactics has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'vaccine-injury-compensation-cover-up': {
    title: 'Vaccine Injury Compensation Cover-Up',
    subtitle: 'Investigation into Vaccine Injury Compensation Cover-Up',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Vaccine Injury Compensation Cover-Up for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Vaccine Injury Compensation Cover-Up has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'voting-machine-certification-failures': {
    title: 'Voting Machine Certification Failures',
    subtitle: 'Investigation into Voting Machine Certification Failures',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Voting Machine Certification Failures for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Voting Machine Certification Failures has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'voter-database-security-breaches': {
    title: 'Voter Database Security Breaches',
    subtitle: 'Investigation into Voter Database Security Breaches',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Voter Database Security Breaches for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Voter Database Security Breaches has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'vaccine-program-demographic-targeting-claims': {
    title: 'Vaccine Program Demographic Targeting Claims',
    subtitle: 'Investigation into Vaccine Program Demographic Targeting Claims',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Vaccine Program Demographic Targeting Claims for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Vaccine Program Demographic Targeting Claims has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },
  'vehicle-tracking-data-broker-industry': {
    title: 'Vehicle Tracking Data Broker Industry',
    subtitle: 'Investigation into Vehicle Tracking Data Broker Industry',
    severity: 'medium',
    category: 'General',
    date: 'March 4, 2026',
    lastUpdated: 'March 4, 2026',
    summary: 'ArkHive\'s automated investigative intelligence has flagged Vehicle Tracking Data Broker Industry for documentation and expanded analysis. This investigation was generated based on cross-references and network analysis of related entities in the accountability database.',
    content: [
      'Vehicle Tracking Data Broker Industry has been identified through ArkHive\'s systematic analysis of institutional power structures, corporate networks, and government accountability gaps.',
      'This investigation is actively maintained and enriched as new publicly available records, court filings, and investigative reports surface through automated intelligence gathering.',
    ],
    tags: ['ArkHive', 'Investigation', 'Accountability'],
    sources: [
      { title: 'ArkHive Investigative Database', url: 'https://arkhive.org', type: 'Database' },
      { title: 'Public Records Analysis', url: 'https://arkhive.org/methodology', type: 'Methodology' },
    ],
    affiliations: [
    ],
  },






};

export default investigations_v;
