#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════
//  ARKHIVE FORGE — TYPE GENERATOR
//  Reads schema.js → outputs TypeScript interfaces for ALL entities
//  and sub-types. Generates src/types/generated.ts
// ═══════════════════════════════════════════════════════════════════

const fs = require('fs');
const path = require('path');
const schema = require('./schema');

const OUT_DIR = path.resolve(__dirname, '../../src/types');
const OUT_FILE = path.join(OUT_DIR, 'generated.ts');

function tsType(fieldDef) {
  switch (fieldDef.type) {
    case 'string':     return 'string';
    case 'number':     return 'number';
    case 'boolean':    return 'boolean';
    case 'date':       return 'string'; // ISO date strings
    case 'string[]':   return 'string[]';
    case 'rich-text':  return 'string';
    case 'object[]':   return 'Record<string, string>[]';
    case 'enum':       return fieldDef.values.map(v => `'${v}'`).join(' | ');
    default:
      if (fieldDef.type && fieldDef.type.startsWith('ref:')) {
        return fieldDef.type.split(':')[1];
      }
      return 'unknown';
  }
}

function generateSubTypeInterface(name, def) {
  const lines = [`export interface ${name} {`];
  for (const [fieldName, fieldDef] of Object.entries(def.fields)) {
    const optional = fieldDef.required ? '' : '?';
    lines.push(`  ${fieldName}${optional}: ${tsType(fieldDef)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function resolveRelationType(typeDef) {
  // e.g. 'CrimeCategory[]' → 'CrimeCategory[]'
  // e.g. 'Affiliation[]' → 'Affiliation[]'
  const match = typeDef.match(/^(\w+)\[\]$/);
  if (match) return `${match[1]}[]`;
  return typeDef;
}

function generateEntityInterface(name, def) {
  const lines = [`export interface ${name}Profile {`];

  // Fields
  for (const [fieldName, fieldDef] of Object.entries(def.fields)) {
    const optional = fieldDef.required ? '' : '?';
    lines.push(`  ${fieldName}${optional}: ${tsType(fieldDef)};`);
  }

  // Relations
  for (const [relName, relDef] of Object.entries(def.relations || {})) {
    lines.push(`  ${relName}?: ${resolveRelationType(relDef.type)};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateQualityInterface() {
  const lines = ['export interface QualityThresholds {'];
  // Collect all unique threshold keys from all entities
  const allKeys = new Set();
  for (const entity of Object.values(schema.entities)) {
    if (entity.qualityThresholds) {
      for (const k of Object.keys(entity.qualityThresholds)) {
        allKeys.add(k);
      }
    }
  }
  for (const k of allKeys) {
    lines.push(`  ${k}?: number;`);
  }
  lines.push('}');
  return lines.join('\n');
}

function generateCrimeCategoryUnion() {
  const cats = schema.crimeCategories.map(c => `  | '${c}'`);
  return `export type CrimeCategoryName =\n${cats.join('\n')};`;
}

function generateSeverityColorMap() {
  const lines = ['export const severityColors = {'];
  for (const [level, colors] of Object.entries(schema.theme.colors.severity)) {
    lines.push(`  '${level}': { bg: '${colors.bg}', text: '${colors.text}', border: '${colors.border}' },`);
  }
  lines.push('} as const;');
  return lines.join('\n');
}

function generateEvidenceColorMap() {
  const lines = ['export const evidenceColors = {'];
  for (const [level, colors] of Object.entries(schema.theme.colors.evidence)) {
    lines.push(`  '${level}': { bg: '${colors.bg}', text: '${colors.text}' },`);
  }
  lines.push('} as const;');
  return lines.join('\n');
}

function generateEntityRegistry() {
  const lines = ['export const entityRegistry = {'];
  for (const [name, def] of Object.entries(schema.entities)) {
    lines.push(`  '${name}': {`);
    lines.push(`    slug: '${def.slug}',`);
    lines.push(`    icon: '${def.icon}',`);
    lines.push(`    description: '${def.description}',`);
    lines.push(`    dataDir: '${def.dataDir}',`);
    lines.push(`    pageDir: '${def.pageDir}',`);
    lines.push(`  },`);
  }
  lines.push('} as const;');
  return lines.join('\n');
}

function generateApiRouteTypes() {
  const lines = ['export const apiRoutes = ['];
  for (const route of schema.apiRoutes) {
    lines.push(`  { path: '${route.path}', methods: [${route.methods.map(m => `'${m}'`).join(', ')}] as const, description: '${route.description}' },`);
  }
  lines.push('] as const;');
  return lines.join('\n');
}

function generate() {
  const sections = [];

  sections.push(`// ═══════════════════════════════════════════════════════════════════`);
  sections.push(`//  AUTO-GENERATED BY ARKHIVE FORGE — DO NOT EDIT MANUALLY`);
  sections.push(`//  Generated: ${new Date().toISOString()}`);
  sections.push(`//  Source: bots/forge/schema.js`);
  sections.push(`//  Re-generate: node bots/forge/generate-types.js`);
  sections.push(`// ═══════════════════════════════════════════════════════════════════\n`);

  // Sub-types first (they're referenced by entity interfaces)
  sections.push('// ── Sub-Type Interfaces ──────────────────────────────────────────\n');
  for (const [name, def] of Object.entries(schema.subTypes)) {
    sections.push(generateSubTypeInterface(name, def));
    sections.push('');
  }

  // Entity interfaces
  sections.push('// ── Entity Interfaces ────────────────────────────────────────────\n');
  for (const [name, def] of Object.entries(schema.entities)) {
    sections.push(generateEntityInterface(name, def));
    sections.push('');
  }

  // Quality thresholds
  sections.push('// ── Quality ─────────────────────────────────────────────────────\n');
  sections.push(generateQualityInterface());
  sections.push('');

  // Crime category union type
  sections.push('// ── Crime Categories ─────────────────────────────────────────────\n');
  sections.push(generateCrimeCategoryUnion());
  sections.push('');

  // Color maps
  sections.push('// ── Color Maps ──────────────────────────────────────────────────\n');
  sections.push(generateSeverityColorMap());
  sections.push('');
  sections.push(generateEvidenceColorMap());
  sections.push('');

  // Entity registry
  sections.push('// ── Entity Registry ─────────────────────────────────────────────\n');
  sections.push(generateEntityRegistry());
  sections.push('');

  // API routes
  sections.push('// ── API Routes ──────────────────────────────────────────────────\n');
  sections.push(generateApiRouteTypes());
  sections.push('');

  const output = sections.join('\n');

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, output, 'utf-8');

  // Stats
  const entityCount = Object.keys(schema.entities).length;
  const subTypeCount = Object.keys(schema.subTypes).length;
  const crimeCats = schema.crimeCategories.length;
  const apiCount = schema.apiRoutes.length;
  const lines = output.split('\n').length;

  console.log(`✓ Generated ${OUT_FILE}`);
  console.log(`  ${entityCount} entity interfaces, ${subTypeCount} sub-types`);
  console.log(`  ${crimeCats} crime categories, ${apiCount} API routes`);
  console.log(`  ${lines} lines of TypeScript`);

  return output;
}

if (require.main === module) {
  generate();
}

module.exports = { generate };
