'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowLeft, AlertTriangle, Users, Calendar, FileText, ExternalLink, Scale, ShieldAlert, Skull } from 'lucide-react';
import GlitchText from '@/components/effects/GlitchText';

const investigation = {
  title: 'Abu Ghraib Torture',
  subtitle: 'Systematic Torture, Sexual Humiliation, and Murder at America\'s Most Notorious Prison — Authorized from the Top, Punished at the Bottom',
  severity: 'critical',
  status: 'EXPOSED — LEADERSHIP UNPUNISHED',
  summary: 'In April 2004, CBS News broadcast photographs from Abu Ghraib prison in Iraq that shocked the world and exposed the systematic torture and abuse of Iraqi detainees by U.S. military personnel. The photographs showed naked prisoners stacked in human pyramids, forced to simulate sex acts, dragged on leashes, threatened with unmuzzled attack dogs, hooded and wired to simulate electrocution, beaten, sexually humiliated, and posed with grinning American soldiers giving thumbs-up signs. But the photographs only captured a fraction of the horror. The Taguba Report, a classified military investigation by Maj. Gen. Antonio Taguba, documented "sadistic, blatant, and wanton criminal abuses" including: punching, slapping, and kicking detainees; forcing naked male detainees to wear women\'s underwear on their heads; positioning naked detainees in sexually explicit positions and photographing them; forcing groups of male detainees to masturbate while being filmed; arranging naked male detainees in a pile and jumping on them; using military working dogs to frighten and bite detainees; sodomizing a detainee with a chemical light and perhaps a broomstick; pouring cold water on naked detainees in cold conditions; and at least one case of a detainee beaten to death. The abuse was not the work of "a few bad apples" as the Bush administration claimed — it was the direct, predictable result of policies authorized at the highest levels of the U.S. government. Defense Secretary Donald Rumsfeld personally approved interrogation techniques including stress positions, hooding, 20-hour interrogations, removal of clothing, and the use of dogs. The so-called "torture memos" from the DOJ\'s Office of Legal Counsel provided legal cover. Military and CIA intelligence officers directed the abusive treatment. Yet only low-ranking enlisted soldiers — the ones photographed — were prosecuted. Not a single officer above the rank of lieutenant colonel faced criminal charges. Not a single Bush administration official was prosecuted. The tortured were punished. The torturers were promoted.',
  keyFigures: [
    { name: 'Donald Rumsfeld', role: 'Secretary of Defense who personally approved the use of stress positions, hooding, nudity, sensory deprivation, 20-hour interrogations, and military working dogs at Guantanamo Bay — techniques that migrated to Abu Ghraib. His December 2002 memo approving these techniques included a handwritten note: "I stand for 8-10 hours a day. Why is standing limited to 4 hours?"', href: '/entities/individuals/donald-rumsfeld', status: 'Deceased (2021) — Never charged' },
    { name: 'George W. Bush', role: 'President who authorized the CIA detention and interrogation program through secret presidential findings. His February 2002 executive order declared Geneva Conventions did not apply to "enemy combatants" — creating the legal framework that enabled Abu Ghraib.', href: '/entities/individuals/george-w-bush', status: 'No accountability' },
    { name: 'Dick Cheney', role: 'Vice President and primary political architect of the "enhanced interrogation" regime. Advocated personally for waterboarding and other extreme techniques. His office coordinated with the DOJ to produce the "torture memos" providing legal cover.', href: '/entities/individuals/dick-cheney', status: 'No accountability' },
    { name: 'Alberto Gonzales', role: 'White House Counsel who authored a January 2002 memo calling the Geneva Conventions "quaint" and "obsolete" — setting the legal stage for torture at both CIA black sites and military prisons like Abu Ghraib. Later became Attorney General.', href: '/entities/individuals/alberto-gonzales', status: 'No accountability' },
    { name: 'John Yoo', role: 'DOJ Office of Legal Counsel attorney who authored the "Torture Memos" redefining torture so narrowly that waterboarding, stress positions, sleep deprivation, and other abuses were deemed legal — providing the legal framework used to justify Abu Ghraib techniques.', href: '/entities/individuals/john-yoo', status: 'UC Berkeley professor' },
    { name: 'Jay Bybee', role: 'Assistant Attorney General who signed the Torture Memos alongside Yoo. The memos defined torture as requiring pain "equivalent to organ failure or death" — effectively legalizing everything short of killing a detainee. Now serves as a federal appellate judge.', href: '/entities/individuals/jay-bybee', status: 'Active — Federal judge' },
    { name: 'Lt. Gen. Ricardo Sanchez', role: 'Commander of coalition forces in Iraq who authorized interrogation techniques at Abu Ghraib beyond those approved by the Army Field Manual — including the use of dogs, stress positions, and sleep deprivation. He was never charged.', href: '/entities/individuals/ricardo-sanchez', status: 'Retired — Never charged' },
    { name: 'Maj. Gen. Antonio Taguba', role: 'Army officer who conducted the classified investigation that documented "sadistic, blatant, and wanton criminal abuses" at Abu Ghraib. His 53-page report was leaked to Seymour Hersh. Taguba was effectively forced into retirement for doing his job honestly.', href: '/entities/individuals/antonio-taguba', status: 'Retired — Forced out for honesty' },
    { name: 'Brig. Gen. Janis Karpinski', role: 'Commander of the 800th Military Police Brigade responsible for Abu Ghraib. Demoted from Brigadier General to Colonel — the only officer to face any consequence. She maintained that military intelligence and CIA officers directed the abuse, and that she was scapegoated to protect superiors.', href: '/entities/individuals/janis-karpinski', status: 'Demoted — Scapegoated' },
    { name: 'Lynndie England', role: 'Army Private First Class who appeared in the most iconic Abu Ghraib photographs — pointing at a naked detainee\'s genitals, holding a leash attached to a naked detainee, and posing with the human pyramid. She became the public face of the scandal while those who created the conditions for abuse escaped prosecution.', href: '/entities/individuals/lynndie-england', status: 'Convicted — 3 years' },
    { name: 'Charles Graner', role: 'Army Specialist and ringleader of the abuses documented in the Abu Ghraib photographs. A corrections officer in civilian life, he organized the human pyramids, dog attacks, and sexual humiliation. Sentenced to 10 years — the harshest sentence among the enlisted soldiers while no officer or official was charged.', href: '/entities/individuals/charles-graner', status: 'Convicted — 10 years (released 2011)' },
    { name: 'Col. Thomas Pappas', role: 'Commander of the 205th Military Intelligence Brigade at Abu Ghraib who approved the use of dogs during interrogation — a technique that directly led to the photographed abuses. Received a fine and letter of reprimand. No criminal charges.', href: '/entities/individuals/thomas-pappas', status: 'Reprimanded — No prosecution' },
    { name: 'Stephen Cambone', role: 'Under Secretary of Defense for Intelligence — Rumsfeld\'s intelligence chief who pushed "Gitmo-ize" Abu Ghraib by importing Guantanamo interrogation techniques to Iraq. His directives created the conditions for systematic abuse.', href: '/entities/individuals/stephen-cambone', status: 'No accountability' },
    { name: 'Maj. Gen. Geoffrey Miller', role: 'Commander of Guantanamo Bay detention operations sent to Abu Ghraib in August 2003 to "Gitmo-ize" the prison — advising that military police should be used to "set the conditions" for intelligence interrogation. His visit directly preceded the documented abuse.', href: '/entities/individuals/geoffrey-miller', status: 'Retired — Invoked Article 31 rights' },
  ],
  timeline: [
    { date: '2002-02-07', event: 'Bush signs executive order declaring Geneva Conventions do not apply to al-Qaeda or Taliban detainees — creating the legal framework that will be exported from Guantanamo to Abu Ghraib' },
    { date: '2002-08-01', event: 'Yoo/Bybee "Torture Memos" signed — redefining torture to require pain "equivalent to organ failure or death," effectively legalizing stress positions, sleep deprivation, nudity, dogs, and other techniques that will be used at Abu Ghraib' },
    { date: '2002-12-02', event: 'Rumsfeld personally approves aggressive interrogation techniques for Guantanamo — including stress positions, forced nudity, hooding, 20-hour interrogations, and the use of dogs. His handwritten note jokes about standing for hours.' },
    { date: '2003-03-20', event: 'U.S. invasion of Iraq begins — within months, thousands of Iraqi civilians will be detained and held at Abu Ghraib, a former Saddam Hussein-era prison already associated with torture and execution' },
    { date: '2003-08-31', event: 'Maj. Gen. Geoffrey Miller visits Abu Ghraib from Guantanamo to advise on "Gitmo-izing" the facility — recommending that military police "set the conditions" for interrogation, blurring the line between detention and intelligence extraction' },
    { date: '2003-09-14', event: 'Lt. Gen. Ricardo Sanchez authorizes interrogation techniques at Abu Ghraib beyond Army Field Manual — including stress positions, sleep deprivation, dogs, and sensory manipulation' },
    { date: '2003-10-01', event: 'Systematic abuse at Abu Ghraib intensifies — military police, acting under pressure from military intelligence and CIA officers, begin the photographed campaign of torture, sexual humiliation, and degradation' },
    { date: '2003-11-04', event: 'Manadel al-Jamadi dies during CIA interrogation at Abu Ghraib — his body is packed in ice and smuggled out on a stretcher to conceal the death. Autopsy rules it a homicide caused by "compromised respiration." Photos show soldiers giving thumbs up next to his corpse.' },
    { date: '2004-01-13', event: 'Army Specialist Joseph Darby anonymously provides a CD of abuse photographs to the Army Criminal Investigation Division — becoming the whistleblower who exposed Abu Ghraib at great personal risk' },
    { date: '2004-01-16', event: 'Central Command issues a one-paragraph press release acknowledging an investigation into "allegations of detainee abuse" — burying the story. The media does not pursue it.' },
    { date: '2004-02-26', event: 'Maj. Gen. Antonio Taguba completes his classified investigation — his 53-page report documents "sadistic, blatant, and wanton criminal abuses" including sexual assault, beatings, and the use of dogs on nude detainees' },
    { date: '2004-04-28', event: 'CBS News 60 Minutes II broadcasts the Abu Ghraib photographs — images of hooded detainees, human pyramids, dog attacks, Lynndie England with a leash, and soldiers posing with brutalized prisoners shock the world' },
    { date: '2004-05-07', event: 'Rumsfeld testifies before Congress, calling the abuse "un-American" and claiming he was not aware of the photographs — while the Taguba Report (which Rumsfeld received months earlier) documented the systemic nature of the abuse' },
    { date: '2004-05-10', event: 'Seymour Hersh publishes detailed reporting on Abu Ghraib in The New Yorker, including excerpts from the Taguba Report that the Pentagon was trying to keep classified. His reporting reveals the abuse was systemic, not the acts of rogue soldiers.' },
    { date: '2004-05-19', event: 'Rumsfeld visits Abu Ghraib and tells troops they are "doing a great job" — while the world is seeing photographs of the torture they committed' },
    { date: '2004-06-22', event: 'OLC withdraws the Yoo/Bybee torture memos under political pressure — but issues new memos that effectively reauthorize the same techniques with different legal reasoning' },
    { date: '2004-08-24', event: 'Schlesinger Report ("Independent Panel to Review DOD Detention Operations") released — acknowledges "institutional and personal responsibility at higher levels" but stops short of recommending criminal prosecution of senior officials' },
    { date: '2004-08-25', event: 'Fay-Jones Report released — finds military intelligence soldiers "requested, encouraged, condoned, or solicited" military police to abuse detainees, confirming the abuse was directed from above, not spontaneous' },
    { date: '2005-01-15', event: 'Charles Graner convicted and sentenced to 10 years — the heaviest sentence of any Abu Ghraib defendant. He is an enlisted specialist. No colonel, general, or political appointee is charged.' },
    { date: '2005-05-02', event: 'Lynndie England convicted and sentenced to 3 years — the most recognizable face of Abu Ghraib. She was 21 years old when the abuse occurred, under the direction of Graner and military intelligence.' },
    { date: '2005-09-29', event: 'Brig. Gen. Janis Karpinski demoted to Colonel — the only officer to face any consequence. She states: "I was the convenient scapegoat... Military intelligence and the CIA were running the show."' },
    { date: '2006-03-22', event: 'CIA contractor David Passaro convicted of assault in the death of Afghan detainee Abdul Wali — one of the only CIA-connected convictions related to the broader detention abuse scandal' },
    { date: '2008-06-18', event: 'Senate Armed Services Committee releases report concluding that Rumsfeld\'s approval of aggressive interrogation "was a direct cause of detainee abuse" at Abu Ghraib — but no prosecution follows' },
    { date: '2015-12-09', event: 'Senate Torture Report confirms Abu Ghraib abuse was connected to the broader CIA/DOD interrogation regime — not isolated to "a few bad apples." Report documents systemic authorization from senior officials.' },
  ],
  legalOutcomes: [
    { defendant: 'Charles Graner (Specialist)', charge: 'Assault, conspiracy, maltreatment, dereliction of duty, committing an indecent act — ringleader of the photographed abuse at Abu Ghraib', outcome: 'Convicted; sentenced to 10 years. Released from military prison in 2011 after serving 6.5 years. The harshest sentence among Abu Ghraib defendants.' },
    { defendant: 'Lynndie England (PFC)', charge: 'Conspiracy, maltreating detainees, committing an indecent act — appeared in the most iconic photographs including the human leash and pointing at naked detainees', outcome: 'Convicted; sentenced to 3 years, dishonorably discharged. She was 21 years old. Has stated she was following orders and was manipulated by Graner.' },
    { defendant: 'Sabrina Harman (Specialist)', charge: 'Conspiracy, maltreating detainees, dereliction of duty — photographed giving thumbs-up next to the corpse of Manadel al-Jamadi and writing "rapeist" on a detainee\'s leg', outcome: 'Convicted; sentenced to 6 months, bad conduct discharge.' },
    { defendant: 'Ivan Frederick (Staff Sergeant)', charge: 'Conspiracy, dereliction of duty, maltreatment, assault, committing an indecent act — senior enlisted soldier at the prison who participated in and facilitated the abuse', outcome: 'Convicted; sentenced to 8 years, dishonorably discharged. Reduced from 10 years in a plea deal.' },
    { defendant: 'Javal Davis (Sergeant)', charge: 'Assault, dereliction of duty — stepped on the hands and feet of detainees forced into a human pyramid', outcome: 'Convicted; sentenced to 6 months, bad conduct discharge.' },
    { defendant: 'Brig. Gen. Janis Karpinski', charge: 'Dereliction of duty as commander of the 800th Military Police Brigade — the only officer to face any consequence', outcome: 'Administratively demoted from Brigadier General to Colonel. No criminal charges. She maintains she was scapegoated while military intelligence ran the operation.' },
    { defendant: 'Col. Thomas Pappas', charge: 'Approved the use of military working dogs during interrogation — technique directly linked to photographed abuse', outcome: 'Received a $8,000 fine and letter of reprimand. No criminal charges. Relieved of command.' },
    { defendant: 'Donald Rumsfeld', charge: 'Senate Armed Services Committee concluded his approval of aggressive interrogation techniques "was a direct cause of detainee abuse" at Abu Ghraib and Guantanamo', outcome: 'Never charged. Resigned as Secretary of Defense in 2006 due to broader Iraq War failures, not Abu Ghraib. Died in 2021 without facing prosecution.' },
    { defendant: 'CIA — Manadel al-Jamadi Death', charge: 'Iraqi detainee died during CIA interrogation at Abu Ghraib — autopsy ruled homicide. Body was packed in ice and smuggled out to conceal the death.', outcome: 'CIA officer Mark Swanner was referred to DOJ for prosecution. DOJ declined to file charges. No one was ever prosecuted for al-Jamadi\'s death.' },
    { defendant: 'Maj. Gen. Geoffrey Miller', charge: 'Sent to Abu Ghraib to "Gitmo-ize" the prison — his recommendations directly preceded the systematic abuse. Invoked Article 31 (right against self-incrimination) when called to testify.', outcome: 'Never charged. Invoked his right to remain silent. Retired from the Army.' },
    { defendant: 'Abu Ghraib Detainees (Civil Lawsuit)', charge: 'Former detainees sued CACI International and L-3 Services (now Engility), private military contractors whose employees directed and participated in torture', outcome: 'CACI settled in 2024 for an undisclosed amount after 16 years of litigation — acknowledging involvement in the abuse for the first time' },
  ],
  charges: [
    { statute: '18 U.S.C. § 2340A — Torture', description: 'Water torture, stress positions, prolonged forced nudity, sexual humiliation, dog attacks, beatings, sleep deprivation, and simulated electrocution — all constitute torture under federal and international law', count: 'Hundreds of detainees subjected to systematic abuse; Taguba Report documented at least 50 specific incidents' },
    { statute: '18 U.S.C. § 1111 — Murder', description: 'Death of Manadel al-Jamadi during CIA interrogation at Abu Ghraib — ruled a homicide by military autopsy. Body was packed in ice to conceal the death.', count: 'At least 1 confirmed death during interrogation at Abu Ghraib; additional deaths connected to the broader detention abuse program' },
    { statute: '18 U.S.C. § 2441 — War Crimes Act', description: 'Torture and inhuman treatment of persons protected under the Geneva Conventions constitutes a federal war crime — Abu Ghraib detainees were protected persons under Geneva Convention IV', count: 'Systematic war crimes across the entire detention facility' },
    { statute: 'Geneva Convention III, Article 13 — Humane Treatment', description: 'Prisoners of war and detained persons must be humanely treated at all times — forced nudity, sexual humiliation, dog attacks, and beatings violate the most fundamental protections', count: 'Hundreds of violations documented in photographs, sworn statements, and the Taguba Report' },
    { statute: 'Geneva Convention IV, Article 27 — Protection of Civilians', description: 'Many Abu Ghraib detainees were Iraqi civilians arrested in sweeps, not combatants — subjecting civilians to torture constitutes a grave breach of the Geneva Conventions', count: 'Estimated 70-90% of Abu Ghraib detainees were eventually determined to have no intelligence value' },
    { statute: '18 U.S.C. § 2242 — Sexual Abuse', description: 'Forced nakedness, forced simulation of sexual acts, forced masturbation while being filmed, sodomy with objects — these acts constitute sexual abuse under federal law', count: 'Multiple incidents documented in photographs and the Taguba Report' },
    { statute: '18 U.S.C. § 1512 — Tampering with Evidence', description: 'Packing the body of Manadel al-Jamadi in ice and smuggling it out of the facility on a stretcher to conceal a homicide constitutes evidence tampering and obstruction', count: 'At least 1 death concealed; unknown number of additional cover-up actions' },
    { statute: 'Convention Against Torture (CAT) — Articles 1-4', description: 'The United States is a signatory to the UN Convention Against Torture, which prohibits torture and cruel, inhuman, or degrading treatment under all circumstances with no exceptions', count: 'Systematic violation of binding treaty obligations' },
    { statute: '18 U.S.C. § 371 — Conspiracy', description: 'Coordinated conspiracy between DOD, CIA, DOJ, and White House to create legal framework authorizing torture, implement torture techniques, and shield perpetrators from accountability', count: 'Multi-agency conspiracy spanning 2002-2004+ involving hundreds of officials' },
    { statute: 'Uniform Code of Military Justice (UCMJ) — Various Articles', description: 'Assault (Article 128), cruelty and maltreatment (Article 93), dereliction of duty (Article 92), conduct unbecoming (Article 133) — applicable to all military personnel involved in or aware of the abuse', count: 'Only 11 soldiers charged under UCMJ; only 7 convicted — all enlisted. No generals, no colonels, no political appointees.' },
  ],
  coverup: [
    'The Bush administration\'s official narrative — repeated by Rumsfeld, Bush, and Cheney — was that Abu Ghraib was the work of "a few bad apples" acting on their own. The Taguba Report, the Schlesinger Report, the Fay-Jones Report, and the Senate Armed Services Committee all concluded the abuse was systemic and originated from policies approved at the highest levels.',
    'The Pentagon attempted to suppress the Abu Ghraib photographs — CBS News had the images for two weeks before broadcasting them, during which time the Pentagon pressured the network to delay the story, arguing it would "endanger American lives."',
    'Maj. Gen. Antonio Taguba\'s classified investigation was meant to remain secret. When Seymour Hersh obtained and published it, Taguba was effectively punished — then-Lt. Gen. William Boykin told him "you do realize your career is done" and he was forced into retirement for honestly documenting the abuse.',
    'The death of Manadel al-Jamadi during CIA interrogation at Abu Ghraib was covered up — his body was packed in ice, an IV was placed in his arm to make it appear he was still alive, and he was smuggled out on a stretcher. The military autopsy ruled his death a homicide. No one was prosecuted.',
    'Central Command\'s initial press release on January 16, 2004 was a single paragraph buried among routine announcements — acknowledging an investigation into "allegations of detainee abuse" without any indication of the scale or severity. The media ignored it for over three months until the photographs emerged.',
    'Donald Rumsfeld testified before Congress that he was "not aware" of the photographs or the severity of the abuse — despite having received the Taguba Report months earlier. The Senate Armed Services Committee later concluded his approved interrogation techniques were "a direct cause" of the abuse.',
    'When Army Specialist Joseph Darby provided the abuse photographs to investigators, his identity was supposed to be protected. Rumsfeld publicly identified him in a Senate hearing, forcing Darby and his family into protective custody. He was ostracized in his hometown and received death threats for exposing the torture.',
    'Maj. Gen. Geoffrey Miller — who recommended "Gitmo-izing" Abu Ghraib — invoked his Article 31 right against self-incrimination when called to testify about his role. He was never compelled to testify and retired from the Army without facing any investigation or charges.',
    'The full trove of Abu Ghraib photographs — estimated at thousands of images — has never been released to the public. The Department of Defense successfully fought FOIA requests, and in 2009 Congress passed a law specifically exempting the photographs from disclosure, ensuring the full scale of the abuse remains hidden.',
    'Private military contractors CACI International and L-3 Services (Engility) — whose employees directed and participated in the torture — fought lawsuits from victims for 16 years before CACI settled in 2024. The contractors claimed sovereign immunity, arguing they were extensions of the U.S. government and therefore could not be sued.',
  ],
  sources: [
    { title: 'Seymour Hersh — "Torture at Abu Ghraib" (The New Yorker)', url: 'https://www.newyorker.com/magazine/2004/05/10/torture-at-abu-ghraib', date: '2004-05-10' },
    { title: 'Seymour Hersh — "Chain of Command" (The New Yorker)', url: 'https://www.newyorker.com/magazine/2004/05/17/chain-of-command-2', date: '2004-05-17' },
    { title: 'Maj. Gen. Antonio Taguba — "Article 15-6 Investigation of the 800th Military Police Brigade" (Taguba Report)', url: 'https://www.thetorturedatabase.org/files/foia_subsite/pdfs/TAGUBA_REPORT.pdf', date: '2004-02-26' },
    { title: 'Senate Armed Services Committee — "Inquiry into the Treatment of Detainees in U.S. Custody"', url: 'https://www.armed-services.senate.gov/imo/media/doc/Detainee-Report-Final_April-22-2009.pdf', date: '2008-12-11' },
    { title: 'Schlesinger Report — "Final Report of the Independent Panel to Review DOD Detention Operations"', url: 'https://www.globalsecurity.org/intell/library/reports/2004/d20040824finalreport.pdf', date: '2004-08-24' },
    { title: 'Philip Gourevitch & Errol Morris — "Standard Operating Procedure" (Penguin Press)', url: 'https://www.penguinrandomhouse.com/books/298541/standard-operating-procedure-by-philip-gourevitch-and-errol-morris/', date: '2008' },
    { title: 'Errol Morris — "Standard Operating Procedure" (Documentary Film)', url: 'https://www.imdb.com/title/tt0896866/', date: '2008' },
    { title: 'The New Yorker — "The General\'s Report" by Seymour Hersh (Taguba\'s Story)', url: 'https://www.newyorker.com/magazine/2007/06/25/the-generals-report', date: '2007-06-25' },
    { title: 'ACLU — "Abu Ghraib Torture Documents"', url: 'https://www.aclu.org/issues/national-security/torture/abu-ghraib', date: '2004-2024' },
    { title: 'Human Rights Watch — "The Road to Abu Ghraib"', url: 'https://www.hrw.org/report/2004/06/09/road-abu-ghraib', date: '2004-06-09' },
    { title: 'The Washington Post — "Abu Ghraib Timeline of Events"', url: 'https://www.washingtonpost.com/wp-srv/world/iraq/timeline/abuse_timeline.html', date: '2004' },
    { title: 'ProPublica — "The Abu Ghraib Files" (Complete Photo Archive Analysis)', url: 'https://www.propublica.org/special/the-abu-ghraib-files', date: '2008' },
  ],
};

export default function AbuGhraibPage() {
  return (
    <div className="min-h-screen pt-20 lg:pt-24 pb-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/investigations" className="inline-flex items-center gap-2 text-zinc-400 hover:text-blood-500 transition-colors mb-6 pt-4"><ArrowLeft className="w-4 h-4" />Back to Investigations</Link>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="border-2 border-blood-800/60 bg-black/80 p-6 lg:p-8 mb-8">
          <div className="flex items-center gap-3 mb-4"><span className="px-3 py-1 text-xs font-bold uppercase border border-red-500/30 bg-red-500/20 text-red-400">{investigation.severity}</span><span className="px-3 py-1 text-xs font-bold uppercase border border-zinc-500/30 bg-zinc-500/20 text-zinc-400">{investigation.status}</span></div>
          <h1 className="text-3xl lg:text-4xl font-black text-white uppercase tracking-wider mb-2"><GlitchText text={investigation.title} /></h1>
          <p className="text-lg text-blood-500 font-bold mb-4">{investigation.subtitle}</p>
          <p className="text-zinc-400 leading-relaxed">{investigation.summary}</p>
        </motion.div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="glass-card p-6 mb-8 border-l-4 border-blood-600">
          <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><ShieldAlert className="w-5 h-5 text-blood-500" />The Cover-Up</h2>
          <div className="space-y-3">{investigation.coverup.map((item, idx) => (<div key={idx} className="p-3 bg-red-950/20 border border-red-500/30"><p className="text-sm text-zinc-300">{item}</p></div>))}</div>
        </motion.div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Users className="w-5 h-5 text-blood-500" />Key Figures</h2>
              <div className="space-y-3">{investigation.keyFigures.map((figure, idx) => (<div key={idx} className="flex items-start justify-between p-3 bg-zinc-900/50 border border-zinc-800"><div className="flex-1">{figure.href ? (<Link href={figure.href} className="font-bold text-blood-400 hover:text-blood-300 transition-colors">{figure.name}</Link>) : (<span className="font-bold text-white">{figure.name}</span>)}<p className="text-sm text-zinc-400 mt-1">{figure.role}</p></div><span className="text-xs px-2 py-1 bg-zinc-800 text-zinc-400 border border-zinc-700 whitespace-nowrap ml-2">{figure.status}</span></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="glass-card p-6">
              <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Applicable Charges &amp; Statutes</h2>
              <div className="space-y-3">{investigation.charges.map((charge, idx) => (<div key={idx} className="p-4 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-blood-400 text-sm font-mono">{charge.statute}</p><p className="text-sm text-zinc-300 mt-1">{charge.description}</p><p className="text-xs text-red-400 mt-1">{charge.count}</p></div>))}</div>
            </motion.div>
          </div>
          <div className="space-y-6">
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Calendar className="w-4 h-4 text-blood-500" />Timeline</h3>
              <div className="space-y-4">{investigation.timeline.map((item, idx) => (<div key={idx} className="relative pl-4 border-l-2 border-zinc-800"><div className="absolute -left-[5px] top-0 w-2 h-2 rounded-full bg-blood-500" /><p className="text-xs text-blood-500 font-mono">{item.date}</p><p className="text-sm text-zinc-300">{item.event}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.1 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2"><Scale className="w-5 h-5 text-blood-500" />Legal Outcomes</h3>
              <div className="space-y-3">{investigation.legalOutcomes.map((item, idx) => (<div key={idx} className="p-3 bg-zinc-900/50 border border-zinc-800"><p className="font-bold text-white text-sm">{item.defendant}</p><p className="text-xs text-zinc-400 mt-1">{item.charge}</p><p className="text-xs text-blood-400 mt-1">{item.outcome}</p></div>))}</div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="glass-card p-6">
              <h3 className="text-lg font-bold text-white uppercase tracking-wider mb-4">Sources</h3>
              <div className="space-y-2">{investigation.sources.map((source, idx) => (<a key={idx} href={source.url} target="_blank" rel="noopener noreferrer" className="flex items-start gap-2 p-2 text-sm text-zinc-400 hover:text-blood-400 hover:bg-zinc-900/50 transition-colors"><ExternalLink className="w-4 h-4 mt-0.5 flex-shrink-0" /><div><span>{source.title}</span><span className="text-zinc-600 ml-2">({source.date})</span></div></a>))}</div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
