#!/usr/bin/env python3
"""Replace the banking-libor-manipulation entry in b.ts with Gold Standard #21 content."""

import re
import sys

FILE_PATH = r"c:\Users\Arkhi\OneDrive\Desktop\dumb project\src\data\investigations\b.ts"

NEW_ENTRY = r"""  'banking-libor-manipulation': {
    title: 'LIBOR Manipulation: The Biggest Financial Fraud in History',
    subtitle: 'How the world\'s largest banks conspired to rig the London Interbank Offered Rate, manipulating $350 trillion in financial instruments and stealing from every borrower, pension fund, and municipality on Earth',
    severity: 'critical',
    category: 'Financial Crime / Systemic Fraud',
    date: 'June 27, 2012',
    lastUpdated: 'March 18, 2026',
    summary: 'Between at least 2003 and 2012, traders at the world\'s largest banks systematically manipulated the London Interbank Offered Rate (LIBOR), the benchmark interest rate used to price over $350 trillion in financial products worldwide -- including mortgages, credit cards, student loans, municipal bonds, and derivatives. Banks submitted false rate quotes to benefit their trading positions, costing borrowers, pension funds, and governments tens of billions of dollars. Investigations by the DOJ, CFTC, UK FSA/FCA, European Commission, and regulators in at least ten countries on three continents resulted in over $9 billion in fines against banks including Barclays, UBS, Deutsche Bank, Rabobank, Royal Bank of Scotland, Lloyds, ICAP, JPMorgan, and Citigroup. Despite evidence of widespread collusion involving hundreds of individuals, fewer than 35 people were charged worldwide, most prosecutions failed, and key convictions -- including that of trader Tom Hayes -- were overturned by the UK Supreme Court in July 2025.',
    content: [
      'THE MECHANISM OF FRAUD: LIBOR was calculated daily based on rate submissions from a panel of 16-18 major banks, representing the rate at which they claimed they could borrow unsecured funds from other banks in the London interbank market. The system was administered by the British Bankers\' Association (BBA) and relied entirely on self-reporting with no independent verification and no requirement that submissions be based on actual transactions. Each day, panel banks submitted their estimated borrowing costs, the highest and lowest quartiles were discarded, and the remaining submissions were averaged to produce the daily LIBOR rate. This architecture -- trusting the world\'s largest financial institutions to honestly report data that directly affected their own profits -- was an invitation to fraud.',
      'THE TRADING CULTURE: Traders at multiple banks colluded via Bloomberg chat rooms, instant messages, emails, and phone calls to manipulate submissions to benefit their trading positions. Internal communications revealed the casual, brazen nature of the corruption. "Pls go for 5.36 libor again, very important that the setting comes as high as possible ... thanks," wrote one Barclays trader in New York to a rate submitter in July 2007. Another trader promised payments to interdealer brokers at ICAP for moving rates: "if you keep 6s unchanged today ... I will fucking do one humongous deal with you ... Like a 50,000 buck deal, whatever ... I need you to keep it as low as possible ... if you do that .... I\'ll pay you, you know, 50,000 dollars, 100,000 dollars... whatever you want ... I\'m a man of my word." These were not rogue actors -- this was the culture.',
      'THE CARTEL IN LONDON: Court documents filed in Singapore by Royal Bank of Scotland trader Tan Chi Min revealed the extent of coordination. In released chat transcripts from August 2007, Tan told colleagues: "It\'s just amazing how Libor fixing can make you that much money or lose if opposite. It\'s a cartel now in London." In another conversation, RBS head of yen products Jezri Mohideen asked traders where they wanted LIBOR set. A colleague responded: "Where would you like it, Libor that is?" and then agreed to "move the curve down 1 basis point, maybe more if I can." By September 2008, a one basis point (1/100 of one percent) move in LIBOR had approximately a $750,000 effect on trader Tom Hayes\'s profit and loss alone.',
      'CRISIS-ERA SUPPRESSION: During the 2007-2009 financial crisis, the manipulation took a second form: banks deliberately suppressed their LIBOR submissions to appear healthier than they were. In a system where higher borrowing costs signaled financial weakness, banks that submitted truthfully risked triggering a run. In one 2008 exchange, a Barclays employee told a New York Federal Reserve analyst: "We know that we\'re not posting an honest Libor, and yet we are doing it, because if we didn\'t do it, it draws unwanted attention on ourselves." Bank of England Governor Mervyn King told the UK Parliament in November 2008 that LIBOR had become "in many ways the rate at which banks do not lend to each other ... it is not a rate at which anyone is actually borrowing."',
      'CENTRAL BANK KNOWLEDGE AND INACTION: The New York Federal Reserve and the Bank of England were aware of LIBOR problems years before the scandal became public. In early 2008, then-New York Fed President Timothy Geithner sent a memo to Bank of England chief Mervyn King recommending ways to "fix" LIBOR, including eliminating incentives for misreporting and increasing the number of contributing banks. Yet no documentation shows these recommendations were acted upon. Months later, a Barclays employee told a New York Fed representative that LIBOR rates were still "absolute rubbish." Paul Tucker, deputy governor of the Bank of England, was also aware of industry concerns as early as November 2007 that LIBOR was being under-reported. The regulators who could have stopped the fraud chose to look the other way.',
      'THE WALL STREET JOURNAL INVESTIGATION: On April 16, 2008, the Wall Street Journal published an article suggesting that some banks were understating their borrowing costs during the credit crunch, potentially misleading others about their financial positions. A subsequent academic study by economists Connan Snider and Thomas Youle in April 2010 confirmed the WSJ\'s findings and concluded that the reason for understatement was not merely that banks wanted to appear strong -- but that they sought to make substantial profits on their enormous LIBOR-linked interest rate portfolios. In the first quarter of 2009, JPMorgan Chase had interest rate swaps with a notional value of $49.3 trillion, Bank of America $49.7 trillion, and Citigroup $14.2 trillion.',
      'BARCLAYS: THE FIRST DOMINO: On June 27, 2012, Barclays became the first bank to settle LIBOR manipulation charges, paying $200 million to the CFTC, $160 million to the DOJ, and 59.5 million pounds to the UK Financial Services Authority -- approximately $453 million in total. The settlement revealed that Barclays had manipulated rates for at least two reasons: routinely, from at least 2005, traders sought favorable submissions to benefit their trading positions; and during the 2008 financial crisis, the bank artificially lowered submissions to appear healthier. The political fallout was immediate. Barclays chairman Marcus Agius resigned on July 2, 2012. The next day, CEO Bob Diamond resigned. Diamond was questioned by Parliament and claimed he was unaware of the manipulation.',
      'UBS AND TOM HAYES: On December 19, 2012, UBS agreed to pay $1.5 billion in fines -- $1.2 billion to the DOJ and CFTC, 160 million pounds to the UK FSA, and 59 million Swiss francs to the Swiss Financial Market Supervisory Authority (FINMA). Investigations revealed that UBS traders had colluded with other panel banks and made over 2,000 written requests for rate movements from at least January 2005 to June 2010. The US sought extradition of traders Tom Hayes and Roger Darin. Hayes, a mathematics graduate who traded yen-denominated interest rate derivatives, was at the center of a network spanning multiple banks and brokers. Through contacts at ICAP, the world\'s largest interdealer broker, he succeeded in having LIBOR reported lower than its true level.',
      'DEUTSCHE BANK: RECORD FINE: On April 23, 2015, Deutsche Bank agreed to pay a combined $2.5 billion -- $2.175 billion to American regulators and 227 million euros to British authorities -- the largest LIBOR-related fine in history and a reflection of the breadth of wrongdoing. The bank also pleaded guilty to wire fraud and acknowledged that at least 29 employees had engaged in illegal activity. Deutsche Bank was required to install an independent monitor -- a first for LIBOR cases. The UK FCA noted: "This case stands out for the seriousness and duration of the breaches ... One division at Deutsche Bank had a culture of generating profits without proper regard to the integrity of the market. This wasn\'t limited to a few individuals but, on certain desks, it appeared deeply ingrained."',
      'THE CASCADE OF BANK SETTLEMENTS: Beyond the three largest settlements, a wave of enforcement actions swept through global banking. The Royal Bank of Scotland settled with US and UK regulators in February 2013 for approximately $615 million, with its Japanese subsidiary pleading guilty to wire fraud. ICAP, the interdealer broker whose employees had facilitated rate-rigging communications between banks, paid $87 million in September 2013 while three former employees were charged. Rabobank was fined 774 million euros by US, UK, and Dutch regulators in October 2013. In December 2013, the European Commission imposed 1.71 billion euros in fines on six financial institutions for participating in yen LIBOR and EURIBOR cartels. Lloyds Banking Group paid $370 million in July 2014. Total fines across all banks exceeded $9 billion.',
      'THE FAILURE OF INDIVIDUAL PROSECUTION: Despite evidence of widespread collusion involving hundreds of traders, managers, and compliance officers at over a dozen banks, only about 35 individuals worldwide were charged. The UK Serious Fraud Office (SFO), which opened its criminal investigation in July 2012, charged 13 traders over the seven-year investigation. Of those, eight were acquitted, four were convicted (Tom Hayes, Alex Pabon, Jay Vijay Merchant, and Jonathan James Mathew), and one pleaded guilty (Peter Charles Johnson). Former Barclays traders were acquitted in the UK\'s fourth LIBOR trial in April 2017. ICAP brokers were acquitted in January 2016. The SFO closed its investigation in October 2019 at a reported cost of at least 60 million pounds -- with almost nothing to show for it.',
      'TOM HAYES: SCAPEGOAT OR CRIMINAL: Tom Hayes, a former UBS and Citigroup trader diagnosed with mild Asperger syndrome, became the face of the LIBOR scandal. He was arrested on December 11, 2012, and became the first person convicted of LIBOR rigging in August 2015, sentenced to 14 years in prison -- reduced to 11 on appeal. Hayes maintained throughout that manipulation was industry-wide, known to management, and expected as part of his job. He served approximately half his sentence and was released in January 2021. In October 2022, the US dismissed criminal charges against Hayes. In the UK, after years of appeals, the Supreme Court on July 23, 2025 overturned the convictions of both Hayes and Carlo Palombo (convicted in 2019), finding that the trial judge\'s directions to the jury were "legally inaccurate and unfair." In October 2025, Hayes sued UBS for $400 million in damages.',
      'MUNICIPALITIES AND HOMEOWNERS: The human cost of LIBOR manipulation extended far beyond trading floors. US states, counties, and local governments that had entered into LIBOR-based interest rate swaps to hedge their municipal bond sales lost at least $6 billion in fraudulent interest payments, above $4 billion they had already spent to unwind their positions. The city of Baltimore and others filed a class action in April 2012. Fannie Mae and Freddie Mac may have lost more than $3 billion. Homeowners with adjustable-rate mortgages saw their rates manipulated upward on reset dates -- statistical analysis showed LIBOR rose on average more than two basis points above average on the first day of each month when most ARMs reset, and between 2007 and 2009 this manipulation reached seven and a half basis points.',
      'THE DEATH OF LIBOR: The scandal ultimately destroyed LIBOR\'s credibility as a benchmark. In September 2012, the BBA announced it would transfer oversight of LIBOR to UK regulators, as recommended by the independent Wheatley Review. The Financial Services Act 2012 made LIBOR a regulated activity and created criminal sanctions for benchmark manipulation. NYSE Euronext took over LIBOR administration in early 2014. In the US, the Alternative Reference Rates Committee selected the Secured Overnight Financing Rate (SOFR) as the preferred replacement. In the UK, the Sterling Overnight Index Average (SONIA) replaced LIBOR. On June 30, 2023, LIBOR was officially discontinued for most currencies after nearly four decades.',
      'THE ACCOUNTABILITY GAP: The LIBOR scandal produced a staggering disparity between the scale of the crime and the consequences. Banks paid $9 billion in fines -- but these represented a tiny fraction of the profits earned through manipulation and were paid by shareholders, not by the executives who directed or benefited from the fraud. No bank lost its banking license. No bank was required to admit to systematic fraud beyond limited stipulations in plea deals. Most penalties were tax-deductible as business expenses. Bob Diamond kept approximately 120 million pounds in compensation from the manipulation period. Senior executives at every implicated bank who oversaw the manipulating desks faced no personal consequences whatsoever.',
      'SYSTEMIC IMPLICATIONS: The LIBOR scandal revealed that the most fundamental benchmark in global finance -- underpinning $350 trillion in instruments affecting every mortgage holder, student loan borrower, credit card user, and pension fund beneficiary on Earth -- was a fiction manufactured by the very institutions that profited from its manipulation. The scandal demonstrated that deregulated financial markets will self-corrupt when participants face no meaningful consequences. The banks that committed the fraud continue to operate as the largest financial institutions in the world. The replacement benchmarks (SOFR, SONIA) are based on actual overnight transaction data rather than self-reported estimates, representing a genuine structural improvement -- but the regulatory apparatus that failed to prevent LIBOR manipulation for over a decade remains largely unchanged.',
    ],
    tags: ['LIBOR', 'banking-fraud', 'interest-rate-manipulation', 'financial-crime', 'Barclays', 'Deutsche-Bank', 'UBS', 'derivatives', 'CFTC', 'benchmark-manipulation', 'Rabobank', 'Royal-Bank-of-Scotland', 'Tom-Hayes', 'wire-fraud', 'price-fixing', 'antitrust', 'rate-rigging', 'SOFR', 'interest-rate-swaps', 'municipal-fraud', 'mortgage-manipulation', 'financial-crisis', 'whistleblower', 'market-manipulation', 'deferred-prosecution'],
    sources: [
      { title: 'CFTC: Order Against Barclays for LIBOR Manipulation', url: 'https://www.cftc.gov/PressRoom/PressReleases/pr6289-12', type: 'Government Filing' },
      { title: 'DOJ: Barclays Bank PLC Admits Misconduct Related to LIBOR', url: 'https://www.justice.gov/opa/pr/2012/June/12-crm-815.html', type: 'Government Filing' },
      { title: 'CFTC: Order Against UBS for LIBOR Manipulation', url: 'https://www.cftc.gov/PressRoom/PressReleases/pr6472-12', type: 'Government Filing' },
      { title: 'Reuters: Deutsche Bank Fined Record $2.5 Billion in Rate Rigging', url: 'https://www.reuters.com/article/us-deutschebank-libor-settlement-idUSKBN0NE12U20150423', type: 'News Report' },
      { title: 'European Commission: Antitrust Fines for Interest Rate Derivatives Cartels', url: 'https://ec.europa.eu/commission/presscorner/detail/en/IP_13_1208', type: 'Government Filing' },
      { title: 'UK Financial Services Act 2012: LIBOR Reform Provisions', url: 'https://www.legislation.gov.uk/ukpga/2012/21/contents', type: 'Legal Document' },
      { title: 'NY Fed: Documents Concerning Barclays and the LIBOR Matter', url: 'https://www.newyorkfed.org/newsevents/news/markets/2012/Barclays_LIBOR_Matter.html', type: 'Government Filing' },
      { title: 'The Wheatley Review of LIBOR: Final Report', url: 'https://www.jdsupra.com/legalnews/the-wheatley-review-of-libor-final-repo-99414/', type: 'Government Report' },
      { title: 'NYT: Deutsche Bank to Pay $2.5 Billion Fine to Settle Rate-Rigging Case', url: 'https://www.nytimes.com/2015/04/24/business/dealbook/deutsche-bank-settlement-rates.html', type: 'News Report' },
      { title: 'BBC: UBS Fined $1.5 Billion for LIBOR Rigging', url: 'https://www.bbc.co.uk/news/business-20767984', type: 'News Report' },
      { title: 'WSJ: Bankers Cast Doubt on Key Rate Amid Crisis', url: 'https://www.wsj.com/articles/SB120831164167818299', type: 'News Report' },
      { title: 'UK Supreme Court: R v Hayes and Palombo (2025)', url: 'https://www.bbc.co.uk/news/articles/cr5vgqr8p14o', type: 'Legal Document' },
    ],
    affiliations: [
      { id: '1', name: 'DOJ', type: 'agency', relationship: 'Prosecuted banks and individuals; secured guilty pleas from UBS Japan and Deutsche Bank; brought wire fraud charges against traders; fines totaled billions but focused on corporate rather than individual accountability', href: '/entities/agencies/doj' },
      { id: '2', name: 'CFTC', type: 'agency', relationship: 'Primary US regulator for LIBOR enforcement; imposed largest fines including $200M against Barclays, $700M against UBS, $800M against Deutsche Bank; most aggressive enforcement among all regulators', href: '/entities/agencies/cftc' },
      { id: '3', name: 'UK Serious Fraud Office', type: 'agency', relationship: 'Opened criminal investigation July 2012; charged 13 individuals over seven years; secured only 5 convictions (2 later overturned); investigation closed October 2019 at cost of 60M+ pounds' },
      { id: '4', name: 'UK Financial Services Authority / FCA', type: 'agency', relationship: 'Imposed regulatory fines on Barclays (59.5M pounds), UBS (160M pounds), Deutsche Bank (227M euros), Lloyds (105M pounds); transitioned into FCA which now oversees LIBOR successor benchmarks' },
      { id: '5', name: 'SEC', type: 'agency', relationship: 'Coordinated with CFTC on enforcement; investigated bond market manipulation linked to LIBOR; limited direct enforcement role compared to CFTC', href: '/entities/agencies/sec' },
      { id: '6', name: 'European Commission', type: 'agency', relationship: 'Imposed 1.71 billion euros in cartel fines December 2013 for yen LIBOR and EURIBOR manipulation; fined RBS (260M euros), Deutsche Bank (259M euros), JPMorgan (80M euros), Citigroup (70M euros)' },
      { id: '7', name: 'FINMA', type: 'agency', relationship: 'Swiss Financial Market Supervisory Authority; fined UBS 59 million Swiss francs as part of the December 2012 settlement; ordered internal reforms' },
      { id: '8', name: 'Bank of England', type: 'agency', relationship: 'Aware of LIBOR problems as early as November 2007; deputy governor Paul Tucker discussed rates with Barclays CEO Diamond; failed to act on manipulation evidence for years despite internal knowledge' },
      { id: '9', name: 'Tom Hayes', type: 'individual', relationship: 'Former UBS and Citigroup trader; first person convicted of LIBOR rigging (August 2015, 14 years reduced to 11); conviction overturned by UK Supreme Court July 23, 2025; sued UBS for $400M October 2025', href: '/entities/individuals/tom-hayes' },
      { id: '10', name: 'Bob Diamond', type: 'individual', relationship: 'Barclays CEO who resigned July 3, 2012 following the $453M LIBOR settlement; questioned by Parliament; denied knowledge of manipulation; retained approximately 120M pounds in compensation from fraud period' },
      { id: '11', name: 'Carlo Palombo', type: 'individual', relationship: 'Former trader convicted in 2019 for EURIBOR manipulation; conviction overturned by UK Supreme Court alongside Hayes on July 23, 2025; court found trial judge directions were legally inaccurate' },
      { id: '12', name: 'Paul Tucker', type: 'individual', relationship: 'Bank of England deputy governor; discussed LIBOR rates with Bob Diamond during 2008 crisis; testified before Parliament denying he encouraged manipulation; aware of rate-reporting concerns since November 2007' },
      { id: '13', name: 'Timothy Geithner', type: 'individual', relationship: 'New York Federal Reserve President who sent memo to Bank of England Governor Mervyn King in 2008 recommending LIBOR reforms; no evidence recommendations were acted upon or followed up' },
      { id: '14', name: 'Marcus Agius', type: 'individual', relationship: 'Barclays chairman who resigned July 2, 2012 -- one day before CEO Diamond -- following the LIBOR settlement; no criminal charges filed' },
      { id: '15', name: 'Roger Darin', type: 'individual', relationship: 'UBS manager who oversaw rate submissions in Tokyo; charged by US DOJ alongside Tom Hayes in December 2012 for wire fraud and antitrust violations related to LIBOR manipulation' },
      { id: '16', name: 'Barclays', type: 'corporation', relationship: 'First bank to settle LIBOR charges ($453M, June 2012); manipulation spanned from at least 2005; traders routinely requested favorable submissions; CEO and chairman both resigned' },
      { id: '17', name: 'UBS', type: 'corporation', relationship: 'Fined $1.5 billion (December 2012); Japanese subsidiary pleaded guilty to wire fraud; traders made over 2,000 written requests for rate movements between 2005-2010; granted EU immunity for revealing cartels' },
      { id: '18', name: 'Deutsche Bank', type: 'corporation', relationship: 'Largest LIBOR fine: $2.5 billion (April 2015); 29 employees involved; required independent monitor; serial misconduct institution (LIBOR, forex, mirror trades, Epstein banking)' },
      { id: '19', name: 'Rabobank', type: 'corporation', relationship: 'Dutch cooperative bank fined 774 million euros (October 2013) by US, UK, and Dutch regulators for LIBOR manipulation; multiple traders subsequently charged' },
      { id: '20', name: 'Royal Bank of Scotland', type: 'corporation', relationship: 'Settled with US and UK regulators for approximately $615 million (February 2013); Japanese subsidiary pleaded guilty; fined additional 260 million euros by EU for yen cartel' },
      { id: '21', name: 'ICAP', type: 'corporation', relationship: 'World\'s largest interdealer broker; facilitated rate-rigging communications between bank traders; settled for $87 million (September 2013); three former employees charged by DOJ' },
      { id: '22', name: 'Martin Wheatley', type: 'individual', relationship: 'FSA managing director and CEO-designate of the new Financial Conduct Authority; led the independent Wheatley Review (September 2012) which recommended comprehensive LIBOR reforms adopted by UK government' },
    ],
    eventOriginDate: '2003-01-01',
    lastActivityDate: '2025-10-27',
    pageUpdatedDate: '2026-03-18',
    timeline: [
      { date: '1986', event: 'The British Bankers\' Association (BBA) formally establishes the LIBOR benchmark rate, based on daily submissions from a panel of major banks estimating their unsecured borrowing costs', type: 'default' },
      { date: '1991', event: 'According to a Financial Times article published July 27, 2012, manipulation of LIBOR had been "common" since at least 1991, predating the official investigations by over two decades', type: 'critical' },
      { date: '2003', event: 'Earliest documented period of systematic profit-driven LIBOR manipulation across multiple banks, with traders requesting specific rate submissions to benefit their trading positions', type: 'critical' },
      { date: '2005', event: 'Internal communications show Barclays traders routinely requesting favorable LIBOR submissions from rate submitters, marking the earliest documented manipulation at the bank', type: 'financial' },
      { date: '2007-08-19', event: 'RBS trader Tan Chi Min in Singapore tells Deutsche Bank trader Mark Wong: "It\'s just amazing how Libor fixing can make you that much money or lose if opposite. It\'s a cartel now in London"', type: 'critical' },
      { date: '2007-11', event: 'Bank of England deputy governor Paul Tucker and other officials become aware of industry concerns that LIBOR is being under-reported, according to Bank of England minutes', type: 'political' },
      { date: '2008-04-16', event: 'The Wall Street Journal publishes investigation suggesting some banks understated LIBOR submissions during the credit crunch, potentially misleading markets about their financial health', type: 'default' },
      { date: '2008-06', event: 'New York Fed President Timothy Geithner sends memo to Bank of England Governor Mervyn King recommending six specific reforms to improve LIBOR integrity; no evidence reforms were implemented', type: 'political' },
      { date: '2008-10', event: 'Months after Geithner\'s reform memo, a Barclays employee tells a New York Fed representative that LIBOR rates are still "absolute rubbish"', type: 'critical' },
      { date: '2008-11', event: 'Bank of England Governor Mervyn King tells UK Parliament that LIBOR has become "in many ways the rate at which banks do not lend to each other"', type: 'political' },
      { date: '2010-04', event: 'Academic study by economists Connan Snider and Thomas Youle confirms WSJ findings and concludes banks manipulated LIBOR to profit from their massive interest-rate-linked portfolios', type: 'default' },
      { date: '2011-03', event: 'Wall Street Journal reports US regulators are focusing on Bank of America, Citigroup, and UBS in their probe of LIBOR rate manipulation', type: 'legal' },
      { date: '2012-02', event: 'US Department of Justice announces formal criminal investigation into LIBOR abuse, examining whether traders were in direct communication with bankers before rates were set', type: 'legal' },
      { date: '2012-06-27', event: 'Barclays becomes first bank to settle: $200 million CFTC fine, $160 million DOJ penalty, and 59.5 million pound FSA fine -- approximately $453 million total', type: 'financial' },
      { date: '2012-07-02', event: 'Barclays chairman Marcus Agius resigns in the wake of the LIBOR settlement', type: 'political' },
      { date: '2012-07-03', event: 'Barclays CEO Bob Diamond resigns; subsequently questioned by Parliament about his knowledge of rate manipulation', type: 'political' },
      { date: '2012-07-06', event: 'UK Serious Fraud Office opens criminal investigation into LIBOR manipulation, not limited to Barclays', type: 'legal' },
      { date: '2012-07-10', event: 'US Congress begins investigating LIBOR scandal; regulators in at least ten countries on three continents are now probing the rigging', type: 'political' },
      { date: '2012-07-16', event: 'Former Barclays executive Jerry del Missier testifies before Parliament that he received instructions from Bob Diamond to lower rates after Diamond\'s conversation with Bank of England', type: 'political' },
      { date: '2012-07-27', event: 'Financial Times publishes article by former trader stating LIBOR manipulation had been common since at least 1991', type: 'default' },
      { date: '2012-10', event: 'US homeowners file class action lawsuit against twelve banks alleging LIBOR manipulation made adjustable-rate mortgage repayments more expensive than they should have been', type: 'legal' },
      { date: '2012-11', event: 'Federal Housing Finance Agency audit estimates Fannie Mae and Freddie Mac may have lost more than $3 billion due to LIBOR manipulation', type: 'financial' },
      { date: '2012-12-11', event: 'Tom Hayes arrested by UK authorities for involvement in manipulating LIBOR rates; subsequently charged by US DOJ alongside Roger Darin', type: 'legal' },
      { date: '2012-12-19', event: 'UBS agrees to pay $1.5 billion in fines to US, UK, and Swiss regulators; US Assistant AG Lanny Breuer describes UBS conduct as "simply astonishing"', type: 'financial' },
      { date: '2013-02-06', event: 'Royal Bank of Scotland settles with US and UK regulators for approximately $615 million; Japanese subsidiary pleads guilty to wire fraud', type: 'financial' },
      { date: '2013-07', event: 'LIBOR becomes a regulated activity under UK Financial Conduct Authority oversight; Financial Services Act 2012 criminalizes benchmark manipulation', type: 'legal' },
      { date: '2013-09', event: 'ICAP settles for $87 million; three former employees charged by DOJ for facilitating LIBOR manipulation as interdealer brokers', type: 'financial' },
      { date: '2013-10', event: 'Rabobank fined 774 million euros by US, UK, and Dutch regulators for widespread LIBOR manipulation', type: 'financial' },
      { date: '2013-12', event: 'European Commission imposes 1.71 billion euros in fines: RBS (260M euros), Deutsche Bank (259M euros), JPMorgan (80M euros), Citigroup (70M euros), RP Martin (247K euros) for yen LIBOR cartel', type: 'financial' },
      { date: '2014-01', event: 'NYSE Euronext takes over administration of LIBOR from the British Bankers\' Association as part of post-scandal reforms', type: 'default' },
      { date: '2014-07', event: 'Lloyds Banking Group fined $370 million (218 million pounds) by US and UK regulators for LIBOR manipulation', type: 'financial' },
      { date: '2015-04-23', event: 'Deutsche Bank agrees to record $2.5 billion fine; acknowledges 29 employees engaged in illegal activity; required to install independent monitor; pleads guilty to wire fraud', type: 'financial' },
      { date: '2015-08-03', event: 'Tom Hayes convicted on 8 counts of conspiracy to defraud and sentenced to 14 years in prison -- the first individual convicted for LIBOR rigging', type: 'legal' },
      { date: '2015-12', event: 'Tom Hayes\'s sentence reduced to 11 years on appeal, but conviction upheld by Court of Appeal', type: 'legal' },
      { date: '2016-01', event: 'Six former ICAP brokers acquitted in London LIBOR trial, dealing significant blow to the Serious Fraud Office prosecution strategy', type: 'legal' },
      { date: '2017-04', event: 'Former Barclays traders acquitted in UK\'s fourth LIBOR trial, further undermining individual prosecution efforts', type: 'legal' },
      { date: '2019-10', event: 'UK Serious Fraud Office closes seven-year LIBOR investigation at estimated cost of 60 million+ pounds; only 5 of 13 charged individuals were convicted', type: 'legal' },
      { date: '2021-01-29', event: 'Tom Hayes released from prison on licence after serving approximately half of his 11-year sentence', type: 'legal' },
      { date: '2022-01-27', event: 'US Court of Appeals for the Second Circuit overturns convictions of Matthew Connolly and Gavin Campbell Black, ruling LIBOR submissions were not proven to have been made with fraudulent intent', type: 'legal' },
      { date: '2022-10', event: 'United States formally dismisses all criminal charges against Tom Hayes, removing the threat of US prosecution', type: 'legal' },
      { date: '2023-06-30', event: 'LIBOR officially discontinued for most currencies after nearly four decades, replaced by SOFR (US), SONIA (UK), and other transaction-based benchmarks', type: 'default' },
      { date: '2024-03', event: 'UK Court of Appeal upholds Tom Hayes\'s conviction after referral by the Criminal Cases Review Commission, ruling there was "indisputable documentary evidence" he sought to move LIBOR', type: 'legal' },
      { date: '2025-07-23', event: 'UK Supreme Court overturns convictions of Tom Hayes (2015) and Carlo Palombo (2019), declaring the trial judge\'s directions were "legally inaccurate and unfair" and the convictions unsafe', type: 'critical' },
      { date: '2025-10-27', event: 'Tom Hayes sues UBS for $400 million in damages, claiming his LIBOR manipulation activities were common practice known and condoned by senior management', type: 'legal' },
    ],

    defendants: [
      { name: 'Barclays', role: 'First bank to settle LIBOR manipulation charges; traders routinely requested favorable rate submissions from 2005-2012; artificially suppressed rates during financial crisis', status: 'settled' as const, fine: '$453 million', notes: 'CEO Bob Diamond and chairman Marcus Agius both resigned. No senior executive criminally charged.' },
      { name: 'UBS AG', role: 'Swiss bank whose traders made 2,000+ written requests for rate movements from 2005-2010; Japanese subsidiary pleaded guilty to wire fraud', status: 'settled' as const, fine: '$1.5 billion', notes: 'Granted EU immunity for revealing yen cartel. Tom Hayes and Roger Darin charged as individuals.' },
      { name: 'Deutsche Bank AG', role: 'Record LIBOR fine recipient; 29 employees engaged in illegal manipulation; culture of generating profits without regard to market integrity', status: 'settled' as const, fine: '$2.5 billion', convictionDate: '2015-04-23', notes: 'Pleaded guilty to wire fraud. Required independent monitor. No individuals criminally charged despite breadth of misconduct.' },
      { name: 'Rabobank', role: 'Dutch cooperative bank engaged in widespread LIBOR manipulation across multiple currencies and trading desks', status: 'settled' as const, fine: '774 million euros', notes: 'Multiple traders subsequently charged by US DOJ. Deferred prosecution agreement with DOJ.' },
      { name: 'Royal Bank of Scotland', role: 'Traders extensively discussed manipulating LIBOR in released transcripts; Japanese subsidiary pleaded guilty to wire fraud', status: 'settled' as const, fine: '$615 million + 260 million euros EU', notes: 'Fined by US, UK regulators and EU Commission separately.' },
      { name: 'ICAP', role: 'Largest interdealer broker; employees facilitated rate-rigging communications between traders at competing banks; brokers spread false information to move rates', status: 'settled' as const, fine: '$87 million', notes: 'Three employees charged by DOJ. Six brokers acquitted at trial in UK.' },
      { name: 'Lloyds Banking Group', role: 'Manipulated LIBOR and other benchmark rates across multiple subsidiaries', status: 'settled' as const, fine: '$370 million', notes: 'Fined by US and UK regulators in July 2014.' },
      { name: 'Tom Hayes', role: 'Former UBS and Citigroup trader who operated network of brokers and traders to manipulate yen LIBOR from 2006-2010; first person convicted of LIBOR rigging', status: 'acquitted' as const, sentence: '14 years (reduced to 11)', convictionDate: '2015-08-03', releaseDate: '2021-01-29', appealStatus: 'granted' as const, notes: 'Conviction overturned by UK Supreme Court July 23, 2025. US charges dismissed October 2022. Suing UBS for $400M.' },
      { name: 'Bob Diamond', role: 'Barclays CEO during the manipulation period who resigned under pressure; questioned by Parliament; denied knowledge of manipulation despite receiving information from Paul Tucker', status: 'pending' as const, notes: 'No criminal charges filed. Retained approximately 120 million pounds in compensation from the manipulation period.' },
      { name: 'Carlo Palombo', role: 'Former trader convicted of EURIBOR manipulation in 2019; maintained innocence throughout proceedings', status: 'acquitted' as const, convictionDate: '2019', appealStatus: 'granted' as const, notes: 'Conviction overturned alongside Tom Hayes by UK Supreme Court on July 23, 2025.' },
    ],

    moneyTrail: [
      { date: '2005-01-01', from: 'LIBOR Panel Banks', to: 'Proprietary trading desks', amount: 'Billions (estimated)', purpose: 'Trading profits derived from manipulated LIBOR rates across interest rate derivatives, basis trades, and swaps', documented: true },
      { date: '2007-01-01', from: 'Municipalities and pension funds', to: 'LIBOR panel banks', amount: '$6+ billion', purpose: 'Losses on LIBOR-indexed interest rate swaps due to artificially suppressed rates during the financial crisis', documented: true },
      { date: '2012-06-27', from: 'Barclays', to: 'US/UK regulators', amount: '$453 million', purpose: 'Combined CFTC ($200M), DOJ ($160M), and FSA (59.5M pounds) settlement for LIBOR and EURIBOR manipulation', documented: true },
      { date: '2012-12-19', from: 'UBS', to: 'US/UK/Swiss regulators', amount: '$1.5 billion', purpose: 'Settlement with DOJ, CFTC ($700M), UK FSA (160M pounds), and Swiss FINMA (59M CHF) for LIBOR manipulation', documented: true },
      { date: '2013-02-06', from: 'Royal Bank of Scotland', to: 'US/UK regulators', amount: '$615 million', purpose: 'LIBOR settlement; Japanese subsidiary pleaded guilty to wire fraud', documented: true },
      { date: '2013-09-25', from: 'ICAP', to: 'US/UK regulators', amount: '$87 million', purpose: 'Settlement for facilitating LIBOR manipulation through interdealer brokerage operations ($65M CFTC, $22M FCA)', documented: true },
      { date: '2013-10-29', from: 'Rabobank', to: 'US/UK/Dutch regulators', amount: '774 million euros', purpose: 'Multi-jurisdictional settlement for widespread LIBOR manipulation across currencies and trading desks', documented: true },
      { date: '2013-12-04', from: 'Various banks', to: 'European Commission', amount: '1.71 billion euros', purpose: 'EU cartel fines for yen LIBOR manipulation: RBS (260M), Deutsche Bank (259M), JPMorgan (80M), Citigroup (70M)', documented: true },
      { date: '2014-07-28', from: 'Lloyds Banking Group', to: 'US/UK regulators', amount: '$370 million', purpose: 'LIBOR and benchmark rate manipulation settlement with CFTC and FCA', documented: true },
      { date: '2015-04-23', from: 'Deutsche Bank', to: 'US/UK regulators', amount: '$2.5 billion', purpose: 'Record LIBOR fine: $2.175B to US regulators, 227M euros to UK FCA; bank pleaded guilty to wire fraud', documented: true },
      { date: '2003-2012', from: 'LIBOR panel banks', to: 'Senior executives', amount: 'Hundreds of millions', purpose: 'Performance bonuses inflated by trading profits derived from LIBOR manipulation; Bob Diamond alone earned 120M+ pounds', documented: true },
      { date: '2012-2025', from: 'Banks', to: 'Civil litigation plaintiffs', amount: 'Billions (ongoing)', purpose: 'Class action settlements for municipalities, pension funds, and institutional investors harmed by LIBOR manipulation', documented: false },
    ],

    whereIsTheMoneyNow: [
      { name: 'Regulatory Fine Proceeds', relationship: 'Fines paid by banks for LIBOR manipulation', transferMethod: 'Corporate settlement payments from bank balance sheets to US, UK, EU, Swiss, and Dutch regulators -- totaling over $9 billion', estimatedValue: '$9+ billion', legalEntities: ['CFTC', 'DOJ', 'FCA', 'European Commission', 'FINMA'], recoveryMechanisms: ['Regulatory enforcement actions', 'Deferred prosecution agreements', 'Guilty pleas'], restitutionStatus: 'paid' as const },
      { name: 'Executive Compensation (Barclays)', relationship: 'Bob Diamond retained compensation from manipulation period', transferMethod: 'CEO salary, bonuses, and stock options earned during active LIBOR manipulation period (2005-2012); resigned without clawback', estimatedValue: '120 million+ pounds', legalEntities: ['Barclays PLC'], recoveryMechanisms: ['Clawback provisions (not exercised)', 'Disgorgement orders (not sought)'], restitutionStatus: 'evaded' as const },
      { name: 'Shareholder Losses', relationship: 'Bank shareholders bore the cost of fines', transferMethod: 'All $9B+ in fines were paid from bank capital and operating income, reducing shareholder value and dividends rather than reaching executives who directed fraud', estimatedValue: '$9+ billion in shareholder value destruction', legalEntities: ['Barclays', 'UBS', 'Deutsche Bank', 'RBS', 'Rabobank', 'Lloyds', 'ICAP'], recoveryMechanisms: ['Shareholder derivative suits'], restitutionStatus: 'unpaid' as const },
      { name: 'Municipal Losses', relationship: 'US states, counties, and cities lost billions on LIBOR-indexed swaps', transferMethod: 'Municipalities entered LIBOR-based interest rate swaps where artificially suppressed LIBOR reduced their swap receipts while bond payments remained at market rates', estimatedValue: '$6 billion+ in fraudulent interest payments, $4 billion+ in unwinding costs', legalEntities: ['City of Baltimore', 'Hundreds of US municipalities'], recoveryMechanisms: ['Class action antitrust treble damages', 'Private litigation'], restitutionStatus: 'partial' as const },
      { name: 'GSE Losses', relationship: 'Fannie Mae and Freddie Mac exposed to manipulated rates', transferMethod: 'Government-sponsored enterprises held massive LIBOR-indexed portfolios that generated lower returns due to rate suppression during the financial crisis', estimatedValue: '$3+ billion (FHFA estimate)', legalEntities: ['Fannie Mae', 'Freddie Mac'], recoveryMechanisms: ['FHFA litigation against panel banks'], restitutionStatus: 'partial' as const },
      { name: 'Consumer Overpayments', relationship: 'Millions of borrowers with LIBOR-indexed products', transferMethod: 'Homeowners with adjustable-rate mortgages, student loan borrowers, and credit card holders paid rates based on manipulated LIBOR -- higher on reset dates, lower during crisis suppression', estimatedValue: 'Billions (unquantified aggregate)', legalEntities: ['Millions of individual borrowers'], recoveryMechanisms: ['Class action litigation (limited success)', 'No individual restitution program'], restitutionStatus: 'unpaid' as const },
      { name: 'Trading Profits Absorbed', relationship: 'Manipulation profits absorbed into bank balance sheets', transferMethod: 'The direct trading profits from LIBOR manipulation were booked as ordinary bank revenue, commingled with legitimate trading income, and distributed as bonuses and dividends', estimatedValue: 'Tens of billions (estimated across all banks, all years)', legalEntities: ['All LIBOR panel banks'], recoveryMechanisms: ['Disgorgement (rarely sought)', 'Criminal forfeiture (minimal)'], restitutionStatus: 'evaded' as const },
      { name: 'Legal Industry Fees', relationship: 'Defense and prosecution costs', transferMethod: 'Banks spent billions on legal defense; regulators and prosecutors spent hundreds of millions on investigations; UK SFO investigation alone cost 60M+ pounds', estimatedValue: 'Billions in combined legal fees', legalEntities: ['Major law firms worldwide'], recoveryMechanisms: ['Not applicable'], restitutionStatus: 'unknown' as const },
    ],

    scrubbedFromInternet: [
      { title: 'Pre-2005 Internal Bank Communications on Rate-Setting Practices', type: 'destroyed' as const, description: 'Internal emails, chat logs, and phone recordings from the earliest period of LIBOR manipulation (pre-2005) were subject to routine document retention policies that destroyed evidence before investigations began', originalSource: 'Internal bank communication systems', dateRemoved: 'Pre-2012 (routine destruction)', removedBy: 'Bank document retention policies', recoveryStatus: 'lost' as const },
      { title: 'Full Diamond-Tucker Conversation Transcripts', type: 'sealed' as const, description: 'Complete transcripts of conversations between Barclays CEO Bob Diamond and Bank of England deputy governor Paul Tucker regarding LIBOR during the 2008 crisis; only Diamond\'s contemporaneous notes released', originalSource: 'Barclays internal records / Bank of England', dateRemoved: '2012', removedBy: 'Parliamentary privilege and regulatory confidentiality', recoveryStatus: 'partial' as const },
      { title: 'UBS Internal LIBOR Rate-Setting Protocols', type: 'redacted' as const, description: 'UBS internal documents describing the actual process by which LIBOR submissions were determined, including the role of trader requests in influencing submissions', originalSource: 'UBS AG internal compliance documents', dateRemoved: '2012-2013', removedBy: 'Partially sealed under settlement terms with FINMA', recoveryStatus: 'partial' as const },
      { title: 'Deutsche Bank Internal Investigation Findings', type: 'sealed' as const, description: 'Deutsche Bank conducted internal investigations into LIBOR manipulation that identified signs of abuse, but the bank failed to take action; full internal findings remain confidential', originalSource: 'Deutsche Bank compliance division', dateRemoved: '2015', removedBy: 'Attorney-client privilege claims', recoveryStatus: 'partial' as const },
      { title: 'Bank of England Sterling Money Markets Liaison Group Meeting Notes', type: 'buried' as const, description: 'Meeting notes from November 2007 and subsequent meetings where industry participants discussed concerns about LIBOR accuracy with Bank of England officials', originalSource: 'Bank of England', dateRemoved: 'Partially released July 2012; full notes remain restricted', removedBy: 'Bank of England archives policy', archiveUrl: 'https://www.bankofengland.co.uk/publications/Pages/news/2012/068.aspx', recoveryStatus: 'partial' as const },
      { title: 'SFO Investigation Files on Senior Bank Executives', type: 'sealed' as const, description: 'UK Serious Fraud Office investigated senior executives at multiple banks for their role in creating incentive structures that encouraged LIBOR manipulation; files sealed after investigation closed in October 2019 without charges', originalSource: 'UK Serious Fraud Office', dateRemoved: '2019', removedBy: 'SFO case closure procedures', recoveryStatus: 'lost' as const },
    ],

    statutes: [
      { code: '18 U.S.C. \u00a7 1343', description: 'Wire Fraud -- primary US charge used against LIBOR manipulators; up to 20 years per count when involving financial institutions' },
      { code: '18 U.S.C. \u00a7 1344', description: 'Bank Fraud -- applicable to false representations made to and by banking institutions in connection with LIBOR submissions' },
      { code: '7 U.S.C. \u00a7 9', description: 'Commodity Exchange Act -- CFTC enforcement authority for manipulation of commodity prices including interest rates; basis for largest fines' },
      { code: '15 U.S.C. \u00a7 1', description: 'Sherman Antitrust Act -- coordinated LIBOR manipulation among competing banks constitutes per se price fixing; treble damages available to private plaintiffs' },
      { code: '15 U.S.C. \u00a7 78j(b)', description: 'Securities Exchange Act / Rule 10b-5 -- securities fraud provisions applicable to manipulation affecting securities markets' },
      { code: 'UK Fraud Act 2006', description: 'Conspiracy to defraud -- basis for UK criminal prosecution of Tom Hayes and other traders; requires proof of dishonesty' },
      { code: 'Financial Services Act 2012 (UK)', description: 'Created specific criminal offense for making false or misleading statements in relation to benchmark-setting; enacted in response to LIBOR scandal' },
      { code: 'Article 101 TFEU', description: 'EU Treaty on the Functioning of the European Union -- prohibits anticompetitive agreements; basis for 1.71 billion euro EU cartel fines' },
      { code: '18 U.S.C. \u00a7 371', description: 'Conspiracy to commit offense against the United States -- used alongside wire fraud charges in multi-defendant LIBOR prosecutions' },
      { code: 'Dodd-Frank Act \u00a7 929-Z', description: 'Wall Street Reform and Consumer Protection Act -- enhanced CFTC enforcement authority over benchmark manipulation and increased penalties' },
    ],
  },"""

def main():
    # Read the file
    with open(FILE_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the start of the banking-libor-manipulation entry
    start_pattern = r"  'banking-libor-manipulation': \{"
    start_match = re.search(start_pattern, content)
    if not start_match:
        print("ERROR: Could not find 'banking-libor-manipulation' entry!")
        sys.exit(1)

    start_pos = start_match.start()

    # Find the next entry after banking-libor-manipulation
    # Look for the pattern "  'pentagon-budget-unauditable-waste':" after our entry
    end_pattern = r"\n  'pentagon-budget-unauditable-waste':"
    end_match = re.search(end_pattern, content[start_pos:])
    if not end_match:
        print("ERROR: Could not find next entry after LIBOR!")
        sys.exit(1)

    # The end position is where the next entry key starts
    # We need to find the closing "},\n" just before it
    end_region = content[start_pos:start_pos + end_match.start()]

    # Find the last "},\n" in the end region which closes the LIBOR entry
    last_close = end_region.rfind('\n  },')
    if last_close == -1:
        print("ERROR: Could not find closing brace of LIBOR entry!")
        sys.exit(1)

    # The entry spans from start_pos to start_pos + last_close + len('\n  },')
    entry_end = start_pos + last_close + len('\n  },')

    old_entry = content[start_pos:entry_end]
    print(f"Found old entry: {len(old_entry)} characters, starts with: {old_entry[:80]}...")
    print(f"Old entry ends with: ...{old_entry[-40:]}")

    # Replace
    new_content = content[:start_pos] + NEW_ENTRY + content[entry_end:]

    # Verify the replacement
    if 'Goldman Sachs' in new_content[start_pos:start_pos + len(NEW_ENTRY) + 100]:
        print("ERROR: Goldman Sachs still present in replacement region!")
        sys.exit(1)

    if 'banking-libor-manipulation' not in new_content:
        print("ERROR: Entry key missing after replacement!")
        sys.exit(1)

    if 'pentagon-budget-unauditable-waste' not in new_content:
        print("ERROR: Next entry missing after replacement!")
        sys.exit(1)

    # Write back
    with open(FILE_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Replaced LIBOR entry ({len(old_entry)} chars -> {len(NEW_ENTRY)} chars)")

if __name__ == '__main__':
    main()
