// Auto-generated by ArkHive Forge — 2026-03-10T18:34:33.785Z
// API route integration tests

import { describe, it, expect } from 'vitest';

const BASE = 'http://localhost:3000';

const routes = [
  {
    "path": "/api/search",
    "methods": [
      "GET"
    ],
    "description": "Full-text search across all entities and investigations"
  },
  {
    "path": "/api/entities/test",
    "methods": [
      "GET"
    ],
    "description": "List entities by type with filtering, sorting, pagination"
  },
  {
    "path": "/api/entities/test/test",
    "methods": [
      "GET",
      "PATCH"
    ],
    "description": "Get or update a single entity"
  },
  {
    "path": "/api/investigations",
    "methods": [
      "GET"
    ],
    "description": "List investigations with filtering"
  },
  {
    "path": "/api/investigations/test",
    "methods": [
      "GET"
    ],
    "description": "Get single investigation"
  },
  {
    "path": "/api/network/test",
    "methods": [
      "GET"
    ],
    "description": "Get network graph data for an entity"
  },
  {
    "path": "/api/timeline",
    "methods": [
      "GET"
    ],
    "description": "Get timeline events with date range filtering"
  },
  {
    "path": "/api/stats",
    "methods": [
      "GET"
    ],
    "description": "Platform-wide statistics"
  },
  {
    "path": "/api/export/test",
    "methods": [
      "GET"
    ],
    "description": "Export data as PDF, CSV, or JSON"
  },
  {
    "path": "/api/audit",
    "methods": [
      "GET"
    ],
    "description": "Audit log of all changes"
  },
  {
    "path": "/api/submit",
    "methods": [
      "POST"
    ],
    "description": "Submit tips and evidence"
  },
  {
    "path": "/api/health",
    "methods": [
      "GET"
    ],
    "description": "Health check endpoint"
  }
];

describe('API Routes', () => {
  routes.forEach(route => {
    route.methods.forEach(method => {
      it(`${method} ${route.path} should respond`, async () => {
        // These tests require a running dev server
        // npm run dev must be running before executing these tests
        try {
          const res = await fetch(`${BASE}${route.path}`, {
            method,
            headers: method === 'POST' ? { 'Content-Type': 'application/json' } : {},
            body: method === 'POST' ? JSON.stringify({ subject: 'test', description: 'test' }) : undefined,
          });
          expect(res.status).toBeLessThan(500);
        } catch (e) {
          // Dev server not running — skip gracefully
          console.warn(`Skipping ${route.path}: dev server not reachable`);
        }
      });
    });
  });
});
