// Auto-generated by ArkHive Forge — 2026-03-10T18:34:33.787Z
// Data file integrity tests — validates all shard files parse correctly

const fs = require('fs');
const path = require('path');

describe('Data File Integrity', () => {
  const dataDir = path.resolve(__dirname, '../src/data');
  const entityDirs = ['individuals', 'agencies', 'corporations', 'organizations'];

  entityDirs.forEach(dir => {
    describe(`${dir} data files`, () => {
      const fullDir = path.join(dataDir, dir);

      it(`${dir} directory should exist`, () => {
        expect(fs.existsSync(fullDir)).toBe(true);
      });

      it('should have parseable shard files', () => {
        if (!fs.existsSync(fullDir)) return;
        const files = fs.readdirSync(fullDir).filter(f =>
          f.endsWith('.ts') && f !== 'types.ts' && f !== 'index.ts'
        );
        expect(files.length).toBeGreaterThan(0);
      });
    });
  });

  describe('investigations data files', () => {
    const invDir = path.join(dataDir, 'investigations');

    it('should have at least 20 shard files', () => {
      if (!fs.existsSync(invDir)) return;
      const files = fs.readdirSync(invDir).filter(f => f.endsWith('.ts') && f.length <= 4);
      expect(files.length).toBeGreaterThanOrEqual(20);
    });
  });
});
