// Auto-generated by ArkHive Forge — 2026-03-10T18:34:33.786Z
// Enrichment pipeline validation tests

import { describe, it, expect } from 'vitest';

const ALL_CRIME_CATEGORIES = ["Financial Fraud","Corruption & Bribery","Obstruction of Justice","Money Laundering","Conspiracy","Environmental Crimes","Human Rights Violations","Tax Evasion","Insider Trading","Regulatory Violations","War Crimes","Election Interference","Cybercrime & Data Theft","Human Trafficking","Drug Trafficking","Arms Trafficking","Racketeering (RICO)","Embezzlement","Extortion & Blackmail","Perjury & False Statements","Espionage","Terrorism Financing","Sanctions Violations","Antitrust & Price Fixing","Intellectual Property Theft","Identity Theft & Fraud","Bank Fraud","Healthcare Fraud","Insurance Fraud","Real Estate Fraud","Forgery & Counterfeiting","Child Exploitation","Domestic Violence & Abuse","Stalking & Harassment","Manslaughter & Negligent Homicide","Kidnapping & False Imprisonment","Witness Intimidation","Jury Tampering","Illegal Surveillance","Civil Rights Violations","Police Brutality & Misconduct","Genocide & Ethnic Cleansing","Forced Labor & Modern Slavery","Maritime & Admiralty Crimes","Aviation Violations","Nuclear & Radiological Crimes","Biological Weapons Violations","Cultural Property Trafficking","Wildlife Trafficking","Illegal Logging & Deforestation","Water Contamination","Medical Malpractice & Negligence","Academic Fraud & Plagiarism"];

describe('Crime Category Coverage', () => {
  it('should have 53 crime categories defined', () => {
    expect(ALL_CRIME_CATEGORIES.length).toBe(53);
  });

  it('should have no duplicate categories', () => {
    const unique = new Set(ALL_CRIME_CATEGORIES);
    expect(unique.size).toBe(ALL_CRIME_CATEGORIES.length);
  });

  it('all categories should be non-empty strings', () => {
    ALL_CRIME_CATEGORIES.forEach(cat => {
      expect(typeof cat).toBe('string');
      expect(cat.length).toBeGreaterThan(0);
    });
  });
});

describe('Schema Validation', () => {
  it('should have entity definitions for all types', () => {
    const entityTypes = ['Individual', 'Agency', 'Corporation', 'Organization', 'Investigation'];
    const schema = require('../bots/forge/schema');
    entityTypes.forEach(type => {
      expect(schema.entities[type]).toBeDefined();
    });
  });

  it('all entities should have required fields', () => {
    const schema = require('../bots/forge/schema');
    Object.entries(schema.entities).forEach(([name, def]) => {
      const required = Object.entries(def.fields)
        .filter(([, f]) => f.required)
        .map(([k]) => k);
      expect(required.length).toBeGreaterThan(0);
    });
  });

  it('all enrichable fields should have merge strategies', () => {
    const schema = require('../bots/forge/schema');
    Object.entries(schema.entities).forEach(([name, def]) => {
      Object.entries({ ...def.fields, ...(def.relations || {}) })
        .filter(([, f]) => f.enrichable)
        .forEach(([fieldName, fieldDef]) => {
          // enrichable fields should have either mergeStrategy on the field or a default
          expect(typeof fieldName).toBe('string');
        });
    });
  });
});

describe('Quality Thresholds', () => {
  it('Individual profiles should have strict quality requirements', () => {
    const schema = require('../bots/forge/schema');
    const thresholds = schema.entities.Individual.qualityThresholds;
    expect(thresholds.minControversies).toBeGreaterThanOrEqual(2);
    expect(thresholds.minSources).toBeGreaterThanOrEqual(2);
    expect(thresholds.minTimeline).toBeGreaterThanOrEqual(3);
    expect(thresholds.minDescriptionLength).toBeGreaterThanOrEqual(200);
  });
});
